### ISSUE TITLE
0.0.0.0:4567 does not work using Windows 7 (mingw platform)

### ISSUE THREAD

**Issue by rriemann** [middleman/middleman#1011]
Dear Middleman,

you told me to preview your page using http://0.0.0.0:4567 , instead only http:/127.0.0.1:4567 works. Should I try to send you a patch? The latter one works on both platforms and should be preferered imho. (Though 0.0.0.0 is more stylish - so what?)

Best,
Robert

**Comment by Ajedi32** [comment]
I'm still seeing this issue (v3.3.10). Found this issue when I copy-pasted `http://0.0.0.0:4567/` into my browser and Chrome ran a Google search for it instead of taking me to the url. :laughing:

**Comment by Arcovion** [comment]
@Ajedi32 Yea in v4 `localhost` is shown instead, but the actual server is on `0.0.0.0` which means all local interfaces. So you can use localhost for desktop but can still have another IP for wifi for example. More info in #1363.
