### ISSUE TITLE
Typo causes build failure when using a custom layouts_dir 

### ISSUE THREAD

**Issue by jiho** [middleman/middleman#1028]
Here are reproducible steps

```
middleman init foo
cd foo/source
middleman build
# OK
mkdir assets
mv layouts assets
echo "set :layouts_dir, 'assets/layouts'" >> ../config.rb
middleman build --verbose
# error: undefined local variable or method `layout_dir' for
# #<Middleman::Application:0x70337227908940>
```

This seems to be l.153 in rendering.rb.
The variable used in the error message is "layout_dir", singular instead of "layouts_dir", plural. This seems to be a typo.

```
echo "set :layout_dir, 'assets/layouts'" >> ../config.rb
middleman build --verbose
# error: Tried to render a layout (calls yield) at ****/foo/source/assets/layouts/layout.erb
# like it was a template. Non-default layouts need to be in source/assets/layouts.
```

**Comment by dblessing** [comment]
I'm still having this issue with latest middleman. Why was this issue closed?

**Comment by tdreyno** [comment]
@dblessing Can you open a new ticket. Sometimes things get closed just because there has been no further reports in months.

**Comment by lolmaus** [comment]
But I even provided a repo with reproduction, see above. :weary:

**Comment by paulmsmith** [comment]
I'm suffering this issue too.
