### ISSUE TITLE
Importing Google Fonts in Sass produces a warning: Error encountered while saving cache 7a…b5/_fonts.sassc: no _dump_data is defined for class Proc

### ISSUE THREAD

**Issue by lolmaus** [middleman/middleman#1075]
When i add this line to my Sass file:

```
@import url(http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic&subset=latin,cyrillic-ext,latin-ext,cyrillic)
```

…and run `bundle exec middleman`, i receive this warning in console:

> Warning. Error encountered while saving cache 7acf7ce6d876d94895476085d077f778547ea9b5/_fonts.sassc: no _dump_data is defined for class Proc

The warning appears the moment a page is requested, but only once for each server (re)load.

It seems not to affect the produced website but is kinda annoying.

**Comment by enriquetuya** [comment]
Ticket #1093 was also closed but I still got the same error. I'm following this issue on sass-rails: 
https://github.com/rails/sass-rails/issues/331

**Comment by mattmartini** [comment]
Both this and #1093 are both closed, but seemingly without resolution.  I am having this issue with sass 3.4.24
