### ISSUE TITLE
Windows: No timezone data source could be found

### ISSUE THREAD

**Issue by lolmaus** [middleman/middleman#1097]
When using Middleman from Github master, it fails with:

> ruby/gems/2.0.0/gems/tzinfo-1.1.0/lib/tzinfo/data_source.rb:199:in `rescue in create_default_data_source': No timezone data source could be found. To resolve this, either install TZInfo::Data (e.g. by running`gem install tzinfo-data`) or specify a zoneinfo directory using`TZInfo::DataSource.set(:zoneinfo, zoneinfo_path)`. (TZInfo::DataSourceNotFound)

I managed to resolve this by adding the following to `Gemfile`:

```
gem "tzinfo-data"
```

and this to `config.rb`:

```
require 'tzinfo'
```

I've looked into master shared templates and failed to find those.

**Comment by jcodesdotme** [comment]
adding this line to Gemfile fixed all:

if you are on 64 bit win system:
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]

if you are on 32 bit win system:
gem 'tzinfo-data', platforms: [:mingw, :mswin]
