### ISSUE TITLE
Support Padrino's partial to accept block

### ISSUE THREAD

**Issue by lolmaus** [middleman/middleman#1099]
Padrino now [supports](https://github.com/padrino/padrino-framework/issues/1504) passing a block to a partial.

Partial:

``` haml
%h1 prefix
.haml-block
  = yield
%h3 postfix
```

Page:

``` haml
= partial 'foo' do
  Yay, a codeblock!
```

Resulting HTML:

``` html
<h1>prefix</h1>
<div class="haml-block">
  Yay, a codeblock!
</div>
<h3>postfix</h3>
```

This functionality is absolutely awesome. Now Pardrino doesn't fall behind Sass and [Jade](http://jade-lang.com) which have supported passing blocks to mixins since forever.

Unfortunately, this won't work in Middleman. Middleman produces the following HTML:

``` html
    Yay, a codeblock!
<h1>prefix</h1>
<div class="haml-block">
  0
</div>
<h3>postfix</h3>
```

@ujifgc, a Padrino maintainer who was kind to implement this feature, supposes that the problem in Middleman might take place due to [this](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-more/core_extensions/default_helpers.rb#L74) monkey patch. He suggests that we should:
1. determine why this monkey patch is there in the first place and
2. either get rid of it or modify it to support modern Padrino.

The reason for the issue may hide elsewhere though.

Here's a sandbox project that can be used to test the issue quickly: https://github.com/lolmaus/middleman-padrino-test-partial-block

PS Yes, i know that Padrino/Middleman partials can accept code blocks by processing them through `capture_html`, assigning the result to variables and passing the variables to partials. But this is just ugly. Partials should be able to accept code blocks naturally, just like mixins in Sass and Jade. Padrino already made that happen. Please make Middleman compatible.

**Comment by jgillich** [comment]
I know it's been a while, but this does in fact work:
```
<% partial :foo do %>
  Bar
<% end %>
```
Then simply `<%= yield %>` in the partial.

I will look into adding that to the docs.

**Comment by davidsilvasmith** [comment]
@jgillich that looks like just what I need!

I wasn't able to get the do yield block to work. :(

in _homepage-slider.erb
    <% partial "/feature-pieces/homepage-slider-1" do %>
        test
    <% end %>`

and in /feature-pieces/homepage-slider-1.erb

    <div class="slider-content">
        <%= yield %>
    </div>

I get this error: 
`Tried to render a layout (calls yield) at /Users/me/apps/myapp/source/_partials/feature-pieces/_homepage-slider-1.erb like it was a template. Non-default layouts need to be in source/_layouts.`

**Comment by jimothyGator** [comment]
@davidsilvasmith I bet the problem is that your partial and template have essentially the same name, other than the leading underscore. Middleman is probably trying to include the template rather than the partial. Trying making the names more distinct, or put them in different directories.

**Comment by davidsilvasmith** [comment]
@jgillich I'm not sure what my issue was, but you are right your example works perfectly.

Sorry for the false alarm.

**Comment by dkeeghan** [comment]
I had the same issue as @davidsilvasmith and it was because I used `<%=` at the start of the partial (like a normal partial load) instead of `<%`. Just in case anyone comes here looking for the same error.

**Comment by ldonis** [comment]
Something interesting I just found:

This fails:
```erb
<% partial "partials/header" do %>
<% end %>
```

This works like a charm:
```erb
<% partial "partials/header" do %>

<% end %>
```

Do you notice the line between the "partial" and the close tag? :D
