### ISSUE TITLE
Middleman won't reload helpers when helpers are edited (though it claims to reload itself)

### ISSUE THREAD

**Issue by lolmaus** [middleman/middleman#1105]
When i edit a helper under `/helpers/`, Middleman says:

```
== The Middleman is reloading
== The Middleman has reloaded
```

But changes in the helper are not applied. I have to restart Middleman manually every time i edit a helper.

Tested on Windows.

**Comment by zmoazeni** [comment]
I am still having problems with helpers reloading properly with v3.4.0

* Create a helper
* Create a page using a method from that helper
* Load the page in the browser
* Change the value of that helper
* Reload the page in the browser. The value doesn't change.

**Comment by tdreyno** [comment]
Does the command line messaging show that "middleman is reloading"?

**Comment by zmoazeni** [comment]
> Does the command line messaging show that "middleman is reloading"?
Yeah.

**Comment by tdreyno** [comment]
... does is ever say it "has reloaded"?

**Comment by zmoazeni** [comment]
Yes. It's very easy to reproduce given the steps I've listed on both 3.4.0 and 4.0.0.rc1.

The html reloads fine, but the helper code in `/helpers` does not reload.

**Comment by zmoazeni** [comment]
In the meantime, this is a very crude way to reload middleman when any ruby changes. _(There are probably more elegant ways to do this, but it's what I ended up getting working)_

```ruby
# in the Gemfile
group :development do
  gem "god"
  gem "guard"
end

# in a new file named: middleman.god
# this will start middleman
God.watch do |w|
  w.name = "middleman"
  w.start = "bundle exec middleman server"
  w.keepalive
  w.log = "#{File.expand_path("..", __FILE__)}/middleman.log"
  w.dir = File.expand_path("..", __FILE__)
end

# in a new file named: Guardfile
# this watches for any ruby changes and tells god to restart middleman
# it would be nice to do this all with Guard, but I don't know enough about managing daemons in Guard
require 'guard/plugin'

module ::Guard
  class God < Plugin
    def reload
      reload_god
    end

    def run_on_additions(paths)
      reload_god
    end

    def run_on_modifications(paths)
      reload_god
    end

    def run_on_removals(paths)
      reload_god
    end

    private

    def reload_god
      `god restart`
    end
  end
end

guard 'God' do
  watch(%r{^.+\.rb$})
end
```

```
# start god first
$ god -c middleman.god

# then start guard
$ guard -i # you should be good to go at this point

# If you want to close down, CTRL-C guard and then run:
$ god terminate
```

You can also use guard-middleman which will rebuild the actual html every time something changes, but I just wanted to stick with the ruby server for now.

This is also handy because it will restart whenever `lib/` changes

**Comment by zslabs** [comment]
@tdreyno Seem to be facing this issue still in 4.1.1. It says it reloads, but manual refreshes still show old code.

**Comment by tdreyno** [comment]
Unfortunately, Ruby's `require` only reads the file the first time. There are ways to hack around this, but they are very invasive.

Are you requiring the files in `helpers/` or  is Middleman automatically doing that?

**Comment by zslabs** [comment]
Hey @tdreyno,
I'm letting Middleman automatically pull them in; following the example in the docs, `careers_helpers.rb` has a `module CareersHelpers` definition.

**Comment by tdreyno** [comment]
Okay, I might be able to hack it in there :) Let me think about it.

**Comment by zslabs** [comment]
Cool - thanks for taking another look!

**Comment by ryanburnette** [comment]
I'm suffering from this issue too. I use Middleman 3.x in my production site with a lot of helpers so it and it makes me cry sometimes.

**Comment by andreamoro** [comment]
This is still an open issue on the most recent version of Middleman

**Comment by fedegos** [comment]
No solution yet?

**Comment by codener** [comment]
As @tdreyno wrote, `require` only reads files the first time. However, there is `load`, which [just loads that file each time you call it](https://stackoverflow.com/a/3170650/3497272).

Since `config.rb` is re-evaluated each time Middleman reboots, this will successfully reload helpers:

    # in config.rb:
    
    # Middleman fails to reload helpers, although it notices their modification
    # This force-reloads them
    Dir['helpers/*'].each(&method(:load))

If you have nested helpers, you need to adapt the glob string to something like `'helpers/**/*'`.

**Comment by ryanburnette** [comment]
This was a game changer for me. Thank you so much!

**Comment by jsoref** [comment]
@tdreyno would it be unreasonable to add the blob from https://github.com/middleman/middleman/issues/1105#issuecomment-305715209 into: https://github.com/middleman/middleman-templates-default/blob/master/template/config.rb (as a comment)? (I'm happy to provide a PR if it's welcome)

**Comment by tdreyno** [comment]
@andreamoro In that case, I think you should switch `require` to `load` and place the file in `lib`. Helpers are specific to template helper methods and require a specific form (an exported module and pure methods)

**Comment by andreamoro** [comment]
@tdreyno ok, if for the classes I've to use a different way (do I need to create a lib folder, where?), Considering the helpers method are just within the helpers subfolder I'm literally missing where and when I should change the require to load.

Can you please give me more hints?

**Comment by tdreyno** [comment]
I would suggest always using `load` if you want their contents to reload on change. Ruby's `require` caches files, which we can't really control.

You can create a `lib` folder as a sibling to `helpers`. Those are the two paths watched by default for `.rb` file changes. The only difference is that there is a little additional processing that happens for files in `helpers` to inject their methods into the template context.

**Comment by andreamoro** [comment]
So, unless I'm mistaken, by creating a lib folder and moving all class files into it sound suffice. Correct?
