### ISSUE TITLE
Proxied local variables are not available within the outer layout when `wrap_layout` is used

### ISSUE THREAD

**Issue by lolmaus** [middleman/middleman#1111]
## Prerequisites

So we have two layouts.

The master layout accesses a local variable `title`:

**/soucre/layouts/layout.haml**

``` haml
%h1= title
= yield
```

Another layout is wrapped by the master layout.

**/soucre/layouts/inner_layout.haml**

``` haml
- wrap_layout :layout do
  = yield
  %h3 Goodbye.
```

A proxy page is created and a local variable is passed into it.

**/config.rb**

``` ruby
proxy "/proxy.html", "/prototype.html", locals: {title: 'Hello old friend'}
```
## Working scenario

When a page is rendered with a master layout directly, the local variable is rendered fine.

**/soucre/prototype.html.haml**

``` haml
%p Yay!
```

**http://localhost:4567/proxy.html**

``` html
<h1>Hello old friend</h1>
<p>Yay!</p>
```
## Failing scenario

But when the master layout is rendered via `wrap_layout`, the local variable is not accessible.

**/soucre/prototype.html.haml**

``` haml

---
layout: inner_layout

---

%p Yay!
```

**http://localhost:4567/proxy.html**

```
undefined local variable or method `title' for #<Middleman::Application:0x31448736>
```

**Comment by Naatan** [comment]
Why was this closed? I'm still seeing this issue.

**Comment by tdreyno** [comment]
No comments in 15 months, figured it was a leftover.

**Comment by huerlisi** [comment]
This is still an issue. Could you please reopen?

**Comment by everflux** [comment]
Is there a workaround available?

**Comment by tdreyno** [comment]
You could use `data:` instead of `locals:` and then access as `current_resource.data` instead. Should work.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿 🌷 🌾 and came across this issue.

Did the suggestion by @tdreyno work? If so, can this be closed?

**Comment by everflux** [comment]
I resolved it using a different conceptual approach. But I assume this issues can be closed, thanks.
