### ISSUE TITLE
`middleman build` doesn't play nice with gzip

### ISSUE THREAD

**Issue by willglynn** [middleman/middleman#1114]
I have a [test case](https://github.com/willglynn/middleman-gzip-testcase) which shows:

```
$ middleman build
      create  build/index.html
        gzip  build/index.html.gz (20 Bytes larger)
        gzip  Total gzip savings: -20 Bytes
$ middleman build
   identical  build/index.html
      remove  build/index.html.gz
        gzip  build/index.html.gz (20 Bytes larger)
        gzip  Total gzip savings: -20 Bytes
```

I think the second `middleman build` should ignore the `index.html.gz` rather than deleting and re-creating it. Besides the test case, I have a real site with a build process that takes significantly longer than necessary due to this behavior.

**Comment by ahoward** [comment]
i just wanted to leave a little note to @tdreyno that including things outside the sitemap shouldn't be considered an exception.  we're build around 20 middleman sites at dojo4 and each, and every one has this issue.  each time i work around differently.  in fact, i'm struggling with a bunch of content that needs included in a build, but must remain untouched by middleman, right now.  simply putting it source, in my case, will slow the build down by 100% ;-(
