### ISSUE TITLE
Switch to ActionView helpers (and template handling) from Padrino

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1130]
We've had some trouble with Padrino, and Rails developers are generally more familiar with ActionView's helpers than the slightly different ones in Padrino. Beyond that, most templating engines already ship and test support with ActionView, while we often have to patch or work around incompatibilities. I propose that, for V4, we look into ripping out Padrino and replacing it with ActionView.

**Comment by marcamillion** [comment]
I would love to be able to access this `cycle` method from ActionView::Helpers::TextHelper - http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-cycle 

Is there a simple way for me to just "require" say this module, or a link to the GH file or something, so I can use the `cycle` method?

If not, what is the alternative to being able to get the same functionality without polluting my view?

**Comment by tdreyno** [comment]
Maybe:

```
require 'actionview/lib/action_view/helpers/text_helper'
helpers ::ActionView::Helpers::TextHelper
```

Depends on how magical Rails is trying to be in that file.

**Comment by cllns** [comment]
Just to note: another benefit would be that Middleman could use some Rails-specific gems (ones that only interact with ActiveView), like: https://github.com/stefanpenner/country_select

**Comment by tdreyno** [comment]
We'd happily merge some that supports this, but only Rails gods know the internals :(
