### ISSUE TITLE
I18n v3: linking to the same page from foreign language to default language, with relative paths?

### ISSUE THREAD

**Issue by lolmaus** [middleman/middleman#1146]
Hi!

I've got an I18n setup with `mount_as_root` enabled.

I would like to create a link from page `ru/foo.html` to the same page but in default language.

If i do `link_to 'Foo', 'foo.html'`, it links to `ru/foo.html`, i. e. it does not switch the language!

If i do `link_to 'Foo', '/foo.html'`, it links to `/foo.html`: it does switch the language but it produces an absolute url, which makes it impossible to publish the site on Github Pages.

Please help me to resolve this.

**Comment by joallard** [comment]
#1466
