### ISSUE TITLE
Images invisible to Middleman during CSS build phase

### ISSUE THREAD

**Issue by GSI** [middleman/middleman#1172]
**In a file named stylesheets/deferred.css.scss.erb I have the following code:**

```
// image-preloader
body:after {
  content: url() <% image_resources_in('thumbs', true).each do |img| %>
                   <%= " url(#{img.path}) " %>
                 <% end %>;
  display: none;
}
```

Now at the moment the Ruby-part is executed, Middleman seems to be unable to see the images and thus the Enumerable is empty and nothing is written.

**NOTE** The very same code works perfectly fine in `middleman server`.
Also, the snippet is tested to work fine within .html.erb files (in both, server and build).

**Can this be resolved directly in Middleman in order to achieve consistency over the two environments?**

Is there a workaround that allows me the keep the definitions in the CSS?
(I want to avoid having HTML elements with style attributes.)

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Since 4.0 the primary handling of advanced pre-processing of assets is to use an external pipeline. I'd suggest that this issue is closed.
