### ISSUE TITLE
Middleman helpers not available inside Liquid templates

### ISSUE THREAD

**Issue by unicornsandbots** [middleman/middleman#1202]
Hey guys,

I am trying to use Liquid as the templating language for a new Middleman site. Everything works fine except I cannot access regular Middleman helpers using the following syntax:

```
{{ current_page.data.title }}
```

This snippet returns an empty string. Calling it with `{%` and `%}` generates the following error:

```
Liquid::SyntaxError at /
Unknown tag 'current_page'
```

What is the proper way to access them? Do I need to define my own Liquid helpers?

You can find a sample repository [here](https://github.com/unicornsandbots/liquid_middleman_example).

Thanks in advance!

P.S.: I posted [here](http://forum.middlemanapp.com/t/middleman-helpers-not-available-inside-liquid-templates/1210) a couple days ago as well.

**Comment by jacquescrocker** [comment]
@unicornsandbots were you able to define your own helpers, accessible from liquid? if so how?

any help appreciated!
