### ISSUE TITLE
problems building when using less

### ISSUE THREAD

**Issue by holden** [middleman/middleman#1212]
I've been using Middleman together with Less for a project and everything works perfectly using the local development server.  However when I try to `build` the project it doesn't work.  It gives me undefined variable errors which make no sense since it works fine in both development and using codekit.

It seems to try to parse random less files that aren't directly in the application.css file.  Or that's my guess.  How can I fix this so that it only tries to build the less files which are inside my application.css file?

I saw someone else say something similar here:

http://spin.atomicobject.com/2013/10/31/detecting-less-changes-middleman/

> Middleman treats its source files differently when it builds the static site, as opposed to running a local development server. In order to keep it from trying to compile all of the LESS files it comes across in the source/stylesheets directory, you have to configure it to ignore them. You can do this by adding an ignore line in config.rb:

```
configure :build do
  ignore "*.less"
end
```

Which allows build to complete, however it doesn't parse any LESS files. ;-)

Also, to make thing weirder, since LESS importing doesn't require the asset pipeline I've put most of my LESS source files outside the stylesheets folder just in a separate folder `assets/startup-kit/`

```
set :css_dir, 'assets/stylesheets'
set :js_dir, 'assets/javascripts'
set :images_dir, 'assets/images'
```

application.css

```
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.

 *= require bootstrap
 *= require common-files/css/animations
 *= require style

*/
```

style.less

```
@startup-basePath: '/assets/startup-kit/';
@startup-fontPath: '/assets/startup-kit/common-files/fonts/';
@local-font-path: '/assets/startup-kit/flat-ui-pro/fonts/lato/';
@icon-font-path: '/assets/startup-kit/flat-ui-pro/fonts/';

@import '../startup-kit/flat-ui-pro/less/variables.less';
@import '../startup-kit/flat-ui-pro/less/mixins.less';

@import '../startup-kit/common-files/less/mixins.less';
@import '../startup-kit/common-files/less/common.less';
@import '../startup-kit/common-files/less/helper.less';
@import '../startup-kit/common-files/less/navbar.less';
```

**Comment by ikedhidenori** [comment]
I'm just encountering at exactly same issue.
The project with less seems to be perfect on development(`middleman server`), but fails on build.

Here's really just a part of the results of  `bundle exec middleman build --verbose`.
I got handreds of same 'undefined' errors actually. 

```
== Request: /resources/assets/startup/ui-kit/ui-kit-header/css/style.css
== Finishing Request: resources/assets/startup/ui-kit/ui-kit-header/css/style.css (0.0s)
   identical  build/resources/assets/startup/ui-kit/ui-kit-header/css/style.css
== Request: /resources/assets/startup/ui-kit/ui-kit-header/css/ui-kit-styles.css
== Finishing Request: resources/assets/startup/ui-kit/ui-kit-header/css/ui-kit-styles.css (0.0s)
   identical  build/resources/assets/startup/ui-kit/ui-kit-header/css/ui-kit-styles.css
== Request: /resources/assets/startup/ui-kit/ui-kit-header/less/header-1.css
       error  build/resources/assets/startup/ui-kit/ui-kit-header/less/header-1.css
variable @font-family-demo is undefined
at /Users/hi/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/less-2.6.0/lib/less/js/lib/less/parser.js:604:31
/Users/hi/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/less-2.6.0/lib/less/parser.rb:100:in `block in to_css'
```

and maybe the same case this is:
https://forum.middlemanapp.com/t/build-fails-with-bootstrap-and-less-but-render-works/1201

Anyway, building files seem to be succeeded, but ommit lots of errors. 
I want to deploy files by `middleman deploy`, however I've got suspension couse of that errors.

Any ideas?

**Comment by ikedhidenori** [comment]
This may not be good solution, but works.

```config.rb
configure :build do
  ignore '/**/less/*.css'
end
```

I found the errors are made by `*.css`files inside`/less`directory. (Actually there are no css file there, though...) Anyway, this works.

**Comment by ikedhidenori** [comment]
This may not be good solution, but works.

```config.rb
configure :build do
  ignore '/**/less/*.css'
end
```

I found the errors are made by `*.css`files inside`/less`directory. (Actually there are no css file there, though...) Anyway, this works.

**Comment by tdreyno** [comment]
Looks like this are partials, meant to be included by other files, that fail to render individually. Middleman will ignore files prefixed with an underscore or you can ignore them yourself as you have done able.
