### ISSUE TITLE
Templates in extensions

### ISSUE THREAD

**Issue by Aupajo** [middleman/middleman#1217]
I'd like to include a template in my extension, but it doesn't seem possible.

``` ruby
def manipulate_resource_list(resources)
  resources << my_extension_resource
end

def my_extension_resource
  template = File.expand_path("../path/to/extension/template", __FILE__)
  # ...
  Middleman::Sitemap::Resource.new(app.sitemap, target_path, template)
end
```

What I'd like to do is create a `Resource` with an absolute `source_file` path, but there seems to be numerous checks peppered throughout Middleman to ensure a file is relative to the source root.

As a last-ditch effort, I thought that it might be possible to inherit from `Resource` and provide my own `render` method.

``` ruby
class MyExtensionResource < Middleman::Sitemap::Resource
  def render
    # ...
  end
end
```

But:

```
super: no superclass method `get_source_file`
```

Is there a way, or is this not currently supported?

**Comment by Aupajo** [comment]
Would you accept a PR allowing exceptions to be made to the ignore list?

**Comment by Arcovion** [comment]
@Aupajo What sort of interface are you after? You could always do:
```ruby
app.config[:file_watcher_ignore].delete /^vendor(\/|$)/
```

**Comment by Aupajo** [comment]
@Arcovion Is that not detrimental? I assumed the point of that setting was to prevent scanning what can easily be thousands of files included in gems.

I just want to add one path explicitly to the file watcher; the template my extension provides.

**Comment by Arcovion** [comment]
Good point, you could construct some elaborate regex:
```ruby
app.config[:file_watcher_ignore].delete /^vendor(\/|$)/
app.config[:file_watcher_ignore].push   /^vendor(\/|$)(?!dir/template.xyz)/
```
Or monkeypatch one of the [filewatcher methods](https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-core/core_extensions/file_watcher.rb#L161-L167).

v4 doesn't appear to ignore the [vendor folder](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/core_extensions/file_watcher.rb#L19-L24) any more actually... maybe we should only be monitoring the source dir for changes and select files like `config.rb`.

**Comment by Aupajo** [comment]
Thanks, @Arcovion.

I'm reluctant to monkey patch, and I'm reluctant to `delete`/`push` – both solutions serve me, but they won't necessarily serve the next extension.

Imagine two extensions using the same technique:

```ruby
# Extension A
app.config[:file_watcher_ignore].delete /^vendor(\/|$)/
app.config[:file_watcher_ignore].push   /^vendor(\/|$)(?!extension_a/templates)/

# Extension B
app.config[:file_watcher_ignore].delete /^vendor(\/|$)/
app.config[:file_watcher_ignore].push   /^vendor(\/|$)(?!extension_b/templates)/
```

The latter extension would override the former; they'd be incompatible to use together.

**Comment by Aupajo** [comment]
@Arcovion After some debugging, I've found that changing the ignore pattern doesn't work.

The ignore patterns are used in `FileWatcher#reload_path`:

```ruby
::Middleman::Util.all_files_under(path, &method(:ignored?)).each ...
```

But `Middleman::Util.all_files_under` works like this:

```ruby
def all_files_under(path, &ignore)
  path = Pathname(path)

  return [] if ignore && ignore.call(path) # <--- problem

  if path.directory?
    path.children.flat_map do |child|
      all_files_under(child, &ignore)
    end.compact
  elsif path.file?
    [path]
  else
    []
  end
end
```

You can understand it like this:

1. Middleman starts at the site root.
2. It descends into each file and directory, checking if `ignore?` matches.
3. If a directory is to be ignored, it does not descend any further.

So Middleman checks the `vendor` directory against the pattern (`^(?!vendor/some_extension/templates/)vendor(\/|$)/`). This pattern matches `vendor`, and so the directory is ignored. `vendor/some_extension/templates` will never be checked.

**Comment by tdreyno** [comment]
In v4, the file watching is opt-in, rather than opt-out.

**Comment by Arcovion** [comment]
You should be able to use your original `manipulate_resource_list` method w/ `Pathname('template/dir').relative_path_from(Pathname(app.root))` - provided your template is just a static file that doesn't need to be watched for changes.

**Comment by Aupajo** [comment]
@Arcovion If I try something like:

```ruby
def manipulate_resource_list(resources)
  # Template path must be a string
  template = Pathname('templates/dir/template.html.erb').relative_path_from(Pathname(app.root)).to_s
  resources << Middleman::Sitemap::Resource.new(app.sitemap, "some_path", template)
end
```

I get an error:

```
different prefix: "" and "/path/to/app"
/Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/pathname.rb:508:in `relative_path_from'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:98:in `render'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:260:in `process_request'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:210:in `block in call!'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:209:in `catch'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:209:in `call!'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:195:in `call'
/path/to/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
/path/to/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
/path/to/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
/path/to/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/path/to/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/path/to/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/path/to/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/Users/pete/.gem/ruby/2.2.2/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
/Users/pete/.gem/ruby/2.2.2/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
/Users/pete/.gem/ruby/2.2.2/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/cli/build.rb:255:in `render_to_file'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/cli/build.rb:221:in `build_resource'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/cli/build.rb:213:in `each'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/cli/build.rb:213:in `execute!'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/cli/build.rb:128:in `invoke!'
/Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/cli/build.rb:70:in `build'
/Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:72:in `method_missing'
/Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
/Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
/Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/pete/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:20:in `start'
/Users/pete/.gem/ruby/2.2.2/gems/middleman-core-3.3.12/bin/middleman:18:in `<top (required)>'
/Users/pete/.gem/ruby/2.2.2/bin/middleman:23:in `load'
/Users/pete/.gem/ruby/2.2.2/bin/middleman:23:in `<main>'
```

**Comment by Arcovion** [comment]
Change:
```ruby
Pathname('templates/dir/template.html.erb').relative_path_from(Pathname(app.root)).to_s
```
to
```ruby
Pathname(app.root).join('templates/dir/template.html.erb').relative_path_from(Pathname(app.root)).to_s
```
The backtrace `pathname.rb:508:in 'relative_path_from'` shows it couldn't build the path as the arguments must be [both absolute or both relative](http://ruby-doc.org/stdlib-2.2.2/libdoc/pathname/rdoc/Pathname.html#method-i-relative_path_from).

**Comment by Aupajo** [comment]
@Arcovion Ah yes, I see – my mistake.

Fixing this still fails, though; the FileWatcher eliminates it it's `known_paths` because it matches an entry in the `IGNORE_LIST` :disappointed:

**Comment by Arcovion** [comment]
If it's in `/vendor` then it's a static file the user isn't going to change, so doesn't need to be watched for changes right?
If it's in a directory like `source/templates` where the user can edit it, that shouldn't be ignored from the file watcher by default, so you're able to add it in with `app.files.reload_path`.

**Comment by Aupajo** [comment]
@Arcovion That sounds perfectly reasonable to me, and that approach is [what I've been using](https://github.com/Aupajo/middleman-search_engine_sitemap/blob/master/lib/middleman/search_engine_sitemap.rb#L55-L60) for some time now. It works fine until my gem is bundled into a `vendor` directory.

If you want to take a look yourself at what's going on, here's an example I've put together: https://github.com/Aupajo/mm-ses-example-for-arcovion

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Did the suggestion work? If so, can this be closed?

**Comment by Aupajo** [comment]
@sandstrom The demo app I provided above to illustrate the problem now works on Middleman 4.1.11. However, I would hesitate to mark this bug as closed – might be worth confirming the new behaviour around watching `vendor`.
