### ISSUE TITLE
Default partials_dir to 'partials'

### ISSUE THREAD

**Issue by barraponto** [middleman/middleman#1220]
I'm under the impression that `layouts_dir` defaults to `layouts`, but `partials_dir` doesn't default to `partials`. Which would be awesome and consistent :)

**Comment by lewiseason** [comment]
So... this option been removed? Per:

> Partials should live next to content, or be addressed with absolute paths.

Is this an "opinionated framework" opinion, or is there a technical reason I should be doing it this way?

**Comment by tdreyno** [comment]
People didn't like grouping their partials. Some did, but most didn't, so now we allow partials to be placed anywhere, not just 1 directory.

**Comment by lewiseason** [comment]
So quite the opposite? Excellent. Thanks for clarifying
