### ISSUE TITLE
proxy cannot use layouts from /layouts folder

### ISSUE THREAD

**Issue by schultyy** [middleman/middleman#1226]
Hello,

I faced an issue with the proxy functionality.
My case:
I have blog posts which should be accessible under different urls:
- A url that conforms to the pattern configured in `config.rb`
- A legacy url (From the old blog version, here the url pattern is not conistent, but all posts should be accessible under their old url as well)

For the legacy url I use the [proxy feature](http://middlemanapp.com/basics/dynamic-pages/). 
My setup in `config.rb`:

```ruby
ready do
  sitemap.resources.each.do |page|
    #old_link is configured in frontmatter
    if old_link = page.data['old_link']
      proxy old_link, '/layout/posts.html', :locals => { :current_article => page }
    end
  end
end
```
The blog post should now be available under the `old_link`. As layout I want to use the posts layout like for all other posts.

When I try to access the post with the legacy url I get this error message:

`Path old/path/to/blogpost/index.html proxies to unknown file layouts/posts.html`

After a couple of hours of research I found out that the layout file must be in one of the folders which are available in the build output i.e. `/blog` (which contains all the blog posts) but not in the `/layouts` folder.
I'm not sure if this is a bug in middleman itself or in the documentation.

**Comment by zslabs** [comment]
@bhollis Just to make sure I understand, if I have a layout helper like this:

```
page "/features/*", :layout => "features"
```

And a proxy setup like this:

```
data.apps.each do |application|
  proxy "/features/apps/#{application.name.downcase.gsub(" ", "-").gsub(".", "-")}/index.html", "/templates/layouts/apps.html", :locals => { :application => application }
end
```

Then that wouldn't actually set a layout of `features` around the single apps; I'd need to specify the layout in the frontmatter? In v3 this seemed to work okay, but is not working anymore unless I make that change. [Here](https://github.com/middleman/middleman/issues/1813) is a bit more context. Thanks!

**Comment by tdreyno** [comment]
Hmm, I think it's just the word `layout` that's blacklisted. Can you see if it works with another name?

**Comment by zslabs** [comment]
@tdreyno Thanks for the response. So I'm using that param to pass down the layout it should accept, which it does for "regular" pages, but it wasn't working with proxies. I ended up doing the following:

```
data.apps.each do |application|
  proxy "/features/apps/#{application.name.downcase.gsub(" ", "-").gsub(".", "-")}/index.html", "/templates/layouts/oneclick.html", :layout => "features", :locals => { :application => application}
end
```

and passed in the layout variable that way. This seems different than how MM3 worked, so wasn't sure if this was something that changed.

**Comment by tdreyno** [comment]
nope, that's exactly how it should work.

Not seeing in the earlier example where you were trying to set the layout at all.

**Comment by zslabs** [comment]
Awesome thanks; so I was assuming if you set a matching pattern through `page "/features/*", :layout => "features"` that it would also come through on any proxies under that directory match as well.

**Comment by tdreyno** [comment]
Oh, I see. Hmm... I guess if it were my guess I'd say it's a 50/50 whether that works. Seems reasonable, but I can also see why it wouldn't. Let me take a look and write a test case

**Comment by zslabs** [comment]
Ok great thanks!

**Comment by zslabs** [comment]
Thanks @tdreyno !
