### ISSUE TITLE
Using configuration via ERb in JavaScript files can cause silent build failure

### ISSUE THREAD

**Issue by JamesCropcho** [middleman/middleman#1231]
Hello,

I'll describe what I _think_ is happening here.

Scenario 1: I render pages in browser via `middleman server`. Then I `middleman deploy -b`. The JavaScript files on the server have the ERb rendered for the `development` environment; JavaScript breaks. I locally execute `rm -rf build/ .cache/`, then redo `middleman deploy -b`\- everything works.

Scenario 2: I `middleman deploy -b`, then continue working locally via `middleman server`. Local JavaScript has the ERb rendered for the `build` environment; JavaScript breaks.  I locally execute `rm -rf build/ .cache/`, then redo `middleman server`\- everything works.

So, either I'm doing something wrong, or it's a bug(...ish), right?

If the former, I see several possible fixes, but each with their own caveat- no "silver bullet."

Thoughts?

-James

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred instead of sprockets. I'd suggest closing this issue, and if the problem resurfaces a new issue can be opened.
