### ISSUE TITLE
Unable to build source/.well-known/keybase.txt file

### ISSUE THREAD

**Issue by bostonaholic** [middleman/middleman#1243]
I'm trying to verify my site for keybase.io and Middleman is unable to publish the `domain.com/.well-known/keybase.txt` file it needs.

I have put it in `source/.well-known/keybase.txt` but `middleman build` does not recognize the `source/.well-known` directory. Is there a config I can use to do this?

**Comment by a1rat91** [comment]
Thanks! @tdreyno
