### ISSUE TITLE
ERB should be parsed before frontmatter variables are assigned

### ISSUE THREAD

**Issue by pomartel** [middleman/middleman#1246]
With Middleman-blog, I am trying to define a dynamic frontmatter variable this way :

```

---
title: My Title
date: 2012/11/08
published: <%= dynamic_condition %>

---
```

This is not working because it seems the frontmatter variables are assigned before the ERB is actually parsed. Is that a bug or the intended behaviour?

**Comment by shaunakv1** [comment]
@tdreyno  was there any resolution on this issue? I am looking to do something similar.  I have am building a site with multiple blogs.  

The tags come from a unrelated enterprise database. I was hoping to generate tags from a json file in data folder, which I externally keep in sync with the database. 

I am looking for a way to achieve something like this: 
 
```ruby
;;;
	"title":"Benthic Terrain Modeler",
	"date":"2015/09/07",
	"id": <%= data.tools[current_page.slug].tags %>
;;;
```
This way, the tag relation ships can come from a external database, and developers of this site won't have to manually 100's of articles manually when the tags update.

Is there a better way to do this? Any help would be greatly appreciated!

**Comment by tdreyno** [comment]
You could write an extension which adds metadata to Resources.

```
class TagMerger < ::Middleman::Extension
  def manipulate_resource_list(resources)
    resources.map do |r|
      r.add_metadata(app.data.tools[r.slug].tags) if something_or_other
      r
    end
  end
end

::Middleman::Extensions.register(:tag_merger, TagMerger)

activate :tag_merger
```

**Comment by Yellarkh** [comment]
if you want to change dynamically "title", set :locals on link_to or proxy
```
<%= link_to 'text', '/page.html', :query => { :title => 'your title' } %>

```

then in your layout
```
  <title><%= locals.key?(:title) ? title : current_page.data.title ? current_page.data.title : data.settings.site.title %></title>
```
