### ISSUE TITLE
i18n in blog pages not working

### ISSUE THREAD

**Issue by krisimmig** [middleman/middleman#1263]
I have a problem with i18n strings in blog pages/partials. If I use i18n in those files, they produce an error message: "translation missing: false.string.iam.looking.for

in the regular pages, everything works as expected.

all partials or pages that get called/created from the blog layout file don´t work with i18n. Partials that I load from the main layout file do work. 

i18n settings: 

``` ruby
activate :i18n, :mount_at_root => :false, :path => ":locale", :langs => [:de, :en]
```

blog setting:

``` ruby
activate :blog do |blog|
  blog.layout = "work"
  blog.permalink = ":lang/work/:title.html"
  blog.sources = "work/:lang-:title.html"
  blog.per_page = 999
end
```

Have I missed a setting to make this work?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

I'd suggest closing this issue. If the problem resurfaces a repro or failing test would increase the chances of finding and solving the issue.
