### ISSUE TITLE
Trouble with building MS Excel file

### ISSUE THREAD

**Issue by biblichor** [middleman/middleman#1264]
Have a trouble when building, Microsoft Excel files get broken.
No error stack trace is shown, but the files are unable to open and get small size.
Strangely, It is occurred not in old Excel files(.xls), but only in new Excel files(.xlsx)

**Comment by takuan-osho** [comment]
Is there any progress?

**Comment by tdreyno** [comment]
No, I don't use windows. Happy for any PR or exploration to help.

**Comment by Arcovion** [comment]
Fixed in https://github.com/middleman/middleman/pull/1741

**Comment by takuan-osho** [comment]
@Arcovion Thanks!
