### ISSUE TITLE
Support for including css_splitter gem

### ISSUE THREAD

**Issue by bluerouse** [middleman/middleman#1273]
Dear Middleman-Team
As mentioned here https://github.com/zweilove/css_splitter/issues/31 I'd need some help for including this gem. It would solve exactly my issue, but i didn't reach to configure and initialize correctly. My project now bundles correctly and middleman starts, but the precompile configuration and the split_stylesheet_link_tag-helper don't work yet. 
Could you help me, where to start including this functionality?
Thanks a lot for your support!

**Comment by Tuckie** [comment]
@bluerouse: could I ask for a working example of that portion of your config.rb?  I'm currently getting the error ```undefined method `register_bundle_processor' for #<Middleman::Sprockets::ConfigOnlyEnvironment:0x00000004a3f3a0>```

**Comment by bluerouse** [comment]
@Tuckie 
I got the following in my config.rb:

```
require 'active_support/all'
require 'css_splitter/splitter'
require 'css_splitter/sprockets_engine'
sprockets.register_bundle_processor 'text/css', CssSplitter::SprocketsEngine
```

**Comment by Tuckie** [comment]
Thanks! I wasn't able to get it to work once I moved it inside the `ready` block in the config file, although I'm not sure if that was the best place for it.  (running 3.3.7)

**Comment by maxmeyer** [comment]
@tdreyno 

Looks like an issue for the `middleman-guides` would you mind to introduce a label for that?
