### ISSUE TITLE
Compass helper `image-url()` returns broken URLs when `relative_assets` and `debug_assets` are activated

### ISSUE THREAD

**Issue by lolmaus** [middleman/middleman#1299]
With `realtive_assets` and `debug_assets` disabled, this line of Sass:

``` sass
background-image: url('foo.png')
```

results in this string:

``` css
background-image: url("/__assets/images/foo.png");
```

This URL works fine, the image gets displayed.

With `realtive_assets` and `debug_assets` activated, the same line of Sass results in the following CSS:

``` css
background-image: url("__assets/images/foo.png");
```

According to [CSS spec](http://www.w3.org/TR/2011/REC-CSS2-20110607/syndata.html#value-def-uri), relative URLs are defined relative to the location of the CSS file. With the CSS file being located at `/__assets/stylesheets`, browsers would look for the image at the following URL:

```
http://localhost:4567/__assets/stylesheets/__assets/images/foo.png
```

The described behavior is identical for both Compass 0.12 and 1.0.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets. Does that help with this?
