### ISSUE TITLE
loading scripts from bootstrap-sass gem

### ISSUE THREAD

**Issue by NARKOZ** [middleman/middleman#1302]
When I require bootstrap javascripts via `//= require bootstrap` in `all.js` 
I get this content in `/javascripts/all.js` as a result:

```
throw Error("ArgumentError: wrong number of arguments (4 for 1)\n  (in /Users/user/Development/middleman-project/source/javascripts/all.js:1)")
```

Loading stylesheets from the same gem works as expected.

**Comment by NARKOZ** [comment]
I'm getting this error whenever I create a new app. This is an issue with middleman. 
Btw I'm using Mac OS.

**Comment by jarednorman** [comment]
Fine, I'll fix this. PR incoming in like 2 minutes.

**Comment by tdreyno** [comment]
Thanks for tracking down @jarednorman
