### ISSUE TITLE
Different URL for different languages

### ISSUE THREAD

**Issue by jvaclavik** [middleman/middleman#1306]
Is there a way how to do it different URL for different languages? 
For example:

/en/sightseeing
/cs/zajimavosti
/de/sehenswurdigkeiten

instead of:
/en/sightseeing
/cs/sightseeing
/de/sightseeing

**Comment by robertwbradford** [comment]
I wrote this helper which seems to work:

    # Returns a hash of localized paths for a given page. Handy for use in a language selector.
    def localized_paths_for(page)
      localized_paths = {}

      (langs).each do |locale|
        # First look to see if locale version for the page exists:
        locale_version_of_page = sitemap.resources.select do |resource|
          # Find a page that matches the same file name with only the locale portion replaced
          resource.proxied_to == page.proxied_to.gsub(".#{page.metadata[:options][:lang]}.", ".#{locale}.")
        end.first

        # If it exists, populate the localized_paths hash.
        localized_paths[locale] = locale_version_of_page.url if locale_version_of_page
      end

      localized_paths
    end

This method assumes the source files for the different locale versions are similarly named and any path translations are handled in the locale file (See https://middlemanapp.com/advanced/localization/#localizing-paths). For example:

    localizable/
      |-- some-directory/
      |     |-- some-page.en.html.md
      |     +-- some-page.es.html.md
      +-- another-directory/
            |-- another-page.en.html.md
            +-- another-page.es.html.md

I don't know if using the `proxied_to` method is a robust enough choice for everyone, but it seems to work for my setup. You can see I'm just swapping the ".locale." portion of the source file name when searching. I thought a regex replacement might be a better choice, but who knows what file names people might have with all the template extension chaining.

I then have a `_language-selector.erb` partial with the following:

      <% localized_paths_for(current_page).each do |text, path| %>
        <%= link_to text, path %>
      <% end %>

This displays the locale abbreviations as the text for the links. You can probably then use the `I18n.translate` method to display the actual languages.

**Comment by joallard** [comment]
You might be interested in giving some feedback on #1466 then maybe

**Comment by robertwbradford** [comment]
@joallard This weekend is pretty full right now, but I will take a look when I have a chance. 

My helper above may need some refactoring because building will throw errors on any templates that are located in the root of `source/`. However, since this is for use on a site that has i18n, I'm assuming all the templates would be located in the `source/localizable/` directory, and these work fine. (Although did I read the `localizable` directory is going away in a future version?

Anyway, I'll take a look at #1466...

**Comment by joallard** [comment]
Yep, with I18n activated we're just going to assume it is localizable unless we have metadata to the contrary (iirc)

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! While I think it's a good idea, I'd suggest either closing this issue or submitting a PR with an implementation.

Also, the good suggestions by @lolmaus and @robertwbradford should also work!
