### ISSUE TITLE
Partial of the same name as page produces an infinite loop when `partials_dir` is set: ruby_executable_hooks:15: stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by lolmaus** [middleman/middleman#1316]
This bug was discovered by @mkmd and pinned down by me.
## Take 1 (works fine)
1. Create a blank Middleman project.
2. Create a `source/_index.erb` partial.
3. From `source/index.html.erb`, call this partial with:
   
   ```
   <%= partial :index %>
   ```
4. Run `bundle exec middleman build --verbose` and see it work fine.
## Take 2 (works fine)
1. Move the partial into a `source/partials/` subfolder.
2. Adjust the call to the partial in `source/index.html.erb`:
   
   ```
   <%= partial 'partials/index' %>
   ```
3. Run `bundle exec middleman build --verbose` and see it work fine.
## Take 3 (fails)
1. Keep the partial as `source/partials/_index.erb`
2. Adjust the default path to partials in `config.rb`:
   
   ```
   set :partials_dir, 'partials'
   ```
3. Adjust the call to the partial in `source/index.html.erb`:
   
   ```
   <%= partial :index %>
   ```
4. Run `bundle exec middleman build --verbose` and see it fail with:

> /home/lolmaus/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15: stack level too deep (SystemStackError)
## Notes

The bug does not appear in development, only during build.

Minimal demo project: https://github.com/lolmaus/middleman-recursion-test/

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

`partials_dir` was removed in 4 (https://middlemanapp.com/basics/upgrade-v4/). I'd suggest closing this issue.
