### ISSUE TITLE
Non-template partials (e.g. HTML, SVG) with _underscore names fail

### ISSUE THREAD

**Issue by tdeck** [middleman/middleman#1330]
The new functionality for including arbitrary files using the partial directive is really helpful to me, but it doesn't seem to work if you name the included file according to the underscore convention. If I have a file called _snippet.html, I get separate errors when trying to include it using either `partial '_snippet.html'` and `partial 'snippet.html'` (`partial 'snippet'` doesn't work either, but I assume that's by design).

I dug around and wrote some failing tests to demonstrate this issue in [my own branch](https://github.com/tdeck/middleman/tree/underscore-partials), but haven't had time to try to fix the issue.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! While I think it's a good idea, I'd suggest either closing this issue or submitting a PR with an implementation.
