### ISSUE TITLE
Sitemap::Resource#render does not return the correct current_page variable

### ISSUE THREAD

**Issue by tmaier** [middleman/middleman#1340]
## Problem

Given I have a page (Page A) where I want to do something like this:

``` ruby
resources = []
sitemap.resources.dup.each do |resource|
  resources << resource.render(layout: false)
end

{ entries: resources }.to_json
```

and a page (Page B) where I use something like this

``` haml

---
my_special_variable: true

---
- raise unless current_page.data.my_special_variable
```

This would raise an error when calling page A but not when calling page B.
## Reason

`current_page` (or better `current_path`) when rendering Page B still refers to the original Page A.

`app.current_path` won't be changed when calling `resource.render`.
https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-core/sitemap/resource.rb#L124
## Proof

Change Page A to 

``` ruby
resources = []
resources << current_path
sitemap.resources.dup.each do |resource|
  next if resource.url == '/page_a.html'
  resources << resource.app.current_path
end
resources << current_path

{ entries: resources }.to_yaml
```

The result would be something like this

``` yaml

---
:entries:
- page_a.html
- page_a.html
- page_a.html
- page_a.html
- page_a.html
- page_a.html
```

Expected would be

``` yaml

---
:entries:
- page_a.html
- page_b.html
- page_c.html
- page_d.html
- page_e.html
- page_a.html
```
## Suggested solution

Temporarily change `resource.app.current_path` within the `#render` method

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! This should work in v4. If not a a PR with a failing test would be a great start.
