### ISSUE TITLE
Handling assets with external build

### ISSUE THREAD

**Issue by oskarrough** [middleman/middleman#1345]
Hi, this might be out of scope but I'd like to keep using my Gulp/Grunt setup for handling assets and the server. This way I wouldn't have to adapt my knowledge to a new system. What I would like to keep from Middleman is the way it handles layouts, markdown files, urls, middleman-navtree etc.

Is there a way to disable Middleman touching my assets? Perhaps I just need clever folder structure?

**Comment by sandstrom** [comment]
I think this is solved in https://github.com/middleman/middleman/pull/1321
