### ISSUE TITLE
hang when query is passed a non-existent method

### ISSUE THREAD

**Issue by docwhat** [middleman/middleman#1353]
This should work on any middleman setup:

```
[0] pry(#<Middleman::Application::MiddlemanApplication1>)> sitemap.where(bogusattr: 'value').method_doesnt_exist
^CNoMethodError: undefined method `method_doesnt_exist' for #<Middleman::Sitemap::Queryable::Query:0x007ff40bdfd3e0>
from (pry):7:in `__pry__'
```

The `^C` is where I got bored and hit control-c.  As you can see, the proper exception (`NoMethodError`) pops up after that.  So it _knows_ something went wrong, but it just hangs instead of reporting it back.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! This should work in v4. If not a a PR with a failing test would be a great start.
