### ISSUE TITLE
middleman forced polling cranks up CPU

### ISSUE THREAD

**Issue by toobulkeh** [middleman/middleman#1360]
As I discussed 6+ months ago in [a different issue](https://github.com/middleman/middleman/issues/730), I use middleman inside a vagrant VM which requires force-polling to update pages properly. It's not only slow, but it kills the VM's CPU or disk usage which in turn ramps up my laptops' fans because the battery starts draining like crazy.

Any ideas how to fix this?

**Comment by marclennox** [comment]
I'm trying to run middleman using boot2docker and fig, with the source code being host-mounted back to osx.

This setup works extremely well with my Rails application.  File changes are picked up immediately.

The same setup with middleman does not pickup file changes, I have to restart the middleman server every time.

Any idea why it would work with Rails and not with middleman?  And is there any way I can just tell middleman to reload files on every request?

**Comment by tdreyno** [comment]
Not sure. Pretty sure we use the same file watcher.

**Comment by marclennox** [comment]
I seem to have it working well now with --force-polling turned on.

**Comment by makeaweli** [comment]
Vagrant using VirtualBox with the default shared folders never worked for me with Middleman server. force polling fixes this but always maxes out the CPU.

Reconfiguring Vagrant to use rsync works amazingly well. AND, you don't need to use force polling with middleman server. The only drawback is that the rsync only works one-way, so make sure to deploy direct from Vagrant or revert back to shared folders to grab your build.

**Comment by marclennox** [comment]
@makeaweli I recently came up with a better approach than "force polling".  I'm using docker and docker-compose to run my development environment (which uses Virtualbox in the background), so I created an additional docker container which runs unison sync (bi-directional) to continually sync my local sandbox into a docker volume container.

It's working really well for me, allowing me to edit locally but have changes recognized by middleman (and other processes) running in the virtualbox vm.

**Comment by makeaweli** [comment]
Great to hear unison is working well for you!

Unison was my first thought when encountering the rsync one-way issue, but I was scared off by comments about bad performance with the unison vagrant plugin.

**Comment by toobulkeh** [comment]
@marclennox - do you still use unison / docker / virtualbox?

I'm re-investigating replacing our vagrant stack as we move to more front-end development where this problem (inotify not working over NFS shared folders) is causing us headache.

**Comment by marclennox** [comment]
Hi @toobulkeh.  No I do not.  Docker machine and compose have gotten a lot more stable since, so I use that in conjunction with a very excellent project called dinghy (https://github.com/codekitchen/dinghy).  Dinghy basically ties up all the loose ends for developing in Docker on a mac, I highly recommend it.

**Comment by toobulkeh** [comment]
Thanks for the reference! I'm trying out https://github.com/adrienkohlbecker/vagrant-fsnotify, but am running into some problems / limitations. I'd love to give docker a try eventually and that pushes me in that direction.

Thanks again!
