### ISSUE TITLE
Helpers automatically included in templates but not partials.

### ISSUE THREAD

**Issue by michaelbarton** [middleman/middleman#1361]
I believe I have found a bug where helpers are not automatically included in partials. I have a helper in the file:

./helpers/page_helpers.rb

I _can_ use the methods in my templates without a problem, however I get a "method not found: error if I try to use a method from this helper in a partial. To make the method available I have to do the following in my config.rb:

require "helpers/page_helpers"
helpers PageHelpers

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.
