### ISSUE TITLE
No filename in output for gzip [master]

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1364]
On `master`, when I have `:gzip` extension activated, I get "gzip" status lines but no filename prints.

**Comment by bhollis** [comment]
This still happens in v4.0.0.

**Comment by tdreyno** [comment]
I didn't look into it :( Bad maintainer, bad! Thanks for bumping

**Comment by iiska** [comment]
I did encounter this one too. Please see if my patch at #1763 is something you would use to fix issue.

**Comment by tdreyno** [comment]
Closed here: #1763 

Thanks @iiska
