### ISSUE TITLE
Partials do not work [master]

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1366]
This is on Middleman `master`.

In a template `index.html.haml`, I have:

```haml
= partial 'nav'
```

In the same directory, I have a file `_nav.html.haml`. The partial is not included in the output, but there is no error or warning.

**Comment by dperrymorrow** [comment]
@bhollis looks like there is a test for this that is passing. Any idea why the test does not catch this extension naming issue? Is it specific to just HAML partial rendering?

https://github.com/middleman/middleman/blob/master/middleman-core/features/chained_templates.feature#L58

**Comment by tdreyno** [comment]
I think this was to accommodate non-template partials (static includes like inline SVG). Not sure if it was intentional.

I think that test make not be testing having a "static" extension in the chain. So `erb.haml` would work, but not `html.haml`

**Comment by dperrymorrow** [comment]
gotcha, thanks

**Comment by samme** [comment]
I believe I'm seeing this in MM 4.1.1: no partials are rendered (as `_partial.haml`) but there's no error or warning.

**Comment by tdreyno** [comment]
@samme full path relative to `source` is required now. What's the full path of `_partial.haml` and the template code that calls it?

**Comment by samme** [comment]
Ah, I had been using `set :partials_dir, "partials"` and `= partial "partial"` (for `source/partials/_partial.haml`). Removed `:partials_dir` and moved partials to `source/` and it works now. Strange it didn't give me an error before though.

**Comment by tdreyno** [comment]
`partials_dir` is gone in v4.
