### ISSUE TITLE
i18n multiple root languages for deployments with multiple hostnames

### ISSUE THREAD

**Issue by leighmcculloch** [middleman/middleman#1378]
It's not uncommon to do i18n across domains where each localization of the website is hosted at root but on different hostnames. It'd be cool if this is a feature of i18n.

With v3 I'm achieving this with an environment variable that defines which language I'm building for, and a different S3 bucket for each, but this is super hacky and I think there's a clean way to build this into the standard i18n functionality or as an extension that's much cleaner.

I'm interested in contributing this as an extension once the v4-i18n refactor has taken place if it doesn't make sense to be a core feature.

**Comment by sisihagen** [comment]
Hello,

Has anyone found a solution which he would share public? I have the same problem like @leighmcculloch , three languages and all sharing the style sheets, images, etc. I has looked over the github repo of Leigh, but as non programmer is not easy understand what is work there. 

Were nice someone share the result if have found. At moment i use 3 middleman installation and stylesheets etc. must optimize with extern tools. Middleman is powerful tool but for non coder little harder. 

Silvio

**Comment by tdreyno** [comment]
I do this using ENV vars these days and use a shell script or Rake to basically run `LANG=en middleman build` multiple times which varying the LANG.
