### ISSUE TITLE
Can't enable compass sourcemap

### ISSUE THREAD

**Issue by judewang** [middleman/middleman#1387]
Hi, I want to use sass and compass sourcemap feature with Middleman, but just can't get it to work.
I'm using middleman v3.3.6 and I saw compass is on v1.01, sass is v3.4.5.
Here's the config.rb's code:

```
set :sass, sourcemap: true
compass_config do |config|
  config.sourcemap = true
end
```

By the way, setting `debug_assets` to true will make sense when using `#=require` in scss files, but I'd rather use `@import` to import sass partials and it needs sass sourcemap to debug.

Thanks.

**Comment by Swelly** [comment]
Hey @tdreyno I wanted to know where I should look to get sourcemaps enabled with a middleman server. Any ideas?

**Comment by tdreyno** [comment]
I've started using external tools (like gulp) inside Middleman for this kind of stuff. Compass/Sass never really gave us an API to get source maps from them.

**Comment by Swelly** [comment]
Thanks for the response. Any solid repos out there to gain information from as to how I'd setup Gulp with Middleman? I'll get on my google fu for now.

**Comment by sandstrom** [comment]
@Swelly You can use the *external* feature from Middleman V4 ([More details here](https://github.com/middleman/middleman/pull/1321)).

I think v4 will be released soon (I'm eagerly waiting! :smile:), but I don't know the exact planned release date.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets. I'd suggest closing this issue.

**Comment by judewang** [comment]
I'm now using webpack with Middleman.
