### ISSUE TITLE
I18n: Localized paths helper and frontmatter keys

### ISSUE THREAD

**Issue by joallard** [middleman/middleman#1390]
I've done a bit of reading in the issues, and I think it's time I bring up my pet enhancement in Middleman, which is out-of-the-box link helpers for localized paths. I even want to go a step further, which is to make it work without putting the paths in the dictionary.

We've discussed refactoring in depth in #924, but I think that this enhancement warrants its own issue as I18n is a bit of a mega-feature. Multiple people also seem to have raised such a need, such as #1146, #1306.

Here are the end goals I see:
- Have the possibility to easily link to localized content in a language-agnostic way, ie. in a layout nav
- Install a locale switcher link, which would link to the same resource, if available, in the target locale
- Not relying on the locale dictionary to make this work

The alternative I'd suggest to putting paths in the locale file is this: Put a frontmatter key on localized pages that would identify pages. If no key is there, the extensionless path of the page is assumed.

In Gherkin terms, here's what I have in mind:

``` gherkin
    Given an i18n fixture app
    And a file named "config.rb" with:
      """
        activate :18n
      """
    And a locale dictionary like:
      """
        en:
          about: About
        fr:
          about: À propos
      """
    And a layout file with:
      """
        <%= link_to t(:about), locale_path(:about) %>
      """
    And a file named "about.en.html.erb" with:
      """
        Here's what it's all about
      """
    And a file named "a-propos.fr.html.erb" with:
      """
        ---
        key: about
        ---
        Voici ce que nous faisons
      """
    Given the server is running
    When I go to "/"
    And I click on "About"
    Then I should see "Here's what it's all about"
    When I go to "/fr/"
    And I click on "À propos"
    Then I should see "Voici ce que nous faisons"
```

I realize `key` is probably not the ideal... uh... key.

In code terms, the `localization_data` hash seems like the perfect place to store this kind of info.

I'd contribute it myself, I just need to know if my approach is the one we want to take. I'm also a bit disoriented about where to put my fixtures and tests, but nothing impossible!

Time for feedback!

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation.

**Comment by Dalpatgohil115** [comment]
Set it
