### ISSUE TITLE
Supporting srcset attribute analogously to src attr in image_tag

### ISSUE THREAD

**Issue by komor72** [middleman/middleman#1396]
There is a relatively new [srcset](http://caniuse.com/#feat=srcset) attribute in `img` tag that can be useful for HiDPI/Retina devices and is the second easiest way to support them. To properly use it in Middleman it should be handled analogously to `src` attribute (supporting relative/absolute paths computing). Unfortunately it also means hacking it in Markdown engines and other high-level HTML-abstractions plugged into Middleman.

I'm considering an example with extended syntax using [attribute list definition](http://kramdown.gettalong.org/syntax.html#attribute-list-definitions) from Kramdown:

``` markdown
![Alternative text](/folder-relative-or-absolute/image.jpg "Title attribute"){: srcset="/folder-relative-or-absolute/image@2x.jpg 2x"}
```

This should generate (in case of relative paths enabled and Markdown source 1 folder deeper than image folder):

``` html
<img alt="Alternative text" title="Title attribute" srcset="../folder-relative-or-absolute/image@2x.jpg 2x" src="../folder-relative-or-absolute/image.jpg">
```

The generated path in `srcset` attribute of `img` tag should be computed relative/absolute-wise the same way as `src` is. Currently it’s not, so the `../` part is missing, I only get `/`. To make things more difficult the syntax of `srcset` is quite flexible and contains more than a path, in the simpliest case.

Any hope?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Did the suggestion by @tdreyno work? If so, can this be closed?

**Comment by komor72** [comment]
Wow, I haven’t seen **dperrymorrow**’s commit. Will check if it works (in MM 3.4.1) any time soon. Unfortunately I’m a occasional user (and don’t use MM4 in any project yet, at least not untill some crucial gems are compatible).
