### ISSUE TITLE
i18n available locales

### ISSUE THREAD

**Issue by alem0lars** [middleman/middleman#1418]
There's a discrepance between values returned by the middleman's builtin helper `langs` and the i18n gem's method `I18n.available_languages`.

I've activated the extension:
```Ruby
activate :i18n, mount_at_root: :it
```
This is what `langs` gives me:
```Ruby
langs
# => [:en, :it]
```
in fact I have yamls only for languages `:it` and `:en`

This is the value of `I18n.available_languages`:
```Ruby
I18n.available_locales
# => [:en, :cs, :da, :de, :es, :fr, :hu, :it, :ja, :lv, :nl, :no, :pl, :pt_br, :ro, :ru, :sv, :tr, :uk, :zh_cn, :zh_tw]
```

Maybe the two values should be kept in sync?
Why there isn't *only* `I18n.available_locales`?

Ty

**Comment by tdreyno** [comment]
I think `I18n.available_locales` refers to all the langs Padrino has localized its helpers in. We can't control `I18n` as it is global. Our `i18n` extension should be considered canonical.
