### ISSUE TITLE
Ignores for project templates (or a dedicated folder for template content)

### ISSUE THREAD

**Issue by mojavelinux** [middleman/middleman#1419]
In order to ensure we generate a clean project from a project template, there needs to be a way to tell middleman to ignore certain files and folders when generating a project from a project template.

I'll provide two examples.

(1) Project templates are usually stored in git. When we generate the project from the project template, we don't want to bring over the .git directory. The project needs to start out without a .git directory, or a .git directory that was created for the new project.

(2) Project templates have auxiliary files like a README or LICENSE file that are for the project template, not for the generated project.

One way to solve this issue is to introduce a convention that the content for the project template is tucked away under a subfolder in the template project. That way, there is a clean separate between what is template content and what is content for the template project.

**Comment by mojavelinux** [comment]
To be it in other terms, I'm getting a lot of junk in the generated project that I don't want using the current approach.

**Comment by tdreyno** [comment]
This makes total sense. I think the subfolder idea works best.

**Comment by tdreyno** [comment]
Changed my mind on this. Basically, repos will continue to act as simple clones *unless* a `Thorfile` is present. If it is, control is handed off to that script which can do any custom processing it wants. For example: https://github.com/middleman/middleman-templates-default

**Comment by mojavelinux** [comment]
Nice! That was the hook I was looking for. Thanks!

**Comment by pzi** [comment]
Hey @tdreyno 

is the Thorfile support only in Middleman v4+ ? I have added [the Thorfile](https://github.com/middleman/middleman-templates-default/blob/master/Thorfile) from the `middleman-templates-default` into my [middleman-basis](https://github.com/pzi/middleman-basis/tree/feature/thorfile) template but to no avail.

Appreciate your support.

Cheers

Patrik

**Comment by tdreyno** [comment]
Yes, it is 4+

**Comment by pzi** [comment]
Ok, time to update my template then :) Couldn't find a straightforward answer without digging through codebase.

Thanks for the reply!
