### ISSUE TITLE
Error in asset pipeline docs?

### ISSUE THREAD

**Issue by dcosson** [middleman/middleman#1420]
Hi, not sure if this is a bug, an error in the docs, or I'm just misreading the docs. In the [asset pipeline helpers section](http://middlemanapp.com/basics/asset-pipeline/#helpers) it says:

Those helpers prepend the correct directory/url to your asset, e.g. `image-path('lightbox2/img/close.png')` becomes `images/lightbox2/img/close.png`. To reference a bower controlled asset you need to use its relative name `lightbox2/img/close.png` for an image which is part of the `lightbox2`-component.

That second sentence reads to me like images in bower components should just work if you try to access them with `image-url()` in scss, but that's not the behavior I'm seeing. I'm needing to explicitly import all images from bower components with `sprockets.import_asset`.

**Comment by tdreyno** [comment]
You are correct, you must import assets outside of your `source` directory. I think those docs are unclear.

**Comment by dcosson** [comment]
Thanks for clarifying
