### ISSUE TITLE
in v4, Util.recursively_enhance returns nil if given string

### ISSUE THREAD

**Issue by stevenosloan** [middleman/middleman#1421]
This causes it to return an array of nils if given an array. It looks like  `#recursively_enhance` from Middleman's [`HashWithIndifferentAccess`](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/util/hash_with_indifferent_access.rb#L87-L100) has the correct behavior returning the original data if it isn't a Hash or Array. Not sure if there was a reason for the different implementations, but:

```ruby
Middleman::Util.recursively_enhance ['foo', 'bar']
# => [nil, nil]

Middleman::Util::HashWithIndifferentAccess.new.send(:recursively_enhance, ['foo', 'bar'])
# => ['foo', 'bar']
```

So if you have a data file that's just an array:

```yaml
# data/foo.yml

- foo
- bar
```
You'll just get an array of nils when accessing it via `data.foo`.

**Comment by tdreyno** [comment]
Looks like a bug, thanks.

**Comment by stevenosloan** [comment]
fixed with that PR, thanks @tdreyno
