### ISSUE TITLE
Sitemap.resource array reversed when building 

### ISSUE THREAD

**Issue by olliekav** [middleman/middleman#1423]
This is a really odd one, I've tried to debug as best I can but I can't find the issue. I'm building a sitemap.resource array for some page navigation for a portfolio. So using the code below...
```
<% work_pages = sitemap.resources.select{|p| p.data.type == "work-item" } %>
<ul class="work-nav">
  <% work_pages.each_with_index do |p, index| %>
    <% if p.url == current_page.url %>
      <% next_page = work_pages[index+1]  %>
      <% prev_page = work_pages[index-1] %>
      <li class="prev"><%= link_to("<span>Prev</span> «", prev_page.url) unless index == 0 %></li>
      <li class="next"><%= link_to("<span>Next</span> »", next_page.url) unless index == work_pages.size - 1 %></li>
    <% end %>
  <% end %>
</ul>
```
I'm dynamically generating these pages using the following code and adding some front matter to the layout template to only pull through those pages.

```
data.work_items.clients.each_with_index do |client, index|
  proxy "/work/#{client.url}.html", "/work-item.html", locals: { 
    client: client
  }, :ignore => true
end
```

This works fine in development but when I build the site the array gets reversed in order. I'm currently having to hack it to reverse it in build.

```
<% if development? %>
  <% work_pages = sitemap.resources.select{|p| p.data.type == "work-item" } %>
<% elsif build? %>
  <% work_pages = sitemap.resources.select{|p| p.data.type == "work-item" }.reverse %>
<% end %>
```

Any ideas? My source code is available at https://github.com/thisiscapra/thisiscapra.com

**Comment by tdreyno** [comment]
Can you post the `.yml` file as well?

**Comment by tdreyno** [comment]
Oh, never mind. I'll look in to it.

**Comment by tdreyno** [comment]
Ah, okay, I know what this is.

The sitemap has no specific order, anything can add, remove or reposition anything else in the sitemap. In build, there is probably additional sitemap manipulators running and rearranging things.

You should sort the result of `select` to make sure it maintains the order you want.

**Comment by olliekav** [comment]
Ah okay, I'll give that a try. Thanks for looking into it, I thought I was going mad! Out of interest is there an easy way to sort by the current data yml order?

**Comment by tdreyno** [comment]
Order? The items in the sitemap are references to file paths usually. Do you have a list of resources elsewhere in yaml? In that case you could take that yaml array, and `map` it to individual sitemap resources and that would have the correct order.
