### ISSUE TITLE
Rewriting subdomain index page

### ISSUE THREAD

**Issue by iabdulin** [middleman/middleman#1425]
Does anybody know a way to make `subdomain.domain.com` display `/subdomain` page with Middleman?

I tried rack::rewrite with no success :(

```ruby
require 'rack/rewrite'
use Rack::Rewrite do
  rewrite   '/',  '/subdomain', :host => "subdomain.domain.com"
end
```

**Comment by tdreyno** [comment]
That is going to be webserver dependent. Do you know what system you're using? Mapping that is pretty easy with Apache/nginx and a built Middleman project.

Rack will only work if you're behind a Ruby server, which is not the suggested approach for Middleman. We suggest building to static and hosting that.

I'm going to close this ticket so it doesn't clutter up the actual bug list, but will happily continue responding on this thread if you have questions.

**Comment by iabdulin** [comment]
I am running a ruby webserver (thin or webrick, I don't remember exactly, but it's a default heroku ruby webserver, if you don't specify one in Procfile).

I was researching a way to list a specific page under website's subdomain... maybe there's another way, idk...
So, I need http://subdomain.ildar.ca to be different from http://www.ildar.ca

**Comment by tdreyno** [comment]
I'd suggest building the MM site on deploy (there are a bunch of Heroku tutorials for this) and then using Rack::Static to mount the path at the root. You'll want to be using `activate :relative_assets` to make the built site portable so the changing path doesn't cause problems.

Also, this: https://divshot.com/blog/hosting/dont-host-static-sites-on-heroku/

**Comment by iabdulin** [comment]
I'll with rack::static, thank you.

I prefer heroku, because my apps are there, and I just like to keep everything in one place (and it's free, you don't need a 2nd dyno to prevent sleeping). I build mm site on deploy and use absolute urls with cdn.

**Comment by dirkkelly** [comment]
@iabdulin how did you go with `Rack::Static`, I have similar opinions about sticking with Heroku and would like to serve subdirectories of the built MM from domains.

**Comment by iabdulin** [comment]
@dirkkelly sorry, I couldn't figure out how to make Rack::Static work, so I just added an internal page :)
