### ISSUE TITLE
Indent problems with pre tags (erb, ...) 

### ISSUE THREAD

**Issue by DrTom** [middleman/middleman#1428]
The output for the following erb code
~~~erb
<pre>1
2
3
</pre> 
~~~
is the following html
~~~html
      <pre>1
      2
      3
      </pre>
~~~~
This apparently messes up indention. It seems not to be an exclusive erb problem. I can reproduce the same with  kramdown e.g. too.

**Comment by lolmaus** [comment]
Not Middleman's fault, imo.

Haml has a [feature](http://haml.info/docs/yardoc/file.REFERENCE.html#whitespace_preservation) against this problem. There should be some solution for ERb as well.

**Comment by tdreyno** [comment]
@DrTom could you post a full example? Not sure when this would happen. Is there a wrapping layout involved?

**Comment by DrTom** [comment]
@lolmaus  Unlikely because erb should have not context about html like haml does.

**Comment by DrTom** [comment]
@lolmaus @tdreyno  Ah, there is twist here; the layout is haml. Could be that haml does even indent already rendered html which is just passed to it. I'll have a look into it.

**Comment by DrTom** [comment]
HAML is indeed the culprit. The problem disappears if I use an ERB layout instead.
@tdreyno  is there a global configuration to make HAML not indent?

**Comment by DrTom** [comment]
Solved: `set :haml, { ugly: true }` 
May this should find it's way into to middleman main documentation.
