### ISSUE TITLE
Middleman v4 issue with scss resources and compass sprites

### ISSUE THREAD

**Issue by vasco** [middleman/middleman#1432]
I needed to upgrade middleman from version 3 to 4 (currently in 4.0.0.alpha.6) because of https://github.com/middleman/middleman/pull/1293
I'm using jruby.

However this upgrade broke middleman `scss` resources when processing compass sprites, like:
```scss
@import "social/*.png";
@include all-social-sprites;
```

The sprite images are under `.../source/images/social`.

The following error message occurs when running `bundle exec middleman server -e <env>` or `bundle exec middleman build -e <env>` and middleman crashes:
```
File to import not found or unreadable: social/*.png.
Load paths:
  .../source/stylesheets
  .../jruby-1.7.11/gems/compass-core-1.0.3/stylesheets
```

My `config.rb` has:
```ruby
set :css_dir, 'stylesheets'
set :images_dir, 'images'
set :js_dir, 'javascripts'
set :fonts_dir, 'fonts'

sprockets.import_asset '<sass_file_that_raised_the_issue>'
```
I was forced to add `sprockets.import_asset '<sass_file_that_raised_the_issue>'` when I upgraded to middleman v4, because before that middleman didn't found the sass file.

I also tried to `sprockets.append_path` with and without a `after_configuration` instruction, but without any success either.

Is this a middleman v4 issue? Or am I doing something wrong?

**Comment by tdreyno** [comment]
Compass is in the process of removing their Sprite support. `v4` is using the latest Compass code with these changes.

They promise to pull that code into an extension, which we can then use to restore that functionality, but it's not ready yet :(

**Comment by vasco** [comment]
@tdreyno Thank you for your quick answer.

What's the recommended way to do sprites in scss pages (with middleman support)? I would be OK using other technology.

@tdreyno Do you know the time it may take to get all this working again?

**Comment by tdreyno** [comment]
I'd suggest staying on the stable releases until Compass finishes it's new sprite extension.

**Comment by vasco** [comment]
I need https://github.com/middleman/middleman/pull/1293 which is only available in v4.

@tdreyno Could you point me to the Compass issues?

**Comment by Arcovion** [comment]
The issue is here: https://github.com/Compass/compass/pull/1771
v4 isn't fully integrated with Sprockets yet, which is currently in beta. v4 itself is in alpha, so it's not ready for testing - many extensions will be incompatible and bugs inevitable.
