### ISSUE TITLE
Absolute URLs and URLs to different languages of some middleman page

### ISSUE THREAD

**Issue by vasco** [middleman/middleman#1433]
I'm running middleman to generate static websites with i18n support, and in all of the websites I have found the following needs:
* Having to do absolute links for pages that middleman is generating
* Having to do links to different languages of some page

Tu support that, I ended up creating the following methods:
```ruby
# URL_HOST is a constant that each environment must set
def absolute_url(path)
  [URL_HOST.gsub(/\/$/, ''), path.gsub(/^\//, '')].join("/")
end

def url_i18n(path, options={})
  lang = options[:lang] || options[:locale] || I18n.locale
  is_absolute = options[:absolute] || false
  langs = I18n.available_locales
  
  path_without_lang = path.gsub(/^#{langs.join('|')}\//, "")
  path = if I18n.default_locale == lang
    url_for(path_without_lang.gsub(/^([^\/])/,'/\1'))
  else
    url_for(["/#{lang}", path_without_lang.gsub(/^\//, '')].join("/"))
  end
  
  if is_absolute
    absolute_url(path)
  else
    path
  end
end
```

I did this because I didn't found a better way to do this with "middleman support". Is there a better a way?

**Comment by Arcovion** [comment]
See #1390
Currently you're limited to only the methods in `padrino-helpers` and `i18n`
Note i18n is being reworked a bit for v4, so you should stick with the stable branch (re: #1432)
