### ISSUE TITLE
Feature idea: Custom 404 pages in a live Middleman server

### ISSUE THREAD

**Issue by gabebw** [middleman/middleman#1436]
Hello! Middleman is excellent. We are running Middleman and noticed that the 404 page is hardcoded in `Middleman::CoreExtensions::Request`. I would love it if there were a configurable way to use a custom 404 page.

This is a little bit odd because (due to our custom setup around auto-publishing future-dated posts, which I swear makes sense), we aren't compiling the app before serving it, we are just running the app directly with caching in front of it. This means that the standard Rack-based 404 handling in e.g. https://github.com/indirect/middleman-heroku-static-app/blob/master/config.ru isn't viable.

So: What do you think about adding support for an optional custom 404 page?

It might look like this:

```ruby
page "/404.html", layout: false
# :404 is not a valid symbol, unfortunately
set :not_found_page, "404.html"
```

**Comment by gabebw** [comment]
Actually, I did get it working using plain ol' Rack, but it's a little ugly:

```ruby
class ServesA404
  def initialize(middleman)
    @middleman = middleman
  end

  def call(env)
    result = @middleman.call(env)
    status_code = result[0]
    if status_code == 404
      not_found_response
    else
      result
    end
  end

  private

  def not_found_response
    not_found_page = Tilt.new(File.join(__dir__, "source/404.html.haml")).render
    [404, { "Content-Type"  => "text/html"}, [not_found_page]]
  end
end

app = Middleman.server
run ServesA404.new(app)
```

**Comment by gabebw** [comment]
I'm closing this because after some refactoring, I have a neat little Middleware and just do `use Custom404`.

**Comment by maxmeyer** [comment]
Can you provide access to the refactored version? :smile:

**Comment by gabebw** [comment]
Oh yeah sure! It's two files.

```ruby
# custom404.rb
class Custom404
  def initialize(app, path_to_404_file)
    @app = app
    @path_to_404_file = path_to_404_file
  end

  def call(env)
    result = @app.call(env)
    status_code = result[0]
    if status_code == 404
      not_found_response
    else
      result
    end
  end

  private

  def not_found_response
    [404, { "Content-Type"  => "text/html" }, [not_found_page]]
  end

  def not_found_page
    Tilt.new(@path_to_404_file).render
  end
end
```

```ruby
# config.ru
require "rack"
require "middleman/rack"
require "./custom_404"

# This can be whatever, just make sure it points at a file that Tilt can render like Haml, Erb, etc
# Note that __dir__ is new in Ruby 2.0+
not_found_path = File.join(__dir__, "source/404.html.haml")

use Custom404, not_found_path

run Middleman.server
```

**Comment by tdreyno** [comment]
Nice!

**Comment by maxmeyer** [comment]
Thanks a lot.

**Comment by robertwbradford** [comment]
I'm wondering if there is a way to still have the 404 page use one of the layouts from `/source/layouts`. I see the `not_found_page` method for rendering the 404 page. On the site I'm working on, I would still like this 404 page wrapped with my `layout.erb` file so it includes the header, footer, etc. Is this possible?

**Comment by tdreyno** [comment]
You could do some nasty ruby monkey patching, but otherwise that method isn't supposed to be public. What's the goal of having 404 pages in dev mode?

**Comment by marianoviola** [comment]
@robertwbradford I used the @gabebw middleware with an already rendered page, just changing a bit the   `not_found_page` method:

```ruby
def not_found_page
  if File.exist?(@path_to_404_file)
    File.open(@path_to_404_file, 'r').readlines.join
  end
end
```
and then:

```ruby
not_found_path = File.join(__dir__, "build/404.html")
use Custom404, not_found_path
```

I tested it in production with Phusion Passenger and it seems to work.

**Comment by tdreyno** [comment]
Awesome, nice approach

**Comment by robertwbradford** [comment]
When I posted, before I think it was at the end of a long day :) I realized now that all this is for a site that is running from a Rack server and will not be useful for a "built" static site. I ended up just creating a `source/localizable/404.html.erb` page (I'm using I18n), and will figure out a way to have my serve display that when a 404 is encountered.
