### ISSUE TITLE
tests are failing

### ISSUE THREAD

**Issue by kubenstein** [middleman/middleman#1437]
hi,
i noticed that even badge says everything is green, tests are actually failing:
https://travis-ci.org/middleman/middleman

after debugging i found that aruba gem has changed and now method `check_file_content` expects regexp for partial matching:
https://github.com/cucumber/aruba/blob/master/lib/aruba/api.rb#L374

previously, so in version 0.5, it was done automatically: https://github.com/cucumber/aruba/blob/v0.5.4/lib/aruba/api.rb#L150

in my middleman extension i just set `'~>0.5.4'` as an aruba version, and i suggest doing this here as well.

**Comment by Arcovion** [comment]
This is fixed on `master`, needs to be backported:
```
git cherry-pick f027137
```

**Comment by tdreyno** [comment]
Ah, good catch. Will back port this.

**Comment by kubenstein** [comment]
i just wanted to be sure you are aware of this aruba thing. anyway thank you maintaining middleman and please feel free to close this issue.
