### ISSUE TITLE
undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by andreamoro** [middleman/middleman#1438]
Every time I try to use the each method in attempt to loop a collection I get the error message
    `undefined method `each' for nil:NilClass`

In this case, I am using the following bit

	<% current_page.data.ingredients.each do |ingredient| %>
          <li><%= ingredient %></li>
        <% end %>

to get access to a list of ingredients in the YAML section of a partial file being included in a template.

Any hints?

P.S. I'm getting other similar errors when trying to use the collection if saved in the data folder too (despite some copy and paste of apparently working examples).

**Comment by Arcovion** [comment]
Partials don't support frontmatter, so when you render the partial into the current page it's not adding any data to `current_page.data`.
Using a YAML file in the data folder should be working though, a `data/ingredients.yml` file is accessible via `data.ingredients`.

**Comment by andreamoro** [comment]
Thanks @Arcovion 

I arrived to that conclusion, but unfortunately can't get any data/files.yml processed as I always get error in accessing to them.

Say a file called list.yml with my "header" set to ingredients, when accessed to data.list.ingredients I get an error that list is not defined.
Should lists be activated in some way?

**Comment by Arcovion** [comment]
This should work:

`data/list.yml`:
```yaml
ingredients:
  - one
  - two
  - three
```

`page.erb`:
```erb
<% data.list.ingredients.each do |ingredient| %>
  <li><%= ingredient %></li>
<% end %>
```

**Comment by andreamoro** [comment]
Regrettably it doesn't

`Request: /index.html error  build/index.html
undefined method `list' for #<Middleman::CoreExtensions::Data::DataStore:0x007fca63290d30>
/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/data.rb:167:in `method_missing'

**Comment by lolmaus** [comment]
I think this should help you: https://github.com/middleman/middleman/issues/1189#issuecomment-36027155

**Comment by andreamoro** [comment]
Silly me ... I didn't read your edit from mobile. It's the data folder. I thought this was supposed to be nested in the source folder, whereas - as you said - this should be at the same level.
All works now. 
Sorry for the bother.
