### ISSUE TITLE
Timeline for v4

### ISSUE THREAD

**Issue by sandstrom** [middleman/middleman#1440]
Is there a timeline for v4? Some of the labeled issues (https://github.com/middleman/middleman/labels/v4) are pretty old, is that still the relevant todo for v4?

Perhaps the scope could be limited to allow for a smaller, but quicker, release?

I"m eager to see it coming to life, mostly because of this feature: https://github.com/middleman/middleman/pull/1321

**Comment by tdreyno** [comment]
Hoping for a `v4` beta really soon now. Got to ship 2 projects at work in the next 2 weeks, so I'm avoiding compounding that with OSS bugs as well.

That list is valid. i18n won't make it into beta 1 and will probably become and extension again. The rest are nice-to-haves and not blocking.

**Comment by sandstrom** [comment]
Ah, sounds good! I'm looking forward to 1321 :smile:
