### ISSUE TITLE
Package with Traveling Ruby

### ISSUE THREAD

**Issue by FooBarWidget** [middleman/middleman#1441]
Not all of your users are Ruby programmers, and those who are not Ruby programmers may have trouble installing Middleman. Maybe you can package Middleman with [Traveling Ruby](http://phusion.github.io/traveling-ruby/) to solve this problem.

**Comment by tdreyno** [comment]
Never heard of it, but looks awesome

**Comment by rriemann** [comment]
> Traveling Ruby lets you create self-contained Ruby app packages for Linux and OS X.

I think it would be much more important to ease the install on Windows platforms. Installing Middleman on a recent Linux maschine is actually already super easy and if something is missing, one would probably have a look to write some more details docs, wouldn't you? However, I have no experience on Mac.

**Comment by tdreyno** [comment]
@rriemann And I have no experience on Windows :) I would absolutely love any assistance and direction you can given to improve the Windows platform situation.

**Comment by Arcovion** [comment]
Luckily Middleman has no dependencies with C extensions (except `wdm` which is optional), so on Windows you literally just have to click `Next` on RubyInstaller, type `gem install middleman` and everything works.

The premise of Traveling Ruby is that Ruby itself is difficult to install... it's specifically for non Ruby users. With that in mind, I think we would do better to just tell people how to install Ruby in the Middleman README.
I've never had any trouble installing Ruby though personally, this is a non-issue IMO. Windows is trivial and I just use RVM on Linux which equates to three lines in bash. You may need XCode first on OS X but that's a given.

Also I don't think this lets you add gems and extensions like `middleman-blog`, nor would it work with any that have their own C extensions. Correct me if I'm wrong, but this looks like it's designed more for self contained apps that don't give users their own Gemfiles etc.

**Comment by FooBarWidget** [comment]
@rriemann It's important even outside Windows. Installing a Ruby app on Linux using RubyGems is easy for Ruby programmers, but all other users struggle with it.

A good example is [BOSH](https://blog.starkandwayne.com/2014/12/24/traveling-bosh-cli-no-more-installation-pain/). BOSH is a Ruby tool but they have lots of non-Ruby-programmer Linux users, and they often see how such users struggle with installing BOSH.

Another good example is Chef, which suffered from damage reputation due to the installation path. Chef provides platform-specific packages nowadays (RPMs, DEBs), but a few years ago you had to install Chef through RubyGems. Lots of people struggled with that, and even today I encounter people who avoid Chef because they think Chef has to be installed through RubyGems.

**Comment by FooBarWidget** [comment]
@rriemann @Arcovion  It's important even outside Windows. Installing a Ruby app on Linux using RubyGems is easy for Ruby programmers (e.g. you guys), but all other users struggle with it.

A good example is [BOSH](https://blog.starkandwayne.com/2014/12/24/traveling-bosh-cli-no-more-installation-pain/). BOSH is a Ruby tool but they have lots of non-Ruby-programmer Linux users, and they often see how such users struggle with installing BOSH.

Another good example is Chef, which suffered from damage reputation due to the installation path. Chef provides platform-specific packages nowadays (RPMs, DEBs), but a few years ago you had to install Chef through RubyGems. Lots of people struggled with that, and even today I encounter people who avoid Chef because they think Chef has to be installed through RubyGems.

> Also I don't think this lets you add gems and extensions like middleman-blog, nor would it work with any that have their own C extensions. Correct me if I'm wrong, but this looks like it's designed more for self contained apps that don't give users their own Gemfiles etc.

It is correct that self-contained apps is the primary use case. But do *all* Middleman users use Middleman through their own Gemfiles? I think there are also a lot of users out there who just want to use Middleman's standard features without plugins etc.

But plugins through gems (without native extensions) *can* be supported in Traveling Ruby. It's not even all that hard. Traveling Ruby ships with a normal Ruby interpreter so pretty much all Ruby features are available.

**Comment by FooBarWidget** [comment]
@rriemann @Arcovion Also, you're overestimating how easy it is for Windows users to get started using RubyInstaller. RubyInstaller is currently suffering from [a certificate issue](https://groups.google.com/forum/#!topic/rubyinstaller/McLTqcU35FY), meaning that *all* `gem install` commands fail. Furthermore, Luis Lavena -- the guy who has been maintaining RubyInstaller for years -- [is leaving](https://groups.google.com/forum/#!topic/rubyinstaller/nzpIDZqXO-Q). So far the migration to a new maintainer has been a very slow process. The certificate issue still isn't fixed, and a Ruby 2.2.0 release is nowhere in sight.

Users can update RubyGems manually to fix the certificate issue. But are you really asking non-Ruby-programmer users to go through all that trouble? Just imagine the following interaction.

> You: Hey friend, you should use Middleman for your next website. It's awesome!
> Friend: Cool let me try it... uh what is this "gem" thing?
> You: You need to install Ruby first. But don't worry, it's easy. Go to rubyinstaller.org.
> Friend: Okay... *installs*... All right, Ruby is installed now. I guess I have to use cmd.exe to run `gem install middleman`, right?
> You: That's right.
> Friend: Uh... it says "SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed"?
> You: That's easy to fix. Just go to https://gist.github.com/luislavena/f064211759ee0f806c88#installing-using-update-packages-new and follow the 4 steps, and *then* you can install Middleman and try it out.
> Friend: ...you know what, I'll just stick with Wordpress.

**Comment by FooBarWidget** [comment]
Traveling Ruby 20150210 has been released. It now supports Windows.
