### ISSUE TITLE
external setting build_dir

### ISSUE THREAD

**Issue by vasco** [middleman/middleman#1446]
I run/use middleman as a stage of a "bigger" project compilation (e.g. the project also compiles GWT). The build is controlled by maven, which in turn have a goal/mojo that calls middleman. The output directory ("build_dir" variable/instruction) must be controlled by maven.

We are doing this by having an instruction in config.rb like:

``` ruby
set :build_dir, ENV['MM_BUILD_DIR']
```

However it bothers me to have an explicit instruction to set the build_dir. Do you have alternatives?

If we did a PR to allow the build_dir to be set by an external variable, it would be accepted? Is this aligned with "middleman's vision"?

**Comment by tdreyno** [comment]
I think the example above is exactly how I would have implemented it. Any specific reason that bothers you?

**Comment by vasco** [comment]
It's the fact that you have to do things in your project ("set :build_dir, ENV['MM_BUILD_DIR']") to have that flexibility.

For example, to set the environment (e.g. development, staging, production), you don't have to do any instruction in the config.rb. You run the command with the environment you want to run in, and middleman understands that, setting the necessary variables to allow that compilation to happen for that particular environment. It would be odd for me to be forced to have to do:
```ruby
set :environment, ENV['MM_ENV']
````

My point would be to apply the same type of rationals to the build directory: Be able to set it in the "command line" without having to particularize my config.rb file for that matter.

**Comment by tdreyno** [comment]
Gotcha. I think this makes sense. Especially for CI boxes and automated builds.

Maybe a `--output`, `-O` flags for `middleman build`.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation.
