### ISSUE TITLE
When running server and relative_links true, link to parent directory goes to root index

### ISSUE THREAD

**Issue by RyanVerhey** [middleman/middleman#1447]
When running the server with `set relative_links, true`, a link using `link_to` or `url_for` to a parent directory (`/agenda/detail` linking to `/agenda/` for example) redirects to the root index. When looking at the generated code, the link is set as `../`, however clicking on the link redirects to the root index.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.
