### ISSUE TITLE
Serve existing sourcemap files "css/main.css.map" in development mode without interpolation and errors.

### ISSUE THREAD

**Issue by andreimoment** [middleman/middleman#1451]
Note: I am aware that Middleman does not produce sourcemaps at this time. I have set grunt-libsass to preprocess scss into css and it does produce proper sourcemap files. This request is about Middleman serving these sourcemap files in development mode.

I would like for Middleman to serve the `*.css.map` files properly in development mode so that Chrome and Firefox devtools can use the css sourcemaps.

At the end of the libsass process,  `css/main.scss` produces `css/main.css` and  `css/main.css.map`.

`get http://localhost:4567/css/main.css` loads the css file in the browser. 

`get http://localhost:4567/css/main.css.map` produces an error (stack trace below). The .map file is a json file which browsers request in order to get the sourcemap and show the scss sources for each of the css file properties. 

Is there a way to force Middleman to serve a file as a static file without using ExecJS?

`ignore "css/main.css.map"` causes a "Not found" page.

Maybe implement something like 

`serve-static "css/main.css.map"`

#### Error message:

    ExecJS::RuntimeError at /css/main.css.map
    CssSyntaxError: <css input>:3:2: Unknown word "version": 3, "file": "main.css", ^ "sources": [

    Ruby  c:/Ruby200/lib/ruby/gems/2.0.0/gems/execjs-2.3.0/lib/execjs/external_runtime.rb: in extract_result, line 65
    Web GET localhost/css/main.css.map
    Jump to:
    GETPOSTCookiesENV
    Traceback (innermost first)

    c:/Ruby200/lib/ruby/gems/2.0.0/gems/execjs-2.3.0/lib/execjs/external_runtime.rb: in extract_result raise RuntimeError, value...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/execjs-2.3.0/lib/execjs/external_runtime.rb: in exec extract_result(@runtime.exec_runtime(tmpfile.path))...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/autoprefixer-rails-5.1.5/lib/autoprefixer-rails/processor.rb: in process result = runtime.exec(...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/autoprefixer-rails-5.1.5/lib/autoprefixer-rails.rb: in process processor(params).process(css, opts)...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/middleman-autoprefixer-2.4.3/lib/middleman-autoprefixer/extension.rb: in prefix ::AutoprefixerRails.process(content, config).css...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/middleman-autoprefixer-2.4.3/lib/middleman-autoprefixer/extension.rb: in process prefix(extract_styles(response))...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/middleman-autoprefixer-2.4.3/lib/middleman-autoprefixer/extension.rb: in call prefixed = process(response, type, path)...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/showexceptions.rb: in call
          @app.call(env)...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/head.rb: in call status, headers, body = @app.call(env)...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/lint.rb: in _call status, headers, @body = @app.call(env)...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/lint.rb: in call dup._call(env)...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb: in call to_app.call(env)...
    c:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb: in service status, headers, body = @app.call(env)...
    c:/Ruby200/lib/ruby/2.0.0/webrick/httpserver.rb: in service si.service(req, res)...
    c:/Ruby200/lib/ruby/2.0.0/webrick/httpserver.rb: in run server.service(req, res)...
    c:/Ruby200/lib/ruby/2.0.0/webrick/server.rb: in block in start_thread block ? block.call(sock) : run(sock)

**Comment by tdreyno** [comment]
Looks like just a normal bug :)

Fixing here: https://github.com/middleman/middleman/commit/5b39a33ab68a4022bbc49375c0e0d4740702b1ef

Releasing a new version ASAP.

**Comment by andreimoment** [comment]
Thank you so much! I started digging through the code but didn't get to the right place in the limited time I had. 

You fixing this so quickly makes me very grateful for this project and the wonderful community around it. 

Andrei

**Comment by cassidyclawson** [comment]
@andreimoment 

Perhaps you can share your technique for using grunt to accomplish the sourcemap compilation? I'd really love to get this working in an existing middleman project but my efforts so far have been unsuccessful. Do you turn off all CSS compilation in Middleman and substitute for libsass or just rely on grunt/libsass for the sourcemaps?

Thanks much!

**Comment by andreimoment** [comment]
I'd probably prevent middleman from compiling sass and use gulp/grunt + libsass for that. Unfortunately don't have such a project at hand. 

Andrei
