### ISSUE TITLE
'middleman server' reacts slowly on changes if there is a large amount of files

### ISSUE THREAD

**Issue by sarguvlad** [middleman/middleman#1452]
Hi,

Thanks guys for such an amazing tool. I've installed middleman about a month ago, and everything seemed to work fine, until I've added in the source directory few static apps:

'example.com/app/appname/demo' - where /demo/ is a in average a complex web app which shouldn't be watched by middleman. So, once I've added those files, middleman suddenly became slow. I mean it takes up to 10 seconds to detect changes and make a refresh. And vice versa, if I move those files out of the project, middleman works as expected. I even tried to disable the livereload plugin in case it's causing issues and nothing changed, even manual page refresh doesn't help.

Any ideas why that could happen? Maybe there is a way to make middleman ignore those files, and just copy them to the /build/ directory on 'middleman build'?

Tech details:
Middleman 3.3.7
LiveReload 3.3.4
Gem 2.2.3
Windows 8.0

**Comment by Arcovion** [comment]
You can try ignoring the directory, also disabling the file watcher:
```ruby
ignore 'dir'
config[:file_watcher_ignore] << /source\/dir/
```
Or you could add an `after_build` hook and just copy the directory into your build from outside the source dir.

**Comment by sarguvlad** [comment]
Thank you so much for your reply,

This is what I've wrote into my config.rb fie:
```ruby
config[:file_watcher_ignore] += [ /source\/app\/\[.+\]\/demo\// ]
ignore 'app/**/demo/*'
```
Still nothing changed, is there something wrong with those expressions?

**Comment by Arcovion** [comment]
I just tested adding ~3500 files and was able to reproduce the lag, but using a regex for the `:file_watcher_ignore` fixed it (you don't need the other `ignore` call).

Play around with the regex a bit, it should work.

**Comment by sarguvlad** [comment]
Ok, thank you, I'll keep trying. Your help is highly appreciated.

Have a very nice day.

**Comment by svicalifornia** [comment]
This issue seems to have started for me after I upgraded from Middleman 3.4 to 4.1.8. Was the file watcher changed for Middleman 4+?

**Comment by tdreyno** [comment]
@svicalifornia Not on purpose, but it's a dependency of this project so something could have changed in that library between then and now.

That said, this kind of stuff is usually related to vendored or dependency files like Bundler, Bower and NPM. We have blacklists to avoid file watching those files, if they are in expected folders. Perhaps your setup doesn't map to the blacklist. Can you try running the `--verbose` flag and seeing if there are are ton of file updates in folders where you don't actually need to be watching all the files?
