### ISSUE TITLE
Extension not able to add methods to config.rb [4.0.0.alpha.6]

### ISSUE THREAD

**Issue by bb-generation** [middleman/middleman#1453]
Methods added by extensions to config.rb are silently ignored. The following error message gets shown when trying to use such a method: ```config.rb:62:in `evaluate_configuration': undefined local variable or method `say_hello' for #<Middleman::ConfigContext:0x00000005340c60> (NameError)```

# How to reproduce

According to the documentation (https://middlemanapp.com/advanced/custom_extensions/#adding-methods-to-config.rb), you can add new methods to be used in config.rb by calling ```app.extend```:

```ruby
class MyFeature < Middleman::Extension
  def initialize(app, options_hash={}, &block)
    super
    puts "MyFeature activated"
    app.extend ClassMethods
  end

  module ClassMethods
    def say_hello
      puts "Hello"
    end
  end
end
::Middleman::Extensions.register(:my_feature, MyFeature)

activate :my_feature

say_hello
```
(You can also clone https://github.com/bb-generation/mm-classmethods and execute a ```bundle exec middleman build``` to see the error)

I'm just wondering if I'm doing something wrong or the documentation is outdated or there's a bug in middleman (v4).

**Comment by tdreyno** [comment]
The documentation is out of date. Thanks for the heads up.

**Comment by chriseidhof** [comment]
I stumbled on the same thing. As a (dirty) workaround I did the following inside my extension. It's not the proper way (almost certainly), but it works for my purposes.

```
  def initialize(app, options_hash={}, &block)
    super
    app.send :include, ConfigHelpers
  end

  module ConfigHelpers
    def say_hello
      puts "Hello"
    end
  end

```

**Comment by tdreyno** [comment]
For reference, the correct way to do this in v4 is:

```
class MyExtension < Middleman::Extension
  # Will place `say_hello` on `app`
  expose_to_application say_hello: :say_hello

  # Will make `say_hello` available inside config files
  expose_to_config say_hello: :say_hello

  def say_hello
    puts "hello"
  end
end
```
