### ISSUE TITLE
Pagination on root index.html page

### ISSUE THREAD

**Issue by iwarner** [middleman/middleman#1454]
Hiya

Trying to put pagination on the hoe page of my site:

The Next Link is changed to the following and works fine.
http://localhost:4567/page/2/index.html

But this breaks the rule in the docs

should it now be : http://localhost:4567/page/2.html or http://localhost:4567/index/page/2.html 

Now I have created a pagination

PREV - 1 - 2 - 3 - 4 - NEXT 

So the rules for my links to individual pages follow the rule I expect and so break they all link to 
http://localhost:4567/index/page/2.html

Any help appreciated

Many thanks

Ian

**Comment by lolmaus** [comment]
Should probably go to https://github.com/middleman/middleman-blog/issues .

Also, please paste some code. Use https://gist.github.com/ for larger snippets.

**Comment by tdreyno** [comment]
Moved to https://github.com/middleman/middleman-blog/issues/242
