### ISSUE TITLE
Problems with changes in generated html

### ISSUE THREAD

**Issue by vlckomi** [middleman/middleman#1461]
Middleman doesn't change html on local after I change my html.slim file. Changes in sass are generated after refresh correctly. Does anybody have any idea why, please?

**Comment by Announcement** [comment]
Having the same problem O.P. bumping for help.

**Comment by tdreyno** [comment]
@vlckomi What versions?

@Announcement What is prefork?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation as a starting point for discussion around this.
