### ISSUE TITLE
`page.parent` finds `.htaccess` instead of `index`

### ISSUE THREAD

**Issue by thomasritz** [middleman/middleman#1463]
Assume that I have the files `foo.html.erb`, `index.html.erb` and `.htaccess` in the `source` directory.
Calling `parent` on the `foo.html` resource returns `.htaccess` instead of `index.html`.
If I remove the `.htaccess` file `parent` works as expected and returns the `index.html` resource.

Could this be caused by the regexp in
https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-core/sitemap/extensions/traversal.rb#L17

I'm using middleman 3.3.9, ruby 2.1.1

To reproduce:

```shell
middleman init my_new_project
touch source/foo.html.erb
touch source/.htaccess
middleman console
```
```ruby
foo = sitemap.find_resource_by_path('foo.html')
foo.parent.path # => ".htaccess"
foo.parent.parent.path # => ".htaccess"
```

**Comment by tdreyno** [comment]
Interesting. Nice find. Will investigate, but PRs are also very welcome
