### ISSUE TITLE
How do you enable SCSS compliation with middleman-core?

### ISSUE THREAD

**Issue by lpil** [middleman/middleman#1464]
I don't want to have my site have a node dependency, so I'm using middleman-core. https://github.com/middleman/middleman/issues/780

However, I'm unsure as what I need to do to enable SCSS complication now. It seems that merely adding 'middleman-sprockets' to my Gemfile isn't enough.

There doesn't seem to be any info in the templating part of the documentation, though there is for coffeescript. What ought I try next?

Cheers,
Louis

**Comment by lolmaus** [comment]
`gem sass`?

**Comment by lpil** [comment]
sass is already in `Gemfile.lock`

**Comment by lolmaus** [comment]
What error are you getting?

Do you prefix you commands with `bundle exec`?

**Comment by lpil** [comment]
There is no error, just files in my `css_dir`  ending in `.css.scss` don't get compiled to css, instead they just get copied across as is.

If I replace

```ruby
gem 'middleman-core'
gem 'middleman-sprockets', '~> 3.4.1'
```

with

```ruby
gem 'middleman-core'
```

And restart `middleman server` it works as desired.

**Comment by lpil** [comment]
I tried explicitly adding `sass` the the gemfile, and it now works. Bit confused, but happy. THank you for your help.

**Comment by tdreyno** [comment]
@lpil Your solution is correct. The main `middleman` gem is just core, which a bunch of other gems already available. For any of our templating languages, simply adding the gem should suffice.
