### ISSUE TITLE
Can I change date format in article

### ISSUE THREAD

**Issue by sarunw** [middleman/middleman#1470]
```
---
title: My Middleman Blog Post
date: 2011/10/18
tags: blogging, middleman, hello, world
---

```

Does it possible to change date format to dd/mm/yyyy?

**Comment by MinasMazar** [comment]
I think what you are looking for is in the [middleman-blog plugin.](https://github.com/middleman/middleman-blog/blob/master/lib/middleman-blog/blog_article.rb). I think it's not possible to change the frontmatter data generated by `middleman article my-middleman-blog-post` (maybe you have to patch the blog plugin code or dig into Time class) But if you can easily render the date in your preferred format with `Time#strftime`.

**Comment by AndrewKvalheim** [comment]
The [template for new articles][generating] includes the frontmatter. You're free to change it to e.g.:

```erb
---
title: <%= @title %>
date: <%= @date.strftime('%d/%m/%Y') %>
tags:
---

```

as long as the `date` field remains parsable by [`ActiveSupport::TimeZone#parse`][parse]. Your preferred format appears to be supported:

```console
ruby-2.2.0:MiddlemanApplication1$ Time.zone.parse('18/10/2011')
=> Tue, 18 Oct 2011 00:00:00 PDT -07:00
```

Refer to [`TZInfo::Timezone#strftime`][tz-strftime] and [`Date#strftime`][date-strftime] for the formatting syntax.


  [generating]: https://middlemanapp.com/basics/blogging/#generating-articles
  [parse]: http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html#method-i-parse
  [date-strftime]: http://ruby-doc.org/stdlib-2.2.0/libdoc/date/rdoc/Date.html#method-i-strftime
  [tz-strftime]: http://www.rubydoc.info/gems/tzinfo/TZInfo/Timezone#strftime-instance_method

**Comment by MinasMazar** [comment]
Wonderful!
