### ISSUE TITLE
Update data

### ISSUE THREAD

**Issue by MinasMazar** [middleman/middleman#1471]
Would be usefull an equivalent of `Middleman::CoreExtensions::Data::DataStore#touch_file` that takes an object and perform a `YAML#dump` (or JSON equivalent) to make possible the storing of complex application data elaboration. Performing an automatic #touch_file at the end of this method all new generated data will be available in the building process.

**Comment by tdreyno** [comment]
@MinasMazar Sorry for the very late reply, but can you restate the goal of this. It sounds useful to me, but, I'm not sure I'm hearing what you may be saying.

**Comment by MinasMazar** [comment]
A *loc* explains more than tons of words.

~~~ruby
def method_called_from_whatever_resource_manipulator_before_build_process
  resource = get_correct_resource_from_path "blog/a-blog-article.html"
  resource.data["title"] = critical_method_returns_a_title
  resource.data["smart_obj"] = CustomSmartObject.new unless resource.data["smart_obj"]
  resource.save!

  # This mechanism should be available also for app.data instance
  app.data.site["global_data"] = "A global string"
  app.data.save!
end
~~~
and #save! should fix the resource frontmatter at filesystem level.
This could be available also for `app.data` instance.
Really don't know if it could be useful or it has sense at all.
Thanks for the reply. It's never too late for a reply. ;)

**Comment by tdreyno** [comment]
Ah, yeah, I've done something like this to give Middleman an API for my blog editor extension.

I don't think it makes sense in core, but it should be pretty easy to extend `Resource` and `Data` to allow this kind of behavior in an extension.
