### ISSUE TITLE
How to access config from helpers?

### ISSUE THREAD

**Issue by Naatan** [middleman/middleman#1478]
In config.rb I've set a few default config "vars", eg.

```
set :title, "Website Title"
```

I seem to be able to access this from helpers using `title`, however this does not work when the helper is accessed from a partial

What's the proper way of accessing these config vars? 

Thanks

**Comment by Naatan** [comment]
Trying random variables I think I landed on the proper solution: `config[:title]`

**Comment by Arcovion** [comment]
These should all work:
```ruby
title
config.title
config[:title]
settings[:title]
```
I like to use a `site` variable for this (same as Jekyll), so as to not pollute the core namespace which you can view here: [http://localhost:4567/__middleman/config/#core](http://localhost:4567/__middleman/config/#core)
```ruby
set :site, OpenStruct.new(
  title: 'Website Title'
).freeze
# site.title
```

**Comment by Naatan** [comment]
Thanks @Arcovion - using the site namespace is a good idea!

**Comment by tdreyno** [comment]
in v4, config lives in a sandbox so we're going to be a lot safer with naming. That said, `site` reads pretty well.

**Comment by jeffcole** [comment]
@tdreyno can you comment on the current way to do this as of v4.1.2? Here's my approach with the error being raised:

```ruby
# config.rb

# Configure site host for generating absolute URLs
configure :development do
  config[:site] = { host: "http://localhost:4567" }
end

configure :build do
  config[:site] = { host: "https://jeffcole.github.io" }
end

# helpers/twitter_helpers.rb

module TwitterHelpers
  def twitter_share_link(page)
    # Raises: undefined local variable or method `config' 
    # for #<TwitterHelpers:0x007f81b4207e88>
    host = config[:site][:host]
    # ...
  end
end
```

Thanks in advance for any help you can give!

**Comment by tdreyno** [comment]
If you call `helpers TwitterHelpers`, that should be available in templates and work as written.

Are you calling that helper from a non-template context?

**Comment by jeffcole** [comment]
I'm calling it from my blog layout like this:

```
-# source/layouts/blog.haml

= twitter_share_link(current_article)
```

I'm taking advantage of the helper auto loading that works via file name convention. I tried manually requiring and invoking `helper TwitterHelpers` as well and got the same results.

**Comment by tdreyno** [comment]
Hmm, that should work fine. Would you have a repo I could look at?

**Comment by jeffcole** [comment]
@tdreyno I figured it out, I'm actually using a nested class within `TwitterHelpers` to generate the URL, and the nested class doesn't have access to `config`. You're right that `config` is accessible from within the module, so I can just pass it through.

Very sorry for the trouble and thanks for your very speedy help!

**Comment by tdreyno** [comment]
Glad to hear
