### ISSUE TITLE
Setting default frontmatter for blogs

### ISSUE THREAD

**Issue by Naatan** [middleman/middleman#1480]
Hi, I'm trying to set some default frontmatter for blog articles, which is then used from my layout file. 

What I tried is setting it via my config.rb like this:

```
page "/blog/*", :layout => "default", :locals => { :sidebar => "blog" }
```

or

```
page "/blog/*", :layout => "default",  :sidebar => "blog" 
```

(Admittedly I'm not sure what the :locals is used for, I figured it contains custom -non default- frontmatter)

However this does not catch on. How should I be doing this instead?

**Comment by tdreyno** [comment]
Try the `:data` key instead of `:locals`. `:locals` are variables that are available in templates. In your above example, a var named `sidebar` would exist in your template.

**Comment by Naatan** [comment]
Thanks @tdreyno !
