### ISSUE TITLE
Wrap regular .html files

### ISSUE THREAD

**Issue by Naatan** [middleman/middleman#1481]
Some of the files I am using do not need any special parsing, they just need to have their frontmatter interpreted and then be wrapped by the specified layout. However when I simply define a foo.html file with some html and frontmatter it ends up stripping the frontmatter and just printing out the html (no layout).

Is there some type of config var I need to set?

**Comment by tdreyno** [comment]
Simply add a `.erb` extension.

**Comment by Naatan** [comment]
I'm aware of this, my concern is that rather than simply parsing the frontmatter and not bothering with parsing the html it will instead parse the entire file as erb. I'm not familiar with the inner workings but I would assume that this costs extra processing.

**Comment by tdreyno** [comment]
It will parse the entire file, but the performance cost is negligible.
