### ISSUE TITLE
Automate blog detection when using multiple blogs

### ISSUE THREAD

**Issue by lyonsinbeta** [middleman/middleman#1483]
If you want to get the `blog.name`, `blog.prefix`, `blog.articles`, etc. and you're using multiple blogs you have to declare in the frontmatter or in the method call which blog you're accessing. It would be great it the default behavior was to return data for the "current" blog.

Example: I want the name of the blog to appear as an `<h1>` on the index page. If I have one blog I can use `<h1><%= blog.name %></h1>` but if I'm using multiple blogs I have to do either

```

---
blog: "my blog"

---
<h1><%= blog.name %></h1>
```

or

```
<h1><%= blog["my blog"].name %></h1>
```

neither seems like a big deal but it means you have to do some weird trickey to use a single layout file for multiple blogs.

Ideally at build time the layout/template would know which blog it's building the page for based on it's location by default. Then if you needed to access another blog's information you could declare it explicitly.

If I'm crazy and this is already possible someone please correct me. I'm happy to be wrong. :smile:

**Comment by tdreyno** [comment]
How would the build process know which blog was "current"?

Seems like the simplest solution is 2 helpers:

```
helpers do
  def blog1
    blog["blog 1"]
  end

  def blog2
    blog["blog 2"]
  end
end
```

Which will be much clearer than an opaque `blog` reference which could point at different data depending on context.

**Comment by lyonsinbeta** [comment]
> "blog reference which could point at different data depending on context.

That's exactly what I want. :smile: The way I'm thinking is that a blog has to be in a folder and has to have a prefix so when the layout is building pages/articles from the `source/blog1` directory it would say "I'll use `blog1` values by default unless specifically told otherwise. Then when it gets to `source/blog2` it would use `blog2` values by default unless specifically told otherwise. 

The problem with the helper method you outlined is still the same basic issue; you have to explicitly communicate to the layout which blog it's building for.

Maybe I'm the only person who would benefit from this functionality? :sweat_smile:

**Comment by tdreyno** [comment]
I think there may be a benefit, but I also feel like it makes things more confusing unless you are well aware of this behavior.

Maybe, try using a helper for now and see how it feels:

```
helpers do
  def current_blog
    name = current_page.url.match(/blog1/) ? "blog1" : "blog2"
    blog(name)
  end
end
```

**Comment by lyonsinbeta** [comment]
@tdreyno I had to change it up a little (I have 5 blogs on my site with more coming) but that set me on a path to seriously DRYing up my templates/layouts. Thank you very much.

Still be cool to see this functionality built in, but this helped me tremendously.

:+1:

**Comment by tdreyno** [comment]
@lyonsinbeta I think there might be a place for this functionality. Will keep this ticket open and keep thinking about it.

**Comment by abolishme** [comment]
+1

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation as a starting point for discussion around this.

**Comment by lyonsinbeta** [comment]
👌

**Comment by andreamoro** [comment]
Was this implemented somehow?

**Comment by sandstrom** [comment]
@andreamoro Nope, but we'll happily accept PRs if you want to take a stab at it!
