### ISSUE TITLE
If there is whitespace in directory path, Middleman fails to load

### ISSUE THREAD

**Issue by RyanVerhey** [middleman/middleman#1487]
I keep all of my development files in my Dropbox folder. Recently, I linked my work and personal Dropbox accounts, so my dropbox folder was renamed Dropbox (Personal). The path to my Middleman site directory is `~/Dropbox (Personal)/Development/ryanverhey_com`, and when I run `middleman server`, I get the error `/Users/ryan/.rvm/gems/ruby-2.1.2/gems/sprockets-2.12.3/lib/sprockets/base.rb:153:in 'resolve': couldn't find file '/Users/ryan/Dropbox (Personal)/Development/ryanverhey_com/source/images/about-pic.jpg' (Sprockets::FileNotFound)
`. I believe it's because Middleman doesn't know what to do with the whitespace in "Dropbox (Personal)". Because I can't rename my Dropbox folder, can support be added for whitespace in file paths?

**Comment by javierjulio** [comment]
@RyanVerhey you're right, I'm able to replicate this issue with a clean new project. I created a sub folder in /source/images and made sure to include a space in the folder name. Using the image_tag helper I was able to reference an existing image fine but once copying it the sub folder and updating the path in the image_tag it failed. Viewing the source it was replacing the white space so thus concatenating the words in the folder name.

**Comment by tdreyno** [comment]
This is a bug in Sprockets. We had submitted a ticket for it, but it seems like they're not going to support the current version of sprockets any more and their v3 isn't out yet. We will have to migrate as quickly as possible to the new version when it is released.

For now, avoid special characters in directories or don't use Sprockets:

```
gem 'middleman-core'
```

Instead of `middleman`

**Comment by javierjulio** [comment]
Cool thanks @tdreyno. Was looking into why it was happening to help out. Figured might be something else. I verified image_tag padrino-helper correctly handles space in file path. Thought this [line of code might be the issue](https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-more/core_extensions/default_helpers.rb#L171) but then saw your reply. Thanks.

**Comment by RyanVerhey** [comment]
@tdreyno Thank you for looking into it, and thank you @javierjulio for confirming the bug.
