### ISSUE TITLE
Rename config.rb to middleman.rb to avoid conflicts with Compass

### ISSUE THREAD

**Issue by marcinant** [middleman/middleman#1488]
As in topic. Please reopen this issue and implement this feature.

**Comment by tdreyno** [comment]
Already done on `master`

**Comment by marcinant** [comment]
When it's going to be released, or is it possible to use middleman from master directly right now?

**Comment by tdreyno** [comment]
I wouldn't expect a stable release for several months still. If you're comfortable with the bleeding edge, I'm using master for my sites, but then again, I have a little more insight into why things might break.
