### ISSUE TITLE
Locale (i18n) aware link_to, directory_indexes and translated paths

### ISSUE THREAD

**Issue by sn3p** [middleman/middleman#1490]
I'm building a localized website in English and Dutch (NL) and this is the navigation I want to achieve:

__In English:__
```html
<a href="/">Home</a>
<a href="/about/">About</a>
<a href="/about/the-team/">The Team</a>
```
__in Dutch:__
```html
<a href="/nl">Home</a>
<a href="/nl/over/">Over</a>
<a href="/nl/over/het-team/">Het Team</a>
```

Which means my __build file structure__ should look something like:
```
/index.html
/about/index.html
/about/the-team/index.html
/nl/index.html
/nl/over/index.html
/nl/over/het-team/index.html
```

--

In my __config.rb__ I have:
```ruby
activate :i18n, :mount_at_root => :en
activate :directory_indexes
```

And my __navigation.erb__:
```erb
<%= link_to t(:home), "/index.html" %></li>
<%= link_to t(:about), "/about.html" %></li>
<%= link_to t(:team), "/about/the-team.html" %></li>
```

__I've tried:__

- Combining `directory_indexes` with localized child pages.
- Translating paths using the `paths` key in the language YAML files. From the [docs](https://middlemanapp.com/advanced/localization/):

   > In some cases you may want to localize the name of the file in addition to its contents. You can use the special `paths` key in your language YAML files to rename URLs to be language-specific.

But I can't get them to work together properly.
The `link_to` helper doesn't always take locales into account when parsing the URL's. Sometimes I get absolute or broken links (ie. missing slashes). And `directory_indexes`, translated `paths` and child pages don't go well together.

Anyone knows how to achieve this? Or am I missing something?

**Comment by rensverschuren** [comment]
For locale aware link_to you have to define your own helper. For mangrove.com we use:

```ruby
def local_path(path, options={})
  lang = options[:language] ? options[:language] : I18n.locale.to_s
  "/#{lang}/#{path}"
end
```

In the navigation we use this kind of `link_to`:

```ruby
<%= link_to t("pages.company.label"), local_path(t("paths.company")) %>
```

Also, you need to put your template files in `/source/localizable/` instead of `/source`. 

Last but not least, you need to put your translated paths in your locale files, like this:

```yaml
nl:
  company: over-ons
  paths:
    company: over-ons
```

I hope this is all. Good luck ;-)

**Comment by sn3p** [comment]
@rensverschuren thanks :)
I'll give that a try after the weekend.

**Comment by sn3p** [comment]
Thanks :) I'll give that a try after the weekend.

__Edit:__
@rensverschuren I'm using the helper now, slightly modified to omit the language mounted as root.
But I'm still a little confused on how to translate the paths and subdirectories. Are you using `directory_indexes` to build the subdirectories or did you create them manually? ie. `contact` in `www.mangrove.com/nl/contact/rotterdam/`. And what if I wanted to translate "contact"? ;)

**Comment by dgrosso** [comment]
> @rensverschuren I'm using the helper now, slightly modified to omit the language mounted as root.
But I'm still a little confused on how to translate the paths and subdirectories. Are you using directory_indexes to build the subdirectories or did you create them manually? ie. contact in www.mangrove.com/nl/contact/rotterdam/. And what if I wanted to translate "contact"? ;)

@sn3p I'm facing the same problem right now, how did you translate the subdirectories?

**Comment by sn3p** [comment]
> I'm facing the same problem right now, how did you translate the subdirectories?

This is really old and ugly piece of code, but this is what I came up with back then.
Note that this was when we were still running Middleman v3, so will probably break in v4.

```rb
# Localized link_to
def locale_link_to(*args, &block)
  url_arg_index = block_given? ? 0 : 1
  options_index = block_given? ? 1 : 2
  args[options_index] ||= {}
  options = args[options_index].dup
  args[url_arg_index] = locale_url_for(args[url_arg_index], options)
  link_to(*args, &block)
end

# Localized url_for
def locale_url_for(url, options={})
  locale = options[:locale] || I18n.locale
  options[:relative] = false
  url_parts = url.split("#")
  url_parts[0] = extensions[:i18n].localized_path(url_parts[0], locale) ||
                 url_parts[0]
  url = url_parts.join("#")
  url = url_for(url, options)
  # Replace leading locale url segment with domain
  url.sub("/#{locale}/", full_url("/", locale))
end
```

**Comment by unmultimedio** [comment]
Hello everyone! I'm facing this issue and I have to say the helper_method has indeed helped a lot, but I'm facing an issue with this:

I have this in my `config.rb`:
```
# Pretty URLs https://middlemanapp.com/advanced/pretty-urls/
activate :directory_indexes
# i18n https://middlemanapp.com/advanced/localization/
activate :i18n, mount_at_root: :en, langs: %i(en es)
```

And when I'm in a route, let's say `my.site/es/my-page`, this happens:
```
link_to 'HOME', local_path('/')
# or
link_to 'HOME', local_path('/', language: :es)
# Both of them output
<a href="/es">HOME</a>
# Which is absolutely fine and expected, because /es is the root of the current locale
```

But when I'm in a mounted-locale route, let's say `my.site/my-page` _(by default `:en` is mounted)_, this happens:
```
link_to 'HOME', local_path('/', language: :en)
# It outputs
<a href="/en/">HOME</a>
# Which is gives me a 404 error clearly because /en is not valid, :en is mounted.
```

So, I made an exception in the helper:
```
def i18n_path(path, options = {})
  lang = options[:language] ? options[:language] : I18n.locale.to_s
  # English is mounted at root
  lang = '' if lang == :en
  # Replace multiple slashes with one
  "/#{lang}/#{path}".gsub(/\/+/, '/')
end
```

Which is basically the same as saying `link_to 'HOME', '/'`

And here is the issue, when `link_to` is used to redirect to the root, the "root" is anyway with the current locale.

My question would be, how to go to the TRUE root of the site when I'm in locale, using `link_to` helper?

**Comment by phildionne** [comment]
Adding my solution, which is trying to work with middleman internals as much as possible.

```ruby
# config.rb
activate :directory_indexes

helpers do
  def localized_path(path)
    localized_filename = path.sub(/\./, ".#{I18n.locale}.")

    resource = sitemap.resources
      .select { |r| r.try(:target) }
      .find { |r| r.target.match(localized_filename) }

    raise "Can't find resource in sitemap for #{path} with #{localized_filename}" unless resource

    "/#{resource.eponymous_directory_path}"
  end
end
```

```yml
# locales/fr.yml
---
fr:
 paths:
   source-name-of-the-page: ce-chemin-est-en-français
```

```erb
<a href="<%= url_for localized_path('source-name-of-the-page.html') %>">Link</a>
```
