### ISSUE TITLE
Undefined method `say_status` for `Builder`

### ISSUE THREAD

**Issue by LMolr** [middleman/middleman#1492]
I am trying to port some extensions for MMv4. They often call `builder.say_status` on a `after_build` hook, which is no longer defined.
I see that in e.g. gzip extension, `builder.say_status` has been replaced by `builder.trigger`.
Should I do the same (no caveats)?
Thank you!

**Comment by tdreyno** [comment]
The change is basically this. `after_build` used to return an instance of the Thor class which was building the site. Now, it returns an instance of `Middleman::Builder` which allows us to build sites directly in Ruby, without Thor. We still use Thor, but we've moved a lot of the diffing and file creation logic into Middleman.

There are two options now:

* `builder.thor.say_status`: The Thor object is available as `builder.thor`, but it may not always be available. But it probably will for now, on normal `middleman build` commands.

* `builder.trigger :your_extension, "Your Message"`: Basically, trigger emits an event that other parts of the build process can listen to. If the build is running through the command line, it will output unknown event types as messages to the console. *This is the best approach*

Would love to figure out a good way to communicate this change to extension authors. Maybe a separate "Upgrading Extensions to v4" article on the site.
