### ISSUE TITLE
Webfonts not being loaded in on mobile

### ISSUE THREAD

**Issue by iDev0urer** [middleman/middleman#1493]
Not sure what, if anything, can be done about this, but when I pull up the middleman server page on my phone it isn't displaying embedded webfonts. I know that it's not a problem with the phone or my code because when I deployed to my test server the fonts loaded in just fine.

Middleman server:
![img_0336](https://cloud.githubusercontent.com/assets/4535422/7091044/4df564c4-df64-11e4-8c7d-f93d9dc30878.PNG)

Deployed:
![img_0337](https://cloud.githubusercontent.com/assets/4535422/7091058/6bdb456c-df64-11e4-95e5-c94e22fe16df.PNG)

**Comment by tdreyno** [comment]
Are you using a web fonts API? Is your IP whitelisted with them?

**Comment by iDev0urer** [comment]
Actually for some reason it decided to work now :/

Closing the issue
