### ISSUE TITLE
List ignored posts in "middleman build" output

### ISSUE THREAD

**Issue by hbons** [middleman/middleman#1495]
When building, Middleman seems to ignore posts that are in the future. Whilst this is a useful feature, I just spent an hour scratching my head why my post wouldn't build, due to getting the date wrong by a day. There's no way to discover this when you don't know about this feature.

I found this out by stumbling upon this post: https://forum.middlemanapp.com/t/for-some-reason-middleman-is-not-building-pages-for-newly-added-markdown-files/1549. So I'm not the first running into this.

It would be nice if middleman showed the skipped posts in the `middleman build` output.

cc/ @garrett

**Comment by tdreyno** [comment]
Sounds reasonable. Can you move this to the `middleman-blog` bug tracker?
