### ISSUE TITLE
Asset hashes on WOFF vs WOFF2 fonts get confused

### ISSUE THREAD

**Issue by GSI** [middleman/middleman#1496]
**(v3-stable)**

When having both, a font.woff and a font.woff2 file in place/in use, Middleman confuses their hashes.

That's to say, the woff2 font will be referenced  by the hash actually belonging to the woff font.

**Example**

*Actual* file names:
raleway-medium-webfont-46ed8c33.woff
raleway-medium-webfont-7b27610c.woff2

*Referenced* as:
raleway-medium-webfont-46ed8c33.woff
raleway-medium-webfont-46ed8c33.woff2 (doesn't exist)

**Comment by GSI** [comment]
Note: Renaming one of the files to a different base name causes files to be falsely referenced without any hash.

**Comment by tdreyno** [comment]
@GSI Can you post some kind of test case or simple app we can test on? This would seem to depend on some specific config, file naming and maybe sass?

**Comment by GSI** [comment]
@tdreyno, I can confirm that sass is being used. What caused your assumption?

I'll see about the example app.

**Comment by GSI** [comment]
Thomas, here's the code to reproduce the issue. Nothing fancy - just read the four commit messages to get the idea:

https://github.com/GSI/middleman-issue-1496

The third commit is interesting, as it's case should be considered in any according unit test in order to avoid having them pass accidently.

Check the resulting fonts-XXXXXXXX.css to confirm that .woff/woff2 files are referenced by the same hashes regardless of actual names.

**Comment by azoff** [comment]
+1

**Comment by tdreyno** [comment]
Hashing is based on a SHA1 of the file contents. So if the file contents are the same, so should their hash.

**Comment by tdreyno** [comment]
This appears to be working as designed. Is there a reason you'd want the hashes to be different? How does them being the same trigger an error?

**Comment by GSI** [comment]
Sure, that's perfectly fine and sane. The hashes may be the same, but they must not be *expected* to be the same, as it currently is the case.

**Comment by tdreyno** [comment]
Where is that expectation?

**Comment by GSI** [comment]
That's the question :)
Were you able to reproduce the issue with the example project I provided?

**Comment by tdreyno** [comment]
Yes, but I don't see any bug with the way it is working. Sorry, under what conditions does a bug occur?

**Comment by GSI** [comment]
I've added a short README to the repo. Please check if you get the same results as outlined there.

**Comment by tdreyno** [comment]
Gotcha. So the files are correct, but the values in the CSS are wrong.

**Comment by GSI** [comment]
Exactly. Sorry for not being more precise before, in regards to what I meant by "being referenced".

**Comment by akarzim** [comment]
@GSI : I fixed this issue with PR #1533 which have been merged by @tdreyno

**Comment by OnixGH** [comment]
@tdreyno is this fix scheduled for a release? The [Phusion Passenger Library](https://github.com/phusion/passenger_library/) was recently publicly released, and is affected.

Btw. was the middleman v3.3.13 gem [yanked](https://rubygems.org/gems/middleman/versions/3.3.13) on purpose?

**Comment by tdreyno** [comment]
Yes, it had a pretty bad preview bug that required a lot of work to fix. 3.4 should be out soon.
