### ISSUE TITLE
asset_host adds prefix to external JavaScript files

### ISSUE THREAD

**Issue by pixelate** [middleman/middleman#1499]
When `:asset_host` is defined, Middleman will prefix external JavaScript urls with the asset_host. Both HTML as well as JavaScript files are affected by this.

For example:

```
activate :asset_host, host: "http://example.com"
```

Will result in compiled HTML like this when trying to use external urls for JavaScript files:
```
<script src="http://example.com/https://code.jquery.com/jquery-2.1.3.min.js"></script>
```

It will also break jQuery when trying to require it via Sprockets by inserting the asset_host string into the JavaScript file.

**Comment by tdreyno** [comment]
Is this on `master` or the stable series?

**Comment by pixelate** [comment]
This is on master. The problem seems to be that `Pathname.new(asset_path).relative?` returns the wrong result inside `AssetHost.rewrite_url`.

**Comment by tdreyno** [comment]
I can totally see why this is broken on master. We switched to a regex for parsing those URLs and that's always fraught with edge cases.

Let me take a quick look. Or atleast write a failing test case

**Comment by pixelate** [comment]
Maybe it could check if a protocol (`http://` or `https://`) is present in the url and always return `false` for `relative?` in that case.

**Comment by tdreyno** [comment]
Figured it out. Thanks!
