### ISSUE TITLE
Add note about v3-stable vs. master to CONTRIBUTING.md

### ISSUE THREAD

**Issue by cllns** [middleman/middleman#1505]
Hi there, I just submitted a PR (#1504) and I did it against `v3-stable` rather than `master`. 

I'm not sure if that's correct. Could someone add a note to `CONTRIBUTING.md` so people will know which is correct?

**Comment by tdreyno** [comment]
Yup, that's correct. `v3-stable` is the default branch on our repo.

**Comment by cllns** [comment]
Cool. What is `master` used for, in that case?

**Comment by tdreyno** [comment]
The forthcoming v4 series is on master, but it's alpha quality. All commits to `v3-stable` are merged into master periodically.
