### ISSUE TITLE
Slim::Engine: Option :locals is invalid

### ISSUE THREAD

**Issue by davidmles** [middleman/middleman#1514]
When calling partial, this error shows up in the console:

```
Slim::Engine: Option :locals is invalid
```

A workaround is disabling the option validator in ```config.rb```:

```ruby
Slim::Engine.disable_option_validator!
```

**Comment by dg-ratiodata** [comment]
What slim version are you using? Does 3.0.3 do the trick?

**Comment by davidmles** [comment]
Yes, I forgot to say which version I'm using. It's the latest one: 3.0.3

**Comment by brousalis** [comment]
https://github.com/middleman/middleman/issues/612

"temporary" fix there. I'm having the same issue

**Comment by tdreyno** [comment]
This is an internal slim warning (not an error) and not something we plan to fix in our codebase until v4.
