### ISSUE TITLE
Two instances can be running on the same port on Windows

### ISSUE THREAD

**Issue by Arcovion** [middleman/middleman#1520]
I _assume_ it's Windows related, on Linux [the error message](https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-core/preview_server.rb#L210) is raised correctly.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation. Unfortunately I don't have Windows, so I cannot provide any insight here. Perhaps someone with Windows can provide a PR?
