### ISSUE TITLE
Parameter validation

### ISSUE THREAD

**Issue by maxmeyer** [middleman/middleman#1523]
Recently I ran `middleman server -p 'garbage'` and got this error:

```
/usr/lib/ruby/2.2.0/socket.rb:232:in `getaddrinfo': getaddrinfo: Servname not supported for ai_socktype (SocketError)
        from /usr/lib/ruby/2.2.0/socket.rb:232:in `foreach'
        from /usr/lib/ruby/2.2.0/socket.rb:459:in `tcp_server_sockets'
        from /usr/lib/ruby/2.2.0/webrick/utils.rb:70:in `create_listeners'
        from /usr/lib/ruby/2.2.0/webrick/ssl.rb:152:in `listen'
        from /usr/lib/ruby/2.2.0/webrick/server.rb:114:in `initialize'
        from /usr/lib/ruby/2.2.0/webrick/httpserver.rb:45:in `initialize'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/preview_server.rb:217:in `new'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/preview_server.rb:217:in `setup_webrick'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/preview_server.rb:276:in `mount_instance'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/preview_server.rb:24:in `start'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/cli/server.rb:85:in `server'
        from /home/user/.gem/2.2.2/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /home/user/.gem/2.2.2/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /home/user/.gem/2.2.2/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /home/user/.gem/2.2.2/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/cli.rb:72:in `method_missing'
        from /home/user/.gem/2.2.2/gems/thor-0.18.1/lib/thor/command.rb:29:in `run'
        from /home/user/.gem/2.2.2/gems/thor-0.18.1/lib/thor/command.rb:128:in `run'
        from /home/user/.gem/2.2.2/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /home/user/.gem/2.2.2/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /home/user/.gem/2.2.2/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /home/user/data/projects/middleman/middleman-core/lib/middleman-core/cli.rb:20:in `start'
        from /home/user/data/projects/middleman/middleman-core/bin/middleman:18:in `<top (required)>'
        from /home/user/.gem/2.2.2/bin/middleman:23:in `load'
        from /home/user/.gem/2.2.2/bin/middleman:23:in `<main>'
```

What do you think about some argument checking in cli-commands of `middleman`? @tdreyno @bhollis @Arcovion

**Comment by maxmeyer** [comment]
The `port`-parameter is an easy one, only `type: :numeric` is missing here. But what about `:host`. Ideally this should match `^(?=.{1,255}$)[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?(?:\.[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?)*\.?$`.

**Comment by maxmeyer** [comment]
Personally I would like to see `Thor` to handle this. But I'm not aware of any `Regexp`-matching capabilities of it's cli parser.

**Comment by bhollis** [comment]
That's not a bad idea at all, but would adding parameter validation code be solving a real problem people are having?

**Comment by tdreyno** [comment]
Yeah, seems like something very unlikely to occur in the real world. I'd add it if it were upstream in Thor, but otherwise, it's probably a rabbit hole

**Comment by maxmeyer** [comment]
Ok. I started to work on some code which will make this possible in `Thor`:

```ruby
option :port, type: :numeric, matches: -> { |value| (1..65536).to_a.include? v }
```

**Comment by tdreyno** [comment]
Wouldn't the `:numeric` type have caught the `garbage` option in the original post?

**Comment by maxmeyer** [comment]
Absolutely, but you can choose a value larger than 65536.

**Comment by maxmeyer** [comment]
Just for your interest: erikhuda/thor#485 - Add validator to method_options with type :string, :numeric, :array and :hash. 

You may want to back this PR if you like the functionality or may just add a comment if you prefer to have a different implementation.

**Comment by tdreyno** [comment]
Awesome. Thanks @maxmeyer

**Comment by maxmeyer** [comment]
@tdreyno Did you forget to push the release 3.3.13 to rubygems.org?

**Comment by tdreyno** [comment]
@maxmeyer Sorry, I had to back it out. Made a pretty bad bug with i18n. Still verifying it is actually fixed.

**Comment by maxmeyer** [comment]
Ah. Ok. Thanks for the reply.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.
