### ISSUE TITLE
Possible Slim related blog error

### ISSUE THREAD

**Issue by Summonee** [middleman/middleman#1524]
Hello, I recently converted from using simple ERB to style my middleman sites and I now use Slim instead. It was working good for a while, but now I cannot build a certain blog. While when I ```middleman build``` I get no error, when I run ```middleman server``` I eventually get the error ```Slim::Engine: Option :Lang is invalid```

As I have designed my blog strangely, I manually define each page to have its own layout, even though it is exactly the same one.

In my Config.rb file, I have ```require 'slim``` as the only slim related thing there. 

Please help, you're my only hope!

**Comment by tdreyno** [comment]
Can you describe the actual error? The slim warning is just a warning and shouldn't be influencing anything. Are blog articles missing? Is there a Ruby stack trace?

**Comment by Summonee** [comment]
In between writing the original post and now, I managed to fix the error. By adding ``` :git => 'https://github.com/slim-template/slim' ``` to the gemfile after ```require 'slim'```, adding 
```set :slim, :layout_engine => :slim ```
```Slim::Engine.set_options :pretty => true ``` to config.rb and changing the default file extension to ```.slim``` I managed to fix it. 

However, now I'm getting a completely different error. My posts do not build correctly, and don't give any error, instead give off only code [See example](http://www.valiantghost.com/2015/05/grape-surgery). If I change the file extension of a post to ```.html.md``` then again I get a build error again. In the build directory, what I see are the files, but without an extension (I.E ```2015-05-15-grape-surgery``` instead of ```2015-05-15-grape-surgery.html```) leading them to be unable to be read, 

In the original case, the only error message thrown was an error next to the file when using ```middleman build```.

**Comment by tdreyno** [comment]
I'm going to need a copy of your app to diagnose

**Comment by Summonee** [comment]
[Here you go, a good old testing copy]. Good luck!

**Comment by Summonee** [comment]
Sorry, it seems like I linked nothing with my comment. I fixed it.
