### ISSUE TITLE
I18n and clean url's

### ISSUE THREAD

**Issue by nysthee** [middleman/middleman#1525]
Is it normal that Directory Indexes doesn't works when I18n is enabled?

**Comment by tdreyno** [comment]
Unfortunately, you have to activate `directory_indexes` AFTER `i18n` in v3.

**Comment by nysthee** [comment]
Thanks for the quick-response. Could be something for the documentation.

**Comment by tdreyno** [comment]
It's resolved in the v4 betas... but yeah, you're probably right.
