### ISSUE TITLE
Forum issues

### ISSUE THREAD

**Issue by Tuckie** [middleman/middleman#1534]
When attempting to login / authorize via github on forum.middlemanapp.com, I receive the error:

`Sorry, there was an error authorizing your account. Perhaps you did not approve authorization? `

I've tried on multiple browsers with different internet connections.

I'm also getting a certificate error for forum.middlemanapp.com with Chrome. Is anyone else getting this?

**Comment by dietpop** [comment]
Yes, I get the same error on Chrome.  On forum.middlemanapp.com, I clicked the sign up with GitHub button.
<img width="725" alt="screen shot 2015-10-03 at 12 17 45 pm" src="https://cloud.githubusercontent.com/assets/3495428/10264105/d6ceb888-69c8-11e5-8eff-ba6cd01d8f0b.png">

 <img width="800" alt="screen shot 2015-10-03 at 12 15 24 pm" src="https://cloud.githubusercontent.com/assets/3495428/10264085/81557b58-69c8-11e5-88f3-3dc021bac311.png">

**Comment by tdreyno** [comment]
Hmm, haven't changed anything. Maybe I'll try disconnecting and reconnecting the form from Github.

**Comment by tdreyno** [comment]
Oh, actually, looks like this may have broken when I turned SSL-only on. Try now.

**Comment by dietpop** [comment]
It works now!  Checked with Chrome.
