### ISSUE TITLE
WINDOWS padrino

### ISSUE THREAD

**Issue by DRAKUN** [middleman/middleman#1537]
>bundle exec middleman
DL is deprecated, please use Fiddle
E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/meta_pages/sitemap_resource.rb:7:in `<class:SitemapResource>': uninitialized constant Padrino::Helpers::OutputHelpers (NameError)
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/meta_pages/sitemap_resource.rb:6:in `<module:MetaPages>'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/meta_pages/sitemap_resource.rb:4:in `<module:Middleman>'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/meta_pages/sitemap_resource.rb:3:in `<top (required)>'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/meta_pages/sitemap_tree.rb:1:in `require'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/meta_pages/sitemap_tree.rb:1:in `<top (required)>'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/meta_pages.rb:4:in `require'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/meta_pages.rb:4:in `<top (required)>'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/preview_server.rb:5:in `require'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/preview_server.rb:5:in `<top (required)>'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/cli/server.rb:57:in `require'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/cli/server.rb:57:in `server'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:72:in `method_missing'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:20:in `start'
        from E:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.12/bin/middleman:18:in `<top (required)>'
        from E:/Ruby21/bin/middleman:23:in `load'
        from E:/Ruby21/bin/middleman:23:in `<main>'

C:\Users\DRAK\Documents\GitHub\stylus>

**Comment by komor72** [comment]
Have you googled the `DL is deprecated, please use Fiddle` phrase? 
I can see it’s a common problem on Windows and there are some tips provided. Have you tried them?

**Comment by Arcovion** [comment]
You must provide more details like your `Gemfile` and some steps to reproduce this.
