### ISSUE TITLE
Should asset helpers use/honour relative: argument?

### ISSUE THREAD

**Issue by komor72** [middleman/middleman#1539]
`link_to` and `url_for` helpers can have `relative: false` argument, which is very helpful when generating 404 page for the site which has relative links/assets configured to `true` in `config.rb`. But it seems that other asset helpers ignore this argument: `stylesheet_link_tag`, `javascript_include_tag`, `favicon_tag` etc. ignore it when set to `false` and erroneously pass it to compiled HTML when set to `true`:
````html
<link href="css/relative_test.css" rel="stylesheet" type="text/css" relative="true" />
````

If this is an omission and not by design then do you agree it would be helpful to patch this? 404 page needs all assets be addressed absolutely to work in any circumstances (i.e. http://mysite.com/any/wrong/deep/folder/wrong_page.html), but it is helpful to still have the ability to use relative assets in all other situations.

BTW, I cannot find a description of `activate :relative_assets` config option in the current documentation. Do I correctly understand that `set :relative_links, true` option is a MM’s patch to padrino `link_to` and `url_for` helpers only, and `activate :relative_assets` option comes from Sprockets infrastructure?

**Comment by tdreyno** [comment]
`relative_assets` is for "assets". That is, images, css, fonts and js.

Where as, you're right, we've patched some path methods to be relative too.

I made sense before, but I think you're right, the use-case is the same and having 2 approaches is kind of silly. Maybe be make a new extension: `relative_paths` which turns on both `relative_assets` and `relative_links`?

**Comment by komor72** [comment]
You’re the boss, but I think the least invasive way would be to support `relative:` argument in the rest of asset helpers and it would not break old projects and old project-code. But new unified extension is more elegant. A candidate for v4 change?
The main point is that projects which need to be relative in general, require sometimes an exception to pass `relative: false` argument to link **and** asset helpers, to properly build error pages.

**Comment by tdreyno** [comment]
Ah, gotcha. So keep the current extensions, but allow overrides. Will do in the stable branch.

**Comment by komor72** [comment]
This seems to be the simplest solution. If you would do this – it would be great! :)

**Comment by komor72** [comment]
Excellent! Thanks a lot! I just tested it on a small project and it works like charm. Unfortunately, in the process, I discovered a regression (?) from Padrino-helpers, which was updated in my project at the same time. Will make a new issue soon. (It’s unrelated to this closed one.)
