### ISSUE TITLE
Having sorting issues (on my end)

### ISSUE THREAD

**Issue by danhhoang** [middleman/middleman#1543]
This isn't a bug but more me trying to figure out erb.

The data being pulled in is coming in by alphabetical order. I want to change the order of the data but not exactly sure how to do it. A quick fix would be revert the order.

Do I need to declare a variable and then sort it?

```ruby
   <ul class="app-list">
      <% data.apps.each do |app| %>
        <% if app[1][:categories][:featured] && app[1][:categories][:script] %>
          <li>
            <%= partial 'partials/app', locals: { app: app[1] } %>
          </li>
        <% end %>
      <% end %>
   </ul>
```

Here is some code previously that magically sort them in a weird order. I'm still trying to figure out what that default_sort_position mean.

```ruby
    <ul class="app-list">
      <% default_sort_position = 99 %>
      <% sorted_apps = data.apps.sort_by { |app| app[1][:feature_position] || default_sort_position } %>
      <% sorted_apps.each do |app| %>
        <% if app[1][:categories][:featured] && app[1][:categories][:touch] %>
          <li>
            <%= partial 'partials/app', locals: { app: app[1] } %>
          </li>
        <% end %>
      <% end %>
    </ul>
```

**Comment by tdreyno** [comment]
`data.apps.sort_by { |app| app[1][:feature_position] }` will take the value at that piece of data and do `value1 <=> value2` on it. If that's just backwards, add `.reverse` to the end.

The default thing looks like it's saying if the value is missing on the data, default to a very high number.

First step, I'd make sure `app[1][:feature_position]` actually exists for each value. Otherwise, sorting `nil` might result in a crazy order.

**Comment by danhhoang** [comment]
@tdreyno That did it. My data did not have feature_position and I added it and i was able to control what position it is without using reverse.

```ruby
<% default_sort_position = 99 %>
<% sorted_apps = data.apps.sort_by { |app| app[1][:feature_position] || default_sort_position } %>
<% sorted_apps.each do |app| %>
```
For future reference, where would `.reverse` be added because no matter where I tinkered with the code, it would break the page.

**Comment by tdreyno** [comment]
```
sorted_apps.reverse.each do
```
