### ISSUE TITLE
rewriting urls in raw html?

### ISSUE THREAD

**Issue by taf2** [middleman/middleman#1544]
I think this is a bug in middleman or a feature that should be configurable.

But IMO

it should never rewrite URL's in raw HTML.

e.g. the following should never be rewritten:

```
<script src="//foobar.js"></script>
```

with

```
<script src="foobar.js"></script>
```

when setting

```
activate :relative_assets
```

what can be rewritten and would be great is:

```
<%= javascript_include_tag  "all" %>
```

hope this makes sense... using trunk we're seeing <script src being rewritten :(

**Comment by tdreyno** [comment]
This is by design.

**Comment by taf2** [comment]
that's a bad design :)

it breaks many things... google analytics and other external widgets that might want to be explicit about their protocol and host... 

it is a bug that it doesn't correctly identify a url as fully qualified though?

**Comment by tdreyno** [comment]
Yes. Please post cases where the rewrite is breaking things. External assets shouldn't be getting rewritten

**Comment by taf2** [comment]
ok google analytics is a good example of a breaking use case e.g. take the default:

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    _ga('create', 'UA-XXXXX-1',);
    _ga('send', 'pageview');
  </script>
The script url is rewritten to www.google-analytics.com/analytics.js 

it appears middleman is not recognizing a protocol relative URL.

A simpler example would be simple:

<script src="//foobar.com/test.js"></script>

**Comment by tdreyno** [comment]
Okay, so protocol-relative URLs are not being treated as external links? Definitely a bug

**Comment by taf2** [comment]
w00t awesome yes.   Thank you!

**Comment by taf2** [comment]
But for real, modifying the static html that was typed out seem's like a bad feature... I want modified asset path like URL's i should want to be explicit right?

**Comment by tdreyno** [comment]
Seems like you shouldn't need to worry about where the HTML came from, if you ask for a site to be "relative", we need to make that true.

The asset_hash extension has always behaved like this. As have minify css/js. Relative was actually the odd-man-out before.

Many of the Node build tools also do this inline rewriting.

I think it's only a little weird if you're coming from a Rails background.

Definitely worthy of a flag for disabling this. Minify has an `inline` option which defaults to `false`.

**Comment by jgillich** [comment]
@tdreyno Is asset_hash supposed to rewrite random strings in javascript code? It rewrites `g.src=u+'piwik.js';` in my [Piwik tracking code](https://developer.piwik.org/guides/tracking-javascript-guide), which then 404's. I'm not really sure if this is a bug or a feature...

**Comment by tdreyno** [comment]
It's a feature, but can be disabled

```
activate :asset_hash, ignore: [/piwik\.js$/]
```

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I think things are working as intended, and that this issue can be closed. Feel free to disagree and if so a PR with a failing test plus a fix would be a great start.
