### ISSUE TITLE
Permission denied in Middleman with asciidoctor-diagram

### ISSUE THREAD

**Issue by succzero** [middleman/middleman#1545]
I faced an error when generating an image file from an AsciiDoc file via asciidoctor-diagram.
The following is an excerpt of the error message:

```bash
Permission denied - asciidoctor: FAILED: <stdin>: Failed to parse source, Permission denied @ dir_s_mkdir - /images
/Users/succzero/mysite/vendor/bundle/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1362:in `rescue in load'
/Users/succzero/mysite/vendor/bundle/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1281:in `load'
...
```
The full log is [here](https://gist.github.com/succzero/b13b1aeb90da583251a9).

I think that it is caused by [`asciidoctor.rb:22`](https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-core/renderers/asciidoc.rb#L22).
So, I suggest that to apply [the patch](https://gist.github.com/succzero/b13b1aeb90da583251a9#file-asciidoc-patch) to `asciidoctor.rb`.

Details:
`File.join` works as follows.

```ruby
irb(main):001:0> File.join("contents", "images")
=> "contents/images"
```
The above is OK.
But if the left-hand side string is empty, `File.join` returns a path which has a '/' on its head!

```ruby
irb(main):002:0> File.join("", "images")
=> "/images"
```

The path `/images` is a direct subfolder of the root.
So, this case occur "Permission denined".

However, in the method by the patch, we need to run the `middleman build` command twice like as compile LaTeX files.

**Comment by tdreyno** [comment]
Not sure how the asciidoctor extension works, but if they're reading files off disk, they probably don't want `http_prefix` which is only for, well, prefixing HTTP requests.

As we don't control this extension, I'm going to ask that your pursue this fix with them. Feel free to @ mention me into any conversation I can help with.
