### ISSUE TITLE
Padrino-helpers 0.12.4 changes content-type handling which affects Middleman

### ISSUE THREAD

**Issue by komor72** [middleman/middleman#1546]
I just upgraded a project from Middleman 3.3.12 to 3.4.0 (directly from Github repo) and at the same time Padrino-helpers were upped from 0.12.3 to 0.12.5. After usual `middleman build` I diffed the old and new output and noticed missing content-type declarations in build output.

Like this, before upgrade (MM 3.3.12, Padrino-helpers 0.12.3):
```
<link href="css/myproject.css" rel="stylesheet" type="text/css" />
```
After upgrade (MM 3.4.0 from v3-stable, Padrino-helpers 0.12.5):
```
<link href="css/myproject.css" rel="stylesheet" />
```
Same for Javascript helper. After looking into Padrino matters I spotted this in their [changelog](https://github.com/padrino/padrino-framework/blob/master/CHANGES.rdoc): **FIX #1781 Removes the default_filters method setting incorrect content-type**. The corresponding [PR](https://github.com/padrino/padrino-framework/pull/1781), and corresponding [commit](https://github.com/padrino/padrino-framework/commit/0b2b32628c278c8262a11ae9234b819f3ffe04f5). If I correctly identified the source of change, then maybe it’s easy to fix this in Middleman. :)

**Comment by tdreyno** [comment]
I actually removed this manually in my commit. It's no longer necessary in HTML5. Any reason to add it back?

**Comment by komor72** [comment]
You are right, I’ve checked the specs. Well, it’s not a big deal, most of us use HTML5 specs anyway, these days. Although, as a sidenote, I’m not a big fan of early and eager feature removal if it doesn’t hurt to still support them. Now, formally, all non-html5 Middleman templates and projects are obsolete. Not a problem for me.
