### ISSUE TITLE
Partials caching on Windows

### ISSUE THREAD

**Issue by ArrayKnight** [middleman/middleman#1547]
In short I'm running into an issue that appears to be Windows specific (7 & 8.1) where partials are not being updated during development. I have LiveReload setup and I see in my bash console that it registers the change and I see the browser window refresh, but the content update to the partial doesn't come through to the browser. Top level pages do not have this issue, just partials.

Here's a full description of the issue:
http://stackoverflow.com/questions/30989162/middleman-partials-caching-on-windows

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

I'd suggest closing this issue. If the problem resurfaces a repro or failing test would increase the chances of finding and solving the issue.
