### ISSUE TITLE
`uninitialized constant Middleman::Logger` when running with rack

### ISSUE THREAD

**Issue by fny** [middleman/middleman#1550]
My `config.ru` matches the defaults:

```ruby
  require 'middleman-core/load_paths'
  ::Middleman.setup_load_paths

  require 'middleman-core'
  require 'middleman-core/rack'

  require 'fileutils'
  FileUtils.mkdir('log') unless File.exist?('log')
  ::Middleman::Logger.singleton("log/#{ENV['RACK_ENV']}.log")

  app = ::Middleman::Application.new

  run ::Middleman::Rack.new(app).to_app
```

But running `bundle exec rackup config.ru` blows up with the error `uninitialized constant Middleman::Logger (NameError)`

**Comment by maxmeyer** [comment]
Which version of middleman?

**Comment by fny** [comment]
That's from beta 1.  Just upgraded to beta 2, and I get this errror:

    `require': cannot load such file -- middleman-core/rack (LoadError)

**Comment by tdreyno** [comment]
`middleman-core/rack` definitely still exists. Can you try from `master`?

**Comment by olliekav** [comment]
I'm getting this error on 4.0.0.beta.3 (master) as well when using Pow or rackup.

**Comment by tdreyno** [comment]
@olliekav Added a logger require statement there. Try now?

**Comment by olliekav** [comment]
Works for me, thanks.
