### ISSUE TITLE
Autogenerate article subdirectory

### ISSUE THREAD

**Issue by MinasMazar** [middleman/middleman#1552]
Could be a good idea if `middleman article article-name` generates the [article subdirectory](https://middlemanapp.com/basics/blogging/#article-subdirectory)?

**Comment by sandstrom** [comment]
aI'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation as a starting point for discussion around this.
