### ISSUE TITLE
libv8 3.16.14.9 might break middleman, at least on travis

### ISSUE THREAD

**Issue by maxmeyer** [middleman/middleman#1553]
See cowboyd/libv8#174 for a full description.

**Comment by tdreyno** [comment]
Oh boy, thanks for the heads up!

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest closing this issue. If the problem resurfaces a repro or failing test would be a good start in solving this. Ideally also a patch with a fix.
