### ISSUE TITLE
Middleman not updating HTML image assets with an asset hash on build

### ISSUE THREAD

**Issue by bmiles** [middleman/middleman#1554]
When building my middleman site, the correct asset_hash is not being appended to the html.

For instance the build produces this HTML:
```html
<a class="navbar-brand" href="/"><img src="/images/logo.png" alt="Dentally Logo" class="logo" /></a>
```
But names the image asset, ```logo-8826a333.png```

Build section from the config:
```ruby
configure :build do

  activate :minify_css
  activate :minify_javascript

  # Enable cache buster
  activate :cache_buster
  activate :asset_hash

  # Use relative URLs
  activate :relative_assets

  # Compress imges after build
  # On OS X you'll need to run:
  # brew install advancecomp gifsicle jhead jpegoptim jpeg optipng pngcrush
  activate :imageoptim do |options|
    # print out skipped images
    options.verbose = false

    # Setting these to true or nil will let options determine them (recommended)
    options.nice = true
    options.threads = true

    # Image extensions to attempt to compress
    options.image_extensions = %w(.png .jpg .gif .svg)

    # compressor worker options, individual optimisers can be disabled by passing
    # false instead of a hash
    options.pngcrush  = { chunks: ['alla'], fix: false, brute: false}
    options.pngout    = false
    options.optipng   = { level: 6, interlace: false }
    options.advpng    = { level: 4 }
    options.jpegoptim = { strip: ['all'], max_quality: 100}
    options.jpegtran  = { copy_chunks: false, progressive: true, jpegrescan: true }
    options.gifsicle  = { interlace: false }
  end

end
```

Any ideas to fix this? Still happens with Middleman 3.3.12

Cheers

**Comment by tdreyno** [comment]
What does your original html template look like? Does it work without `imageoptim`?

**Comment by tdreyno** [comment]
Also, you should use cache_buster or asset_hash, but both is overkill.

**Comment by bmiles** [comment]
Thanks @tdreyno, works fine without works ok with just cache_buster but I noticed there are no hashes on the assets or the html.

Still broken with asset_hash and ```imageoptim```

Though build works fine with asset_hash without ```imageoptim```

Here's the HTML template:

```html
<a class="navbar-brand" href="/"><%= tag :img, src: "/images/logo.png", alt: "Dentally Logo", class: "logo" %></a>
```

Thanks

**Comment by tdreyno** [comment]
Try:

```
<a class="navbar-brand" href="/"><%= image_tag "logo.png", alt: "Dentally Logo", class: "logo" %></a>
```

**Comment by bmiles** [comment]
Thanks, sadly the HTML template is still not updated contain the hash:
```
[03/Jul/2015 09:56:39] "GET /logo.png HTTP/1.1" 404
```

**Comment by tdreyno** [comment]
well, the request should be for `/logo-{hash}.png`, not `logo.png` so is the logo not being updated in your HTML?

**Comment by bmiles** [comment]
yes that's correct

**Comment by tdreyno** [comment]
Try swapping the order of `relative_assets` and `asset_hash` in your config?

**Comment by bmiles** [comment]
Thanks @tdreyno unfortunately that didn't work either.

I have noticed that when I delete the build directory and build "fresh" everything works as expected. It is only when there is an existing build where it does not append the hash to HTML.

Thanks

**Comment by tdreyno** [comment]
Oh. Does it work in the server/preview mode?

**Comment by bmiles** [comment]
all images load fine when I run ```middleman server``` except the asset I changed from ```/images/logo.png``` to ```/logo.png``` I presume this is because ```imageoptim``` will only run when I build.

**Comment by tdreyno** [comment]
If you can post a version of your project, I can test on my machine

**Comment by bmiles** [comment]
Hi @tdreyno I've added you to a repo, thanks for your help.

**Comment by tdreyno** [comment]
Thanks @bmiles. I'm traveling on bad wifi, so I'll try my best. Will be back home next week.

**Comment by bmiles** [comment]
Hey @tdreyno did you manage to replicate the issue?

**Comment by tdreyno** [comment]
Not yet, backlogged at work from the holiday.

**Comment by bmiles** [comment]
No worries!

**Comment by bmiles** [comment]
Hey, any updates at all? 

All the best

**Comment by tdreyno** [comment]
I think this is a dup of another bug, but, basically, don't use `imageoptim` until they fix their extension.
