### ISSUE TITLE
dynamic pages end up without filename extension after build

### ISSUE THREAD

**Issue by crtvhd** [middleman/middleman#1557]
I am using ```proxy``` to generate dynamic pages based on yaml data:
```ruby
data.portfolio.projects.each do |p|
  proxy "/projects/#{p.client.name.parameterize}/#{p.title.parameterize}", "/projects/show.html", locals: { project: p }, ignore: true
end

```

Also I'm using directory indexes:
```ruby
configure :development do
  activate :directory_indexes
  […]
```
```ruby
configure :build do
  activate :directory_indexes
  […]
```

During DEV mode everything works nicely, however when I build my middleman project all my generated pages are nested false, named false and are missing a filename extension. Instead of ```build/projects/clientname/projectname/index.html``` I end up with ```build/projects/clientname/projectname``` (file with no extension). 
I'm using middleman 4.0.0.beta.2.

**Comment by tdreyno** [comment]
Definitely add `.html` to your proxy output path. Directory index will see that and correctly rename.

**Comment by crtvhd** [comment]
I tried adding ```.html``` but unfortunately directory_indexes won't rename accordingly during build, the filename extension stays. Also during development my routes (```/projects/clientname/projectname```) stopped working.

**Comment by tdreyno** [comment]
Hmm, probably an ordering issue in v3. I guess add `/index.html` for now.

**Comment by dkastl** [comment]
This problem still exists unfortunately in Middleman 4.2.1

**Comment by tdreyno** [comment]
@dkastl Given that this ticket is ~3 years old. Can you please open a new ticket with a reproducible test case?

Also, can you test against the current beta release: 4.3.0.rc.3
