### ISSUE TITLE
Cannot get i18n to do anything on a brand new middleman install

### ISSUE THREAD

**Issue by robertwbradford** [middleman/middleman#1558]
I setup a new Middleman site and started following the instructions here: https://middlemanapp.com/advanced/localization/

However, it's not doing anything for me in the preview mode or when I build. When I visit `http://localhost:4567/hello.html` or `http://localhost:4567/es/hello.html` (I used `source/locallizable/hello.html.erb`) I get 404s. When I build, the localized directories are not created and the `/locales/` directory is included with all the `.yml` files.

What am I missing? I need another pair of eyes. Here is a copy of the app: https://github.com/robertwbradford/middleman-with-i18n-activated

**Comment by floriankessler** [comment]
Hi Robert,

put your locales folder one level up, next to source. Not within source. Ie.

```mv source\locales .```

**Comment by robertwbradford** [comment]
So when it says, "[Middleman] will search the `locales` folder in the root of your project for YAML files," I guess it means they should be in the root of the project :) Missed that part! Thank you, @floriankessler.

**Comment by floriankessler** [comment]
you could say that ;-)
welcome
