### ISSUE TITLE
Uninitialized constant Middleman::Pagination::

### ISSUE THREAD

**Issue by sebastiangraz** [middleman/middleman#1559]
Hi Im able to install Middleman 3.3.12 with no problems. When running ````middleman init```` I get the following error message:

     /Library/Ruby/Gems/2.0.0/gems/middleman-pagination-    1.2.0/lib/middleman/pagination/extension_context.rb:4:in `<class:ExtensionContext>': uninitialized constant Middleman::Pagination::ExtensionContext::Forwardable (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/middleman-pagination-1.2.0/lib/middleman/pagination/extension_context.rb:3:in `<module:Pagination>'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-pagination-1.2.0/lib/middleman/pagination/extension_context.rb:2:in `<module:Middleman>'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-pagination-1.2.0/lib/middleman/pagination/extension_context.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-pagination-1.2.0/lib/middleman/pagination.rb:5:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-pagination-1.2.0/lib/middleman-pagination.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.12/lib/middleman-core/extensions.rb:66:in `block in load_extensions_in_path'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.12/lib/middleman-core/extensions.rb:65:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.12/lib/middleman-core/extensions.rb:65:in `load_extensions_in_path'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.12/lib/middleman-core/load_paths.rb:39:in `setup_load_paths'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.3.12/bin/middleman:10:in `<top (required)>'
	from /usr/bin/middleman:23:in `load'
	from /usr/bin/middleman:23:in `<main>'

Anyone know how I can fix it?

**Comment by tdreyno** [comment]
`gem uninstall middleman-pagination`

Looks like a bug in the module scoping of that extension.
