### ISSUE TITLE
Aruba 0.8 breaks the middleman build

### ISSUE THREAD

**Issue by mauro-oto** [middleman/middleman#1561]
Running the tests locally and in Travis, the build breaks when using Aruba 0.8. `bundle install` installs the latest version for it, released yesterday. 

In my PR https://github.com/middleman/middleman/pull/1560 I locked the Aruba gem to `~> 0.7.4` instead so that it doesn't update to 0.8 yet.

**Comment by mauro-oto** [comment]
Closed after merge of https://github.com/middleman/middleman/pull/1560

**Comment by maxmeyer** [comment]
@mauro-oto Can you tell me, what exactly breaks `middleman`? Are there any logs you can file as issue at http://github.com/cucumber/aruba?

**Comment by mauro-oto** [comment]
@maxmeyer for some reason, on Mac OSX 10.10, it was not creating the directories it was supposed to create. I don't have many details as I didn't look into it too much, but I can reproduce this later and provide you some logs.

**Comment by maxmeyer** [comment]
Ok. That should be fixed with 0.8.1...
