### ISSUE TITLE
Middleman hangs on minifed json with asset_hash enabled

### ISSUE THREAD

**Issue by ryanmark** [middleman/middleman#1563]
I have this json file in my project: http://bl.ocks.org/mbostock/raw/4090846/us.json

When I run build, it hangs on this file. One time we just let it run and it eventually completed after an hour or so.

The snag is here:
https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-more/extensions/asset_hash.rb#L94

I can recreate this issue with these few lines of ruby:

```ruby
re = /([=\'\"\(,]\s*)([^\s\'\"\)]+(\.woff2|\.woff|\.webp|\.ttf|\.svgz|\.svg|\.png|\.otf|\.js|\.jpg|\.jpeg|\.gif|\.eot|\.css))/
open('us.json').read.gsub(re) { |match| puts match }
```

If I pretty format the json before running it through this regex, it goes super fast.

The work around is simple, but not obvious. Smells like a bug to me.

**Comment by tdreyno** [comment]
Interesting. Any difference on different ruby versions?

**Comment by tdreyno** [comment]
I guess in the short term. Pretty print and re-minify at build time... or, add to `asset_hash`'s `ignore` array of regexes.

**Comment by Arcovion** [comment]
You could introduce a max filename limit, which I think is 255:
```ruby
re = /([=\'\"\(,]\s*)([^\s\'\"\)]{1,255}(\.woff2|\.woff|\.webp|\.ttf|\.svgz|\.svg|\.png|\.otf|\.js|\.jpg|\.jpeg|\.gif|\.eot|\.css))/
```
Still bad, but won't take *hours* any more :D

**Comment by tdreyno** [comment]
If I remove the captures, it's a lot faster to test for a single match before trying to replace all.

**Comment by tdreyno** [comment]
Pushed a tweak. Filename limit plus the removal of an unneeded capture.

**Comment by Arcovion** [comment]
I think the capture was needed to group the extensions, otherwise it's like `filename.foo|.bar` instead of `filename(.foo|.bar)`
Changing this line:
```ruby
 @exts_regex_text = @exts.map { |e| Regexp.escape(e) }.sort.reverse.join('|')
```
to
```ruby
 @exts_regex_text = Regexp.union(@exts.sort.reverse)
```
will fix it though, making a non-capturing group `(?:)` which looks like `/filename(?-mix:\.foo|\.bar)/`

**Comment by ryanmark** [comment]
Thanks for looking into this so quickly!

So adding the `ignore` option was the first thing i tried, however this regex is run against hardcoded list of file types. I kinda expected ignore to cause the plugin to not touch any matching files.

I only tested it against ruby 2.1.

Arcovion is right about that capture, that commit tdreyno made might have some strange side-effects.

**Comment by tdreyno** [comment]
Oooh, I see. So `exts` is the list of extensions to look for in content. `ignore` describes which files to rename. There is not option for changing which types have content replaced in them or, being able to skip certain paths when regexing.

I've reverted that last change. Since out next release is 3.4, I can add some new features. I'll make the other extension regex configurable and allow per-match ignoring.

I'll probably switch all 4 options to Procs, but maintain the ability to support arrays as well.

**Comment by sandstrom** [comment]
@ryanmark perhaps this was solved by https://github.com/middleman/middleman/pull/1740, if so feel free to close.
