### ISSUE TITLE
localization not working

### ISSUE THREAD

**Issue by rubytastic** [middleman/middleman#1565]
Localization seems to be not working in Middleman.
Also I would preferrable just have the /source/myfile.html just pick up the language with <%= t(:hello) %> 
Is there a way to change the "lockalized" folder to just "source" root path?

I have this in config.rb ( at the top ) 
activate :i18n

source/local/en.yml
---
en:
  hello: "Hello"

Then inside localizable/index.html 
I have         = t(:hello)  ( using HAML ) 

It throws a 404.

When I place this inside any regular /source/filename.html file lit shows a en.hello translation not found.

Any thoughts on how to resolve these issues?
Documentation seems clear but it is not working like it should after following the steps.

**Comment by tdreyno** [comment]
mv source/local/en.yml locales/en.yml
