### ISSUE TITLE
Repeat extensions being unnecessarily removed

### ISSUE THREAD

**Issue by timcheadle** [middleman/middleman#1568]
Shopify supports very basis SCSS, but expects a single stylesheet file using the Liquid templating language, like so: `theme.scss.liquid`

Shopify compiles any liquid syntax, then compiles the SCSS. However, it doesn't support `@import` of multiple files, so I'm using Middleman to build locally and keep things organized.

I named my file `theme.scss.liquid.scss`, but the build process does this:

`source/assets/theme.scss.liquid.scss` --> `build/assets/theme.liqiud`

If I rename it to `theme.css.liquid.scss` it works fine:

`source/assets/theme.css.liquid.scss` --> `build/assets/theme.css.liqiud`

I need the SCSS extension to make some Shopify theme settings work correctly. I think something is removing everything in the filename that matches `scss`, but this isn't necessary.

As a workaround, I've done this hack in `config.rb`:

```
  after_build do
    File.rename 'build/assets/theme.css.liquid', 'build/assets/theme.scss.liquid'
  end
```

Ultimately this seems like a bug in Middleman, though.

**Comment by tdreyno** [comment]
So, you want to generate a file with Liquid templating still present in the output? And you do not have the `liquid` gem in your project, so the only installed templating engine is the built-in `scss`. Correct?

**Comment by timcheadle** [comment]
That's right.

```
» ack liquid Gemfile.lock
»
```

**Comment by tdreyno** [comment]
Okay, yeah, that seems like a bug. I'll write a test case.
