### ISSUE TITLE
current_page.siblings is always empty

### ISSUE THREAD

**Issue by robertwbradford** [middleman/middleman#1569]
If I'm understanding this method correctly, I should get an array of resources that are in the same directory. I have the following

```
localizable/
  +-- some-directory/
        |-- one.en.html.md
        |-- one.es.html.md
        |-- two.en.html.md
        |-- two.es.html.md
        |-- three.en.html.md
        +-- three.es.html.md
```

In my layout I have the following:

``` erb
<%= current_page.siblings %>
```

When viewing any of these pages it always returns an empty array. I've tried it both with and without `activate :directory_indexes` in my `config.rb`, but it's always empty.

I'm using `gem "middleman", github: "middleman/middleman", branch: "v3-stable"` and am not sure what other factors would be affecting this. What am I missing?

**Comment by tdreyno** [comment]
Not sure. I don't think we have any tests covering the combination of siblings and i18n. I'll write some.

**Comment by robertwbradford** [comment]
I realized this will not work if you do not have an `index` file in the directory acting as the "parent." Makes sense now that I see that in Middleman::Sitemap::Extensions::Traversal. Once I added the index things worked fine.

**Comment by tdreyno** [comment]
Hmmm... maybe still a bug, tho.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest closing this issue. If the problem resurfaces a repro or failing test would be a good start in solving this. Ideally also a patch with a fix.
