### ISSUE TITLE
hash not added to image path in head

### ISSUE THREAD

**Issue by dkdl** [middleman/middleman#1571]
for images I use imageoptim and asset_hash.

config.rb:
````
activate :asset_hash
activate :imageoptim
````

This works great for all images. Except inside the head it won't add the hash to the image url.
````
<head>
  <meta property="og:image" content="<%= data.global.domain %><%= image_path "#{project_id}/1-1.jpg" %>" />
</head>
````

Is there a way to get the hash behind the url inside the head?
Or is it possible to upload the original image files as well on build?

**Comment by tdreyno** [comment]
Any difference if you don't use `imageoptim`.

Also, try `image_url` rather than `image_path`

**Comment by dkdl** [comment]
Hi @tdreyno 
without imageoptim the urls are okay, but I have to use imageoptim due to a lot of images per page.

I tried ````image_url````, but then the build is not working. I use i18n. Maybe it has to do something with that?

**Comment by tdreyno** [comment]
Okay, well, I'm going to have to close this in favor of a bug report on the `middleman-imageoptim` extension (which is a 3rd party extension). Happy to work with their devs to resolve this.

Personally, I just do this:

```
after_build do
  `./bin/my-image-optim-script`
end
```

**Comment by dkdl** [comment]
Hi @tdreyno 
I think I made the question a bit confusing by adding imageoptim. It's only about the asset_hash that is not adding a hash to image url in the ````<head>````

This is what I get:
````<meta property="og:image" content="https://website.com/img/projects/project-1/1-1.jpg">````

But it should be:
````<meta property="og:image" content="https://website.com/img/projects/project-1/1-1-84a740eb.jpg">````

Images inside the ````<body>```` are working fine. Hopefully it's clear now what i'm asking :)

**Comment by tdreyno** [comment]
So, IIRC, we don't hash URLs with a domain since we don't know if that external host is renaming their files. Except, when using the `asset_host` extension.

**Comment by kandebonfim** [comment]
@dkdl I'm having the same issue.

**Comment by dmfrancisco** [comment]
@kandebonfim There's an [ignore option](https://middlemanapp.com/advanced/improving-cacheability/) that you could use:

```ruby
# config.rb
activate :asset_hash, ignore: '1-1.jpg' # The name you use for og:image
```
