### ISSUE TITLE
Using polymer with middleman: cannot do <link rel="import" href="/bower_components/..

### ISSUE THREAD

**Issue by stilllife00** [middleman/middleman#1572]
I am trying to use Polymer with middleman just to include a simple youtube player.
The way of including the Google Elements is a link tag

    <link rel="import" href="/bower_components/google-youtube/google-youtube.html">

But since the bower_components folder is outside the source folder, middleman does not find it.
Moving bower_components into source I don't think is a good solution (it will be compiled and it is not a good practice)

Here  #1330 they suggest an approach with Grunt, which even if it might work, seems like a way to hack around things, when just a file import should be easy and flexible. Thats the point of using Polymer , otherwise I will just use the traditional youtube api.

Any idea on how to solve this ?

**Comment by tdreyno** [comment]
Moving into the source folder would be how a normal Polymer dev setup would work. If you're using minification, you can disable it for the `bower_components` path.

The whole "web components dependency" stuff is a mess right now.

You can use `vulcanize` (via grunt if necessary) to compile down to a single file to be served.
