### ISSUE TITLE
:asset_hash does not work with lazysizes.js

### ISSUE THREAD

**Issue by karland** [middleman/middleman#1573]
[lazysizes](https://github.com/aFarkas/lazysizes) is a lazy loader for images (responsive and normal). It calls images like this:

```html
<img
    data-sizes="100vw"
    src="/img/image-220.jpg"
    data-srcset="/img/image-220.png 220w,
    /img/image-300.png 300w,
    /img/img-600.png 600w,
    /img/image-900 900w" class="lazyload" />
```

For instance, for parent elements of the image larger than 300px it calls `/img/img-600.png`.
The problem is that the `:asset_hash` option only seems to recognize the file in the `src` but not in the `data-srcset`. 

Independent of `lazysizes` `:asset_hash` also does not seem to work with plain `srcset`.

**Comment by pzi** [comment]
Hey @karland, have you tried using `image_path` to resolve the paths to these images?

More advanced would be to create a helper that generates the above tag with attributes for you. Similar to my [srcset_tag_helper](https://github.com/pzi/middleman-basis/blob/18f823cb8c321ea1a278ed777b1c4f31c5607360/helpers/image_srcset_tag_helper.rb)

Hope this helps?

**Comment by tdreyno** [comment]
Is the lack of an extension on `image-900` simply a typo?

We have tests which cover this approach here: https://github.com/middleman/middleman/blob/a38a20322f3832b3d1563c973b14d44f047eda77/middleman-core/features/asset_hash.feature#L34

The template looks like: https://github.com/middleman/middleman/blob/f5fe46cb593dcbe57baf870320ca3f8978ca6377/middleman-core/fixtures/asset-hash-app/source/index.html.erb#L6

https://github.com/middleman/middleman/blob/f5fe46cb593dcbe57baf870320ca3f8978ca6377/middleman-core/fixtures/asset-hash-app/source/index.html.erb#L6

**Comment by karland** [comment]
@pzi, @tdreyno Thanks a lot. My question is now, how could I have found out about `image_path` myself? I checked and `image_path` is neither documented on middlemanapp.com nor in padrino. Or did I overlook anything?

PS: the lack of the extension simply was a typo here but not in the source. Sorry. I corrected it for reference purposes.

**Comment by tdreyno** [comment]
You're probably correct. There's a lot of stuff that's borrowed from Rails and we often forget to document. Thanks for raising the flag.

Maybe we can add a better example here: https://github.com/middleman/middleman-guides/blob/07a5cedc0c47251a634eda214299458bc4f035af/source/advanced/improving_cacheability.html.markdown

Would love a PR if you can think of a way of integrating that information that speaks well to users without my familiarity with the codebase?

**Comment by karland** [comment]
@tdreyno I have done [this PR](https://github.com/middleman/middleman-guides/pull/493). Please see, if it makes you happy. Cheers.

**Comment by tdreyno** [comment]
Thanks so much. :beers:
