### ISSUE TITLE
i18n default as browser lang

### ISSUE THREAD

**Issue by Dfmarulanda** [middleman/middleman#1574]
Its possible to make browser lang as root?

**Comment by tdreyno** [comment]
```
activate :i18n, mount_at_root: :en
```

https://middlemanapp.com/advanced/localization/#default-root-language

**Comment by Dfmarulanda** [comment]
I was wondering if a guy from spain enter the website, root will be spanish, if is someone from UK will be english.

**Comment by tdreyno** [comment]
No, you will be building a static site which has no logic of its own. You can use your web server to detect location and redirect to the correct folder as a result.
