### ISSUE TITLE
I18n.locale always returns "en" in dynamic page templates

### ISSUE THREAD

**Issue by robertwbradford** [middleman/middleman#1575]
For the site I'm working on, we will be using locales such `en-us` and `es-mx`. Everything seemed to be okay until I started messing with dynamic pages today. When I call `I18n.locale` in a template file for dynamic pages, I only get `en`.

I've tried looking around the source code, but couldn't find where this would be happening. Here's a middleman app with the basic setup:

https://github.com/robertwbradford/middleman-with-dynamic-pages-and-locales

You'll see in my `config.rb` that I have a slightly modified version of [these instructions](https://middlemanapp.com/advanced/dynamic_pages/). (My template is in `/localizable/about/template.html`.)

In my template I'm have the following:
```erb
<p><%= I18n.locale %></p>
<p><%= "#{t(:hello)} #{person_name}" %></p>
```
[http://localhost:4567/about/dick](http://localhost:4567/about/dick) outputs:
```html
<p>en</p>
<p>translation missing: en.hello dick</p>
```
I'm not seeing where the I18n.locale gets set.

**Comment by robertwbradford** [comment]
Actually, I just tried changing my locales to `eng` and `spa` and noticed that I'm still always getting `en` when calling `<%= I18n.locale %>` in a dynamic page template.

**Comment by robertwbradford** [comment]
Ok, I believe this has to do with the `mount_at_root` option when activating i18n. I noticed the following in `middleman-core/lib/middleman-more/core_extensions/i18n.rb`:
```rb
def configure_i18n
  ::I18n.load_path += Dir[File.join(app.root, @locales_glob)]
  ::I18n.reload!
  
  ::I18n.default_locale = @mount_at_root

  # Reset fallbacks to fall back to our new default
  ::I18n.fallbacks = ::I18n::Locale::Fallbacks.new if ::I18n.respond_to?(:fallbacks)
end
```
The `default_locale` is getting set to `@mount_at_root`. However, I have this set to false in my config because I want to always force having the locale in the URL. Hmm....

**Comment by tdreyno** [comment]
Where is `/about/dick` coming from?

If you're making your own proxies, you need to setup their langs accordingly.

```
proxy "/about/whatever.html", "/localizable/about/template.html", lang: :eng
```

**Comment by robertwbradford** [comment]
Thank you, thank you! The `about/dick` URL is based on the sample code used from https://middlemanapp.com/advanced/dynamic_pages/. 

I wasn't aware of the `lang` option for the `proxy` method. May be good to add it to the dynamic page documentation.

**Comment by tdreyno** [comment]
For reference, i18n is implemented as a bunch of proxies with the lang set by looping over the contents of `localizable` and creating one for each locale.

Simply proxying to an item in localizable won't work.

**Comment by robertwbradford** [comment]
Right, I will be doing something like the following:
```rb
langs.each do |locale|
  data.people.each do |k, v|
    proxy "/#{locale}/people/#{v.name}.html", "/localizable/templates/people.html", locals: { person: v }, lang: locale
  end
end
```
Thank you.
