### ISSUE TITLE
Latest listen version bump gives dependency error on FontCustom

### ISSUE THREAD

**Issue by RickMeijer** [middleman/middleman#1576]
I'm using middleman-fontcustom for my project, which depends on fontcustom.
Fontcustom has has it's listen version set to `">=1.0","<3.0"` in the gemspec.
Middleman-core has it's listen version set to `"~> 3.0.3"` since 5 days ago. 

As such, these two are now incompatible apparently for no good reason (gemspec is the only file changed, suggesting not using new functionality listen 3.0 introduced). Would it be possible to define the listen gem dependency as just `>= 2.7.9` or something?

There's a [pull request open](https://github.com/FontCustom/fontcustom/pull/283) for this issue where it belongs, but it seems Fontcustom is not really as actively maintained as Middleman.

**Comment by tdreyno** [comment]
:(

This is the same issue we've had with a bunch of projects. They really sure separate their CLI functionality from their assets.

Listen 3 seems to be a very safe upgrade. I'll hold releasing MM 3.4 until this is resolved.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue since it's not related to middleman.
