### ISSUE TITLE
Verify if there is consistency with HTML-output syntax within many templating languages used by Middleman

### ISSUE THREAD

**Issue by komor72** [middleman/middleman#1577]
A little revisit to the specs and HTML5-defaulted output discussed in #1546. I’m going to investigate this, so I open this issue for me. But any discussion is welcomed, of course.

The same project with MM 3.4.0 from v3-stable and Padrino-helpers 0.12.5 (as discussed in #1546).

This HAML input:
```haml
%article
  .article_content
    %h1 404 – blah
    %p
      Blah blah.
    %p.blog_photo
      %img{src: "/site_images/photo.jpg", class: "w630 retina lazy"}
      =image_tag "/site_images/photo.jpg", class: "w630 retina lazy"
```

Generates this HTML output:
```html
<article>
  <div class='article_content'>
    <h1>404 – blah </h1>
    <p>
      Blah blah.
    </p>
    <p class='blog_photo'>
      <img class='w630 retina lazy' src='/site_images/photo.jpg'>
      <img class="w630 retina lazy" src="site_images/photo.jpg" />
    </p>
  </div>
</article>
```
Pay attention to tag-autoclose in the second variant. (Don’t pay attention to lack of absolute path in the second variant, it is OK until later.) This difference is okay [according to the specs](http://dev.w3.org/html5/spec-author-view/syntax.html#syntax-start-tag) but maybe we should revisit and verify the behaviour of many templating languages supported by Middleman.

**Comment by tdreyno** [comment]
I think there is a flag somewhere in... padrino or haml to default to HTML5... we really should these days.
