### ISSUE TITLE
Localize Directory names

### ISSUE THREAD

**Issue by shibulijack-fd** [middleman/middleman#1582]
I have a site with basic localization working fine. But when I move the pages to a directory, there is no way to localize the name of the directory. Is there any workaround for this issue?

**Comment by tdreyno** [comment]
try this: https://middlemanapp.com/advanced/localization/#localized-paths

**Comment by shibulijack-fd** [comment]
No that's not what I was talking about! 
Say for instance I have a page structure:

localizable
|--customer-engagment [directory]

**Comment by tdreyno** [comment]
Should work the exact same way

**Comment by tdreyno** [comment]
```
---
es:
  paths:
    "customer-engagement": "something-else"
```

**Comment by shibulijack-fd** [comment]
Nope. That doesn't work, unless the core i18n extension is modified. Now, I have made the necessary changes in the i18n gem of my project, but it would be nice if it is implemented in [middleman core](https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-more/core_extensions/i18n.rb).

**Comment by tdreyno** [comment]
Should be happening here: https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-more/core_extensions/i18n.rb#L252

We have tests for this, will have to write some more.
