### ISSUE TITLE
Middlemanapp documentation search masks text

### ISSUE THREAD

**Issue by eric-hu** [middleman/middleman#1583]
The documentation site at middlemanapp.com masks typed text in OS X Firefox.

I'm using OS X 10.9.5 and Firefox 40.0.  Using the latest Chrome on the same system shows the text in the search box as intended.

**Comment by stevenosloan** [comment]
Hey @eric-hu I just opened an "alias" issue over on the middleman-guides project where the docs site is generated from.

**Comment by eric-hu** [comment]
:+1:

**Comment by tdreyno** [comment]
Closing the favor of the guides bug
