### ISSUE TITLE
localisable sitemaps support

### ISSUE THREAD

**Issue by bhagyas** [middleman/middleman#1584]
Add sitemaps feature with support for generating multilingual sitemaps.

**Comment by tdreyno** [comment]
You mean like https://github.com/pixelpark/middleman-sitemap

**Comment by bhagyas** [comment]
The Middleman sitemap has no support for generating standards compliant international sitemaps.

https://support.google.com/webmasters/answer/2620865?hl=en

**Comment by tdreyno** [comment]
Gotcha. I suggest you open a ticket on the above extension's bug tracker and see if they're interested in adding the feature.

**Comment by bhagyas** [comment]
Already did. Would you think it's a good idea to be built into the core?

**Comment by tdreyno** [comment]
We're actively slimming down the code and relying on extensions for as many things as possible.
