### ISSUE TITLE
js_dir & asset_hash collision?

### ISSUE THREAD

**Issue by shaekuronen** [middleman/middleman#1585]
This was happening in my project, set up a test app `middleman init test-project` (Middleman 3.4.0) and am seeing similar behavior.

```
set :css_dir, 'stylesheets'
set :js_dir, 'javascripts'
set :images_dir, 'images'

# Build-specific configuration
configure :build do
  set :js_dir, 'test/javascripts'
  activate :asset_hash
end
```

The `javascript_include_tag` helper does not include the hash in the file name if `set :js_dir, 'test/javascripts'` is in the build config. If I comment that out, the file rev works.

Seeing the same behavior with `css_dir` in the test project. 

Is it possible to set these global variables and have file revving?

**Comment by tdreyno** [comment]
Definitely sounds like a bug. I'll dig in

**Comment by mattrussell36** [comment]
Any progress on this bug? I've run into the same problem. However, I was able to get around it by setting 
`:asset_host` to whatever path I needed. 

```
activate :asset_host
set :asset_host do 
  'path'
end
```

**Comment by tdreyno** [comment]
Haven't had a chance, things got busy at work. Happy for any help from the community

**Comment by jordanandree** [comment]
@shaekuronen dumb question here, but are you sure the same js files with matching names exist in `./source/test/javascripts` ?

I can replicate the missing hashed file name with these steps, but I'm not creating any files in `./source/test/javascripts`:
1. init new middleman project (ruby 2.2.3)
2. bundle install
3. copy your config.rb
4. create `./source/test/javascripts` directory
5. run `middleman build`
6. `./build/index.html` has script tag linking to `/test/javascripts/all.js` but with no hash

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.
