### ISSUE TITLE
Thoughts on implementing a/b testing with Middleman?

### ISSUE THREAD

**Issue by rubytastic** [middleman/middleman#1586]
Is there a solution yet for a/b testing for middleman and are there thoughts on this subject?
I was planning to write something to handle this but before making this contribution perhaps there is already something out like that?

**Comment by tdreyno** [comment]
A pretty straight forward approach would be to create an environmental variable and use it in templates.

```
MODE=b bundle exec middleman build
```

Where `config.rb` is something like:

```
set :build_dir, ENV['mode'] == 'b' ? 'build/b' : 'build/a'
```

And template are like:

```
<% if ENV['mode'] == 'b' %>
   CTA 1
<% else %>
  CTA 2
<% end %>
```

**Comment by dsignr** [comment]
This is so cool! Thanks for this trick :+1:

**Comment by foucist** [comment]
Could also use https://github.com/splitrb/split at the rack level
