### ISSUE TITLE
undefined local variable or method 'current_article'

### ISSUE THREAD

**Issue by heynicecode** [middleman/middleman#1589]
I am attempting to use Yaml attributes within my Haml files and am having no success. It appears as if my `current_article` method doesn't exist. Here's my very simple code in a file called `index.haml`:

    ---
    title: Here is my title
    ---
    
    / Here is my comment
    %p Hello world! This is = current_article.title

However, the above only generates this:

    Hello world! This is = current_article.title

Here are the contents of my `gemfile`

    source "https://rubygems.org"
    
    gem "middleman", "~>3.4.0"
    gem "middleman-blog"
    
    # Live-reloading plugin
    gem "middleman-livereload", "~> 3.1.0"
    
    # haml
    gem "haml"

    # neat
    gem "neat"

    # For faster file watcher updates on Windows:
    gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

    # Windows does not come with time zone data
    gem "tzinfo-data", platforms: [:mswin, :mingw, :jruby]

Any ideas what could be wrong?

**Comment by Arcovion** [comment]
Should be no backslash before the two `---` lines

**Comment by heynicecode** [comment]
@Arcovion I removed the backslashed (and updated my previous comment) but am still getting the same thing.

**Comment by Arcovion** [comment]
This line isn't correct:
`%p Hello world! This is = current_article.title`
I think you want:
```haml
%p
  Hello world! This is
  = current_article.title
```

This assigns text to the tag:
`%p text`
This assigns a ruby value:
`%p = value`
You can't mix both in a single line.

Though I might be wrong, haven't used Haml recently.

**Comment by heynicecode** [comment]
Still no dice but it seems like the issue may actually be with the 'current_article' function itself. I've updated this issue to reflect that.

**Comment by Arcovion** [comment]
If your file is `index.haml` then it's probably not in the blog posts directory where the articles are. 
Therefore you should use `current_page`, or maybe it just needs to be `current_article.data.title`.
Try `current_page.data.title`, `page.data.title`... something like this must work.

**Comment by heynicecode** [comment]
I tried `current_page.data.title` and `page.data.title` but to no avail.

Also, where is the blog posts directory? I created this app with a basic `middleman init` but I ran `middleman init --template=blog` again to generate the blog files. `--template=blog` just generated the blog files in the root of my `source` directory.

**Comment by tdreyno** [comment]
`index.haml` will never be a blog post. So, it will never have a `current_article`. Articles must be in Markdown, not HAML. If you have a layout which wraps pages, it will have `current_page.data.title` available.

**Comment by heynicecode** [comment]
@tdreyno Thanks for clearing that up. `current_page.data.title` does work now, although I'm not entirely sure why. I hand been using `--template=html5` before and switched to the [Proteus](https://github.com/thoughtbot/proteus-middleman) starter kit and that's when everything began to work. I assume there's something wrong with Middleman's html5 template but again, I'm not 100% sure about that.

Also, I created a test app with the `--template=blog` to confirm whether haml works, in lieu of Markdown, works for articles and it did. So I guess that's a plus. Thanks again for your help.
