### ISSUE TITLE
sitemap.resources empty when used erb file in javascript directory

### ISSUE THREAD

**Issue by ryanburnette** [middleman/middleman#1590]
I'm rendering some Js on the fly in my project at `./source/assets/javascripts/stuff.js.erb`. `./source/assets/javascripts` is my JavaScript directory. I'm using `sitemap.resources` and iterating over the objects contained within to render my Js on the fly. This works fine while using `middleman server`, but once I run `middleman build`, `sitemap.resources` is empty. This only seems to happen when using `sitemap.resources` from inside the JavaScript directory.. I'm using `sitemap.resources` in several other places around the theme and it works normally during build.

I tried disabling js minification during build and it didn't make a difference.

My issue sounds a little similar to #1172 but I'm not sure if it's related.

**Comment by tdreyno** [comment]
Let me see if I can write a failing test for this.

**Comment by tdreyno** [comment]
Can't reproduce. Can you post your `config.rb`

**Comment by tdreyno** [comment]
and `Gemfile.lock`

**Comment by ryanburnette** [comment]
Sure.

Here are my configs. https://gist.github.com/ryanburnette/94d7d287b6634864f9ba

For now I'm rendering the `stuff.js` file I mentioned outside the `./source/assets/javascripts` directory as a workaround.

**Comment by ryanburnette** [comment]
You'll notice that I gather up my assets inside helper methods, but I get the same results whether using a helper or not.

**Comment by tdreyno** [comment]
Okay, I've reproduced. It only happens when `asset_hash` is activated. I'll dig in.

**Comment by ryanburnette** [comment]
@tdreyno Middleman absolutely rules. Thanks for all your work.

**Comment by tdreyno** [comment]
Made a little change. Can you point your Gemfile at:

```
gem 'middleman', github: 'middleman/middleman', branch: 'v3-stable'
```

**Comment by ryanburnette** [comment]
Awesome. That patch seems to have fixed the issue. What's great about this is that I can now use ERB to generate some JavaScript, include it and have it minified into my global scripts.

**Comment by tdreyno** [comment]
:+1:
