### ISSUE TITLE
Source directories starting with tilde (~) cause Middleman exception

### ISSUE THREAD

**Issue by svicalifornia** [middleman/middleman#1591]
I moved some of my source assets to a folder named `~old`. The tilde separates the folder alphabetically from the other folders in the source assets.

When starting Middleman server, it bombs when trying to expand the `~old` paths. `File.expand_path` is interpreting `~old` as a home directory for a user named `old`:

**.../gems/middleman-core-3.4.0/lib/middleman-core/sitemap/store.rb:179:in `expand_path': user old doesn't exist (ArgumentError)**

Perhaps this could be fixed by escaping any tildes in the path before passing it to `File.expand_path`.

**Comment by svicalifornia** [comment]
The workaround is to use another prefix character, such as underscore. If you choose not to fix this issue, then please at least note it in the Middleman documentation.

**Comment by tdreyno** [comment]
This is a general issue of Ruby, and it is by design. `~ == $HOME`. Thanks for reporting. Hopefully this ticket will serve as documentation for others searching for an answer.
