### ISSUE TITLE
Known dependency issue between middleman 3.3.12 and listen 3.0.3 / 2.10.1 ? 

### ISSUE THREAD

**Issue by syksteaz** [middleman/middleman#1592]
Hello, 
Sorry if not a real issue, I couldn't find anything here or on stackoverflow. 
My config is : 
- middleman 3.3.12
- ruby 2.2.2 (64 bits)
- DevKit x64
- rubygems-update-2.4.8.gem installed on DevKit folder
- windows 8.1

When trying to launch ```middleman server``` I get the following error : 

```
PS C:\Users\edouard\desktop\stylus> middleman server
WARN: Unresolved specs during Gem::Specification.reset:
      activesupport (>= 3.1, ~> 4.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:34:in `block in setup': You have already ac
tivated listen 3.0.3, but your Gemfile requires listen 2.10.1. Prepending `bundle exec` to your command may solve this.
(Gem::LoadError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:19:in `setup'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/setup.rb:8:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/lib/middleman-core/load_paths.rb:29:in `setup_l
oad_paths'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/bin/middleman:10:in `<top (required)>'
        from C:/Ruby22-x64/bin/middleman:23:in `load'
        from C:/Ruby22-x64/bin/middleman:23:in `<main>'
```
Prepending 'bunle exec' to make it 'bundle exec middleman server' does not help.
The content of my gemfile is : 
```
# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem "middleman", "3.3.12"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw]

# Deploy to GitHub Pages
gem 'middleman-deploy', '~> 1.0'

# Assets
gem 'jquery-middleman'
gem 'bootstrap-sass', '~> 3.3.1'
gem 'font-awesome-sass', '~> 4.2.0'
```

When I run `bundle show listen` I get : 
```
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/listen-2.10.1
```
I uninstalled everything and reinstalled, deleted my gemfile.lock and ran 'bundle install' and 'bundle update' but it does not help neither.
Is it a known issue ? Many thx and again sorry if it's an incorrectly classified question. And sorry I'm not yet good enough to submit a pull request..soon !

**Comment by tdreyno** [comment]
Font awesome has a conflict with us on `listen`. They need to not including a CLI by default with their Sass files. Compass accomplished this a long time ago by splitting out `core` from `cli`.

You may see if simply changing that line to this helps:

```
gem 'font-awesome-sass', '~> 4.2.0', require: false
```

If not. I'd suggest simply copying the font awesome files into your project and not using the gem (with its dependencies).

This is a known issue, but not something we plan to fix on the MM side.

Going to close this, but please keep chatting here and I'll get your setup working.
