### ISSUE TITLE
Sitemap API usage for v4?

### ISSUE THREAD

**Issue by olliekav** [middleman/middleman#1595]
I'm just testing v4 but it's broken a lot of my sites that use the Sitemap API. How can I activate this again? Will it be an extension? e.g I do stuff like the following... 

```
<% pages = sitemap.resources.find_all{|p| p.source_file.match(/\.html/)}.sort_by {|p| p.data.order.to_i}.reverse! %>
```

**Comment by tdreyno** [comment]
What's broken?

**Comment by olliekav** [comment]
I get...
```
undefined method `match' for #<Middleman::SourceFile:0x007f8ed1b5a9e8>
```

**Comment by stevenosloan** [comment]
I think you should be able to add a call to `#full_path` or `#relative_path` on the [SourceFile](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/sources.rb#L7) and it'll work again.

```erb
<% pages = sitemap.resources.find_all{ |p| p.source_file.full_path.match(/\.html/) }.sort_by { |p| p.data.order.to_i }.reverse! %>
```

**Comment by tdreyno** [comment]
Ah, gotcha, that type is different now. It's a Struct of Pathnames, rather than a String. `match` doesn't exist on Pathname, I think.

```
<% pages = sitemap.resources.find_all{ |p| p.source_file[:full_path].to_s.match(/\.html/) }.sort_by { |p| p.data.order.to_i }.reverse! %>
```

Might be the ticket.

**Comment by olliekav** [comment]
@stevenosloan @tdreyno That works, thanks!
```

**Comment by tdreyno** [comment]
I'm actually going to reverse this API breakage. No reason to make your original code not work.
