### ISSUE TITLE
Can't load ActiveSupport

### ISSUE THREAD

**Issue by davidmles** [middleman/middleman#1597]
My blog uses ActiveSupport to use the "ordinalize" method with a Fixnum, but now I'm facing this error message:

> undefined method `ordinalize' for 31:Fixnum

So it's clear that Middleman is not loading ActiveSupport, but I can't find how to fix this issue.

The code that generates this error is:

```ruby
article.date.day.ordinalize
```

It's displaying the number 31, and then "ordinalizing" it.

I'm just requiring the gem in the Gemfile like this:

```ruby
gem 'activesupport'
```

I'm using Ruby 2.2.3 and ActiveSupport 4.2.4 (latest versions).

**Comment by tdreyno** [comment]
```
require "active_support/core_ext/integer/inflections"
```

**Comment by davidmles** [comment]
Hey @tdreyno, thanks for the tip. Where should I put that statement?

**Comment by tdreyno** [comment]
`config.rb`
