### ISSUE TITLE
Active navigation

### ISSUE THREAD

**Issue by Morred** [middleman/middleman#1598]
I've been looking for a way to create an active navigation in Middleman and ended up writing a small helper that checks the current_page.url against the link url and adds a class if they match so I can style that navigation link separately. 

Is there something in Middleman that would enable me to do this without the helper, and if not, is this something that could maybe be included?

**Comment by tdreyno** [comment]
This might help: https://github.com/michaek/middleman-navigation

Nothing is included, but a your approach sounds exactly like how I would solve the problem,
