### ISSUE TITLE
How to do linebreak with middleman and locale yaml ?

### ISSUE THREAD

**Issue by rubytastic** [middleman/middleman#1600]
Im trying to do a linebreak inside the middleman yaml.
Tried all documented Rails methods but they all fail
For example:
      title: " my title "
      title_sub:    |+ first line

                        second line 
                        third line

Could anyone please point out how to do linebreaks with middleman inside a locale yaml?

**Comment by tdreyno** [comment]
http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines
