### ISSUE TITLE
v4 DNS Resolution

### ISSUE THREAD

**Issue by tdreyno** [middleman/middleman#1602]
Ported most of the new stuff to v4, but having 2 items still failing (binding to `127.0.0.5`). Didn't we already fix this somehow?

cc @dg-ratiodata

**Comment by dg-ratiodata** [comment]
Sorry for the late reply. Will have a look. Was on vacation.

**Comment by dg-ratiodata** [comment]
I think this was a problem with Mac OS X and the used DNS library. It should use port 5353 or something but uses port 53 which needs root to bind on. I think, this an issue for v3 as well. Hoped, that you found a solution for this. I'm on linux, and that lib works well here. Not sure how I can track that down.

**Comment by tdreyno** [comment]
Oh yeah, shit, it was that bug

**Comment by dg-ratiodata** [comment]
Mmmh... How should we go on with this bug? Can I help in any way?

**Comment by tdreyno** [comment]
I've got no idea. We could just skip it on OS X, but it does seem super weird.

**Comment by dg-ratiodata** [comment]
Are you willing track that one down and open an issue at the dns-gems tracker?

**Comment by tdreyno** [comment]
Yeah, but I'm kinda cool just releasing v4 and getting all that stress out first.

**Comment by dg-ratiodata** [comment]
Any breaking changes or are you going to release some article about the new release? Would like to upgrade `middleman-presentation` as soon as possible then.

**Comment by tdreyno** [comment]
Please do and get back to me if any APIs broke, going to do RC 2 soon

**Comment by maxmeyer** [comment]
Ok. Will make a pre-release if RC2 is available. Is this the "last" planned RC? Any concrete date for 4.0.0?

**Comment by tdreyno** [comment]
Nope, whenever the RCs stop having bugs and regressions :)
