### ISSUE TITLE
Bug: Frontmatter documentation page seem to be corrupted

### ISSUE THREAD

**Issue by inem** [middleman/middleman#1603]
or at least incomplete:
![middleman__frontmatter](https://cloud.githubusercontent.com/assets/9665/9958553/7bb12814-5e0b-11e5-9e26-03dcadece3f0.jpg)

**Comment by Arcovion** [comment]
This is a bug in [Middleman::Util::Data::parse_yaml](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/util/data.rb#L77), it slices off the other frontmatter blocks instead of only paying attention to the first bit... probably just a bad regex.

**Comment by tdreyno** [comment]
I am so terrible at regex.

**Comment by tdreyno** [comment]
@Arcovion can you open a PR or directly commit that?

**Comment by tdreyno** [comment]
The test suite is a tad broken right now on master... working through some aruba issues.

**Comment by Arcovion** [comment]
Ok, should rewrite it though I think - will do so ASAP.
