### ISSUE TITLE
Jquery Plugin loading from js file

### ISSUE THREAD

**Issue by cdesch** [middleman/middleman#1605]
How can I load jquery plugins manually from something like a `script.js` which is included in the `all.js`

all.js

    //= require jquery
    //= require bootstrap-sprockets      
    //= require script

script.js

    var jPM = {};
    var PLUGINS_PATH = './plugins/';
    var SLIDER_REV_VERSION = '4.6';
    jQuery(document).ready(function() {
      "use strict";

  
      
      // ----------------------------------------------------------------
      // Plugin: jPanel Menu
      // data-toggle=jpanel-menu must be present on .navbar-btn
      // @todo - allow options to be passed via data- attr
      // @see: http://jpanelmenu.com/
      // ----------------------------------------------------------------
      if(jQuery('[data-toggle=jpanel-menu]').length > 0) {
        var initjPMenu = function() {
          var jpanelMenuTrigger = jQuery('[data-toggle=jpanel-menu]');
      
          jPM = jQuery.jPanelMenu({
            menu: jpanelMenuTrigger.data('target'),
            direction: jpanelMenuTrigger.data('direction'),
            trigger: '.'+ jpanelMenuTrigger.attr('class'),
            excludedPanelContent: '.jpanel-menu-exclude',
            openPosition: '280px',
            afterOpen: function() {
              jpanelMenuTrigger.addClass('open');
              jQuery('html').addClass('jpanel-menu-open');
            },
            afterClose: function() {
              jpanelMenuTrigger.removeClass('open');
              jQuery('html').removeClass('jpanel-menu-open');
            }
          });
        
          //jRespond settings
          var jRes = jRespond([
            {
              label: 'small',
              enter: 0,
              exit: 991
            }
          ]);
          
          //turn jPanel Menu on/off as needed
          jRes.addFunc({
              breakpoint: 'small',
              enter: function() {
                jPM.on();
                jQuery('html').themeSubMenus();
              },
              exit: function() {
                jPM.off();
                jQuery('html').themeSubMenus();
              }
          });
        };
        jQuery().themeLoadPlugin(["jPanelMenu/jquery.jpanelmenu.min.js", "jRespond/js/jRespond.js"], [], initjPMenu);
      }
 
Where the `jPanelMenu` is loaded through the `script.js`?

**Comment by tdreyno** [comment]
What's the error with the above approach?

**Comment by cdesch** [comment]
It doesn't load the plugin at all. I don't think sprockets is suppose to work like this.

**Comment by tdreyno** [comment]
Sorry, still not understanding your issue. Are you saying the contents of `script` are not in `all.js`?

**Comment by olliekav** [comment]
I'm assuming this is the same issue I've just encountered upgrading to RC2. Sprockets require statement is not pulling in JS files. I'll dig into it more.

**Comment by olliekav** [comment]
Just looked into this further, is sprockets not include by default in v4 now? If I add
```
gem 'middleman-sprockets', github: 'middleman/middleman-sprockets', branch: 'master'
```
It starts working again.

**Comment by tdreyno** [comment]
Ah, yeah, we moved the default dependencies from the `gemspec` to the `Gemfile`. New projects are still generated with Sprockets, but if you're upgrading a project with a straight `gem "middleman"` dependency, Sprockets will be missing.

I definitely need to document that, atleast. Or, maybe even provide a `middleman upgrade` command to provide better guidance.

**Comment by olliekav** [comment]
Yeah I realised that after poking around a little bit. I've been testing upgrading all my projects to RC2.

**Comment by san** [comment]
I know this issue is closed, but I just installed middleman and all.js file is not loading any files that I am trying to load using `//= require file_name` statement.

**Comment by stevenosloan** [comment]
@san what version of Middleman & Middleman::Sprockets? If on Middleman::Sprockets 4.0.0.rc.2, do you have `activate :sprockets` in your config.rb?

**Comment by san** [comment]
@stevenosloan here is what I have:
  
    middleman 4.1.7
    middleman-sprockets 3.4.2

I do not have `activate :sprockets` line in config.rb. Also, I do not have `gem `middleman-sprockets'` explicitly in my `Gemfile`. Do I need it? I tried both with and without it, and it didn't work in either case.

Thanks.

**Comment by stevenosloan** [comment]
Hmm, yeah I'm really not sure about how mm-sprockets 3.x & mm 4.x play together. I've been working on mm-sprockets so that it's *mostly* ready for production use. So to use that:

```ruby
# Gemfile
gem 'middleman', '~> 4.1.7'
gem 'middleman-sprockets', '~> 4.0.x' # the .x will allow rc versions

# config.rb
activate :sprockets
```

If you're still having trouble, your project structure would be helpful. Thanks

**Comment by san** [comment]
@stevenosloan that did the trick. It's working now.

Thank you.
