### ISSUE TITLE
File not picked by "middleman build", but works in "middleman server"

### ISSUE THREAD

**Issue by wkoszek** [middleman/middleman#1606]
My website is in `middleman`. To reproduce:

```
mkdir -p /tmp/debug
cd /tmp/debug
git clone https://github.com/wkoszek/me.git
cd me
bundle install
middleman build --verbose --clean
```

I have it also building on CircleCi;

https://circleci.com/gh/wkoszek/me/70

Problematic file:

https://github.com/wkoszek/me/blob/master/source/blog/2015-09-23-why-its-not-about-self-driving.md

It fails to be incorporated in `build` on both my Mac and on CircleCI.
### Details with LiveReload

On my Mac I run `middleman server` and file is there. When accessed as `http://wkoszek-macbook.local:4567/blog/2015/09/23/why-its-not-about-self-driving/` it works flawlessly. When I update the file, I see:

```
== Inspect your site configuration at http://wkoszek-macbook.local:4567/__middleman
Changed! source/blog/2015-09-23-why-its-not-about-self-driving.md
== LiveReloading path: blog/2015/09/23/why-its-not-about-self-driving/index.html
```

So LiveReload works fine.
### Details with `middleman build`

When built with `middleman build --verbose --clean` the file isn't rebuilt. The `2015/09/23` directory is not there. I'd expect the file to be "picked up" and regenerated to HTML.

Experiments I performed:
1. copy `2015-09-23-why-its-not-about-self-driving.md` to other existing file. It works. By doing this, I proved my front-matter isn't a problem. (that's the typical hiccup I have with `middleman`)
2. add different file to my directory. LiveReload works without problems and sees new file. But `middleman build` it doesn't work: it once again doesn't see this file.
3. when copied to a file with different date, it doesn't work either. Seems the same to [2].

Before I dig deeper I'd like 2nd set of eyes to take a look at it.

**Comment by tdreyno** [comment]
Future-dated articles are not included in build by default. (https://middlemanapp.com/basics/blogging/#draft-articles) Try:

```
activate :blog do |b|
  b.publish_future_dated = true
end
```

**Comment by wkoszek** [comment]
Thomas,

Thanks. Can we throw a warning/notification about that? If the file is skipped, I'd expect that Middleman would let me know why it skips this file and why.

W.

**Comment by wkoszek** [comment]
Just wondering: why is the `publish_future_dated` off by default? It makes sense for dynamic engine (e.g.: batching articles for 1 week upfront), but for a static generator, the default behavior I'd expect is that it'd pick up articles dated in the future too.

**Comment by tdreyno** [comment]
No idea how it came to be, but it's been the default for years. We could reverse it for v4, since that signifies some breaking changes. It does seem to confuse a lot of people.

**Comment by wkoszek** [comment]
I certainly was confused. Typically it takes me 1-2 days to write and review a piece, and while doing so, I want to have my file in place, checked-in to Github. In other words: it quite likely I'll name a file with a future date. Either we change it, or just add a printout.

Anyway, thanks for help. I appreciate it.

**Comment by cbetta** [comment]
It seems to me more that adding dates in filenames just is a bit inflexible.

**Comment by tdreyno** [comment]
@cbetta They are optional, you could store dates in front matter too.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I think things are working as intended, and that this issue can be closed.

Feel free to disagree and if so a PR with a failing test plus a fix would be a great start.
