### ISSUE TITLE
`set :debug_assets, true` seems to have no effect in v4

### ISSUE THREAD

**Issue by gkop** [middleman/middleman#1607]
Tried both 4.0.0.rc.1 and master.

Created a new middleman app with 4.0.0.rc.1.

Instead of generating multiple \<script> tags, I did not observe any difference when setting debug assets to true.

Editing the Gemfile to point back to middleman 3.4.0 fixed this issue for me.

**Comment by tdreyno** [comment]
This is true. I had removed that feature in favor of sourcemaps... but then discovered Sprockets sourcemap support is still in beta :(

Not sure what to do now, either stall until Sprockets 4 or add this feature back in. I'll leave this ticket open until we've got a plan

**Comment by bhollis** [comment]
Missing `:debug_assets` is going to make it tough for me to use v4.

**Comment by tdreyno** [comment]
@bhollis Well, since I don't plan on releasing Sprockets for v4, thats going to be a bigger problem. I'll start the media push in January to find a sprockets maintainer.

That said... Since Rails 5 is shipping, maybe Sprockets fixed their sourcemaps?

**Comment by bhollis** [comment]
Hmm, I'm watching the relevant issues and haven't seen any activity. But
maybe they just didn't update those issues.
