### ISSUE TITLE
Encoding issue after build

### ISSUE THREAD

**Issue by zenati** [middleman/middleman#1609]
Hello. When i run the server I get this in index view:

`LA NOUVELLE FAÇON - Développez votre patrimoine.`

When I do `middleman build`, I get this in the HTML:

`LA NOUVELLE FAÃ‡ON - DÃ©veloppez votre patrimoine.`

I added: `set :encoding, "utf-8"` but it does not work. Any idea? Thank you.

**Comment by tdreyno** [comment]
Which version of MM and what OS?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.
