### ISSUE TITLE
Custom renderer not receiving current_page

### ISSUE THREAD

**Issue by spiffytech** [middleman/middleman#1612]
I'm using a custom renderer that handles Mustache templates, but it's not receiving the per-page data (`current_page`). It's only receiving the `data` hashes (which you cant see I'm passing it in the `locals` hash key).

I cannot figure out how to pass the `current_page` data to my Mustache template, and cannot find any documentation on this. How can I do it?

```
# Require Gem
require 'tilt-mustache'

module Middleman
  module Renderers
    # Liquid Renderer
    module MiddlemanMustache
      # Setup extension
      class << self
        # Once registerd
        def registered(app)
          require 'mustache'

          app.before_configuration do
            template_extensions mustache: :html
          end

          # After config, setup liquid partial paths
          app.after_configuration do
            Mustache.template_path = source_dir

            # Convert data object into a hash for mustache
            sitemap.provides_metadata %r{\.mustache$} do
              { locals: { data: data.to_h } }
            end
          end
        end

        alias_method :included, :registered
      end
    end
  end
end
::Middleman::Extensions.register(:mustache, Middleman::Renderers::MiddlemanMustache)
```

**Comment by spiffytech** [comment]
It appears the `current_page` data is showing up under `data.page`, but only *sometimes*. 

When shown from `middleman build`, the data is never present.

When run from `middleman server`, there is some sort of caching going on. This is what my workflow looks like (what a particular variable value is set to for a given page, and what shows up on the page. This applies to the entire page data structure - it's stale until a refresh. This happens with cURL too, so it's not my browser cache).

```
+-------------+     
|   (=true)   |     
|             |     
|    true     |     
+-----+-------+     
      |             
      | Page change 
      |             
+-----v-------+     
|  (=false)   |     
|             |     
|    true     |     
+-----+-------+     
      |             
      | Refresh page
      |             
+-----v-------+     
|  (=false)   |     
|             |     
|    false    |     
+-----+-------+     
      |             
      | Page change 
      |             
+-----v-------+     
|   (=true)   |     
|             |     
|    false    |     
+-----+-------+     
      |             
      | Refresh page
      |             
+-----v-------+     
|   (=true)   |     
|             |     
|    true     |     
+-------------+     
```

**Comment by tdreyno** [comment]
In v3, `current_page` is a global value (which is attempting to lock itself for concurrent requests) that should be available on the `app`. I believe Mustache prefers to have concrete data (not instances) and avoid if statement, so I'm not sure how you'd get that information into the template.

I assume your mustache support is coming from a Tilt plugin? You might be able to pass in either the `app` or `app.current_page` during the `render`.

In v4, `current_page` is passed as a "local" to all Tilt templates.

**Comment by spiffytech** [comment]
Yes, Mustache support is coming from a tilt plugin.

`app.current_page` is not available to my renderer. Neither in `app.method.sort` inside the `sitemap.provides_metadata` `do` loop in the above code sample, nor inside my template if I pass `app` in anyway.

**Comment by tdreyno** [comment]
is `app.current_path` available?

**Comment by spiffytech** [comment]
No, it's not - throws `method_missing`.

FYI, here's what looks to be all the methods attached to `app` at that point (`puts (app.methods.sort - Object.methods.sort)`):

```
_hooks
_hooks=
after_build
after_configuration
after_render
before
before_build
before_configuration
before_render
build_config
cache
call
callbacks_for_hook
compass_config
config
configure
define_hook
define_hook_writer
define_hooks
development_config
helpers
inheritable_attr
initialized
inst
inst=
instance_available
map
method_missing
prototype
ready
register
reset!
root
root_path
run_hook
run_hook_for
server
set
to_rack_app
use
```

**Comment by tdreyno** [comment]
Ah. That looks like the app class, not instance. In v3 (sorry, rounding out a very long refactor), `app` isn't an instance (with methods) until the `after_configuration` callback. In v4, it is always an instance.

Can you see if you can get the correct reference in:

```
app.after_configuration do |real_app|
  puts real_app.methods
end
```

**Comment by tdreyno** [comment]
You know, what might be a good idea is if you could write a test/feature to fail for mustache, then I could investigate the magical series of commands to make it work :)

**Comment by spiffytech** [comment]
Done! Submitted pull request #1617, which adds Mustache as a core renderer and adds a failing unit test that will pass when the current page data is passed in under the `current_page` locals key.

I took my best guess at the right semantics to use for everything, please let me know if anything needs changing.

**Comment by spiffytech** [comment]
I'll also note that I haven't figured out how to make helpers work from Mustache templates, either. I don't know if that comes along for free with fixing `current_page`, but I'd appreciate if you could take a look at it too.

**Comment by tdreyno** [comment]
@spiffytech Again, and I haven't used Mustache in years, I thought not allowing external code (like MM helpers) was part of the Mustache philosophy?

Thanks for the PR, I'll check it out.

**Comment by spiffytech** [comment]
Yes, Mustache does have some limited support for accessing helper functions. See the "Lambdas" section in [their documentation](https://mustache.github.io/mustache.5.html).

**Comment by spiffytech** [comment]
*bump*

Have you had a chance to work out how to pass per-page variables to the Mustache renderer?

(The lambdas are great to have working, but aren't an active problem up my project at the moment).

**Comment by tdreyno** [comment]
Sorry, not yet. Don't use Mustache personally, so it's at the bottom end of the stack beneath getting v4 out ASAP

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! This should work in v4. If not a a PR with a failing test would be a great start.
