### ISSUE TITLE
Access JS variable on template

### ISSUE THREAD

**Issue by Gabiras12** [middleman/middleman#1615]
Hello, I'm trying to create an A/B testing feature for my website. I'm setting the version I want the user to see to a variable on a JS file where I store/retrieve the user's cookie.

I'm able to access the variable on any JS file, but I can't use the value on the template to choose what partial to render.

**Comment by tdreyno** [comment]
@Gabiras12 Can you share some code or give some samples of how you're trying to accomplish this?

**Comment by Gabiras12** [comment]
@tdreyno Sure! Here's how i'm trying do accomplish this:
1) On application launch i run the following JS code: 

 ```coffeescript
class @CookieManager
  constructor: () ->
    @setIndexPage()

  setIndexPage: () =>
    # check if cookie already defined
    if Cookies.get('index') is undefined
      Cookies.set('index', @generateRandomIndex())

  generateRandomIndex: () =>
    randomNumber = Math.floor(Math.random() * 2)
    if randomNumber is 1
      return 'default_index'
    else
      return 'new_index'

  getIndexPage: () =>
    Cookies.get('index')
```
Now i'm able to retrieve the page that the user should see like this:

 ```coffeescript
cookieManager = new CookieManager()
ab_index = @cookieManager.getIndexPage()
```

The problem that i'm facing is how to use the `ab_index` var to render the right template.

```slim
- if ab_index == "default_index"
  = partial 'shared/default_index'
- else
  = partial 'shared/new_index'
```

I know that the render process is server running and the CookieManager run on client side. I tried to send the the `ab_index` var via AJAX but with no success - I don't know where to send. 

I hope that explains how i'm trying to do this. If you've a new solution to this, please share with us. 

Thank you.

**Comment by tdreyno** [comment]
Ah, so it sounds like you're selecting a file client side. You should make 2 pages (maybe without layouts) for default_index and new_index. something like:

`source/partial_pages/default_index.html.erb`

Where that file is prefixed with:

```
---
layout: false
---
```

Now, in your client side code, simply AJAX the `/partial_pages/default_index.html` (or new_index, depending on your ab test variable) and insert the resulting HTML somewhere in your page. 

Make sense?

**Comment by Gabiras12** [comment]
This totally make sense! It's working now! Thanks @tdreyno.
