### ISSUE TITLE
Can't install Middleman on OS X El Capitan (10.11)

### ISSUE THREAD

**Issue by beaulidden** [middleman/middleman#1618]
Hello. I just inherited a new iMac and need to install Middleman to continue dev work. I followed all the usual instructions but sadly I'm running into this error every time I run _**sudo gem install middleman**_

```
ERROR:  While executing gem ... (Errno::EPERM)
Operation not permitted - /usr/bin/kramdown
```

Does anyone know how I can fix this? Thanks :)

**Comment by beaulidden** [comment]
P.S. Xcode has been downloaded as well, so from my knowledge all the dependencies are accounted for?

**Comment by iwarner** [comment]
Did you install the command line tools

    xcode-select --install

Run this in terminal to check

**Comment by beaulidden** [comment]
Hi iwarner. Yep, checked and it appeared I hadn't installed it yet. I proceeded with the install, restarted my machine, did a:

```
gem update --system
```

To be sure, but still seeing the same error :-1:

**Comment by tdreyno** [comment]
I would suggest waiting until the ecosystem stabilizes. This is going to be rough for any homebrew-based libraries. They usually don't bother fixing bugs until the OS is released, which makes the first couple weeks awful.

**Comment by HParker** [comment]
Works fine for me on el cap, did you follow the homebrew [instructions](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md) on upgrading to 10.11?

**Comment by beaulidden** [comment]
Thanks guys. Not sure why this is happening. My MacBook Pro is running Middleman fine, but it was installed prior to the El Capitan update. I purchased my iMac the other day and immediately upgraded to El Capitan before install anything else (Middleman et al)

HParker - I wasn't aware of this. I ran the first comment the article suggested:

```
sudo chown -R $(whoami):admin /usr/local
```

And it seemed (?) to be fine...no warnings came up. Regardless, when I tried running **sudo gem install middleman** I see the same error :(

**Comment by HParker** [comment]
@beaulidden ah, I assumed you were using brew and/or rvm you manage packages and gems.
I should have noticed where middleman was looking for kramdown.
I would check the perms on `/usr/bin` and run a similar command to the one you ran on `usr/local` on `/usr/bin`, but you might need to own it for `root`. I am assuming that is safe. I don't know the default perms on `usr/bin`

Any particular reason you are using system ruby?

**Comment by beaulidden** [comment]
@HParker no particular reason, it was just the way I was introduced to Middleman and how I've since used it :) sure, so you're suggesting I run

```
sudo chown -R $(whoami):admin /usr/bin
```

Correct?

**Comment by beaulidden** [comment]
@HParker yep running ^ that comment resulted in a ton of 'Operation not permitted' errors. Any clues?

**Comment by HParker** [comment]
hmm, yeah I am out of ideas. Sorry Beaulidden.

**Comment by beaulidden** [comment]
All good, thanks for your help so far @HParker :)

Any other ideas @tdreyno or @iwarner?

**Comment by tdreyno** [comment]
I would suggest removing home-brew and rum via their commands for doing so and re-installing.

**Comment by beaulidden** [comment]
Thanks for the suggestion @tdreyno I did exactly that, then re-installed Homebrew, then attempted a Middleman install. Still no luck. Surely there's a way this works on El Capitan? Is there a way I can just blow away everything and start again without having to reformat the entire machine?

**Comment by tdreyno** [comment]
If you use RVM, you won't need to `sudo`

**Comment by beaulidden** [comment]
You'll have to forgive me @tdreyno but is rvm associated with Homebrew? If so, how would I trigger it? I've **always** used the regular instructions on the Middleman website (which uses normal expressions such as _gem install middleman_)...what's happened to go an alternative route all of a sudden?

**Comment by glennc** [comment]
I think the problem you are having is that you are using the system installed Ruby (ruby that comes with the Mac). Which is setup to require permissions to modify since doing so could possibly cause some unintended side effect with built in programs using the built-in version of Ruby (pure speculation I have no idea if that is the reason why it is restricted).

However, if you go and use RVM or something like that to grab and install your own copy of Ruby and manage it separately to the system Ruby install then you will not need the extra permissions and you should be good to go. In my case I used rbenv and a plugin of rbenv that will install Ruby for me.

That is my vague understanding of what I did to make this work on my own El Capitan machine anyway. My assumption on why this works on your other machine is that you probably done this step (installing a different version of Ruby to the system one) at some time in the past and forgot.

**Comment by tdreyno** [comment]
@beaulidden as I said above, the ecosystem gets weird around every new OS release. I believe everything will normalize and those default instructions will work on El Capitan, it might just take a couple weeks. For now, it sounds like RVM (as an alternative to the system Ruby) is currently a good workaround.

**Comment by beaulidden** [comment]
Okay sounds good @glennc and @tdreyno - I really appreciate your help. For now I'll have a crack using NVM otherwise I'll wait a few weeks once El Capitan has settled and attempt again. Thanks again for all your assistance guys :+1: :smile:

**Comment by iwarner** [comment]
Hiya - RVM or RBENV is a good shout, I prefer RBENV, just a little simpler I think to get going, have included my setup script.

    brew update
    brew install rbenv rbenv-gem-rehash ruby-build
    echo 'eval "$(rbenv init - --no-rehash)"' >> ~/.bash_profile
    eval "$(rbenv init - --no-rehash)"

    CONFIGURE_OPTS="--disable-install-doc --with-readline-dir=$(brew --prefix readline)" rbenv install 2.1.3

    rbenv global 2.1.3
    rbenv rehash

http://jonathan-jackson.net/rvm-and-rbenv

**Comment by tzungtzu** [comment]
1.Boot into the Recovery HD by restarting whilst holding ⌘R.
2.Open Terminal (from the Utilities menu).
3.Run the following command in Terminal:
csrutil disable
4.Restart.
