### ISSUE TITLE
Add hook to preview server

### ISSUE THREAD

**Issue by maxmeyer** [middleman/middleman#1624]
@tdreyno What do you think. Does it makes sense to add some kind of before(:server)-hook to the preview server? We/I/One could then build a middleman extension which makes things like the `launchy`-thing at the end of this [article](https://www.fedux.org/articles/2015/10/05/give-the-middleman-a-start-script.html) possible. It would get the URL to the server passed in.

**Comment by tdreyno** [comment]
Sounds like a great idea

**Comment by dlitvakb** [comment]
:+1:  This would be an awesome idea.

I'm the active maintainer of https://github.com/contentful-labs/contentful_middleman and would love to have a server hook.

Currently I'm hooking onto `after_configuration` but this runs on any middleman command.

What I'm trying to accomplish is having a secondary thread running a WEBrick server to receive webhook calls from the Contentful API and rebuild the middleman site upon receiving a call.

The process currently works, but when calling `bundle exec middleman contentful --rebuild` more and more webhook server processes try to spawn (though they die quickly enough).

**Comment by maxmeyer** [comment]
Added PR with #1678

**Comment by tdreyno** [comment]
@dlitvakb Hey, I'm using a combination of Middleman and Contentful for most projects at work and we're looking at forking or creating out own extension to fit our needs better. If you're interested, email me at me@tdreyno.com and maybe we can chat about the kind of features we need and whether those would be good in the core gem.
