### ISSUE TITLE
Configure I18n in cofig.rb

### ISSUE THREAD

**Issue by iwarner** [middleman/middleman#1628]
Hiya

I want to use the load.path of I18n to pull in locales files from re-usable submodules.

I have seen something like the below - but does not seem to work correctly.

    # I18n
    # @see http://www.rubydoc.info/github/svenfuchs/i18n/I18n
    Time.zone                      = "Europe/London"
    I18n.load_path                 = Dir[Middleman::Application.root_path.join('locales', '**', '*.{yml}')]
    activate :i18n, langs: [ :en ], mount_at_root: :en

Any help appreciated.

**Comment by nysthee** [comment]
What is not working exactly?

**Comment by iwarner** [comment]
Hiya,

Under domain.com/__middleman
The load.path configuration is not showing up at all, and not pulling in my other locale .yml files.

Thanks

**Comment by tdreyno** [comment]
`i18n` will automatically setup the load paths, don't override it.

`langs` is hard coding the list to only `en`, you should remove that to be able to use multiple langs

**Comment by iwarner** [comment]
@tdreyno Hiya - yeah I have i18n all setup - its just I want module specific language files so if I reuse a module I do not have to make sure that the language elements are copied over to the project specific language files

I think I saw this as a wishlist from another dev also in the v4 locales - will search that out

nb/ at the moment I only have english in this project.

hope that makes sense.

**Comment by tdreyno** [comment]
Sorry, can you try to explain " I want module specific language files so if I reuse a module I do not have to make sure that the language elements are copied over to the project specific language files". Not following.
