### ISSUE TITLE
step_definitions seems to be broken in v3.4.0

### ISSUE THREAD

**Issue by jagthedrummer** [middleman/middleman#1635]
When I run my test suite with version `3.3.13` of `middleman-core` everything is working fine. When I upgrade to `3.4.0` all of my cucumber features fail with this error:

```
undefined local variable or method `current_directory' for #<Object:0x007fdc352c28d8> (NameError)
      features/alias.feature:3:in `Given the Server is running at "alias-app"'
```

I'm guessing it's related to this commit where `current_dir` is replaced with `current_directory` throughout all of the step definition files. https://github.com/middleman/middleman/commit/68a6eacc333b283bf90df1519a4b55660fa82de3

My original cucumber version was `1.3.10` and the problem remains after I upgrade to `2.1.0`.

**Comment by tdreyno** [comment]
I believe you need these 3 very specific gems and version ranges:

https://github.com/middleman/middleman-sprockets/blob/master/Gemfile#L16-L18

**Comment by jagthedrummer** [comment]
`'aruba', '~> 0.7.4'` seemed to do the trick. Thanks!

**Comment by tdreyno** [comment]
@jagthedrummer We've got tickets open upstream, so this should get easier soon
