### ISSUE TITLE
jQuery 1.11.3 and Middleman v4 build error (Cannot assemble URI string)

### ISSUE THREAD

**Issue by danielmag** [middleman/middleman#1638]
Using Middleman v4 with jQuery 1.11.3 and **both** `minify_javascript` and `asset_hash` activated gives the following error when building:
`Cannot assemble URI string with ambiguous path: ':ne.css'`

Tested with the default Middleman 4 template, with rc1 and master.

**Comment by tdreyno** [comment]
Thanks for filing, we'll check it out. What platform are you on and Ruby version?

**Comment by danielmag** [comment]
osx yosemite and ruby 2.2.0

**Comment by alekseyg** [comment]
I'm having the same issue. My environment:

OS X El Capitan
Ruby 2.1.5
Middleman 4.0.0.rc.1 and 4.0.0.rc.2
jQuery 1.11.3

I'll also attach my Gemfile.lock in case it might be helpful.
[Gemfile.lock.zip](https://github.com/middleman/middleman/files/59005/Gemfile.lock.zip)

**Comment by alekseyg** [comment]
BTW, perhaps this issue belongs in the middleman-sprockets project?

**Comment by tdreyno** [comment]
Are you using the raw JS file or loading it from something like ruby gems or bower/npm

**Comment by alekseyg** [comment]
I've tried the raw JS and the jQuery-rails gem. The JS file is identical either way and I get the same error either way.

**Comment by tdreyno** [comment]
Great, thanks, I think this is a bug in asset_hash, will investigate. If you've got a repo already I could use to test, that'd be amazing.

**Comment by alekseyg** [comment]
The website I'm working on now is a private repo, but I extracted the necessary parts to reproduce the issue here: https://github.com/alekseyg/middleman-break-jquery

**Comment by tdreyno** [comment]
You're the best. I'll take a look over the weekend. This is definitely a blocker for v4 final
