### ISSUE TITLE
Segmentation fault when running middleman build

### ISSUE THREAD

**Issue by kimh** [middleman/middleman#1639]
Hi team,

I'm facing segmentation fault when running `bundle exec middleman build` very stably. I only see the segmentation fault when I run this on CircleCI, and not locally. [Here](https://circleci.com/gh/kimh/locationkit-android-docs/10) is an example of failed build.

```
...
      create  build/javadoc/socialradar/locationkit/package-frame.html
      create  build/javadoc/socialradar/locationkit/package-summary.html
      create  build/javadoc/socialradar/locationkit/package-tree.html
/home/ubuntu/locationkit-android-docs/vendor/bundle/ruby/2.2.0/bin/middleman: [BUG] Segmentation fault at 0x00000000000000
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0001 p:0000 s:0002 E:000a40 TOP    [FINISH]


-- Machine register context ------------------------------------------------
 RIP: 0x00007f89b8eb9845 RBP: 0x00000000000000a0 RSP: 0x00007fffe6e7ade0
 RAX: 0x2d6568742d746567 RBX: 0x00000000061af510 RCX: 0x0000000000011a68
 RDX: 0x2d746e6572727563 RDI: 0x00007f89b91f9760 RSI: 0x0000000000000000
  R8: 0x8000000420000000  R9: 0x00007f89b91f97b8 R10: 0x00007f89b91f9798
 R11: 0x00007f89b91f97b0 R12: 0x00000000061af590 R13: 0x0000000000000020
 R14: 0x0000000001a62200 R15: 0x00007f89b91f9760 EFL: 0x0000000000010206
```

I'm using middleman 3.3.12 and ruby 2.2.3 but I got the same seg fault with any version of ruby 2.x.

Any help is appreciated.

Thanks,
Kim

**Comment by tdreyno** [comment]
Hmm, can you try MM `3.4.0`? I've got a bunch of `3.4.0` and `4.0.0.rc.1` apps running on Circle without issue.

**Comment by kimh** [comment]
I tried 3.4.0 and getting different error.

```
*** Error in `ruby': double free or corruption (!prev): 0x0000000003b2cf30 *** Action failed: bundle exec middleman build
```

Here is [build](https://circleci.com/gh/kimh/locationkit-android-docs/14).

Actually, I've gotten the double free error as well as the seg fault with 3.3.12 and the double free error is easier to get than the seg fault.

I've tried 4.0.0.rc.1 but I got some totally different errors, but I think that's because contents are not written for 4.0.0, so not sure if 4.0.0 will fix the issue.

**Comment by tdreyno** [comment]
Wow, I really doubt this is MM related. How is ruby being installed on the CI box? Looks like something you see when a compile has gone bad

**Comment by kimh** [comment]
We just use RVM, so I'm not sure if that makes difference. I will try install ruby with some different way and see if that works.

**Comment by tdreyno** [comment]
Does CircleCI not provide a way of configuring this? Are you compiling a ruby version in each build context?

**Comment by kimh** [comment]
Well, CircleCI pre-installed different version of ruby via RVM and users will chose which version to which in build. Does this answer your question?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest closing this issue. If the problem resurfaces a repro or failing test would be a good start in solving this. Ideally also a patch with a fix.

**Comment by kimh** [comment]
As per @sandstrom's comment, I'll close this issue since I'm not working on this and don't know if I can still reproduce the issue.
