### ISSUE TITLE
v4.0.0.rc.1: with gzip and overwrite options, building without changes causes files to be updated

### ISSUE THREAD

**Issue by monfresh** [middleman/middleman#1641]
If nothing has changed, I would expect the gzipped files to be considered identical so that they don't get uploaded to S3 (for example). Thoughts?

**Comment by tdreyno** [comment]
Not sure gzip is idempotent, maybe someone can enlighten me. But it a lot of compression algorithms, the actual output isn't predictable.

**Comment by sandstrom** [comment]
Gzip isn't idempotent by default (since a timestamp is included), but there is usually an option to skip them. On Unix `gzip -n` should produce idempotent output.

http://unix.stackexchange.com/questions/31008/why-does-the-gzip-version-of-files-produce-a-different-md5-checksum

**Comment by tdreyno** [comment]
Hmm, doesn't look like the Ruby library for gzipping supports that flag :(

I'm going to close this, but I would suggest a post-build task to gzip using the command line tool mentioned above with the `-n` flag to avoid this issue in your particular situation.
