### ISSUE TITLE
Unable to set sass precision in 3.4

### ISSUE THREAD

**Issue by craigmdennis** [middleman/middleman#1642]
When using `set :sass, precision: 7` the sitemap configuration page reflects the change but the rounding is actually still set to the default of 5.

The only way to actually update it is with the following:
`::Sass::Script::Number.precision = [7, ::Sass::Script::Number.precision].max`

I'm not sure if this is a bug or not.

**Comment by tdreyno** [comment]
`precision` is not an exposed value on the Sass options object, which is why we can't set it via `set`.

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#options
