### ISSUE TITLE
Localizing the layout does not work

### ISSUE THREAD

**Issue by eaigner** [middleman/middleman#1643]
I tried putting the layout file into multiple localizable paths, neither of them seems to work
- `/source/localizable/layouts/layout.erb`
- `/source/layouts/localizable/layout.erb`

middleman doesn't find the layout in both cases

**Comment by joallard** [comment]
What about just not putting it in a `localizable` folder?

**Comment by tdreyno** [comment]
yeah, pretty sure this doesn't work. Work around might be something like a default `layout.erb` with the contents:

```
<% wrap_layout(I18n.locale) do %>
  <%= yield %>
<% end %>
```

Where you have a layout for each locale, something like `en.erb`

**Comment by eaigner** [comment]
@tdreyno I solved it by moving the localizable parts to partials.

**Comment by johnnyshields** [comment]
@eaigner You can call I18n functions inside your layout, even though it is not in the localizable folder.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I think things are working as intended, and that this issue can be closed. Feel free to disagree and if so a PR with a failing test plus a fix would be a great start.
