### ISSUE TITLE
It would be nice if Middleman could run as a daemon background process

### ISSUE THREAD

**Issue by NathanBowers** [middleman/middleman#1645]
For example, Webrick has the **-d** option and Rack has **--daemonize**.

That way I could leave Middleman running on a dev server or my local Mac without having to keep a terminal open.

Note that **$ middleman &** works, as in it keeps the process alive after closing terminal, but the web server is unresponsive.

**Comment by maxmeyer** [comment]
What about running it with `screen`? Or write a `unit-file` if you're using `systemd` (dev server)? Did you tried that?

**Comment by maxmeyer** [comment]
Maybe you need to install `screen` first. Alternatively use `tmux` what I prefer over `screen`.

**Comment by johnnyshields** [comment]
This should be fixed now with https://github.com/middleman/middleman/pull/1683

**Comment by NathanBowers** [comment]
Works! Awesome! :sparkling_heart:

**Comment by allthesignals** [comment]
This is great! But I think it breaks livereload when overriding the host. 

```
configure :development do
  activate :livereload, host: "0.0.0.0"
end
```

`middleman serve --bind-address 0.0.0.0 -d`

**Comment by logemann** [comment]
Can it be that when putting it in background via "-d" middleman no longer sees any file changes?
