### ISSUE TITLE
sassc-ruby not yet compatible with Windows

### ISSUE THREAD

**Issue by johnnyshields** [middleman/middleman#1648]
Three points about SassC which was added to master:

1. Although SassC itself can be built on Windows, the SassC-Ruby gem does not yet come bundled with a binary for Windows and hence doesn't work on Windows yet. See this issue:  https://github.com/sass/sassc-ruby/issues/18

2. When starting latest middleman v4 master branch I get the following error. This adds quite a bit of "wat" into the setup process, its not obvious that one needs to add `sassc` to the Gemfile.

   ```
   C:/ruby21/lib/ruby/gems/2.1.0/bundler/gems/middleman-3cd84eb4d182/middleman-core/lib/middleman-core/renderers/sass_functions.rb:108:in `<top (required)>': uninitialized constant SassC::Script (NameError)
   ```

3. I'm eagerly awaiting a full release of Middleman 4, it's the best static site generator out there. That being said, I am questioning why the authors of Middleman 4 are switching the Sass library (a core dependency) when the version is "Release Candidate 1" stage. It would seem to me this sort of change can wait until 4.1, or otherwise be done in a way that adds backwards-compatibility with the existing Ruby Sass library. I politely urge the authors of this gem to focus on issues which are blockers for the v4 release!

**Comment by johnnyshields** [comment]
@tdreyno this should be a blocker for RC2 release.

**Comment by tdreyno** [comment]
:disappointed: Oh, Ruby-Sass, what a let down.

2. Is definitely a bug, I'll look at it.

3. A good argument. I just spent a lot of time dealing with Ruby Sass' slowness on a project and this was the solve. SassC is supposed to be a drop-in replacement for Ruby Sass, so the impact is minimal, but if there is no Windows version, well that changes things. It's easy to revert, or to swap the precedence so SassC is opt-in.

**Comment by johnnyshields** [comment]
@tdreyno would be nice if you can revert this (or make it switchable) on master so it's stable.

**Comment by tdreyno** [comment]
On my radar

**Comment by johnnyshields** [comment]
This is fixed, thanks!
