### ISSUE TITLE
manipulate_resource_list doesn't work with I18n

### ISSUE THREAD

**Issue by johnnyshields** [middleman/middleman#1651]
I am using a deploy plugin (middleman-s3_sync) which uses the `manipulate_resource_list` hook to sync the sitemap to a remote file store.

Some files weren't syncing properly and I found that it's because Middleman Core is now generating the correct sitemap list.

I believe the issue is related to I18n. Here's my config:

```
I18n.available_locales = %i(ja en)
activate :i18n, templates_dir: 'templates', langs: I18n.available_locales, mount_at_root: :ja
```

The sitemap includes:

```
 #<Middleman::Sitemap::Resource path=templates/index.html>
```

I expect to see:

```
index.html
en/index.html
```

**Comment by johnnyshields** [comment]
Just a further thought here, is Sitemap intended to exactly represent the structure of the build dir (in which case there's a bug), or it is it intended to represent the source dir (in which case this plugin should find an alternate way to read the build dir)?

**Comment by tdreyno** [comment]
It represents the "output" sitemap (so build dir, or what you get during dev mode). Is it possible that `deploy` is simply running before `i18n`? There is a `priority` option when creating extensions to make sure they run in a certain order.

**Comment by johnnyshields** [comment]
I've solved the issue by setting resource_list_manipulator_priority on the plugin. Thanks!
https://github.com/fredjean/middleman-s3_sync/pull/100

One thing I've noticed, not really a problem but if I have the following config:

```
I18n.available_locales = %i(ja en)
activate :i18n, templates_dir: 'templates', langs: I18n.available_locales, mount_at_root: :ja
```

Then my sitemap includes:

```
templates/index.html     <-- should not be in sitemap
index.html     <-- OK
en/index.html     <-- OK
```

**Comment by tdreyno** [comment]
Hmm, is this only true if you renamed `localizable` to `templates`?
