### ISSUE TITLE
Build generated .html files broken after upgrading to `3.4.0`

### ISSUE THREAD

**Issue by damirstuhec** [middleman/middleman#1658]
**middleman version**: 3.4.0
**ruby version**: 2.0.0p247
**OS version**: OS X 10.11.1

Not sure if this is something on my end but after upgrading middleman to `3.4.0` all of my build generated `.html` files became empty with absolute path to the layout file in them.

**Example**:
Contents of `test.html` file:
`/Users/Damir/.../website/source/layouts/homepage.haml`

In this example, the `homepage.haml` file is responsible to provide layout for `test.html` file.

Building with `--verbose` switch doesn't give any warnings, errors or any other useful information. Everything worked before upgrading.

Not sure how relevant this is but this is my *Gemfile*:

    gem "middleman"
    gem "middleman-blog"
    gem 'middleman-protect-emails'
    gem 'middleman-pry'
    gem "middleman-syntax"
    gem 'middleman-inliner'
    gem 'middleman-blog-drafts'
    gem 'middleman-deploy'
    gem 'middleman-cdn'
    gem "redcarpet"
    gem 'liquid'
    gem 'nokogiri'
    gem 'therubyracer'
    gem 'less'
    gem 'html-proofer'
    gem 'builder'
    gem 'ansi'

Let me know if I can provide anything else. Thanks!

**Comment by tdreyno** [comment]
I think the format of `content_for` or `wrap_layout` changed upstream in Padrino at this time. Swap the `-` prefix with `=` or vis a versa.

**Comment by damirstuhec** [comment]
@tdreyno thanks but unfortunately this doesn't seem to work. Moreover, I don't use `wrap_layout`or `content_for` for all pages but all .html pages are empty. I use `wrap_layout` only for blog pages in `blog_single` layout but changing the prefix there doesn't fix the issue.

**Comment by tdreyno** [comment]
Can you disable all those `middleman-` plugins and confirm the behavior exists still

**Comment by damirstuhec** [comment]
Just did. The same thing...

**Comment by tdreyno** [comment]
Would you be able to post (or share privately) a copy of your repo so I can debug?

**Comment by damirstuhec** [comment]
@tdreyno Sure. Can I send it to your email?

**Comment by damirstuhec** [comment]
@tdreyno I sent it to you. Any updates?

**Comment by tdreyno** [comment]
@damirstuhec Sorry, probably won't have time to look until the weekend

**Comment by damirstuhec** [comment]
@tdreyno No problem!

**Comment by damirstuhec** [comment]
@tdreyno Any updates?

**Comment by damirstuhec** [comment]
@tdreyno Any progress? Can I help you in any way?

**Comment by tdreyno** [comment]
Digging in today.

**Comment by tdreyno** [comment]
Okay, found it. Looks like our upstream callback library (hooks) changed their API which was passing incorrect values into your `after_render` extension. Fixed on master, will try to get a new gem out soon.

**Comment by damirstuhec** [comment]
Amazing! I just noticed that if I don't activate `add_links_to_navigation` everything works as expected.

**Comment by tdreyno** [comment]
Good catch! Thanks for the test case and sorry for the delay.

**Comment by damirstuhec** [comment]
No problem. Glad you figured it out! :+1:
