### ISSUE TITLE
LoadError while loading middleman.gemspec

### ISSUE THREAD

**Issue by danielbayerlein** [middleman/middleman#1671]
My [middleman-google-analytics](/danielbayerlein/middleman-google-analytics/tree/issue-20) Travis CI Build is broken, any idea why?

https://travis-ci.org/danielbayerlein/middleman-google-analytics/jobs/88618074:

```
Fetching git://github.com/middleman/middleman.git
There was a LoadError while loading middleman.gemspec: 
cannot load such file -- middleman-core/version from
/Users/travis/build/danielbayerlein/middleman-google-analytics/vendor/bundle/ruby/2.2.0/bundler/gems/middleman-c9bb4540b340/middleman/middleman.gemspec:4:in
`<main>'
```

Looks like 3a7848da9e9ce9acfd59b36fe47e1bce841a3161 is responsible for that.

**Comment by tdreyno** [comment]
Yup, I see it now: https://github.com/middleman/middleman/commit/3a7848da9e9ce9acfd59b36fe47e1bce841a3161#diff-0cf9b8262769b3b86b51b66d081ea6efR4

That path is looking for a `middleman/version` file, which doesn't exist since the file is always in `-core`

**Comment by tdreyno** [comment]
Try now

**Comment by danielbayerlein** [comment]
![](https://travis-ci.org/danielbayerlein/middleman-google-analytics.svg)

:+1: Thanks @tdreyno
