### ISSUE TITLE
How do I use mixin by compass with middleman v4.0.0.rc.1?

### ISSUE THREAD

**Issue by kkotaro0111** [middleman/middleman#1672]
**middleman version**: 4.0.0.rc.1
**ruby version**: 2.2.3 with rbenv
**OS version**: OS X 10.10.5

When I added ``@import "compass";`` to site.css.scss, I get an error message displayed ``Sass::SyntaxError: File to import not found or unreadable: compass.`` on my web browser.

For example.
```shell
$ middleman version
Middleman 4.0.0.rc.1

$ middleman init --skip-bundle
// ...
Do you want to use the Asset Pipeline? y
Do you want to use Compass? y
Do you want to use LiveReload? y
// ...
Do you want a Rack-compatible config.ru file? y

$ bundle install --path vendor/bundle 
// ...

$ bundle exec middleman
// success work.

$ vi source/stylesheets/site.css.scss
// 1-1 @charset "utf-8";
//  -2 + @import "compass";
// 2-3 @import "normalize";

$ bundle exec middleman
// I access to localhost:4567 with a web browser, then show 'not found or unreadable: compass'.

$ vi source/stylesheets/site.css.scss
// 1-1 @charset "utf-8";
// 2- - @import "compass";
// 3-2 @import "normalize";
// ..
// 4-4 body {
//  -5 + @include clearfix;
// 5-6 background: #EC561;

$ bundle exec middleman
// I access to localhost:4567 with a web browser, then show "undefined mixin 'clearfix'".
```

I get ``$ bundle list``
```
Gems included by the bundle:
  * activesupport (4.2.4)
  * addressable (2.3.8)
  * atomic (1.1.99)
  * backports (3.6.6)
  * bundler (1.10.6)
  * chunky_png (1.3.5)
  * coffee-script (2.4.1)
  * coffee-script-source (1.9.1.1)
  * compass (1.0.3)
  * compass-core (1.0.3)
  * compass-import-once (1.0.5)
  * contracts (0.9)
  * em-websocket (0.5.1)
  * erubis (2.7.0)
  * eventmachine (1.0.8)
  * execjs (2.6.0)
  * fastimage (1.6.8)
  * ffi (1.9.10)
  * haml (4.0.7)
  * hamster (1.0.0)
  * hashie (3.4.3)
  * http_parser.rb (0.6.0)
  * i18n (0.7.0)
  * json (1.8.3)
  * kramdown (1.9.0)
  * listen (3.0.3)
  * middleman (4.0.0.rc.1)
  * middleman-cli (4.0.0.rc.1)
  * middleman-compass (4.0.0.rc.1)
  * middleman-core (4.0.0.rc.1)
  * middleman-livereload (3.4.3)
  * middleman-sprockets (4.0.0.rc.1)
  * minitest (5.8.2)
  * multi_json (1.11.2)
  * padrino-helpers (0.12.5)
  * padrino-support (0.12.5)
  * rack (1.6.4)
  * rack-livereload (0.3.16)
  * rb-fsevent (0.9.6)
  * rb-inotify (0.9.5)
  * sass (3.4.19)
  * sprockets (3.4.0)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (1.4.1)
  * tzinfo (1.2.2)
  * uglifier (2.7.2)
```

**Comment by tdreyno** [comment]
Sprockets and Compass may not be correctly working in conjunction. I'll look into it

**Comment by philippbecker** [comment]
I came across almost the same error message when importing `breakpoint`:

```
SassC: SyntaxError: Error: File to import not found or unreadable: breakpoint
```

```
Gems included by the bundle:
  * activesupport (4.2.4)
  * addressable (2.3.8)
  * ast (2.1.0)
  * astrolabe (1.3.1)
  * atomic (1.1.99)
  * autoprefixer-rails (6.0.3)
  * backports (3.6.6)
  * breakpoint (2.5.0)
  * bundler (1.10.6)
  * capybara (2.5.0)
  * coffee-script (2.4.1)
  * coffee-script-source (1.9.1.1)
  * compass-import-once (1.0.5)
  * contracts (0.12.0)
  * em-websocket (0.5.1)
  * erubis (2.7.0)
  * eventmachine (1.0.8)
  * execjs (2.6.0)
  * fastimage (1.7.0)
  * ffi (1.9.10)
  * haml (4.0.7)
  * hamster (1.0.0)
  * hashie (3.4.2)
  * htmlcompressor (0.2.0)
  * http_parser.rb (0.6.0)
  * i18n (0.7.0)
  * json (1.8.3)
  * kramdown (1.9.0)
  * listen (3.0.3)
  * middleman (4.0.0.rc.2 3cd84eb)
  * middleman-autoprefixer (2.6.1)
  * middleman-cli (4.0.0.rc.2 3cd84eb)
  * middleman-core (4.0.0.rc.2 3cd84eb)
  * middleman-livereload (3.4.3)
  * middleman-minify-html (3.4.1)
  * mime-types (2.6.2)
  * mini_portile (0.6.2)
  * minitest (5.8.1)
  * nokogiri (1.6.6.2)
  * padrino-helpers (0.13.0)
  * padrino-support (0.13.0)
  * parser (2.2.3.0)
  * powerpack (0.1.1)
  * rack (1.6.4)
  * rack-livereload (0.3.16)
  * rack-test (0.6.3)
  * rainbow (2.0.0)
  * rb-fsevent (0.9.6)
  * rb-inotify (0.9.5)
  * rubocop (0.34.2)
  * ruby-progressbar (1.7.5)
  * sass (3.4.19)
  * sassc (1.7.1)
  * sassy-maps (0.4.0)
  * scss_lint (0.42.2)
  * slim (3.0.6)
  * temple (0.7.6)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (1.4.1)
  * tzinfo (1.2.2)
  * uglifier (2.7.2)
  * xpath (2.0.0)
```

**Comment by mremco** [comment]
For what it's worth, I've been having similar issues since rc.1. If I remember correctly, I've been able to solve all of them by using full file names in my `@import` statements, ie. `@import "mixins.css.sass"`, where before I used `@import "mixins"`.

For imported gems, I can use `@import "breakpoint"` without any issue.

**Comment by tdreyno** [comment]
I think this was actually a change upstream in Sprockets. I remember renaming some imports for the tests. Valid Sass names should be:

`whatever.css.scss` for built files.
`_whatever.scss` for partial/mixins.

I'll see if there's a way to work around Sprockets and enable the original behavior

**Comment by srerickson** [comment]
I've been tried changing the import to include the full extension, but compaas still isn't working.

**Comment by srerickson** [comment]
I this the problem might be here: 
https://github.com/middleman/middleman-sprockets/blob/master/lib/middleman-sprockets/extension.rb#L219
?

`append_paths_from_gems` does not seem to catch the `stylesheets` folder in compass-core ?

**Comment by tdreyno** [comment]
Don't they automatically add their files to sass paths on boot up?

**Comment by bradgessler** [comment]
I can confirm `middleman-sprockets` and `middleman-compass` aren't playing nice together in `middleman rc2`

**Comment by bradgessler** [comment]
From what I can tell both `compass` and the `modular-scale` gem are not adding their paths to the `Sass` configuration. I'm not familiar enough with `compass` at the moment to know exactly where and how this problem is happening.

**Comment by tdreyno** [comment]
Seems to work fine without `sprockets`, but with just `compass`.

**Comment by bradgessler** [comment]
@tdreyno yeah, when both`middleman-compass` and `middleman-sprockets` are present I get the following error:

![CSS compilation error](https://bradgessler.s3.amazonaws.com/screenshots/2015-12-14-11-33-ksbik-23sg6.png)

As you can see the compass paths are not present. Is the `middleman-sprockets` gem overriding a configuration instead of appending?

I can confirm this is still an issue in RC3 with the following gems:

```
site[master] → bundle list | grep middleman
  * middleman (4.0.0.rc.3)
  * middleman-cli (4.0.0.rc.3)
  * middleman-compass (4.0.0.rc.2)
  * middleman-core (4.0.0.rc.3)
  * middleman-sprockets (4.0.0.rc.1)
  * middleman-syntax (2.0.0 e83a478)
```

**Comment by bradgessler** [comment]
The paths are coming from https://github.com/rails/sprockets/blob/3.x/lib/sprockets/sass_processor.rb#L63 I suspect the `middleman-compass` gem configures the Sass engine first, then the `middleman-sprockets` gem over writes that config data with these options.

**Comment by coskuntekin** [comment]
best configuration is 
```
#Middleman
gem 'middleman', '~> 4.0.0.beta.2'

# Middleman-sprockets
gem 'middleman-sprockets', '~> 4.0.0.beta.1'

# Compass
gem 'compass', '1.0.3'
```

Other wise it's not working.

**Comment by furunkel** [comment]
Calling
```ruby
::Sass.load_paths.concat(compass.sass_load_paths)
```
at the end of the `::Compass.configuration` block seems to fix this.

**Comment by coskuntekin** [comment]
@furunkel do you have live example ?

**Comment by tdreyno** [comment]
I've added this directly to the Compass extension as well

**Comment by furunkel** [comment]
@tdreyno: Thanks, seems to fix this issue altogether.

**Comment by bradgessler** [comment]
:+1: I too can confirm that fixes the issue. Thanks @tdreyno!

**Comment by kkotaro0111** [comment]
:+1:

**Comment by tdreyno** [comment]
Released v4.0.1 with this fix.

**Comment by balthisar** [comment]
I was facing a frustrating issue with `@import 'breakpoint'` not working for me (Google brought me to this issue).

After some experimenting adding the `breakpoint` gem _before_ the `middleman-compass` gem fixed my issue. I'm guessing this is some unintended effect of Middleman’s auto-requiring things in the Gemfile. Up until now I've kept the Gemfile organized, and I wasn't expecting behavioral difference due to their order in the Gemfile.

**Comment by tdreyno** [comment]
There really shouldn't be any difference between gem order
