### ISSUE TITLE
Trouble building Middleman project on Windows 10

### ISSUE THREAD

**Issue by LandonSchropp** [middleman/middleman#1673]
I'm using Middleman to distribute [the examples](https://github.com/LandonSchropp/unraveling_flexbox) for my book, and a few of my customers running Windows mentioned they've had issues getting Middleman up and running. I downloaded Windows 10 on my Macbook and have been trying to get my repo to compile since. Here's what I've done so far:
- I switched Middleman to the `v3-stable` branch in the Gemfile after experiencing the errors mentioend in #1601 and reading about the fix in #1640.
- I added a missing `require` to the `default_helpers.rb` file. (I'll send out a PR for this shortly.)

Running `bundle exec middleman build` fails with this error:

```
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:153:in `resolve': couldn't find file 'C:\Users\landonschropp\unraveling_flexbox\source\images\chapter14\close.svg' (Sprockets::FileNotFound)
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/asset.rb:12:in `initialize'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/extension.rb:99:in `new'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/extension.rb:99:in `block in manipulate_resource_list'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/extension.rb:98:in `each'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/extension.rb:98:in `manipulate_resource_list'
        from C:/Users/landonschropp/middleman/middleman-core/lib/middleman-core/sitemap/store.rb:217:in `block (2 levels) in ensure_resource_list_updated!'
        from C:/Users/landonschropp/middleman/middleman-core/lib/middleman-core/sitemap/store.rb:216:in `each'
        from C:/Users/landonschropp/middleman/middleman-core/lib/middleman-core/sitemap/store.rb:216:in `block in ensure_resource_list_updated!'
        from C:/Ruby21-x64/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from C:/Users/landonschropp/middleman/middleman-core/lib/middleman-core/sitemap/store.rb:208:in `ensure_resource_list_updated!'
        from C:/Users/landonschropp/middleman/middleman-core/lib/middleman-core/sitemap/extensions/on_disk.rb:31:in `block in initialize'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `instance_exec'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `proc!'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:82:in `evaluate_for'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:60:in `call'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:59:in `evaluate_callback'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:55:in `execute_callback'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:40:in `block in run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `each'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `inject'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks.rb:55:in `run_hook_for'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/instance_hooks.rb:6:in `run_hook'
        from C:/Users/landonschropp/middleman/middleman-core/lib/middleman-core/core_extensions/request.rb:57:in `inst'
        from C:/Users/landonschropp/middleman/middleman-core/lib/middleman-core/cli/build.rb:95:in `shared_instance'
        from C:/Users/landonschropp/middleman/middleman-core/lib/middleman-core/cli/build.rb:62:in `build'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Users/landonschropp/middleman/middleman-core/lib/middleman-core/cli.rb:72:in `method_missing'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Users/landonschropp/middleman/middleman-core/lib/middleman-core/cli.rb:20:in `start'
        from C:/Users/landonschropp/middleman/middleman-core/bin/middleman:18:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/bin/middleman:23:in `load'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/bin/middleman:23:in `<main>'
```

@tommysanterre mentioned the same issue in #1640. If I delete `close.svg`, I get the same `Sprockets::FileNotFound` error on the next file.

If there's anything I can to do help with this issue, please let me know. I'm happy to contribute, especially if it helps resolve this issue quicker.

**Comment by LandonSchropp** [comment]
My #1674 PR helps to address this, but it doesn't solve the `Sprokets::FileNotFound` issue. I'd like to keep this open until that's fixed if you wouldn't mind.

**Comment by tommysanterre** [comment]
I still have this issue as well

**Comment by LandonSchropp** [comment]
@tdreyno Oops, I forgot to tag you above. Would you mind reopening this?

**Comment by LandonSchropp** [comment]
I've been tracking this down and I *think* it might be related to [this issue](https://github.com/rails/sprockets/pull/116) in Sprockets. It looks like they've fixed the problem and added support for Windows file systems in 3.3. However, the current version of middleman-sprockets is using 2.12. I've noticed the master branch of middleman-sprockets has been bumped to 3.x, but it doesn't seem to be widely released yet. Is there any ETA on when that will be ready to go?

**Comment by tdreyno** [comment]
The master version of `middleman-sprockets` will be released along-side Middleman 4 and won't be back ported to v3.

I find it hard to believe this is an issue with all Windows, we've had windows users for years. is this only on windows 10?

**Comment by LandonSchropp** [comment]
Honestly I'm not sure. I'm a Mac user myself, so I couldn't really speak to that. I was testing on a clean install of Windows 10, and I installed Ruby with [RubyInstaller](http://rubyinstaller.org/), so it seems unlikely to be specific to my setup.

**Comment by jimothyGator** [comment]
@LandonSchropp 

Did you also install the dev kit? This is necessary for Gems that have native extensions, which may include some of those used in Middleman. You can [download the dev kit](http://rubyinstaller.org/downloads/) from the same place as RubyInstaller. (This is just a guess, as I'm also a Mac user, but I recall having to help a colleague build a Middleman project on Windows).

**Comment by LandonSchropp** [comment]
@jimothyGator I did install the dev kit. Good suggestion though. :smiley:

**Comment by jahed** [comment]
The FileNotFound is caused by the underscore in `unraveling_flexbox`. Sprockets seems to have problems with symbols. See rails/sprockets#75

I'm having a similar problem on Windows 10. Guess I'll be going back to my Linux VM for now. :disappointed:

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets. I'd suggest closing this issue.

If it's still a problem it should be filed in https://github.com/middleman/middleman-sprockets

**Comment by LandonSchropp** [comment]
Makes sense.
