### ISSUE TITLE
Middleman 4: Layout applied to Sass files with `.scss` suffix when using `files.watch`

### ISSUE THREAD

**Issue by jimothyGator** [middleman/middleman#1677]
Related to issue #1676. This does not happen if the file is given a `.css.scss suffix`.

Given:
* An additional source folder is used, using `files.watch`
* A Sass file exists with `.scss` (not `.css.scss`) suffix

Then:
* The layout (`layout.erb`) is applied to the compiled Sass file, so that it is a mix of HTML and CSS.

Assume this folder structure:

```
.
├── source
│   ├── layouts
│   │   └── layout.erb
│   └── stylesheets
│       └── site.css.scss
└── source2
    └── stylesheets
        └── more-styles.scss
        └── styles3.css.scss
```

`layout.erb`:
```
<!DOCTYPE html>
<html>
<head>
  <title>Middleman 4 Test</title>
</head>
<body>
  <%= yield %>
</body>
</html>
```

`more-styles.scss`:
```
$myColor: #123456;

body {
  color: $myColor;
}
```

`styles3.css.scss`:
Same contents as `more-styles.scss`

`config.rb`:
```
files.watch :source, path: File.join(root, 'source2')
```

Running `bundle exec middleman build` results in these files:

`build/stylesheets/more-styles` (note missing `.css` suffix, see #1676):
```
<!DOCTYPE html>
<html>
<head>
  <title>Middleman 4 Test</title>
</head>
<body>
  /* line 3, more-styles.scss */
body {
  color: #123456; }

</body>
</html>
```

`build/stylesheets/styles3.css`:
```
/* line 3, styles3.css.scss */
body {
  color: #123456; }
```

Note that if the suffix is `.css.scss`, then the layout is not applied. As explained in #1676, the `.css.scss` suffix is deprecated, so it's desirable to use the `.scss` suffix instead, especially when sharing Sass files between Middleman and other projects (such as when using Middleman to prototype sites that will be build on other platforms, such as Rails).

**Comment by jimothyGator** [comment]
Tested against master branch and version 4.0.0.rc.1.

For master branch, middleman revision is ec99a7b28f6aa67ba33beb52e2d061138023823b. middleman-sprockets revision is 1177edb30c452211caca0a5751f59c1816320807.

**Comment by tdreyno** [comment]
Fixed here: https://github.com/middleman/middleman/commit/684a80c9061fd5cabe4b78c1c2bce9785fbaf000
