### ISSUE TITLE
Middleman Server hangs/won't load if a '.scss' file exists in the 'stylesheets' folder

### ISSUE THREAD

**Issue by beseku** [middleman/middleman#1685]
Using Middleman 3.4.0 with Livereload and Autoprefixer, Ruby 2.2.3 (via rbenv) on OS X 10.11.

This may reveal a larger issue, but through misnaming a file via Textmate, I ended up with a hidden file called .scss in my stylesheets folder. This caused the middleman server to hang after live reload detected the change and CTRL-C wouldn't end the process.

Trying to restart the server caused middleman to lock up - using --verbose revealed the hidden file was causing the issue and removing it fixed middleman.

**Comment by tdreyno** [comment]
I can see why this might happen, but I'm going to close this as a very unlikely to happen situation. Thanks for reporting, this will serve as documentation for any other users who may stumble across this.
