### ISSUE TITLE
Installation Instructions Incomplete

### ISSUE THREAD

**Issue by rdodev** [middleman/middleman#1688]
I'm running:
OS: Ubuntu 15.04
Ruby: ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
Gem: 2.2.2
build-essential, ruby-dev, zlibc packages installed.

I then run, as shown in your docs:

`sudo gem install middleman`

I keep getting the following error

```
Building native extensions.  This could take a while...
ERROR:  Error installing middleman:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby2.1
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build

extconf failed, exit code 1
```
So it seems there are some pre-requirements that aren't listed in your install instructions and it would be much appreciated if those can be fleshed out and made explicit.

**Comment by Arcovion** [comment]
According to this: http://www.nokogiri.org/tutorials/installing_nokogiri.html
You might need this: `sudo apt-get install zlib1g-dev`

**Comment by rdodev** [comment]
Sigh. That seemed to work. Thanks. Given it's an upstream dependency issue not sure if it's worth documenting in this project, but, from the ux perspective is rather frustrating running commands as instructed and those not working.

**Comment by Arcovion** [comment]
Yea Nokogiri has always been a pain to install.
I think we just use it for making article summaries in `middleman-blog`, could probably switch to using [Oga](https://github.com/YorickPeterse/oga) instead for v4 or find some other way.
