### ISSUE TITLE
Use #register_resource_list_manipulator in extension

### ISSUE THREAD

**Issue by dg-ratiodata** [middleman/middleman#1691]
Hi @tdreyno, 

Given I want to write an extension which needs to modify the ressources list. Is it safe to use [#register_resource_list_manipulator(https://github.com/middleman/middleman-blog/blob/master/lib/middleman-blog/extension.rb#L136) in my extension? Is it part of the public API?

Cheers,
Dennis

**Comment by tdreyno** [comment]
If you need to register multiple separate manipulators, sure, but if you only need it once you can make a method which will automatically self-register:

```
class Test < Middleman::Extension
  def manipulate_resource_list(resources)
    resources
  end
end
```

**Comment by dg-ratiodata** [comment]
Ah, ok. Thanks a lot.
