### ISSUE TITLE
[Windows] Middleman requires rubyinstaller devkit

### ISSUE THREAD

**Issue by zacps** [middleman/middleman#1692]
This is a request to add the requirement for rubyinstaller-devkit to be added to the readme. The dependency JSON requires the devkit to be installed in order to run. Without it middleman init will fail. Could you add this to the readme? I would do it myself, but I'm quite new to Github and don't know exactly how I would go about doing it.

**Comment by tdreyno** [comment]
Click the "edit" button when you are looking at the `README.md`
