### ISSUE TITLE
Localization and Directory Indexes

### ISSUE THREAD

**Issue by yazinsai** [middleman/middleman#1693]
I was having an issue where Directory Indexes (pretty URLs) were not working after I had enabled localization.

Here's what my `config.rb` looked like before:

``` ruby
# Directory indexes NOT working
activate :directory_indexes
activate :i18n,
  :langs => [:en, :ar],
  :mount_at_root => :en,
  :no_fallbacks => true
```

In this last example, localization worked .. but directory indexes did NOT.

However, once I moved the `activate :directory_indexes` AFTER the `activate :i18n` line, it worked fine. Here's what the file looked after:

``` ruby
# Directory indexes working fine
activate :i18n,
  :langs => [:en, :ar],
  :mount_at_root => :en,
  :no_fallbacks => true
activate :directory_indexes
```

Is this a bug, or by design?

**Comment by tdreyno** [comment]
Due to the way v3 worked. Should be fixed in v4.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! This should work in v4. If not a a PR with a failing test would be a great start.

**Comment by yazinsai** [comment]
No worries, thanks @sandstrom
