### ISSUE TITLE
Middleman article "[title]" creates bad front-matter when title contains colon

### ISSUE THREAD

**Issue by jayliu50** [middleman/middleman#1697]
The command `middleman article "Title: subtitle"` should wrap the given title in quotes when producing front-matter, or else this results in a page that cannot be built or displayed.

Current yaml output:
```title: Title: subtitle```

Desired yaml output:
```title: "Title: subtitle"```

**Comment by tdreyno** [comment]
Definitely a good bug. However, we've removed that command entirely in v4.

Thanks for reporting.
