### ISSUE TITLE
v4: i18n + proxy

### ISSUE THREAD

**Issue by GhostGambler** [middleman/middleman#1701]
i18n together with the proxy command does not work in v4.

For example:
```ruby
["ug"].each do |shortname|
  proxy "/localizable/#{shortname}/publications.html", "/localizable/publications.html", locals: { person_short_name: shortname }, ignore: true
end
```
gives
> You can't proxy ug/publications.html to localizable/ug/publications.html which is itself a proxy. (RuntimeError)

**Comment by tdreyno** [comment]
Not sure why this is necessary. The i18n extension will already do this for you.

**Comment by GhostGambler** [comment]
I want to have one (localized) file, which receives the short_name as parameter, instead of having to put 5 files into the sources. (The "ug" one-element-list is just an example.)

I do not see how this can be achieved otherwise. Basically I just want the first example from here localized: https://middlemanapp.com/advanced/dynamic_pages/

**Comment by tdreyno** [comment]
Not sure I'm understanding. The language will already be available inside each template as `I18n.locale`

**Comment by GhostGambler** [comment]
I have a file .html.erb file containing:
```erb
<h1><%= t('publications') %></h1>
<%= show_publications_of short_name %>
```

This file should be accessible via the following paths
```
/DE/person1/publications.html -> short_name = person1, locale = de
/EN/person1/publications.html -> short_name = person1, locale = en
/DE/person2/publications.html -> short_name = person2, locale = de
/EN/person2/publications.html -> short_name = person2, locale = en
```
which in my understanding should be achievable by combining proxy and i18n?

**Comment by tdreyno** [comment]
Ah, gotcha. That's a reasonable assumption, but i18n can't be in that way currently.

You can do it outside of `i18n` like so:

```
[:de, :en].each do |locale|
  ["ug"].each do |shortname|
    proxy "/#{locale}/#{shortname}/publications.html", "/publications.html", locals: { person_short_name: shortname }, ignore: true, lang: locale
  end
end
```

Where you don't place the publications file in the `localizable` folder.

**Comment by GhostGambler** [comment]
Your code works. Maybe something to be added to the documentation?

While the pages work, the solution breaks the [resource hierarchy used by Middleman-breadcrumbs](https://github.com/marnen/middleman-breadcrumbs/blob/master/lib/middleman-breadcrumbs/breadcrumbs_helper.rb#L11). In detail the localized and the non-localized resource subtrees seem to be separated. (Most likely not only in this case, but whenever one wants to mix localized and non-localized pages.)

[The traversal method of Middleman uses path](https://github.com/middleman/middleman/blob/b4457c98d2007464a58336dc43e63a7c688f35f5/middleman-core/lib/middleman-core/sitemap/extensions/traversal.rb#L7), whereas for breadcrumbs I guess destination_path is more suitable. Is this something which should be added to Middleman or monkey patched in Middleman-breadcrumbs?

**Comment by tdreyno** [comment]
@GhostGambler Yeah, they should definitely be using path, or the built-in traversal methods: https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/sitemap/extensions/traversal.rb

**Comment by GhostGambler** [comment]
Well, they [use the traversal methods of Middleman](https://github.com/marnen/middleman-breadcrumbs/blob/master/lib/middleman-breadcrumbs/breadcrumbs_helper.rb#L11), so if this should work, then it is a bug in Middleman.

**Comment by tdreyno** [comment]
Hmm, that does seem like a bug.

**Comment by hrigu** [comment]
I've the same problem: (middleman 4.1.10). I followed the suggestion of tdreyno from the 10 Dec 2015 without success:
* While running the code with middleman server, I got a "page not found" when I follow the link to the dynamic pages. 
* When I build the website, the 4 pages are rendered, but all with the default locale inside...
`/DE/person1/details.html -> short_name = person1, locale = de
/EN/person1/details.html -> short_name = person1, locale = en
/DE/person2/details.html -> short_name = person2, locale = de
/EN/person2/details.html -> short_name = person2, locale = en`

Any suggestions to work with i18n and dynamic pages?
