### ISSUE TITLE
v4: non-utf8 characters prohibit execution

### ISSUE THREAD

**Issue by GhostGambler** [middleman/middleman#1702]
If a non-utf8 character is somewhere in the file, the regex, which searches for a frontmatter, fails:
```
/.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/util/data.rb:40:in `match': invalid byte sequence in UTF-8 (ArgumentError)
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/util/data.rb:40:in `parse'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/core_extensions/front_matter.rb:68:in `data'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/core_extensions/front_matter.rb:33:in `block in manipulate_resource_list'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/core_extensions/front_matter.rb:30:in `each'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/core_extensions/front_matter.rb:30:in `manipulate_resource_list'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/sitemap/store.rb:206:in `block (2 levels) in ensure_resource_list_updated!'
	from /.../gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `each'
	from /.../gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /.../gems/hamster-2.0.0/lib/hamster/vector.rb:431:in `each'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/sitemap/store.rb:204:in `block in ensure_resource_list_updated!'
	from /Users/ulrichgabor/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/sitemap/store.rb:196:in `ensure_resource_list_updated!'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/sitemap/store.rb:153:in `block in resources'
	from /Users/ulrichgabor/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/sitemap/store.rb:152:in `resources'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/util.rb:504:in `find_related_files'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/sources/source_watcher.rb:237:in `update'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/sources/source_watcher.rb:188:in `poll_once!'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/sources.rb:123:in `watch'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/core_extensions/i18n.rb:42:in `after_configuration'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/extension.rb:385:in `block in bind_after_configuration'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/callback_manager.rb:51:in `instance_exec'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/callback_manager.rb:51:in `block in execute'
	from /.../gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `each'
	from /.../gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /.../gems/hamster-2.0.0/lib/hamster/vector.rb:431:in `each'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/callback_manager.rb:51:in `execute'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/application.rb:289:in `start_lifecycle'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/application.rb:265:in `initialize'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/preview_server.rb:140:in `new'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/preview_server.rb:140:in `initialize_new_app'
	from /.../gems/middleman-core-4.0.0.rc.2/lib/middleman-core/preview_server.rb:33:in `start'
	from /.../gems/middleman-cli-4.0.0.rc.2/lib/middleman-cli/server.rb:86:in `server'
	from /.../gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /.../gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /.../gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /.../gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /.../gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /.../gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /.../gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /.../gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /.../gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /.../gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /.../gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /.../gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /.../gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /.../gems/middleman-cli-4.0.0.rc.2/bin/middleman:23:in `<top (required)>'
	from /.../bin/middleman:23:in `load'
	from /.../bin/middleman:23:in `<main>'
	from /.../bin/ruby_executable_hooks:15:in `eval'
	from /.../bin/ruby_executable_hooks:15:in `<main>'
```

I suppose such characters should be silently ignored, since the actual content of a file should not be relevant. The affected file does not even contain a frontmatter.

**Comment by tdreyno** [comment]
Are non-UTF8 characters valid? Or should the error message just be more clear?

**Comment by GhostGambler** [comment]
In this case it is just another character set (ISO 8859-1), which would work if the html is passed over. The html header specifies the character set, so a browser can render this file correctly.

I would expect middleman to ignore the actual content of a file, besides the frontmatter. (Frankly I do not know the character set convention of the front matter? This seems like a related issue to me.)

**Comment by tdreyno** [comment]
Ruby is weird with various encodings. Basically, the whole file has to be the same encoding to be read. Can the content not be represented as utf-8?

**Comment by GhostGambler** [comment]
I guess best solution would be to catch the exception and print an error complaining about an unexpected character encoding and pointing towards the "encoding" setting. The encoding setting should also be documented more clearly in the docs.

I thought a while about the problem and I doubt it makes sense to mix two character sets in one file (front matter + content). I also doubt it makes sense to mix different character sets in one middleman project at all.

**Comment by tdreyno** [comment]
I don't think we have a centralized encoding setting, I'm pretty sure we're expecting utf8 in a bunch of places.

**Comment by GhostGambler** [comment]
Actually there [is one](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/application.rb#L157), but it does not work...

I think [the position where the setting is used](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/application.rb#L256) is too early. The config file has not been read at that point yet. If one moves this lines e.g. into the middle of `start_lifecycle()` the config file has been parsed and the setting can be used.

Furthermore the call to set the *internal* encoding should be removed, see documentation:
> You should not set ::default_internal in ruby code […]
http://docs.cs.up.ac.za/programming/ruby/ruby_2_2_0_core/Encoding.html#method-c-default_internal-3D

**Comment by tdreyno** [comment]
Is there any way to write a test to test this?

**Comment by GhostGambler** [comment]
Yes, this is possible.

### Prevent exception (1.) ###
First think make sure Middleman does not crash and reports something useful, so check if this starts without an exception:
``` bash
mkdir bugreport && cd bugreport
echo "gem 'middleman', '>= 4.0.0.rc.2'" > Gemfile
bundle install && bundle binstub middleman-cli
mkdir source
cat <<EOT > source/index2.html.erb
---
title: ÄÖÜ
---
ÄÖÜ
EOT
iconv -f UTF-8 -t ISO-8859-1 source/index2.html.erb > source/index.html.erb
rm source/index2.html.erb
touch config.rb
./bin/middleman server preview
```
```
== The Middleman is loading
...gems/middleman-core-4.0.0.rc.2/lib/middleman-core/util/data.rb:40:in `match': invalid byte sequence in UTF-8 (ArgumentError)
...
```
Which obviously does not work yet.

### Check for correct HTTP header (2., 3.) ###
Change the project like
```bash
echo "set :encoding, "ISO-8859-1" >> config.rb
./bin/middleman server preview
```
and move the code like I mentioned in the previous comment and Middleman starts, but opening `http://localhost:4567/` displays wrong umlauts (`���`) that is because the preview server sends everything as UTF8:
> Response Headers:
> Connection:Keep-Alive
> Content-Length:4
> Content-Type:text/html; charset=utf-8
> Date:Fri, 25 Dec 2015 09:56:19 GMT
> Server:WEBrick/1.3.1 (Ruby/2.1.1/2014-02-24) OpenSSL/1.0.1g

So next two tests should be for the Content-Type header, without an encoding setting it should contain `charset=utf-8`, whereas with encoding setting it should contain `charset=#{config[:encoding]}`. (This is a little bit duplicated, because the encoding setting defaults to `utf-8` so maybe just one test here.)

### Check for correct output file (4.) ###
There should be one further test, which checks the built file for the correct bytes.
```bash
./bin/middleman build
```
```ruby
output = File.read('build/index.html', :encoding => 'iso-8859-1')
expected_utf8 = "ÄÖÜ"
expected_iso = expected_utf8.encode('iso-8859-1')
assert(output.strip == expected_iso)
```

**Comment by tdreyno** [comment]
Forgive my ignorance, but shouldn't UTF-8 work for all those characters or am I missing something?

**Comment by GhostGambler** [comment]
Yes, `ÄÖÜ` can be encoded in `UTF-8` too, although the bit string is different:
```ruby
$ irb
2.1.1 :001 > "ÄÖÜ".encode("UTF-8").bytes
 => [195, 132, 195, 150, 195, 156] 
2.1.1 :002 > "ÄÖÜ".encode("ISO-8859-1").bytes
 => [196, 214, 220] 
```
One could re-encode all files and just use `UTF-8`, but this issue is rather about "repairing" the character encoding awareness of Middleman...

The default external encoding of ruby is based on the system locale, but it is currently (accidentally always) overwritten with `UTF-8`. This is good for portability of Middleman projects, but bad for systems which do not use `UTF-8`, because they cannot use (mostly) *any* umlauts at all. (As long as one does not save files in `UTF-8` independently of the locale.)

The encoding setting should come handy in all cases, (1) expected behavior with non-`UTF-8` locale and (2) portability of Middleman projects, but it is broken and does nothing.

First step should be to repair the encoding setting, to have any control over the encoding.
Second step should be a discussion about the default value of the setting, which could be either `UTF-8` for improved portability or not be overwritten for a default value based on the locale. (I guess most editors will default to `UTF-8` now, so default should likely stay with `UTF-8` as for Middleman portability might be more important.)

**Comment by tdreyno** [comment]
Cool, I'll look into in. All help appreciated as I'm not well versed in the encoding stuff at all, but I'll try to blindly address your items above.

**Comment by GhostGambler** [comment]
I did most of the things described only missing the appropriate `content-type...charset=:encoding` http header of the preview server. I guess you can do this faster than me.
