### ISSUE TITLE
link_to with i18n not working correctly

### ISSUE THREAD

**Issue by Flink** [middleman/middleman#1703]
I’m trying to make a website with two locales (FR, EN) with EN mounted as root.
I did see that `link_to` should be aware of i18n to create links but it seems there’s a bug.
When I do a link to `/`, if I set `locale: :fr` then the generated link is `/fr` as expected. But with another path (`/contact`), it stays as `/contact` instead of generating a `/fr/contact` link.

I saw that tests should ensure it works but that’s clearly not the case :/ I’m using middleman 3.4.0.
Also I don’t have relative links activated, I don’t know if it’s a problem or not.

**Comment by tdreyno** [comment]
Can you try a couple variations: `/contact/` and `/contact/index.html` and see if either of those gets picked up?

**Comment by Flink** [comment]
Nope, same result :/ But I forgot to indicate that I enabled `directory_indexes` (it seems you were thinking about that ;)).

**Comment by Flink** [comment]
If I remove the leading `/` it correctly generate the link but I think that’s more of a side effect than anything else (being already in the `/fr` path).

**Comment by tdreyno** [comment]
yeah, I think you're right

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation (or at least a failing test) as a starting point for discussion around this.

**Comment by crtvhd** [comment]
So in the end this issue was never really resolved. Apparently forcing a locale on a link only seems to work when linking to "/".

**Works when linking to "/"**

```ruby
= link_to t("nav.home"), "/", :locale => :en
```

**Doesn't work when linking to any other path**
Doesn't work as in doesn't influence locale in the url.
```ruby
= link_to t("nav.home"), t("paths.imprint"), :locale => :en
```
```yaml
# en.yml
de:
  paths:
    imprint: imprint
```

/cc @tdreyno @Flink

**Comment by sandstrom** [comment]
@crtvhd Do you have any suggestions on how to solve this? Pull requests are always appreciated! 😄

**Comment by crtvhd** [comment]
I wish @sandstrom, unfortunately I'm no ruby developer 🙍‍♂️
