### ISSUE TITLE
v3/v4 documentation

### ISSUE THREAD

**Issue by bjankord** [middleman/middleman#1706]
With v4 rolling out, curious what the plans are for v3 documentation. It would be really nice to view v3 or v4 documentation, similar to how I can view [ruby 2.2.3 doc](http://ruby-doc.org/core-2.2.3/) or [ruby 1.9.3 doc](http://ruby-doc.org/core-1.9.3/)

**Comment by tdreyno** [comment]
That's a great question. I was probably going to branch the repo and leave `v3.middlemanapp.com` up, and allow the main site to have v4 docs.

**Comment by bjankord** [comment]
Fat finger closed this issue on my phone. That sounds like a good approach.
