### ISSUE TITLE
How to generate an article in 4v?

### ISSUE THREAD

**Issue by romamilkovic** [middleman/middleman#1708]
Hello guys. I reaed documentation, but a command middleman article TITLE doesn't work(Could not find command "article".). 

My gemfile:
source 'https://rubygems.org'

gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

gem "middleman", "~> 4.0.0"
gem "middleman-blog"
gem "middleman-livereload"

gem 'redcarpet', '~> 3.3', '>= 3.3.3'

gem "builder", "~> 3.0"

Thanks.

**Comment by tdreyno** [comment]
Yes, that command has been removed. I'd suggest creating the article text file manually. The command wasn't really doing that much. Will update the docs soon.

**Comment by dg-ratiodata** [comment]
Mmmh,

@tdreyno I really like the helper and still find it useful and use it regularly.

Now one needs to ...

* remember how a blog article is structured
* add the title to the front matter yourself
* convert the title to a valid file name
* have a template for a new article somewhere else - quite annoying if you've got a complex layout for articles.

What was the reason to remove it? Can we extend/change it to make it more useful to you/other contributors/others?

Cheers,
Dennis

**Comment by tdreyno** [comment]
We could bring it back. I asked on Twitter and nobody admitted to using it.

**Comment by dg-ratiodata** [comment]
Mmh... Ok... I "just" started to use twitter and most times I'm overwhelmed by the tweets found there. Maybe I just oversaw it. Wouldn't it be better to ask those things via Github and reference this issue in a tweet in the future?

**Comment by dg-ratiodata** [comment]
I really like the helper and use it every time I create a new article. It's quite convinient to have it around.

**Comment by dg-ratiodata** [comment]
I'm going to ask for feedback on gitter.im as well.

**Comment by dg-ratiodata** [comment]
Using either date in path or front matter is `v4` only correct? In v3 I get an exception:

~~~
== Request: /articles/killing-me-softly-1-4-cleanup-ruby-scripts-after-sigterm.html
       error  build/articles/killing-me-softly-1-4-cleanup-ruby-scripts-after-sigterm.html
       undefined method `date' for #<Middleman::Sitemap::Resource:0x0000000291d6e0>
       /home/user/data/projects/fedux_org-site/lib/fedux_org_site/articles/article.rb:123:in `method_missing'
~~~

**Comment by tdreyno** [comment]
I don't think so... seems easy to write a test for this. Will have to investigate.

**Comment by dg-ratiodata** [comment]
Mmmh... See middleman/middleman-blog#272

**Comment by kisin** [comment]
im also missing this helper.
was very useful in creating new articles

**Comment by Afrenz** [comment]
I just started using Middleman and have been racking my brain trying to figure why this command wasn't working. Is there a place online that we can directly go to that will list deprecated items for future reference? Thanks

**Comment by dg-ratiodata** [comment]
I'm not aware of such a list. I asked @tdreyno if he would reconsider removing this helper.

**Comment by tdreyno** [comment]
That list is here: https://middlemanapp.com/basics/upgrade-v4/

But as this is an extension (blog) not core, it isn't mentioned.

As @dg-ratiodata mentioned, I'll likely be adding it back soon. Didn't realize so many relied on it.

**Comment by trevortwining** [comment]
@tdreyno I *loved* that command. I don't follow you on twitter, so there's no way I would have seen that post, but from a workflow standpoint it's kind of vital to blogging using middleman. I've patched together an aText expansion that replaces the functionality, but I would also find it useful to be back in middleman-blog.

Also, if there are any documentation changes needed in response to putting it back, let me know. I'd love to find a way to help out the project now that I'm using it regularly.

Also, thanks for helping build a great product.

**Comment by tdreyno** [comment]
@trevortwining It'll definitely be back in v4.1.0 really soon now.

We'd love to have any help you're willing the give. Usually, it's best to scratch your own itch. Keeping track of the issues and features you care about and helping us solve and document them.

**Comment by agustifernandez** [comment]
@tdreyno Thanks for taking it back!

**Comment by dhonig** [comment]
@tdreyno :+1: for bringing it back!

**Comment by lalebarde** [comment]
Just tried Middleman 4.1.1 with middleman-blog which is still 4.0.0. And `middleman article 'test article'` leads still to `Could not find command "article"`

**Comment by tdreyno** [comment]
will show up in blog 4.1, whenever that goes out.

**Comment by densityx** [comment]
@tdreyno I am using middleman (4.1.2) and middleman-blog (4.0.0) but that command is still not working, and the documentation is still outdated. How can i create article? How's the format? are there any tutorial or post?

I am new to middleman, since 2 days ago
Peace :) Middleman is great staticgen

**Comment by tdreyno** [comment]
Blog 4.1, not core 4.1. Blog is still 4.0 for now

**Comment by khalilgharbaoui** [comment]
is there any other solution for now? at least an easy way for the readers.. or a link to another way to make articles? saves time... thanx

**Comment by tdreyno** [comment]
If you've got some Github Chops, recoving that code from v3 and making a PR would help. Otherwise, I'm the only person working on this and I'm in crunch time at the day job right now

**Comment by dinomite** [comment]
@tdreyno I pulled the article command and what I think is its wiring (it's still mentioned in `extension.rb:42`), though I still get «Could not find command "article".» when trying to run it.

Code is here: https://github.com/dinomite/middleman-blog/tree/features/new-article-command

**Comment by ericraio** [comment]
Wow what a real bummer, I just started using middleman from using octopress. With Octopress/Jekyll I always generated the boilerplate article.

**Comment by tdreyno** [comment]
@dinomite I think v4 requires the commands to be registered, rather than happening automatically. If you turn that commit into a PR, I'll take a look at getting it working.

**Comment by dinomite** [comment]
Created: https://github.com/middleman/middleman-blog/pull/284

@tdreyno Thanks for being so quick!  I looked around and couldn't figure out how to do that registration—interested in seeing your PR for how it's done.

**Comment by farishkash** [comment]
Any eta on this, even current documentation shows this as the command to use?


![middleman__blogging](https://cloud.githubusercontent.com/assets/5844161/14625584/3c798444-0599-11e6-8454-b759e3906fb7.png)

**Comment by tdreyno** [comment]
@farishkash https://twitter.com/middlemanapp/status/720288267648696322

**Comment by farishkash** [comment]
Thank you, 

Weird I had 4.0 by using gem "middleman-blog", I forced it to 4.0.1 by using gem 'middleman-blog', '~> 4.0.1'

Thanks again.

**Comment by tdreyno** [comment]
Bundler will lock down versions unless you run `bundle update`

**Comment by dinomite** [comment]
@tdreyno Thanks for doing the work to get this back in!

**Comment by knopfler81** [comment]
Hi there...
I am in trouble , I read lots of review but can't fix it 
here is what I stil have :(
`Could not find "source/new-article.erb" in any of your source paths. Your current source paths are:
/Users/nelly/.rvm/gems/ruby-2.3.0/gems/middleman-blog-4.0.1/lib/middleman-blog/commands`

**Comment by danbartlett** [comment]
I upgraded to middleman-blog 4.0.1 but still get `Could not find command "article".`

**Comment by dg-ratiodata** [comment]
I think @tdreyno meant blog-4.1.0 not blog-4.0.1. It's a new feature so the version number should be really a 4.x.0 not 4.0.x:

http://semver.org/:
  * MAJOR version when you make incompatible API changes,
  * MINOR version when you add functionality in a backwards-compatible manner, and
  * PATCH version when you make backwards-compatible bug fixes.

**Comment by danbartlett** [comment]
Ah ok. Unfortunately even with

```
gem "middleman", "~> 4.0.0"                                                                             
gem 'middleman-blog', '~> 4.1.0'                                                                                
gem "middleman-sprockets", "~> 4.0.0.rc"
```

and a `bundle update` I get:

`Could not find gem 'middleman-blog (~> 4.1.0)' in any of the gem sources listed in your Gemfile or available on this machine`

**Comment by dfeng** [comment]
Changing

```
gem "middleman", "~> 4.0.0"
gem 'middleman-blog', '~> 4.1.0'
````

to

```
gem "middleman"
gem "middleman-blog"
```

worked for me.
