### ISSUE TITLE
Middleman v4 build wiped out my build/.git

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1716]
I've taken to keeping my `build` directory checked into a separate Git repository, simply so I can diff the generated output with previous versions. This is very handy, especially when debugging whether Middleman changes have caused something drastic or incorrect to happen to the output files. Unfortunately, running `middleman build` with v4 has wiped out all the regular files (but not the directories) of my `build/.git` folder, which has lost all my build history, as well as making it difficult to debug my transition to v4 in the same way.

**Comment by tdreyno** [comment]
Hmm, think a whitelist of "don't clean" paths is the best idea?

**Comment by bhollis** [comment]
That's how I was thinking of doing it.

**Comment by tdreyno** [comment]
Went with a proc instead.
