### ISSUE TITLE
Can no longer access preview server from localhost

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1717]
Running v4, if I run `middleman server`, I can no longer access the server from `http://localhost:4567` - instead, I must use my hostname or IP.

**Comment by tdreyno** [comment]
Works for me :(

OSX?

**Comment by bhollis** [comment]
Yeah, OSX. I can try again in a bit.

**Comment by bhollis** [comment]
My bad, this was just the server taking really long to start and me thinking it was up because the "LiveReload" message had started.
