### ISSUE TITLE
`page` helper in `config.rb` can no longer take a regex argument

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1718]
In v4, the `page` helper cannot take a regex argument. So this no longer works to prevent directory index creation for all my 404.html pages:

```ruby
page /404\.html/, :directory_index => false
```

Is this an intended feature removal, or a regression?

**Comment by bhollis** [comment]
Looks like globs still work, though. I'd like to be able to use regexes wherever I can use globs.

**Comment by tdreyno** [comment]
I agree. This is a regression

**Comment by tdreyno** [comment]
There was a mis-type def'd bit, but test passes.

**Comment by tdreyno** [comment]
Waiting for confirm :)

**Comment by bhollis** [comment]
Blocked on further testing by #1749.

**Comment by tdreyno** [comment]
Cool, that other one should be resolved.

**Comment by bhollis** [comment]
Awesome, the `page` helper is back in action!
