### ISSUE TITLE
Page data displays poorly in sitemap view

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1719]
I'm visiting my sitemap in v4, at http://legion.local:4567/__middleman/sitemap/.

Where I used to see a nice hash view of page data, I now see this less-friendly display:

```
#<Hashie::Mash date="2015-12-20 22:36 PST" tags="Emacs, Programming, Node" title="Node.js stack traces in Emacs compilation-mode">
```

**Comment by tdreyno** [comment]
Derp, my bad. You're finding all the features I never use :)
