### ISSUE TITLE
Strange error running middleman: "`initialize': undefined method `include' f"

### ISSUE THREAD

**Issue by tansaku** [middleman/middleman#1729]
I'm getting the following error on OSX Yosemite

`/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/extension.rb:51:in `initialize': undefined method `include' for #<Middleman::Application:0x70244427118780> (NoMethodError)`

My colleague on El Capitan is not encountering this.  We are on the same version of ruby (2.2.2) - anyone ever seen this?  any ideas what might be behind it?

**Comment by tdreyno** [comment]
Which version of Middleman?

**Comment by davideparisi** [comment]
I'm getting this error too, ruby 2.2.3 and middleman 4.0.0, any help appreciated

**Comment by tdreyno** [comment]
Sprockets is not supported on Middleman 4.

You can use `gem "middleman-sprockets", github: "middleman/middleman-sprockets", branch: "master"` as a stop-gap, but that gem is unsupported.

**Comment by dsignr** [comment]
Hi, it's very difficult for someone new to Middleman to find out how to integrate Middleman with sprockets. I've been trying to find out for the last few hours..Just my feedback :)

**Comment by tdreyno** [comment]
That's fair, because there is no official way to do so in the current version of Middleman.

**Comment by vasco** [comment]
@tdreyno what should we be using in middleman 4 instead of sprockets? (What's recommended?)

**Comment by dsignr** [comment]
@vasco I suppose most of them (based on questions on SO) use Gulp or something similar.

**Comment by vasco** [comment]
@dsignr tks. Is the idea to integrate that stack with middleman 4 via the new external pipeline https://middlemanapp.com/advanced/external-pipeline/ ?

If that's the case can someone explain me better the parameters:
* source
* latency

and what's the goal of the "name" parameter (in the external pipeline)?

Thanks.

**Comment by tdreyno** [comment]
`name` is just to make console messages more informative.
`source` is the folder to watch.
`latency` is how often to poll that folder for updates.

**Comment by vasco** [comment]
@tdreyno thank you.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! Did the suggestion by @tdreyno work? If so, can this be closed?
