### ISSUE TITLE
Middleman SSL Certificate expired

### ISSUE THREAD

**Issue by lukeadams** [middleman/middleman#1730]
This is probably not the right place for such an issue, but here goes.
The wildcard cert you guys have for `middlemanapp.com` expired yesterday (3 Jan). 
This causes the forums to show an SSL error:
![The message](https://i.imgur.com/9cAm0AI.png)

Might I suggest Let's Encrypt? :smile:

**Comment by dg-ratiodata** [comment]
> Might I suggest Let's Encrypt?

@tdreyno I can recommend this as well. I'm using this for my own website. If you need some help give me or my alter ego @maxmeyer a ping.

What was suprising for me on the first sight: You need renew the certificate every 3 months. But using cronjobs or something similar for this fixed this quite easily for me.

This [article](https://wiki.archlinux.org/index.php/Let%E2%80%99s_Encrypt) of the Arch Linux wiki was quite helpful.

**Comment by tdreyno** [comment]
I have a cert, I've had it for 3 weeks :) I just hate doing sysops so I haven't gotten around to SSH-ing into a Docker box and messing with text files in a remote terminal. Bleh.

**Comment by maxmeyer** [comment]
Then you definitively want to use "Let's encrypt": You don't need to do the renewal of the certificate but let a cronjob do the legwork for you. Works fine for me.
