### ISSUE TITLE
partials_dir on config.rb not working

### ISSUE THREAD

**Issue by kisin** [middleman/middleman#1732]
my config has partials_dir set to "partials" folder
but when calling the partial method i must add the partials folder for it to find the file

  
config.rb
```
set :partials_dir, 'partials'
```

layout.erb (if i remove the partials folder it will not work)
```
<%= partial "partials/header-top" %>
```

**Comment by joshukraine** [comment]
The `partials_dir` setting has been removed as of 4.0.0.beta.1:

> Remove the partials_dir setting. Partials should live next to content, or be addressed with absolute paths.

See [CHANGELOG.md](https://github.com/middleman/middleman/blob/master/CHANGELOG.md#400beta1).

**Comment by kisin** [comment]
ok, good to know.

**Comment by rtack** [comment]
this should be documented in the https://middlemanapp.com/basics/upgrade-v4/ page. Just spent half a day trying to figure out why it wasn't working anymore.

**Comment by tdreyno** [comment]
Sure thing: https://github.com/middleman/middleman-guides/commit/324b035af07e57e43e8b2d7e2818799f71bad708
