### ISSUE TITLE
error when opening config.rb

### ISSUE THREAD

**Issue by lbischof** [middleman/middleman#1736]
I get this error when editing helpers (empty class):

```
E, [2016-01-06T18:19:11.098648 #23537] ERROR -- : run() in thread failed: stream closed:\n /home/lorenz/.rvm/gems/ruby-2.2.3/gems/rb-inotify-0.9.5/lib/rb-inotify/notif
ier.rb:295:in `readpartial'
```

What am I doing wrong?

**Comment by tdreyno** [comment]
Not sure. Does the same thing happen when editing `config.rb`?

**Comment by lbischof** [comment]
Yes. I can post the full output if needed.

**Comment by tdreyno** [comment]
Yes please. Can you post your config and Gemfile.lock too

**Comment by lbischof** [comment]
Error output: http://pastebin.com/qABmD35X

I just commented out everything from my config.rb except:
```
configure :development do                                                                                                                                            
  activate :livereload                                                                                                                                               
end
```
and deleted all helper files. This is my Gemfile:
```
source 'https://rubygems.org'
gem 'middleman'
gem 'middleman-livereload'

``` 
I ran `bundle update` and am on the latest versions. The problem still persists (I think the mutex warning is new). Happy to give more info if you need it.

**Comment by tdreyno** [comment]
And removing `activate :livereload`, removes the message?

**Comment by lbischof** [comment]
No removing livereload does not fix the bug.

**Comment by woodall** [comment]
@lbischof any chance your project is public so I can test it locally?

**Comment by lbischof** [comment]
[yeah sure](https://github.com/lbischof/maplesplendor.ca)

**Comment by cybernetlab** [comment]
same issue when editing helpers:

```
E, [2016-07-06T14:53:10.314467 #17015] ERROR -- : run() in thread failed: stream closed:\n /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:300:in `readpartial'
```

**Comment by JTronLabs** [comment]
same issue

**Comment by BigChief45** [comment]
I have this same issue. Any solutions yet?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.

Does this error occur in all environments (OS + ruby version), or just some?

A great start would be an example repo (based off a clean install) that exhibit this error.

**Comment by fxmountain** [comment]
Same problem

**Comment by sandstrom** [comment]
@fxmountain If you want to help fix this a great start would be an example repo (based off a clean install) that exhibit this error.

**Comment by fxmountain** [comment]
Can't reproduce it any more, but also switched to 4.2.1
