### ISSUE TITLE
Duplicated key Warning

### ISSUE THREAD

**Issue by matyus** [middleman/middleman#1742]
When I run a middleman server, everything works. However I get this warning:

```
== The Middleman is loading
/Users/me/.rvm/gems/ruby-2.2.1/gems/middleman-blog-4.0.0/lib/middleman-blog/blog_data.rb:170: warning: duplicated key at line 170 ignored: :lang
== Blog Sources: {year}-{month}-{day}-{title}.html (:prefix + :sources)
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"
```

Mac OSX El Capitan 10.11.2

**Comment by woodall** [comment]
I'm not sure but my thought is it's related to; `config.rb` or some frontmatter?

**Comment by matyus** [comment]
@woodall Yeah, I'm not sure, I closed the issue here and posted it in the /middleman-blog repo because I realize it's actually coming from the plugin and not middleman core.
