### ISSUE TITLE
environments/production.rb not working in 4.0.0

### ISSUE THREAD

**Issue by alshamma** [middleman/middleman#1748]
According to https://middlemanapp.com/basics/upgrade-v4/:
> Like Rails, we support automatically loading environment specific config from a predefined path. If you have a lot of production config, create a file at environments/production.rb and its contents will automatically be evaluated when in production.

I am unable to get this to work on my machine: OS X, El Capitan, middleman-cli 4.0.0. I expected to find the values in ENV. I also tried putting the file in config/environments/production.rb. 

I was hoping that other environments would work, too. E.g., staging.rb, development.rb.

**Comment by tdreyno** [comment]
All this does is only parse a specific ruby file when in a current environment. It has nothing to do with unix ENV variables.

So `config.rb` with `configure :production` is identical to a file `environments/production.rb`

**Comment by alshamma** [comment]
Just to clarify, am I correct in understanding that when configure :production is first encountered, that environments/production.rb will be executed? That seems to match my experiment just now. 

I see that environments/development.rb is also supported, though I don't see it in the docs. 

Thanks!
