### ISSUE TITLE
Inline SASS includes debug comments in production build

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1750]
Using the `master` branch code, I noticed that inline SASS results in code with the debug line-number comments in it, instead of minified CSS:

``` haml
:sass
  #googlebox
    padding: 10px
    background: white
    margin: auto
    border: 1px solid #ccc
    width: 450px
```

Results in:

``` html
<style>
  /* line 1, (__TEMPLATE__) */
  #googlebox {
    padding: 10px;
    background: white;
    margin: auto;
    border: 1px solid #ccc;
    width: 450px; }
</style>
```

 This is doubly confusing since I have `:minify_css` activated in my `build` configuration:

``` ruby
configure :build do
  activate :minify_css
end
```

So I would expect that comments would be stripped, as well as all that indentation.

**Comment by tdreyno** [comment]
Weird. The tests pass, so that's weird. What if you take it out of the `configure` block?

**Comment by tdreyno** [comment]
Is sprockets active?

**Comment by bhollis** [comment]
Should be

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets. I'd suggest closing this issue, and if the problem resurfaces a new issue can be opened in the middleman sprockets repo. Does that sound like a good next step @bhollis?

**Comment by wiesson** [comment]
> With Middleman 4 the external pipeline is preferred method for assets.

How would you deal with "inline-css" then? (I would like to load the core css for the first 1200px within <style></<style> tags to render to improve the loading time)

**Comment by sandstrom** [comment]
I think you can access [the resource](http://www.rubydoc.info/github/middleman/middleman/Middleman/Sitemap/Resource#source_file-instance_method) and then the underlying source file. Read from this source file and output the content within <style> tags.

**Comment by cbernaut** [comment]
Adding the following line to `config/application.rb` or `config/environments/{ENV}.rb` works for me:
`config.sass.quiet = true`
