### ISSUE TITLE
Asset host inappropriately inserted in inline JS

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1751]
I have `:asset_host` on, but it's a bit more aggressive with the `master` code.

`config.rb`:

```ruby
configure :build do
  activate :asset_host, host: 'http://benhollis.net'
end
```

Input (trimmed down a bit to relevant lines): 

```haml
:javascript
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + 
      '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
```

```html
<script>
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + 
      'http://benhollis.net/.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
```

You can see that the string `'.google-analytics.com/ga.js'` has been modified to `'http://benhollis.net/.google-analytics.com/ga.js'`, which breaks the script.

**Comment by bhollis** [comment]
Interesting, maybe it's not the asset host. On another page, I see the URL modified to `"http://benhollis.net/blog/2006/05/02/.google-analytics.com/ga.js"`. So it's inserting the full path before the URL!

**Comment by bhollis** [comment]
Thanks for knocking these out so quick!

**Comment by sandstrom** [comment]
We are using `public_suffix` (https://github.com/weppos/publicsuffix-ruby) for things like this. Just thought I'd let you know, don't know if it would have been useful in this case.

**Comment by tdreyno** [comment]
`.google.com` still passes public suffix :(

**Comment by sandstrom** [comment]
Are you sure? This is the output I get:

```ruby
# gem 'public_suffix'

PublicSuffix.parse('.google.com').as_json
#=> {"tld"=>"com", "sld"=>"google", "trd"=>""}

# other example (this is where it's useful)
PublicSuffix.parse('google.co.uk').as_json
#=> {"tld"=>"co.uk", "sld"=>"google", "trd"=>nil}
```

**Comment by tdreyno** [comment]
So, the code in question here is basically saying. If a string is a relative or root relative path, replace it. The problem is that "./file.png" and ".google.com" are both passing. There is a check to see if the string contains a domain (making it offsite and not replaceable), but both addressable and public suffix "fail" this (though I'm sure the spec is correct).

```
PublicSuffix.valid?('.google.com') #=> true
```

It really sure be false IMO.

**Comment by tdreyno** [comment]
but if I try to load that in Chrome it works, so it must be valid, just confusing

**Comment by bhollis** [comment]
Do we really want to mess with strings inside JavaScript?

**Comment by tdreyno** [comment]
Heh... ¯\_(ツ)_/¯

Can be turned off via config. The goal is for everything to be auto-magical, but it's a difficult goal.
