### ISSUE TITLE
New asset_host filter breaks asset_hash

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1752]
I have both `:asset_host` and `:asset_hash` on.

In one of my pages, I have this HTML:

```html
<img alt="Win Mini" id="image10" src="/blog/uploads/2006/04/winmac.jpg" />
```

What gets produced is this:
```html
<img alt="Win Mini" id="image10" src="http://benhollis.net/blog/uploads/2006/04/winmac.jpg" />
```

In 3.3, I get this:

```html
<img alt="Win Mini" id="image10" src="/blog/uploads/2006/04/winmac-2d7e54a7.jpg" />
```

The actual filename is the hashed one, `winmac-2d7e54a7.jpg`.

**Comment by bhollis** [comment]
Hm, on another page, it seems to fill out a relative URL into an abolute one. Before
```html
<img src="collapsibleamazon_screen.png" alt="An Example Screenshot of Collapsible Amazon" />
```

After:
```html
<img src="http://benhollis.net/blog/2006/11/30/updated-collapsible-amazon/collapsibleamazon_screen.png" alt="An Example Screenshot of Collapsible Amazon" />
```

**Comment by bhollis** [comment]
The same thing is happening for Javascript references - relative links are being turned into absolute links with a host included.

**Comment by tdreyno** [comment]
Seems like the correct result should be:

```
<img alt="Win Mini" id="image10" src="http://benhollis.net/blog/uploads/2006/04/winmac-2d7e54a7.jpg" />
```

Right? With the host and the hash?

**Comment by bhollis** [comment]
Yeah that seems best.

**Comment by tdreyno** [comment]
Ah, tests have this order:

```
activate :asset_hash
activate :asset_host, host: 'http://middlemanapp.com'
```

But reverse breaks, so I'll add tests for that.
