### ISSUE TITLE
Middleman-blog pagination not working with v4

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1753]
Let me know if I should file middleman-blog issues over in that repo - I'm starting here because it hasn't changed so I'm assuming the problem is on the middleman-core side.

I've noticed with the code in `master` that my blog no longer has pagination working for it. For example, the 2006 archive page shows 14 articles and no second page, even though my blog is configured to paginate (and there's a default page size of 10):

``` ruby

activate :blog do |blog|
  blog.prefix = "blog"
  blog.taglink = "category/:tag.html"
  blog.layout = "article"
  blog.summary_separator = /<!--more-->/
  blog.summary_length = nil

  blog.tag_template = "blog/tag.html"
  blog.calendar_template = "blog/calendar.html"
  blog.paginate = true
end
```

**Comment by bhollis** [comment]
Hmm, deeper pages are still being generated, though. I wonder if I need to update my pagination partial, too. Here it is now:

```haml
.paginate.btn-toolbar
  .btn-group
    - if defined?(prev_page) && prev_page
      = link_to '&#x25C0; Previous Page', prev_page, :class => 'archives btn btn-default'

    - if defined?(next_page) && next_page
      = link_to 'Next Page &#x25BA;', next_page, :class => 'archives btn btn-default'
```

Are `prev_page` and `next_page` not defined as locals anymore?

**Comment by tdreyno** [comment]
Pagination tests are currently broken on blog, so that may be it

**Comment by bhollis** [comment]
:+1: This and the performance stuff is the only thing left as regressions for my blogs. :tada:

**Comment by tdreyno** [comment]
Excellent. I think the perf stuff can be solved by a bit more caching... which introduces its own complexity, but that's life.

**Comment by bhollis** [comment]
Hmm, I pulled the latest from `master`, and now I'm getting 10 articles per page, and multiple pages are generated, but `prev_page` and `next_page` still aren't showing up as locals.

**Comment by bhollis** [comment]
At the time of rendering (when `Sitemap::Resource#render` is called), the locals seem correct:

```
PATH: blog/index.html
["paginate",
 "page_number",
 "num_pages",
 "per_page",
 "page_start",
 "page_end",
 "next_page",
 "prev_page",
 "page_articles",
 "articles",
 "blog_controller",
 :rack,
 :current_path]
```

But when I print out `methods` from my template, it's not there.

There *is* an instance variable called `@locs` that contains my locals though. Is that how it's supposed to work now?

**Comment by tdreyno** [comment]
This really should be getting caught by the tests around this: https://github.com/middleman/middleman-blog/blob/master/fixtures/paginate-app/source/index.html.erb#L13-L14

**Comment by bhollis** [comment]
A pertinent detail I missed - my pagination stuff is happening *in a partial*.

**Comment by tdreyno** [comment]
Whoa, partials weren't getting their parent locals. Nasty. Resolved.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

@bhollis Sorry that this has lingered for quite a while! Did the commit by @tdreyno work? If so, can this be closed?

**Comment by iwarner** [comment]
This is similar I think to my reference

https://github.com/middleman/middleman-blog/issues/320
