### ISSUE TITLE
Very slow to start preview server

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#1754]
Using the code from `master`, starting the preview server with `middleman server` takes ~45 seconds. Note that the LiveReload line gets printed at ~10s. My site isn't too big - a relatively small blog/personal site. Around 550 total files in source.

The same site using Middleman 3.3 takes less than 4s to start the server.

**Comment by bhollis** [comment]
Timings for `build` are also much slower:

Middleman `master` (4.1): 30s
Middleman 3.3: 18s

**Comment by tdreyno** [comment]
New asset_hash and host are SLOW. Are those on? I'll benchmark

**Comment by bhollis** [comment]
Yeah, both are on.

**Comment by tdreyno** [comment]
each one ads it's own parse step. Let me try consolidating those.

**Comment by tdreyno** [comment]
Gone down profiling rabbit hole. Asset Hash is a big bear, looking into it more now. Also, for some file types, they are being double rendered.

**Comment by tdreyno** [comment]
Massive speedup using `::Digest::SHA1.file` to hash binary files rather than running through rack middleware request

**Comment by tdreyno** [comment]
Did a bunch of perf work here today: https://github.com/middleman/middleman/tree/perf

One "feature" I might have to lose is allowing front matter in non-templates. So if you need it in a `text.txt` file, you'll have to add `.erb`

**Comment by tdreyno** [comment]
Can you benchmark against that branch?

**Comment by bhollis** [comment]
Sorry, I'll be able to try it out on Friday.

**Comment by bhollis** [comment]
For `build`, `master` was 32s, `perf` was 35s.

For `server`, both `master` and `perf` were ~45s.

**Comment by Tuckie** [comment]
@tdreyno would this change break the ability to sideload frontmatter to pdfs or other binary files? (Actually, does this even still work in 4? I'm still on 3.X)

**Comment by tdreyno** [comment]
@bhollis Any way I can debug on your setup? I was using my own blog as reference, but it was mostly micro optimizations.

**Comment by tdreyno** [comment]
@Tuckie That core functionality was removed in v4, but still tested for in the form of this extension: https://github.com/middleman/middleman/blob/master/middleman-core/fixtures/frontmatter-settings-neighbor-app/config.rb#L10-L40

**Comment by Tuckie** [comment]
@tdreyno awesome, thanks -- sorry for the sidetrack.

**Comment by bhollis** [comment]
I sent you a zip of my site, hopefully it's helpful for profiling.

**Comment by tdreyno** [comment]
Awesome, digging now :)

**Comment by Tuckie** [comment]
@tdreyno Sorry to take this off topic again, is there a clean way to activate / include [neighbor_frontmatter](https://github.com/middleman/middleman/blob/master/middleman-core/fixtures/frontmatter-settings-neighbor-app/config.rb#L10-L40), or do I just need to copy it into my project?

**Comment by tdreyno** [comment]
Copy it

**Comment by bhollis** [comment]
This has been fixed, at some point...
