### ISSUE TITLE
Page build speed very slow

### ISSUE THREAD

**Issue by eaigner** [middleman/middleman#1756]
We have a site with multiple locales (8 languages). This results in a lot of pages (~750 total) middleman needs to generate. With a page build speed of 300ms per page this almost grinds to a halt.

PS: Is there something that can be done out of the box to improve build times?

**Comment by tdreyno** [comment]
The `asset_host`, `asset_hash`, `cache_buster` and `relative_assets` extensions can dramatically slow rendering down. If you have those active, try benchmarking without. Otherwise, it tends to be a combination of Ruby being slow and disk I/O

**Comment by eaigner** [comment]
Unfortunately no extensions are active and its still that slow

**Comment by tdreyno** [comment]
@eaigner If there is any way for me to debug, I can try to help. Is this repo public or can you send me private access?

**Comment by tdreyno** [comment]
@eaigner I would love to take a shot at this before releasing 4.1.0 if you've got a way to get me a test case.

**Comment by eaigner** [comment]
Unfortunately I can't release the complete page, but I'll try to derive a test case if possible.

**Comment by tdreyno** [comment]
@eaigner I've been making changes this week that may help. Try running against `master` and see if there is any improvement

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! Did the suggestion by @tdreyno work? If so, can this be closed?
