### ISSUE TITLE
[Suggestion] Use "bot" like gordon the turtle to check for information required by guidelines

### ISSUE THREAD

**Issue by maxmeyer** [middleman/middleman#1758]
@tdreyno I'm not sure if you're a fan of github bots, like https://github.com/jfrazelle/gordon-bot or https://hubot.github.com/ or https://github.com/litaio/lita.

At least the docker one (gordon the turtle) is used to check - see https://github.com/GordonTheTurtle?tab=activity - if all required information is available in new github issues, that may reduce the amount of work on your side. I had a quick glance at lita but more for chatops style ops, but didn't implement such a thing myself. Just saw that huge amount of issues coming with the release of v4.

Maybe @bhollis has some experience in that area?

Example issue:
middleman/middleman-sprockets#62

Cheers
Dennis

**Comment by sandstrom** [comment]
@maxmeyer great suggestion! What steps would be needed to use this in the middleman repo? where would the bot run? how much work is it to maintain the bot?

Somewhat related, we added this (https://github.com/middleman/middleman/commit/ffef14deb48bdf18037675607fb2b501a4033203) a while bag, which may have helped some.
