### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by cllns** [middleman/middleman#1760]
Just noticed Middleman doesn't seem to have a Code of Conduct.

http://contributor-covenant.org/ seems like a good and popular option!

**Comment by cllns** [comment]
This issue is seems like it's being purposely ignored.

January 15th - I created this issue.
January 17th - @tdreyno [tweeted a link to this issue](https://twitter.com/tdreyno/status/688794030633693184) saying he's "going nowhere near this" and that it's an "Insta-drama-bomb". 

I'd like to keep this discussion organized by keeping it all in one place, rather than having it spread around to multiple Twitter threads.

**Comment by justincampbell** [comment]
:+1: Would love to feel good about continuing to use Middleman

**Comment by tdreyno** [comment]
Cool. Yeah. Leave me out of the drama please.
