### ISSUE TITLE
v4 Wrong contract?

### ISSUE THREAD

**Issue by GhostGambler** [middleman/middleman#1764]
This contract seems wrong:
https://github.com/middleman/middleman/blob/28a0071be7cffd12f4420998d4491158b9f1eabe/middleman-core/lib/middleman-core/core_extensions/i18n.rb#L187

The method does (and [apparently should](https://github.com/middleman/middleman/blob/28a0071be7cffd12f4420998d4491158b9f1eabe/middleman-core/lib/middleman-core/core_extensions/i18n.rb#L84) be able to) return `nil` sometimes, which is prohibited by the current contract:

> Contract violation for return value: Expected: String, Actual: nil Value guarded in: Middleman::CoreExtensions::Internationalization::localized_path With Contract: String, Symbol => String At: /Users/xyz/middleman/middleman-core/lib/middleman-core/core_extensions/i18n.rb:194

**Comment by tdreyno** [comment]
Thanks
