### ISSUE TITLE
git clone result check is bogus, results in misleading error message

### ISSUE THREAD

**Issue by danielkasza** [middleman/middleman#1765]
`middleman init` clones a git repository into a temporary directory and verifies the result by checking if the directory exists:

````
        run("git clone --depth 1 #{branch_cmd}#{repo_path} #{dir}")

        unless File.directory?(dir)
          say 'Git clone failed, maybe the url is invalid or you don\'t have the permissions?', :red
          exit 1
        end
````

This check, however, is broken because the temporary directory was created using `Dir.mktmpdir`, so the directory will exist and the check will pass even if the git clone failed.

This results in a very misleading error message:

````
$ middleman init
         run  git clone --depth 1 git://github.com/middleman/middleman-templates-default.git /tmp/d20160118-29533-192e1ht from "."
       exist  
         run  bundle install from "."
Could not locate Gemfile or .bundle/ directory
````

I think it would also make sense to add "git not installed" to the list of possible reasons.

**Comment by tdreyno** [comment]
Good idea, I'm going to borrow Bundler's: bundler github private repo
