### ISSUE TITLE
Config setting in config.rb

### ISSUE THREAD

**Issue by iwarner** [middleman/middleman#1768]
Hiya

Just trying an upgrade to V4 test

I used to be able to set in config.rb
    set :dataConfig, data.config

I am now getting complaints about this.

**Comment by tdreyno** [comment]
What's the complaint?

**Comment by iwarner** [comment]
That in V4 this does not now work :)

in config.rb
    set :dataConfig, data.config

in index.html.haml
    = dataConfig

Error produced
    undefined local variable or method `dataConfig' 

So basically question is how do I now set global variables in the config.rb that can be used throughout the templates.

Many thanks

**Comment by tdreyno** [comment]
use `config[:dataConfig]` in templates in v4.
