### ISSUE TITLE
Thread.exclusive is deprecated, use Mutex

### ISSUE THREAD

**Issue by kaishiro** [middleman/middleman#1769]
Ruby 2.3.0 / Middleman 4.0.0

Upon running a `bundle exec middleman` I'm getting the following trace: https://gist.github.com/kaishiro/efb89d80891bd28bd8f3

Site is served fine locally, any file modifications fire additional warnings/traces.

Warnings aren't present in Ruby 2.3.0 / Middleman 3.4.1

**Comment by tdreyno** [comment]
This is already fixed on master, will be out in v4.1.0 soon

**Comment by marnen** [comment]
It's not in 4.1.14, certainly. Will try 4.2.

**Comment by marnen** [comment]
Wait, there it is. It's in the middleman-livereload gem: https://github.com/middleman/middleman-livereload/pull/85. Will try upgrading that one.
