### ISSUE TITLE
MIDDLEMAN: “$ middleman init my_new_project” not working (screenshot attached)

### ISSUE THREAD

**Issue by suresh44t** [middleman/middleman#1773]
I just installed Ruby and Middleman for the first time and I cannot get past the very first "$ middleman init my_new_project" step. I have tried Googling for solution to my problem but unfortunately I couldn't find anything that looks like the error I'm encountering.

I hope someone can help me out.

OS: Windows 8 | Ruby: 2.2.3 (x64) (tried Ruby 2.1.7 first) | Middleman: 4.0.0

This is the error message I'm getting when I try to create a new project in a folder I created to try out Middleman:

run git clone --depth 1 git://github.com/middleman/middleman-templates-default.git C:/Users/Lenovo/AppData/Local/Temp/d20160120-1612-c2sqbk from "."
    exist new_project_test
      run bundle install from ".new_project_test"
Could not locate Gemfile or .bundle/ directory

This just creates an empty "new_project_test" folder.

**Comment by tdreyno** [comment]
Do you have `git` installed?

**Comment by kofude** [comment]
Hi team, I'm about to learn using middlemman ... and I've got an error. Thank you for any help.
I'm using Git bash (Git-2.7.1.2-64-bit.exe) linked to bitbucket with ssh
Here are lines of my output:

kofude@TOSHIBA-L850-W7 MINGW64 /d/myGitRepo/myMiddleman (master)
$ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

kofude@TOSHIBA-L850-W7 MINGW64 /d/myGitRepo/myMiddleman (master)
$ middleman init adse
         run  git clone --depth 1 git://github.com/middleman/middleman-templates-default.git C:/Users/kofude/AppData/Local/Temp/d20160221-3088-969jm4 from "."
Cloning into 'C:/Users/kofude/AppData/Local/Temp/d20160221-3088-969jm4'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 22 (delta 0), reused 14 (delta 0), pack-reused 0
Receiving objects: 100% (22/22), 6.07 KiB | 0 bytes/s, done.
Checking connectivity... done.
       exist
      create  C:/Users/kofude/AppData/Local/Temp/d20160221-3088-969jm4/template/.gitignore
C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Invalid argument @ dir_s_mkdir - D:/myGitRepo/myMiddleman/adse/C: (Errno::EINVAL)
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:210:in `each'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:61:in `block in invoke!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:92:in `block in execute!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:80:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:80:in `execute!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:66:in `invoke!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:52:in `directory'
        from C:/Users/kofude/AppData/Local/Temp/d20160221-3088-969jm4/Thorfile:10:in `copy_default_files'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.1/lib/middleman-cli/init.rb:77:in `block in init'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:184:in `block in inside'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:127:in `chdir'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:184:in `inside'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.1/lib/middleman-cli/init.rb:71:in `init'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.1/bin/middleman:23:in `<top (required)>'
        from C:/Ruby22/bin/middleman:22:in `load'
        from C:/Ruby22/bin/middleman:22:in `<main>'
--end

**Comment by kofude** [comment]
A more word:
middleman (4.1.1, 4.0.0)
middleman-cli (4.1.1, 4.0.0)
middleman-core (4.1.1, 4.0.0)

**Comment by tdreyno** [comment]
What kind of terminal is this? I see you `cd` to `/d/` which then later maps to `D:/`?

Basically, MM downloads a copy of the template to your local temp directory, which seems to be on `C:/` then tries to copy to your requested designation on `D:/`. It kind of feels like the system is masquerading at Unix, so it gets confused by this "target path": `D:/myGitRepo/myMiddleman/adse/C:`

**Comment by joelugwu** [comment]
**I have the same issue.**
Here is my system configuration:
- Windows 7
- Ruby Installer 2.2.4 (I have tried 32 and 64 bit)
- Middleman 4.1.1
- Git Bash terminal (git version 2.7.1)

Is there a workaround that could be used for those having trouble with `middleman init` in a Windows environment?

**Comment by tdreyno** [comment]
`git clone https://github.com/middleman/middleman-templates-default.git` should work too

**Comment by sileomahony** [comment]
I am having the same problem. I am using Windows 10, ruby 2.2.5p319, rubygems 2.6.8, and middleman 4.1.10.  And using Git Bash.
I notice that I am also getting a funky path when it tries to make the dir. Did anyone figure out how to get this working?

Any help appreciated, thanks!

```
exco 41@DESKTOP-Q22AI8R MINGW64 ~
$ middleman init new_project
         run  git clone --depth 1 https://github.com/middleman/middleman-templates-default.git C:/Users/EXCO41~1/AppData/Local/Temp/d20161102-15196-43n1nd from "."
Cloning into 'C:/Users/EXCO41~1/AppData/Local/Temp/d20161102-15196-43n1nd'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 22 (delta 0), reused 14 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), done.
       exist
      create  C:/Users/exco 41/AppData/Local/Temp/d20161102-15196-43n1nd/template/.gitignore
C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Invalid argument @ dir_s_mkdir - C:/Users/exco 41/new_project/C: (Errno::EINVAL)
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:210:in `each'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:61:in `block in invoke!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:92:in `block in execute!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:80:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:80:in `execute!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:66:in `invoke!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:52:in `directory'
        from C:/Users/EXCO41~1/AppData/Local/Temp/d20161102-15196-43n1nd/Thorfile:10:in `copy_default_files'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.10/lib/middleman-cli/init.rb:77:in `block in init'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:184:in `block in inside'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:127:in `chdir'
        from C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:184:in `inside'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.10/lib/middleman-cli/init.rb:71:in `init'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.10/bin/middleman:72:in `<top (required)>'
        from C:/Ruby22/bin/middleman:22:in `load'
        from C:/Ruby22/bin/middleman:22:in `<main>'

```

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I think things are working as intended, and that this issue can be closed. Feel free to disagree and if so a PR with a failing test plus a fix would be a great start.
