### ISSUE TITLE
Sass Source Maps

### ISSUE THREAD

**Issue by reneruiz** [middleman/middleman#1775]
Is this feature working or am I doing something wrong? `__middleman/config/` reports `:sass_source_maps = true`, but I can't seem to find any maps being generated?

**Comment by tdreyno** [comment]
They should be inline at the bottom of the generated CSS

**Comment by reneruiz** [comment]
Hey tdreyno, thanks for the response! So that was the first place I had looked, but I don't see them in there. Here's a [gist](https://gist.github.com/reneruiz/f0b30c63b53301883ab8) of how I have my Middleman setup.

**Comment by tdreyno** [comment]
@reneruiz By default, sourcemaps are only enabled during the dev server, not the build mode. Is that output CSS from server or build?

**Comment by reneruiz** [comment]
That's copy pasted from Chrome during 'middleman server'.

--
Rene




On Sun, Jan 24, 2016 at 12:20 PM -0800, "Thomas Reynolds" <notifications@github.com> wrote:












@reneruiz By default, sourcemaps are only enabled during the dev server, not the build mode. Is that output CSS from server or build?

**Comment by tdreyno** [comment]
Ah, this is likely because you are using Sprockets, which does not support source maps. If you remove that gem, it should work.

**Comment by reneruiz** [comment]
That was it, thank you!
