### ISSUE TITLE
asset_host prefixes javascript functions breaking the build

### ISSUE THREAD

**Issue by adam-h** [middleman/middleman#1780]
The asset_host extension detects `jQuery.css` (amongst others) as a URL and prefixes it :(

Input:

```
var a = jQuery.css("h1", "font-size");
console.log(a);
```

Output:

```
var a = //myprefix.cloudfront.net/javascripts/jQuery.css("h1", "font-size");
console.log(a);
```

Config:

```
activate :asset_host,
  host: "//myprefix.cloudfront.net"
```

Looks to be an issue with the regex [here](https://github.com/middleman/middleman/blob/c7a46181664bf47e5dd149932d2f0302e212030a/middleman-core/lib/middleman-core/util.rb#L344) not working correctly for JS files (it should only affect strings)

Example repo: https://github.com/adam-h/middleman-4-asset-host-bug
Example output JS: https://github.com/adam-h/middleman-4-asset-host-bug/blob/master/build/javascripts/all.js#L1

**Comment by tdreyno** [comment]
Thanks for reporting. I think I need to separate the regex for CSS (does not require quotes) with the JS regex.

**Comment by tdreyno** [comment]
See if that helps

**Comment by adam-h** [comment]
@tdreyno Yup that works! Thanks for the swift fix (again) :)

**Comment by djiqwy** [comment]
Hi @tdreyno 

This problem still exists :(

Before (jQuery.js)

```
(o+=J.css(e,n+_e[a],!0,r))
```

After:

```
(//cdn.example.com/javascripts/o+=J.css(e,n+_e[a],!0,r))
```

Config:

```
activate :asset_host, host: '//cdn.example.com'
```

Gemfile:

```
gem 'middleman', '>= 4.1.6'
gem 'middleman-sprockets', '4.0.0.rc.1'
```

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets. I'd suggest closing this issue, and if the problem resurfaces a new issue can be opened.
