### ISSUE TITLE
Can't see nor use installed gems

### ISSUE THREAD

**Issue by osabate** [middleman/middleman#1786]
I'm using the following RoR configuration and Middleman 3:

```
- RUBYGEMS VERSION: 2.2.2
- RUBY VERSION: 2.0.0 (2014-05-08 patchlevel 481) [x86_64-darwin13.1.0]
- INSTALLATION DIRECTORY: /Users/user/.rvm/gems/ruby-2.0.0-p481@middleman
- RUBY EXECUTABLE: /Users/user/.rvm/rubies/ruby-2.0.0-p481/bin/ruby
- EXECUTABLE DIRECTORY: /Users/user/.rvm/gems/ruby-2.0.0-p481@middleman/bin
- SPEC CACHE DIRECTORY: /Users/user/.gem/specs
- RUBYGEMS PLATFORMS:
  - ruby
  - x86_64-darwin-13
- GEM PATHS:
   - /Users/user/.rvm/gems/ruby-2.0.0-p481@middleman
   - /Users/user/.rvm/gems/ruby-2.0.0-p481
   - /Users/user/.rvm/gems/ruby-2.0.0-p481@global
- GEM CONFIGURATION:
   - :update_sources => true
   - :verbose => true
   - :backtrace => false
   - :bulk_threshold => 1000
- REMOTE SOURCES:
   - https://rubygems.org/
- SHELL PATH:
   - /Users/user/.rvm/gems/ruby-2.0.0-p481@middleman/bin
   - /Users/user/.rvm/gems/ruby-2.0.0-p481@global/bin
   - /Users/user/.rvm/rubies/ruby-2.0.0-p481/bin
   - /Users/user/.rvm/bin
   - /usr/local/bin
   - /usr/bin
   - /bin
   - /usr/sbin
   - /sbin
   - /Users/user/.rvm/bin
   - /Users/user/.rvm/bin
```

I run bundle install, `middleman build / server` and I don't get any errors. Yet when I install gems like `zurb-foundation` or `font-awesome-middleman` via the `gemfile`, I can't access nor embed their source files in my project.

I've already edited my `.bashrc` file (@middleman gemset). And when I execute `rvm @middleman do gem list gem list` looks good as well. Nonetheless I can't figure out what it is wrong with my configuration.

Any help would be greatly appreciated. Thanks

**Comment by tdreyno** [comment]
What is RoR?

Have you tried requiring those gems in `config.rb`? Bundler usually does this automatically, but might help.

In what way are you embedding the assets in your project? Sprocket `//= require`?

**Comment by osabate** [comment]
Thanks Thomas for your quick response. RoR = Ruby on Rails.

Gems are included on the `.config.rb` and bundler installs them well (no errors) but can't see them on my local repository. 
For example, `font-awesome` or `foundation` source files don't show under assets, and thus can't include nor require them anywhere.

Hope it makes sense.

**Comment by tdreyno** [comment]
Those are gems, so their contents will be inside their gems (usually shared across all projects on your system). If you want them to appear in your Middleman build, you need to include them. Here's an example of someone using foundation with Middleman: http://blachniet.com/blog/middleman-foundation/

**Comment by osabate** [comment]
I'm using middleman 3, thus traditional asset pipeline. This example uses Bower, etc.

I know gems are being installed in the gemset path but still I should be able to see them in my project directory, right?

Right now I'm importing these CSS libraries under my `main.sass.css` file but obviously nothing loads:
```
@import "normalize"
@import "foundation"
```

It has to be something stupid but can't figure out what it is, and I've already spent few hours in this.

Thanks Thomas!

**Comment by tdreyno** [comment]
Asset gems will not appear in your project unless imported. But, since you have those imports, it should be working.

That said, Foundation abandoned Gems for Bower a very long time ago, so it may simply no longer work for that specific gem.

Are there any errors when you try to import those missing items?

**Comment by osabate** [comment]
Alright, I'm very close but haven't figured it out yet.
This is the error I get when trying to import `foundation`. By the way, I can import `font-awesome` successfully but not this one. So that means environment is well setup.

I'm using this one: [zurb-foundation](https://rubygems.org/gems/zurb-foundation) v.4.3.2 and I've run bundle show gem and it shows. Also navigated to it and all files are in place.

Again, thanks very much for looking into this :-) It's been quite frustrating..

```
Error Compiling CSS asset
Sass::SyntaxError: File to import not found or unreadable: foundation.
Load paths:
  /Users/oriolsabate/code/middleman/porta/source/stylesheets
  /Users/oriolsabate/.rvm/gems/ruby-2.0.0-p481@middleman/gems/compass-core-1.0.3/stylesheets
  Compass::SpriteImporter
  (in /Users/oriolsabate/code/middleman/porta/source/stylesheets/main.css.scss:9)"
``

**Comment by tdreyno** [comment]
That gem is 3 years old and Foundation is currently on version 6 :)

Investigating now, it looks like Foundation never used the same folder layout that Sprockets expects, so it  has some hacks in it's main file.

Try these:

```
require 'zurb-foundation'
require 'foundation/sprockets'
```

**Comment by osabate** [comment]
Yeeeesss!! It works!

So this is how my gemfile looks like now.
```
gem "zurb-foundation", "~> 4.3.2"
...
require 'zurb-foundation'
require 'foundation/sprockets'
```

I would've used the latest version of foundation but this is how far this gem gets and I'm working on an old project.

By the way, how did you debug this? How did you come up with this answer?

Greatly appreciated Thomas! :+1:

**Comment by tdreyno** [comment]
We used to use foundation on the Middleman docs site. I just happened to know the specific weirdness of this gem :)

**Comment by osabate** [comment]
:+1:
