### ISSUE TITLE
Can't run middleman init 

### ISSUE THREAD

**Issue by hebasmit** [middleman/middleman#1788]
Hey guys,

I am having issues with the `middleman init` command here is the stack trace

```
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.1/lib/middleman-core/load_paths.rb:25:in `join': no implicit conversion of false into String (TypeError)
    from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.1/lib/middleman-core/load_paths.rb:25:in `setup_bundler'
    from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.1/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
    from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.1/bin/middleman:10:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.3.0/bin/middleman:23:in `load'
    from /usr/local/var/rbenv/versions/2.3.0/bin/middleman:23:in `<main>'
```

any help would be much appreciated.

**Comment by tdreyno** [comment]
Can you post the full init command you used?

It looks like the folder the middleman command is being run in does not have a `Gemfile`

**Comment by jtara** [comment]
I have the same problem. I'm trying to update a project from version 3.0.11. No, there is no Gemfile.

How does one start-up a fresh project, then? There seems to be a Catch-22:


>Gemfile
Middleman will respect a Bundler Gemfile for specifying and controlling your gem dependencies. When creating a new project, Middleman will generate a Gemfile for you which specifies the same version of Middleman you are using.

**Comment by jtara** [comment]
FYI, `middleman init` will work on an empty directory. So, it only seems a problem when updating from 3.x.

**Comment by jtara** [comment]
Oh, oh, oh... Middleman installed a bunch more Gems during init... Not sure I like that! Maybe it's always done that, it's been quite a while...

Is there any general guide to upgrading? I've read "upgrading", but that really just lists the differences, rather than guiding about what has to be changed.

The bug here is that Middleman 4.x will utterly fail if started-up in a 3.x directory. You can't even get `-help`.

**Comment by tdreyno** [comment]
@jtara So you updated Gemfile to point to MM 4 and ran `bundle exec middleman server`?

**Comment by jtara** [comment]
I didn't have a Gemfile.

**Comment by tdreyno** [comment]
It should use the current directory

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I think things are working as intended, and that this issue can be closed. Feel free to disagree and if so a PR with a failing test plus a fix would be a great start.
