### ISSUE TITLE
Can't install gem.

### ISSUE THREAD

**Issue by tylerrollins** [middleman/middleman#1793]
I am trying to install middleman, I have x-code select installed, but I get an error each time I try to install the gem. I installed several other gems around the same time with no problems. The only error I receive is from running 'gem install middleman'. I tried several times, each with the same result - 

$ gem install middleman

$  ERROR:  While executing gem ... (URI::InvalidURIError)
    bad URI(is not URI?):

**Comment by tdreyno** [comment]
Looks like your internet was down?

**Comment by tylerrollins** [comment]
No, internet was definitely up, as I installed other gems and searched online for help articles related to error.

I just tried again, and what do ya know... success! Everything is installed correctly now, just curious as to what was causing the issue, and why it magically works as normal again. 

Thanks for such a quick response though!
