### ISSUE TITLE
middleman init my_project

### ISSUE THREAD

**Issue by robotwholearned** [middleman/middleman#1795]
```
$ - middleman init
         run  git clone --depth 1 git://github.com/middleman/middleman-templates-default.git /var/folders/g2/sdqs4vnj6jncrfk24x_t02fnwb5pz4/T/d20160205-77888-1b5lmo from "."
Cloning into '/var/folders/g2/sdqs4vnj6jncrfk24x_t02fnwb5pz4/T/d20160205-77888-1b5lmo'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Connection refused

Git clone command failed. Make sure git repository exists: git://github.com/middleman/middleman-templates-default.git
```
That is the error message I received everytime I tried to init a new project. I was able to curl and visit the page to verify its existence, but the only way I was able to genrereate a new project using init.rb was to run: 
`middleman init https://github.com/middleman/middleman-templates-default`

The ability to switch what method is used to reach the template files would be useful.

**Comment by robotwholearned** [comment]
I had a case of the dumbs, not even remotely, was any of this happening

**Comment by tdreyno** [comment]
Ha, nice. Glad it worked out :)
