### ISSUE TITLE
Localizing paths and links with i18n and directory_indexes (v4.1.1)

### ISSUE THREAD

**Issue by sn3p** [middleman/middleman#1798]
This is almost a duplicate of https://github.com/middleman/middleman/issues/1587, from when I was using `v3.4.0`.
Now I'm giving this another try in `v4.1.1`, but still can't get it to work properly ;(

The actual pages are translated correctly, but the `link_to` and `url_for` output is not.
I've created a new project to test this.

**config.rb**

``` rb
activate :directory_indexes
activate :i18n, mount_at_root: :en, langs: [:en, :nl]
```

(also tried activating `i18n` first)

**locales/nl.yml**

``` yml

---
nl:
  paths:
    welcome: welkom

  welcome: Welkom
```

**localizable/index.html.erb**

``` erb
<%= link_to t("welcome"), "/welcome.html" %>
<%= url_for "/welcome.html" %>
```

output (`http://localhost:4567/nl`):

``` html
<a href="/welcome/">Welkom</a>
/welcome/
```

expected:

``` html
<a href="/nl/welkom/">Welkom</a>
/nl/welkom/
```

**Without `directory_indexes` paths are correctly translated unless they have hashes or params**:

```
<%= url_for "/welcome.html" %>
<%= url_for "/welcome.html#foo" %>
<%= url_for "/welcome.html?foo=bar" %>
```

output (`http://localhost:4567/nl`):

``` html
/nl/welkom.html
/welcome.html#hash
/welcome.html?foo=bar
```

(Paths with hashes or params do work when I remove the `paths` translations)

All a bit confusing... Am I overlooking something or is this a bug?

**Comment by tdreyno** [comment]
This looks like a combo of bugs. Thank you for the fantastic test cases. I'll get this fixed up soon.

**Comment by sn3p** [comment]
Thanks, looking forward to it!

For your information, this does work:
```rb
link_to t("menu.pricing"), extensions[:i18n].localized_path("/pricing.html", I18n.locale)
url_for extensions[:i18n].localized_path("/pricing.html", I18n.locale)
```

But breaks when using hashes or params.

**Comment by slash7** [comment]
Looks like still not fixed on v4.1.10.
Any news on this ?

**Comment by joallard** [comment]
Related to #1466

**Comment by andreamoro** [comment]
Not sure I'm late here, but why don't you use the paths: (for the i18n).

Simply add your locale language file, then something like this:

en.yml
\_ paths:
    \___something: "name-of-your-local-page"

it.yml
\_ paths:
    \___something: "il-nome-della-pagina"

Then get access to the page name as t(:paths)[:something]
