### ISSUE TITLE
Middleman puts the raw Stylus file in the build

### ISSUE THREAD

**Issue by sebastianbarfurth** [middleman/middleman#1800]
I'm using the external asset pipeline to have Stylus compiled by Gulp instead of Middleman, which works wonky in testing but it works (BrowserSync doesn't work quite right, it requires double, sometimes triple saving the file).

So now that works alright and I'm trying to build, but Middleman is putting ``site.styl`` in ``build/stylesheets``. I have no idea why, Middleman shouldn't even mess with stylesheets anymore as Gulp does all the stylesheet work.

How can I fix this?

**Comment by tdreyno** [comment]
```
ignore "*.styl"
```

**Comment by sebastianbarfurth** [comment]
Thanks!
