### ISSUE TITLE
Including vendored assets in extensions

### ISSUE THREAD

**Issue by johanhalse** [middleman/middleman#1801]
Hi,

I created [an extension](https://github.com/varvet/middleman-scavenger) a couple of months ago. It watches a directory full of SVG files for changes and builds a sprite sheet that makes the svg:s available with some easy helpers. Updating to Middleman 4 breaks my extension and I'm trying to fix it!

My gem comes bundled with a JS file that async loads the sprite and inserts it into the `<body>` element. This used to live in `assets/javascripts/middleman-scavenger.js.erb` so the user could just do

```
//= require middleman-scavenger
```

and everything would work fine. It doesn't anymore - that require just shows up as a comment in all.js now that the asset pipeline is gone. How do I make my extension's JS available for inclusion?

**Comment by stevenosloan** [comment]
Hey @johanhalse, I've been working through some similar things. I added an example of a sprockets asset to my [external_resource_test](https://github.com/stevenosloan/middleman_external_resource_test). Hopefully that's helpful.

In testing it looks like the only thing you need to do is add that path for sprockets (you'll need to include the middleman-sprockets gem in your Gemfile for 4.x projects)

```ruby
# in config.rb
sprockets.append_path YOUR_PATH

# or an extension
def after_configuration
  # ...
  app.extensions[:sprockets].environment.append_path YOUR_PATH
  # ...
end
```

**Comment by tdreyno** [comment]
Yeah, the difficulty here is that most sprockets gems add explicit support for Rails, but never tell us that they exist.

**Comment by johanhalse** [comment]
Thank you @stevenosloan, the js file loads now. But the context seems to have changed. I'm accessing a helper inside my js file and that's not available anymore. The helper is defined in my extension like so:
```
helpers do
  def scavenger_sprite_path
    image_path external_sprite_path
  end
end
```
That works inside a normal html.erb file in middleman, but not in the required js file. Any idea why? I've played around a bit in pry and the helpers aren't available. Typing `app.helpers` gets me this error:
```
[10] pry(#<#<Class:0x007facecb40550>>)> app.helpers
NoMethodError: undefined method `helpers' for #<Middleman::Application:0x70190334427600>
```

**Comment by stevenosloan** [comment]
I think this is related to a change where helpers are now just added to templating context instead of the entire application [[here](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/extension.rb#L369-L371)]. So to me, it feels like a bug in middleman-sprockets -- @tdreyno what do you think? should that template_context get passed along to sprockets as well? (I think I've got a handle on what needs to be done, so can work on a PR if you agree)

**Comment by tdreyno** [comment]
I'm not sure what chaos sharing a context between sprockets and middleman might cause, but if you've got a good handle on it, that'd be great.

**Comment by johanhalse** [comment]
@stevenosloan are you on this? Or could you maybe point me in the general direction of what needs to be done?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets, and this seems to stem from sprockets.

I'd suggest closing this issue, and if the problem resurfaces (or still exist) a new issue can be opened in the [middleman sprockets repo](https://github.com/middleman/middleman-sprockets/).
