### ISSUE TITLE
Serve, build and deploy localized website separately

### ISSUE THREAD

**Issue by sn3p** [middleman/middleman#1802]
#### What the best way to serve, build and deploy translated websites separately?

Our website is translated in three languages which are deployed on separate domains:

`en` to www.learningspaces.io
`nl` to www.learningspaces.nl
`de` to www.learningspaces.de

At the moment we serve and build our localized websites using `-e` environment flags:

```bash
bundle exec middleman -e en
bundle exec middleman -e nl
bundle exec middleman -e de

bundle exec middleman build -e en
bundle exec middleman build -e nl
bundle exec middleman build -e de
```

**config.rb:**
```rb
# middleman -e en
configure :en do
  activate :i18n, langs: [:en]
end

# middleman -e nl
configure :nl do
  activate :i18n, langs: [:nl]
end

# middleman -e de
configure :de do
  activate :i18n, langs: [:de]
end
```

Is there a better way or convention for doing this with Middleman?

#### Can I somehow get translations from locales that are not loaded?

I would like to have language selector on all are pages, that link to the translated version of the page.
For example, on `learningspaces.io/welcome` I'd like a link to `learningspaces.nl/welkom`.
Normally this would work like this:

```rb
link_to t("menu.pricing", locale: :nl), "/pricing.html", locale: :nl
```
But since we're building our localized websites separately (see Question 1) this is not possible because i18n is not activated with the `:nl` locale:

```
activate :i18n, langs: [:en]
```

Is there any way to fetch translations from locales without building them?

**Comment by sandstrom** [comment]
Put something like this in a rake task called `build_all`:

```ruby
['gb', 'de', 'nl'].each do |country_code|
    env_variables = { 'COUNTRY' => country_code, 'BUILD_DIR' => "#{BUILD_DIRECTORY}/#{country_code}" }
    system(env_variables, "middleman build")
  end
```

Then make the languages adjustments (and other adjustments) based on the country code. Similarly, you'll override the build directory with `set :build_dir, (ENV['BUILD_DIR'] || 'build')`.

**Comment by sn3p** [comment]
Thanks your suggestions were very useful 👍
