### ISSUE TITLE
Should data_for_path only allow returning hashes?

### ISSUE THREAD

**Issue by stevenosloan** [middleman/middleman#1803]
Starting to look at 4.1 compat for middleman-data_source, and I think I found a case of a contract that's a bit too constrained (see [this failing build](https://travis-ci.org/stevenosloan/middleman-data_source/builds/108911334), w/ `CONTRACTS=false` everything is peachy).

The contract in question is for [`data_for_path`](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/core_extensions/data.rb#L151), it's expecting a return of Hash or nil, although I think array, string, integer would all be valid possibilities. (really any "data" type, not sure what a good list of that would be).

Local data that as far as I can tell is always coming from [`method_missing`](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/core_extensions/data.rb#L166) doesn't have that same constraint.

**Comment by tdreyno** [comment]
Hmm, all that data is from front matter so it's always a Hash. Are you side-loading arrays from somewhere. I can see making this more permissive, but I'd like to know what the 3rd party extensions are doing

**Comment by stevenosloan** [comment]
Yeah, adding data callbacks for things -- but I would think it'd be possible to get other types as well with local data (at least arrays). If you had a file in data like:

```yaml
# data/foo.yaml
- one
- two
- three
```

Then `data.foo`, would return `['one', 'two', 'three']`

**Comment by tdreyno** [comment]
Cool, then sure, get me a PR to loosen the Contract and I'm cool with that.
