### ISSUE TITLE
'middleman init' fails to get files from git

### ISSUE THREAD

**Issue by paulgeisler** [middleman/middleman#1804]
This is the process and error message:

```
$ middleman init
         run  git clone --depth 1 git://github.com/middleman/middleman-templates-default.git /var/folders/0p/_5091nq53ms_9gkhyv56nffw0000gp/T/d20160213-85963-7vxwcs from "."
Cloning into '/var/folders/0p/_5091nq53ms_9gkhyv56nffw0000gp/T/d20160213-85963-7vxwcs'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Operation timed out

Git clone command failed. Make sure git repository exists: git://github.com/middleman/middleman-templates-default.git
```

**Comment by paulgeisler** [comment]
I guess it's the no-so-correct url in the process.

This workaround helped me to solve the problem:

Backup your `~/.gitconfig` and run this in your terminal

`git config --global url."https://github.com".insteadOf git://github.com`

It will modify your `~/.gitconfig` by adding this lines:

```
[url "https://github.com"]
	insteadOf = git://github.com
```

**Comment by kidwm** [comment]
so it does not support SSH?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I think things are working as intended, and that this issue can be closed. Feel free to disagree and if so a PR with a failing test plus a fix would be a great start.
