### ISSUE TITLE
Less stylesheets doesn't work in 4.1

### ISSUE THREAD

**Issue by morgoth** [middleman/middleman#1806]
I'm trying to update to latest middleman (previously on 3.3.12) and my less stylesheets are not working.
I have `less` gem in Gemfile and when I request `stylesshets/application.css` it cannot be found.
When I create `application.css` file then it's loaded properly.
What should I do to make less work? It was working fine on 3.3.x

**Comment by tdreyno** [comment]
So, you have a `stylesheets/application.css.less`, correct?

**Comment by morgoth** [comment]
No, I was having `application.less` after adding `.css` something is working, but now I'm getting error from middleman-sprockets gem - I'll dig more and eventually open issue there. Thanks
