### ISSUE TITLE
Bower components - replace sprockets

### ISSUE THREAD

**Issue by iwarner** [middleman/middleman#1811]
Hiya

As per the docs I am trying to replace

```
sprockets.append_path File.join( root, "bower_components" )
```

with 

```
import_path File.expand_path( 'bower_components', root )
```

unfortunately this does not seem to work as expected

**Comment by tdreyno** [comment]
What is your expectation?

**Comment by iwarner** [comment]
Sorry I am always useless at writing decent issues. I will strive to get better.

Ok - before with sprockets we could add an include path so shortcut to the bower_components folder.

That bower_components would become part of the include path, so calling : 
//= require bootstrap-sass-official/assets/javascripts/bootstrap-sprockets
Would work when calling in the required JS or CSS file

so assumption from the middleman guides of 
import_path File.expand_path( 'bower_components', root ) was that it would do the same

Thread on forum about it : https://forum.middlemanapp.com/t/import-a-scss-file-in-bower-components-folder-using-middleman-4/2011

**Comment by iwarner** [comment]
Here it is in the migration guide:

External Tools
We want to support as many possible tools as we can. Want to run Grunt? Maybe ClojureScript JVM in the background? How about browserify or ember-cli? That's what the goal of external_pipeline is. Here's an example of how Middleman v4 can control an external process, which outputs into an arbitrary directory and is then consumed by Middleman:

https://middlemanapp.com/basics/upgrade-v4/

activate :external_pipeline,
  name: :ember,
  command: "cd test-app/ && ember #{build? ? :build : :serve} --environment #{config[:environment]}",
  source: "test-app/dist",
  latency: 2

This feature is hosted on top of a lower-level feature which allows multiple directories to be overlaid to create the combined sitemap for Middleman. This is great for keeping things like bower_components separate from your source directory, but still available to Middleman:

import_path File.expand_path('bower_components', app.root)

**Comment by tdreyno** [comment]
`import_path` will add it to your project, but will not replace the inclusion or dependency management portions of Sprockets. For that, `<%= partial` should be used to include the newly imported files.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets, and this seems to stem from sprockets.

I'd suggest closing this issue, and if the problem resurfaces (or still exist) a new issue can be opened in the [middleman sprockets repo](https://github.com/middleman/middleman-sprockets/).
