### ISSUE TITLE
Kramdown link_to issue

### ISSUE THREAD

**Issue by zslabs** [middleman/middleman#1812]
Hi,
I have a `.yaml` file I'm importing into a page and using a fairly basic template to look through the data:

```
<% data.help.general.each do |questions| %>
  <h3><%=markdown questions.question %></h3>
  <p><%=markdown questions.answer %></p>
<% end %>
```

`questions.answer` contains standard Markdown links; some internal, such as `[Test](http://domain.com/test)`

But, I'm getting getting errors that seem to be referencing the `build/` directory prefix:

```
== Request: /help/index.html
       error  build/help/index.html
undefined method `link_to' for #<Object:0x007f810489c718>
```

Mind this is a MM3 install that I've been slowly upgrading to 4, but this is my next obstacle to overcome. I've tried using Redcarpet as explained in the docs, but that did not change the error. Thanks for any help.

**Comment by tdreyno** [comment]
Where does the `markdown` method come from?

**Comment by tdreyno** [comment]
Seems like where it is defined, it needs a copy of the middleman context

**Comment by zslabs** [comment]
Hi,
The inline markdown helper comes from a small pager helper:

```
module PageHelpers
  def markdown(txt)
    return unless txt

    Tilt['markdown'].new { txt }.render
  end
end
```

Is there a better way to force markdown parsing nowadays?

**Comment by zslabs** [comment]
I'm following [this example](https://github.com/middleman/middleman/issues/653).

**Comment by tdreyno** [comment]
You definitely need to forward the Middleman scope as in that example: `(scope=self)`

**Comment by zslabs** [comment]
That did it; thanks!
