### ISSUE TITLE
Linux Encoding issue MM4

### ISSUE THREAD

**Issue by zslabs** [middleman/middleman#1814]
Hi all,
I've seen some chatter around this topic on here previously with some fixes that didn't work; including trying to manually force UTF-8 (but it looks like it's set by default). Locally on a UNIX box, my project builds just fine, but on a Linux box in staging, I'm getting the following:

```
/usr/local/bundle/gems/middleman-core-4.1.1/lib/middleman-core/util/data.rb:71:in `match': invalid byte sequence in US-ASCII (ArgumentError)`
```

Any thoughts on what else I can try? This is a MM3 project I'm upgrading, which doesn't appear to have this issue, so trying to see what else could be going on here. Thanks!

**Comment by tdreyno** [comment]
So, you have a file of type US-ASCII? Or have you configured Ruby to read files in that format?

**Comment by zslabs** [comment]
I believe it's the former; doing a quick search does show some Adobe Illustrator assets with that, but isn't ASCII a subset of UTF-8? http://stackoverflow.com/questions/11303405/force-encode-from-us-ascii-to-utf-8-iconv

**Comment by tdreyno** [comment]
No, I think all encoding types are separate. Though ASCII characters can easily be converted to UTF-8

**Comment by zslabs** [comment]
This appears to be an environment issue; sorry for opening here (Docker/Ruby related).
