### ISSUE TITLE
v4 throws error on build; development server still works

### ISSUE THREAD

**Issue by egardner** [middleman/middleman#1816]
At some point in the last few days, my v4 Middleman project began refusing to `build` on my main development machine, a Mac running OSX 10.9. Running commands as `bundle exec middleman build` did not resolve the error, but on another machine running OSX 10.10 everything works fine. The development server still works without problems. The first line of the stack trace mentions `middleman-sprockets`, so perhaps that is playing a role?

```
/Users/egardner/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:235:in `initialize': undefined method `source' for nil:NilClass (NoMethodError)
```

The site is pretty standard, using the Thoughtbot's [Proteus](https://github.com/thoughtbot/proteus-middleman) starter as a scaffold.

I've posted  the full stacktrace as well as my Gemfile and Gemfile.lock in a [gist](https://gist.github.com/egardner/266201bdf8e165481d4d) in case anyone wants to take a look.

Any help is greatly appreciated.

Thanks,

Eric

**Comment by tdreyno** [comment]
Can you try pointing your `middleman-sprockets` dependency at github master?

`gem "middleman-sprockets", github: "middleman/middleman-sprockets"`

**Comment by egardner** [comment]
That did it! After changing the gem source to github the project builds normally again.

**Comment by tdreyno** [comment]
We're working on a stable release of sprocket for v4, but it is slow going. Sprockets had a major API breaking update between Middleman releases and we're still recovering. Hopefully getting close.

**Comment by egardner** [comment]
@tdreyno good to know, I'll keep my eye on that repo and look out for the next stable release. Thanks for the help!

**Comment by egardner** [comment]
So, here's an update a few months later: sprockets errors have returned, but they vary depending on my exact project setup. 

**Scenario 1: Mac OSX 10.11, middleman-sprockets 4.0.0.rc.2 (Github version)**:
Both build and preview fail (running both via `bundle exec`), and an error is thrown about a contract violation:
```
% bundle exec middleman build
== Sprockets Debug: #<Middleman::Sitemap::SearchIndexResource path=search.json>
bundler: failed to load command: middleman (/Users/eric/.rbenv/versions/2.3.1/bin/middleman)
ReturnContractError: Contract violation for return value:
        Expected: String,
        Actual: nil
        Value guarded in: Middleman::Sitemap::Resource::source_file
        With Contract: NilClass => String
        At: /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/sitemap/resource.rb:84 
```
Full stack trace [here](https://gist.github.com/egardner/cc58b7eecadf402a56618c5c5f36e286#file-stack-trace), along with some other relevant files. This project includes a custom extension that creates a child class of `Middleman::Sitemap::Resource` (to spit out simple JSON files for things like search index) but doing this never threw errors until now. 

**Scenario 2: Mac OSX 10.11, middleman-sprockets 4.0.0.rc1 (from RubyGems)**:
The preview server works fine (the site builds as expected, all CSS, JS, assets are working as expected).
But if I attempt to run `bundle exec middleman build`, I get the following output:
```
% bundle exec middleman build
== Preferring use of LibSass
bundler: failed to load command: middleman (/Users/eric/.rbenv/versions/2.3.1/bin/middleman)
NoMethodError: undefined method `source' for nil:NilClass
  /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-sprockets-4.0.0.rc.1/lib/middleman-sprockets/extension.rb:235:in `initialize'
# full stacktrace continues...
```

**Scenario 3: Mac OSX 10.10, middleman-sprockets 4.0.0.rc1 (from RubyGems)**:
Build and preview server both work normally.

It seems like the root cause is something that changed between rc1 and rc2 of `middleman-sprockets`, but the fact that the OSX version changes the outcome really threw me. After a lot of confusion over the last day I have managed to consistently reproduce the behavior here on a few different machines.

I know that `middleman-sprockets` is still in flux, but any ideas on what might be causing this?

**Comment by tdreyno** [comment]
Ping @stevenosloan

**Comment by stevenosloan** [comment]
Thanks @tdreyno, looks like we found that case for checking [`base_resource?`](https://github.com/middleman/middleman-sprockets/pull/97#issuecomment-198108101)  😉 

Best I can tell I just happen to be hitting an edge case in Middleman with some of the changes in MM::Sprockets -- the contract for [`Resource#source_file`](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/sitemap/resource.rb#L81-L86) is stricter than reality. Since the [`file_descriptor`](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/sitemap/resource.rb#L26-L27) is optional the contract should be `Maybe[String]` I think. Any [`StringResource`](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/sitemap/resource.rb#L206-L224) would have this issue -- @egardner happens to be running into it w/ the `SearchIndexResource`.

I'm happy to switch MM::Sprockets to just use the file_descriptor directly, but wondering if it makes sense to change that contract in core as well?

**Comment by egardner** [comment]
I could probably work around the stricter contract too, but I'm not sure how to satisfy it – in my project, I'm generating a few objects that descend from `Sitemap::Resource` which have a `destination_path` but no `source_file` (they don't exist until the app runs); doing this seemed better than having a few `.json.erb` templates littering the project...

Here's an example of one of the offending classes, if this helps:
https://github.com/gettypubs/romanmosaics/blob/master/extensions/search_index_resource.rb

**Comment by tdreyno** [comment]
I think `Maybe[String]` makes sense

**Comment by stevenosloan** [comment]
Cool, I'll add a test case in MM::Sprockets for StringResource as well to make sure it'll handle that nil gracefully.

**Comment by stevenosloan** [comment]
@egardner I needed to guard that nil anyway, so worked it out to be compatible w/ the currently released middleman. If you'll update middleman-sprockets pointed at master it should work for you now.

**Comment by egardner** [comment]
@stevenosloan looks like your change fixed my problem, I just pulled down the latest version of middleman-sprockets from Github and everything is working again. Thanks!
