### ISSUE TITLE
External Pipeline: Best Gulp Example?

### ISSUE THREAD

**Issue by zslabs** [middleman/middleman#1817]
Hi,
Reading over the external pipeline feature (which is awesome by the way) I'd like to make sure I understand how a typical workflow would look like using something like Gulp; since I didn't see a full-fledged example.

Using https://github.com/pfulton/mm4-ext-pipeline as a reference, this user has both their src files and build files in the `source/` directory and ignoring the source files on the MM build. I'm seeing a `.tmp/dist` path mentioned as the `source` on both the MM docs and in this example, so I didn't know if I should really be building my assets with gulp in that `.tmp/dist` directory or if I should be doing what this repo is and have them both co-mingled; which I'd rather not to avoid confusion on my team.

It also seems like we could just pull-out the gulp assets from the `source/` directory all-together, but not sure if that adds another layout of complexity. Would appreciate some guidance on how others are doing this. Thanks!

**Comment by tdreyno** [comment]
Basically, create a gulp watch or build command which deposits files in a folder. Point the external pipeline at that folder. Where it lives doesn't really matter.

The ignoring of files in source is so they are served by external pipeline. You could also keep your gulp-related files outside of source so you don't need this step.

**Comment by zslabs** [comment]
Hey @tdreyno,
Thanks for the reply; as always :)

So if my directory structure looked like the following:

```
assets/
   css/
      style.scss
source/
   index.html.erb
config.rb
gulpfile.js
```

Then if I had the assets set to build to `.tmp/build` through any gulp tasks, then I could simply set the external pipeline to be:

```
activate :external_pipeline,
  name: :gulp,
  command: "./node_modules/gulp/bin/gulp.js",
  source: ".tmp/build"
```

Does that sound about right?

**Comment by tdreyno** [comment]
Yes. Notice, that gulp will only do what you tell it to. Since you're not specifying a task for gulp  to run, then your default task should be doing what you expect.

External pipeline runs in parallel. So if you want it to be constantly watching and re-building file changes, you need to make sure gulp is configured to do that.

**Comment by zslabs** [comment]
Cool, sounds good. Thanks!

**Comment by zslabs** [comment]
Hey @tdreyno,
How do we take advantage of Compass utilities such as `image-url()` within the scope of Gulp to reference the correct path to built images:

```
url('foo.png')
```

Would return:

```
url('/assets/images/foo-398ds09.png')
```

**Comment by zslabs** [comment]
Oh awesome! I get it, since the external pipeline still ultimately passes through Middleman (for any cache-busting or gzipping) Middleman still reads those style files and injects the needed updated paths, right?

**Comment by tdreyno** [comment]
Yup

**Comment by zslabs** [comment]
Cool, thanks @tdreyno
