### ISSUE TITLE
Partial not working in 4.1.2

### ISSUE THREAD

**Issue by kaceo** [middleman/middleman#1820]
I upgraded my project from 3.4.1 to 4.1.2, and now all the partials are not working.  Only blank lines appear where the inclusion should appear.

I downgrade back to 3.4.1 and it's working again. 

I repeated with a fresh blank template "Middleman init testproject", same results with partials.

Any ideas?

**Comment by kaceo** [comment]
I see this is a dup of #1366, several months old issue.

The information about partials_dir being removed in V4 has not been reflected to main documentation, this is very careless  to release code without a major caveat to template designer.

**Comment by kaceo** [comment]
The page to update is https://middlemanapp.com/basics/partials/ as that is where the concept of Partials is explained, but not V3/V4 difference is mentioned.

**Comment by tdreyno** [comment]
Which part of that page is inaccurate?
