### ISSUE TITLE
Pretty URL not working V4.1.2?

### ISSUE THREAD

**Issue by kaceo** [middleman/middleman#1821]
Seems like there is no difference in the output build with or without

> activate :directory_indexes

in the config.rb

Has there been a change?

**Comment by kaceo** [comment]
I traced the error.  I have this line in my config

set :index_file, "index.htm"

and this caused the pretty url to not work.

FWIW under V3 this option also did not create the correct target file as described in the documentation here https://middlemanapp.com/advanced/pretty_urls/

**Comment by tdreyno** [comment]
Ah, I see. The extension expects the extensions of the source files and the index file to match. So it's looking for `original-file.htm`, but I suspect you're still using `.html` for those other files.

I think this is a bug and will fix.
