### ISSUE TITLE
Use File::FNM_EXTGLOB flag when globbing during build

### ISSUE THREAD

**Issue by WickyNilliams** [middleman/middleman#1822]
Would be handy if I could pass more complex globs like:

`middleman build --glob"/some/directory/{foo,bar}/**"`

This requires the `File::FNM_EXTGLOB` be passed to `File.fnmatch` here: https://github.com/middleman/middleman/blob/e14107ba656f7824dd804d2b0aea1ff2130fe1ed/middleman-core/lib/middleman-core/builder.rb#L120

**Comment by tdreyno** [comment]
Sure thing.
