### ISSUE TITLE
Cannot change config[:source] successfully (4.1.2)

### ISSUE THREAD

**Issue by balthisar** [middleman/middleman#1823]
(This one _really_ threw me for a loop. I'll try to figure out why, but I'll log this here in case smarter and faster people than me know the issue immediately.)

**Issue:** if `config.rb` changes `config[:source]` then frontmatter is _rendered_ instead of acted upon.

**Steps to reproduce:**
- take the default middleman project template and change the `source` directory to `content`
- add `config[:source] = 'content'` to `config.rb` (old `set` syntax produces same result)
- start the server `bundle exec middleman`
- when the site loads, the page title is "Middleman" and the front matter content appears in the body:
  - --- title: Welcome to Middleman --- 

**Other notes:** The sample file is an ERB; when rendering markdown, the front matter is converted into markdown, typically an &lt;hr> followed by the content followed by an em-dash.

I can work around this in the short term, but my particular app counts on being able to get source from a directory name that matches a different convention (in this case, 'Content').

**Comment by balthisar** [comment]
Hope this helps: in `file_renderer.rb:100` the line `file = @app.files.find(:source, @path)` is returning `nil` when the source is set to anything other than "source", whereas it returns a struct with all of the pertinent data when source is set to "source".

I can't seem to find the source code to files.find, and where it takes me in the debugger is way beyond my knowledge. Sorry I couldn't be more help.

**Comment by balthisar** [comment]
Amending the above:

In `source_watcher.rb:128` find it returning a bad value if source is anything but "source". Specifically the index `p` is being improperly built so we end up with, e.g., `Source/Source/index.html`.

I'm probably out of time tonight, but I'm guessing something isn't being synchronized somewhere when `config[:source]` is set somewhere, versus when the default value is used when the app is initialized.

I hope this is useful. Thanks.

**Comment by tdreyno** [comment]
There might be some hard coded `source` strings instead of using the config, I'll look

**Comment by balthisar** [comment]
Awesome, thanks! Version bump and release soon? No response needed; issue is closed. That's just a nudge-nudge, wink-wink, say no more.

**Comment by tdreyno** [comment]
Probably within the next week
