### ISSUE TITLE
Non-existent/misspelled partials do not generate an error

### ISSUE THREAD

**Issue by gltarsa** [middleman/middleman#1825]
This is my first Middleman-based project and I have mostly enjoyed the experience.   We are using the framework to prototype a UI.

One issue I encountered is that there is no feedback when one misspells the name of a partial.  This is easily replicated: just take a working page that uses a partial and change the name.

I looked at the code and found that there is no test for this and the bug is one line in `middleman-core/lib/middleman-core/template_context.rb` that needs to be removed:

```
    Contract Any, Or[Symbol, String], Hash => String, Maybe[Proc] => String
    def render(_, name, options={}, &block)
      name = name.to_s

      partial_file = locate_partial(name, false) || locate_partial(name, true)

      # remove me: return '' unless partial_file
      raise ::Middleman::TemplateRenderer::TemplateNotFound, "Could not locate partial: #{name}" unless partial_file
```

I also took the liberty of creating a test to verify the existence of the bug and the fix; it needs one new file and a new scenario:

`fixtures/partial-app/source/index_missing.html.erb`:

```
<%= partial "shared/header" %>
<%= partial "i_do_not_exist" %>
<%= partial "shared/footer" %>
```

Scenario in `features/partials.feature`:

```
Scenario: Flags error when partial is not found
  Given the Server is running at "partials-app"
  When I go to "/index_missing.html"
  Then I should see "Error: Could not locate partial"
```

I have submitted a PR with this test and change.

I hope it proves helpful.

Thanks,
Greg

**Comment by tdreyno** [comment]
Thank you, Greg.
