### ISSUE TITLE
Middleman blog - categories and sub categories

### ISSUE THREAD

**Issue by suresh44t** [middleman/middleman#1827]
I want to do something like this

```
blog.custom_collections = {
    category: {
      link: ':category.html',
      template: 'category.html'
    },
    subcategory: {
      link: '{category}/{subcategory}.html',
      template: 'subcategory.html'
    }
  }
```

then using, http://localhost:4567/category.html, i should see all articles listed under that category

and tthen using http://localhost:4567/category/subcategory.html,  i should see all articles listed under that subcategory which are inturn part of the main category

Here is live example:
http://www.shamalasuresh.com/category/bootstrap-themes/
http://www.shamalasuresh.com/category/bootstrap-themes/bootstrap-admin-dashboard-themes/

is this possible with middleman blog?

Thanks,
Suresh

**Comment by tdreyno** [comment]
It's possible, but you'd have to write some code. Something like:

```
resources.reduce({}) do |sum, r|
  r.data.category.each do |c|
    sum[c] ||= []
    sum[c] << r
  end

  sum
end.each do |category, resources|
  proxy "/#{category}.html", "category.html", locals: {
    category: category,
    resources: resources
  }
end
```

The above is pseudo code, but you get the idea.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! Did the suggestion by @tdreyno work? I'd suggest closing this issue.
