### ISSUE TITLE
v4 favicon_tag does not respect relative_links

### ISSUE THREAD

**Issue by jjgreen** [middleman/middleman#1830]
In v3, with `set :relative_links, true`, the erb code
```
<%= favicon_tag('/img/favicon.ico') %>
```
produces
```
<link href="../../../img/favicon.ico" rel="icon" type="image/ico" />
```
but in v4
```
<link href="/img/favicon.ico" rel="icon" type="image/ico" />
```
which is not as relative as one would hope.

**Comment by tdreyno** [comment]
Cool, I think `.ico` might just be missing from our list of valid extensions for that
