### ISSUE TITLE
The `ready` block in v4 doesn't have access to methods defined in `helper` block

### ISSUE THREAD

**Issue by bradgessler** [middleman/middleman#1831]
The following `config.rb` file doesn't run in Middleman 4

```ruby
###
# Page options, layouts, aliases and proxies
###

# Per-page layout changes:
#
# With no layout
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

# With alternative layout
# page "/path/to/file.html", layout: :otherlayout

# Proxy pages (http://middlemanapp.com/basics/dynamic-pages/)
# proxy "/this-page-has-no-template.html", "/template-file.html", locals: {
#  which_fake_page: "Rendering a fake page with a local variable" }

# General configuration

###
# Helpers
###

# Methods defined in the helpers block are available in templates
helpers do
  def my_url_helper(path)
    "/a/path/#{path}"
  end
end

ready do
  proxy my_url_helper("/"),  "/"
end

# Build-specific configuration
configure :build do
  # Minify CSS on build
  # activate :minify_css

  # Minify Javascript on build
  # activate :minify_javascript
end
```

but does on v3. When I run via 4.x I get the following error:

```sh
$ bundle exec middleman server
== The Middleman is loading
/Users/bradgessler/Desktop/crapapp/config.rb:33:in `block in evaluate_configuration!': undefined method `my_url_helper' for #<Middleman::ConfigContext:0x007fb292cf1330> (NoMethodError)
	from /Users/bradgessler/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.2/lib/middleman-core
```

I didn't see any deprecation for this in the documentation at https://middlemanapp.com/basics/upgrade-v4/. Is this the intended behavior for this in v4 or a regression?

**Comment by bradgessler** [comment]
I should add, if this is not a regression I'm happy to document the new behavior and put into a PR. Just need some guidance on how this is suppose to work.

**Comment by tdreyno** [comment]
I believe the new behavior is correct. The former behavior is actually a state bug (helpers can clobber methods on the root Middleman app). Helpers are for views/templates only.

If there are docs with this behavior, let me know and I can fix them.

**Comment by bradgessler** [comment]
You're right, these weren't in the docs but 3.x did behave that way. Here's how I can hack that config to get it running in 4.x:

```ruby
###
# Page options, layouts, aliases and proxies
###

# Per-page layout changes:
#
# With no layout
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

# With alternative layout
# page "/path/to/file.html", layout: :otherlayout

# Proxy pages (http://middlemanapp.com/basics/dynamic-pages/)
# proxy "/this-page-has-no-template.html", "/template-file.html", locals: {
#  which_fake_page: "Rendering a fake page with a local variable" }

# General configuration

###
# Helpers
###

module MyHelper
  def my_url_helper(path)
    "/a/path/#{path}"
  end
end
# Methods defined in the helpers block are available in templates
helpers MyHelper
app.extend MyHelper

ready do
  proxy my_url_helper("/"),  "/"
end

# Build-specific configuration
configure :build do
  # Minify CSS on build
  # activate :minify_css

  # Minify Javascript on build
  # activate :minify_javascript
end
```

Its not pretty, but it will get Middleman to boot until the code is better sorted out.

**Comment by tdreyno** [comment]
Hmm, yeah, that's easier accomplished with an extension which shares the same methods between config and templates. It does seem like an issue that it is difficult to do directly in config.

**Comment by bradgessler** [comment]
Interesting. I'll play around with extensions and reloading and see if I can figure out a pattern for an ./extensions folder per project for an easier way to accomplish this. I'll report findings back to this thread.

**Comment by sn3p** [comment]
Any progress or update on this?

**Comment by tdreyno** [comment]
@sn3p Nope. For now, bottle up your methods in an extension and expose them to the desired places (app, config or template). It would help to know what the expected behavior should be. Would you expect to be able to define a method in config and automatically have access to it in template?

**Comment by bradgessler** [comment]
When I was playing around with this, I was assuming the following would work in the `config.rb` file:

```ruby
module MyHelper
  def my_url_helper(path)
    "/a/path/#{path}"
  end
end
# Methods defined in the helpers block are available in templates
helpers MyHelper
include MyHelper

ready do
  proxy my_url_helper("/"),  "/"
end
```

To my surprise `include` didn't work as expected and the error message took me a bit of time to figure out what was going on. I finally figured out that I need to call `app.extend`.

One idea would be to implement two different types of methods: `helpers` that would deal with making the module available in the template context and at the app level and a new method, `view_helpers` that only extends the template context.

```ruby
helpers do
  def my_url(path); end;
end

view_helpers do
  def render_it(that); end;
end

app_helpers do
  # You get the idea
end
```

That seems like it would throw a bit of a wrench into https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/core_extensions/external_helpers.rb#L25. Does a module in the `./helper` directory extend the app and template context or only the template context?

For the issue I ran into, I would prefer that it did both. Currently I'm running this hack to deal with the original problem I documented for this ticket:

```ruby
Dir["./helpers/*.rb"].each  { |path| load path }
# MM has to be restarted for files in `lib` to update.
Dir["./lib/*.rb"].each      { |path| require path }
# Methods defined in the helpers block are available in templates
helpers URL2PNG::Helper, UrlHelpers, PageCollectionHelpers, PageHelpers
# The app is extended with helpers that the after_configuration block
# runs through to configure our SEO urls via the `proxy` calls.
app.extend PageHelpers, PageCollectionHelpers, UrlHelpers
```

and now I'm double loading modules.

Its also worth noting that I didn't mind having to prepend all of my `after_configuration` block helper methods with `app.`. That ended up looking something like this:

```ruby
after_configuration do
  app.website_pages.each do |page|
    path = "#{app.how_to_keynote_mac_path(page)}.html"
    proxy path, page.path, layout: "website/mac_keynote"
  end
end
```

**Comment by tdreyno** [comment]
I actually would suspect that your above `include` approach would work. I know why it isn't, but let me see if I can fix that.
