### ISSUE TITLE
Addressable Dependency Conflict

### ISSUE THREAD

**Issue by stringlytyped** [middleman/middleman#1832]
There appears to a conflict in Middleman's RubyGems dependencies. `middleman-core` seems to require `addressable ~> 2.4.0` as well as `fastimage ~> 1.8`. FastImage, in turn, depends on `addressable ~> 2.3.5`. As a result, when running `gem install middleman`, I receive the following error:
```
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: middleman-core requires addressable (~> 2.4.0); fastimage requires addressable (~> 2.3.5)
```

**Comment by tdreyno** [comment]
We'll fix this. For now, add the following to your Gemfile:

```
gem 'fastimage', '1.8.1'
```

**Comment by michaelmcroskey** [comment]
I'm having the same issue, but adding that to my file did not allow me to install middleman, any tips?

**Comment by tdreyno** [comment]
@michaelmcroskey Same error?

**Comment by michaelmcroskey** [comment]
Yes
`ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: middleman-core requires addressable (~> 2.4.0); fastimage requires addressable (~> 2.3.5)`

**Comment by tdreyno** [comment]
Cool, see how `master` treats you now

**Comment by michaelmcroskey** [comment]
It's working now, thank you so much!

**Comment by Ggpsv** [comment]
I still can't get this to work, `gem install middle` still returns `Unable to resolve dependencies: middleman-core requires addressable (~> 2.4.0); fastimage requires addressable (~> 2.3.5)`. Any ideas on how to solve this? I need to get this gem installed asap.

**Comment by tdreyno** [comment]
@Ggpsv Try now.

**Comment by AJKim41** [comment]
I got it to work for me by installing the dependencies separately. sudo "gem install fastimage" and "gem install addressable"
