### ISSUE TITLE
Proxy *may* be dependent on sitemap order

### ISSUE THREAD

**Issue by stevenosloan** [middleman/middleman#1833]
I'm not sure if this is really an issue or not -- I can't seem to reproduce it w/ any kind of sane limited case (the instance I'm running into it we're doing quite a bit of sitemap manipulation). But, if you manage to get in a state where the `ProxyResource` is ahead of it's target -- the build will fail with the `proxies to unknown file` error.

Here's an example I *was* able to create by manually resorting proxy resources to be first:
- [Example](https://github.com/stevenosloan/tmp_middleman_proxy_test)
- [Failure log](https://travis-ci.org/stevenosloan/tmp_middleman_proxy_test/builds/115917341)

I can probably find a workaround for my case, but if you think this is an actual issue I'm happy to dive in on it -- would just like to know where/how you think it should be handled.

cheers,
steven

**Comment by tdreyno** [comment]
I thought this should have fixed it: https://github.com/middleman/middleman/commit/0d983231d0ab90e64e6a96da06d9fe62c8f28fab

Maybe you just need to run your manipulator later?

**Comment by tdreyno** [comment]
Basically, that stuff has 2 passes.

1. On config load
2. On invalidation of loops in config (if the value of data.whatever changes)

That second form runs near the end of the sitemap manip run. It's been causing issues.

**Comment by stevenosloan** [comment]
I was able to fix it for now by changing the filename we were proxying to from `doc_page.html.haml` => `01-doc_page.html.haml`. I'll keep playing with it and see if I can get a reduced test case working (that isn't just an attempt to sabotage the order there)

Here's an output from the real case if it's any help: https://gist.github.com/stevenosloan/d85df22ac530ff03c1b8

**Comment by stevenosloan** [comment]
Closed with #1836
