### ISSUE TITLE
Unable to setup multiple blogs

### ISSUE THREAD

**Issue by ellingen** [middleman/middleman#1834]
I’m having issues setting up a second blog to an existing website.

```
activate :blog do |blog|
  blog.layout = "article_layout"
  blog.permalink = ":title.html"
end

activate :blog do |blog|
  blog.name = 'jobs'
  blog.prefix = "jobs"
  blog.permalink = "jobs/{title}.html"
  blog.sources = "/jobs/:year-:month-:day-:title.html"
end
```

There seems to be a problem using `blog.name`, when I try to start middleman I’m getting the following error:

```
/config.rb:2:in `block in initialize': undefined method `name=' for #<Middleman::Blog::Options:0x007f8527069038> (NoMethodError)
```

**Comment by tdreyno** [comment]
Hmm, what if you set a name on both?

Can you post your `Gemfile.lock` and the full error message?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation as a starting point for discussion around this.
