### ISSUE TITLE
performance regression on startup after 1f3bf47e

### ISSUE THREAD

**Issue by stevenosloan** [middleman/middleman#1837]
Looking into some performance issues w/ middleman-sprockets I noticed that the sitemap manipulators were being run *before* the build or server task were kicked off. I think I tracked it down to https://github.com/middleman/middleman/commit/1f3bf47e3c2179f9de2747e52abc75ffde1b450e.

Best I can tell when the app is initialized here: https://github.com/middleman/middleman/blob/1f3bf47e3c2179f9de2747e52abc75ffde1b450e/middleman-cli/bin/middleman#L48-L50, it causes both the `#before_configuration` and `#after_configuration` callback to be fired for the file watcher, which I think then triggers all of the sitemap manipulators to be triggered. In the case of middleman-sprockets this ends up being really expensive since it renders each asset to find the linked assets.

I can no-op there by looking for `config[:exit_before_ready]`, but it feels like this could be an issue for other extensions as well. I think I'd even be happy with a "config only" environment like "build" or "server" -- would feel more natural to target than `config[:exit_before_ready]`.

**Comment by tdreyno** [comment]
Yeah, we're booting up a second instance to check config. I think we can safely say "config will not change in `after_configuration`. Not sure we can say the same about `before_configuration`.

Let me see about making sure `config[:exit_before_ready]` doesn't trigger a sitemap pass.

**Comment by tdreyno** [comment]
Hmm, actually, it has to so `config.rb` has context. You're right, we need a special "config-only" path that will run `config.rb` with an empty sitemap. Proxies and such won't be useful, but we can get `config` and `set` results.

**Comment by tdreyno** [comment]
Try now @stevenosloan

**Comment by stevenosloan** [comment]
:+1: Looks great
