### ISSUE TITLE
Permission denied @ dir_initialize - /.DocumentRevisions-V100 (Errno::EACCES)

### ISSUE THREAD

**Issue by craigmdennis** [middleman/middleman#1840]
I'm not sure this is related to middleman or not but seems to be related to https://github.com/middleman/middleman/issues/1399

I'm trying to create a gulp workflow for Middleman v4 and am running into a permissions issue but can't figure out where it's coming from.

You can see the repo here: https://github.com/craigmdennis/middleman-gulp/tree/develop

``` rb
activate :external_pipeline,
  name: :gulp,
  command: build? ? 'npm run production' : 'npm run gulp',
  source: "/",
  latency: 1
```

When I run `middleman build` I get the following error:

``` sh
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/pathname.rb:430:in `open': Permission denied @ dir_initialize - /.DocumentRevisions-V100 (Errno::EACCES)
```

When I run `npm run production` it completes successfully.
When I comment out the above configuration and run `middleman build` it completes successfully

**Comment by tdreyno** [comment]
Looks like some crazy OS X thing: https://discussions.apple.com/thread/4295423?start=0&tstart=0

Are you running out of a special folder, an icloud path or maybe external disk?

Can you post the full error stack trace?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.
