### ISSUE TITLE
Asset hash and three.js

### ISSUE THREAD

**Issue by stilllife00** [middleman/middleman#1841]
I've noticed some cases where the asset hash doesn't seem to work.

One example is about texture images loaded by three.js . Middleman puts the proper hash on jpg images but the library tries to load the asset without hash.
It happened also with Angular.js trying to load template.html files asyncronously.
A guess is that it has to do with assets requested with XHR

Is there a workaround?
is this a bug ?
shall I send more info?

I am using ruby/2.2.0/gems/middleman-3.2.2

**Comment by tdreyno** [comment]
You can create a manifest of the new names and use those as variables in your libraries:

manifest.json.erb
```
<%= sitemap.resources.select { |r| r.ext == '.jpg' }.map { |r| { name: r.path, rename: r.destination_path } }.to_json %>
```

Something like that.

Alternatively, v4 will try to be more clever about where it replaces paths... it's still not 100% about reaching into library code though

**Comment by stilllife00** [comment]
thanks, I will try that, but I woder: on json files (that are used by three.js to load textures) how this can work ?
I have a json file like

     "mapBump" : "wood-texture.jpg",
     "mapDiffuse" : "wood-texture.jpg",

there is no way to append the hash... right ? the only way would be to load texture from the three js main file, which defeats a bit the purpose of a json file

**Comment by tdreyno** [comment]
`asset_hash` has an extensions option which defaults to `%w(.jpg .jpeg .png .gif .webp .js .css .otf .woff .woff2 .eot .ttf .svg .svgz .map)`. Adding `.json` to this list might cause the hash to appear in your JSON. Unfortunately, it will try to find the file relative to the json, not the executing JS (if that matters).

The manifest approach is probably required if you're passing around paths like that.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I think things are working as intended, and that this issue can be closed. Feel free to disagree and if so a PR with a failing test plus a fix would be a great start.
