### ISSUE TITLE
CLI options don't override config.rb options

### ISSUE THREAD

**Issue by balthisar** [middleman/middleman#1843]
In #1f3bf47, @tdreyno added support for CLI options. Although this is still undocumented it's in master. It's a bit broken (thus this issue), but the idea is you can do, e.g.,

~~~ bash
bundle exec middleman build --build_dir some_other_dir
~~~

It works for _all_ possible application config variables. _However_ the logic is a little bit broken currently, as `config.rb` will always override the CLI arguments (whereas the opposite should be true).

This is happening in `application.rb:302`, the call to `instance_eval`.

**Comment by tdreyno** [comment]
This should help: https://github.com/middleman/middleman/commit/aab7bac8a6f531cea02572bb0a1614f9de88a932

As a bonus, `config[:cli_options]` is now available for looking at what was passed in.

**Comment by balthisar** [comment]
+1, thanks!
