### ISSUE TITLE
Livereload: "Uncaught SyntaxError: Invalid regular expression flags"

### ISSUE THREAD

**Issue by T-Boss** [middleman/middleman#1848]
Using middleman 4.1.3 with middleman-livereload 3.4.6 on OSX. No pages served by middleman are reloading with livereload and all have this error in the javascript console: `Uncaught SyntaxError: Invalid regular expression flags`

The error is coming from `/__rack/livereload.js:493`, which is the second line in this code snip:

```
if (options.liveCSS) {
  if (/__rack/path.match(/\.css$/i)) {
    if (this.reloadStylesheet(path)) {
      return;
    }
  }
}
```

It appears to be caused by the value `/__rack/` being stuck in there, but I can't find the source file to take a look. That extra bit does not exist in the code at https://github.com/livereload/LiveReload/blob/develop/mac/livereload.js#L493. I've tried uninstalling all of the middleman gems manually and reinstalling them, but that did not resolve the issue.

**Comment by tdreyno** [comment]
This comes from https://github.com/johnbintz/rack-livereload/blob/master/js/livereload.js

Let me take a look

**Comment by T-Boss** [comment]
I manually uninstalled: 

```
gem uninstall rack
gem uninstall rack-livereload
gem uninstall rack-test
```

and then `bundle install` to reinstall, but I'm seeing the same behavior after building and running the site. The rack versions are:

rack (1.6.4)
rack-livereload (0.3.16)
rack-test (0.6.3)

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.
