### ISSUE TITLE
i18n build step not working

### ISSUE THREAD

**Issue by maclover7** [middleman/middleman#1849]
Hi, I tried to follow the tutorial [here](https://middlemanapp.com/advanced/localization/) to add i18n to my Middleman app, but separate build `index.html` files are not being created for the two `en` and `es` locales I have in my application. Would you be able to take a look at my app [here](https://github.com/maclover7/booth) and see if there's anything I can improve upon? Thanks!

**Comment by tdreyno** [comment]
You must use the `localizable` directory for content you want localized.

So move `source/index.html.erb` to `source/localizable/index.html.erb`

**Comment by maclover7** [comment]
Ahh, gotcha :+1:
