### ISSUE TITLE
Split content to inject partial?

### ISSUE THREAD

**Issue by NetOperatorWibby** [middleman/middleman#1850]
Hi everyone!

After realizing today that Jekyll 3 broke my category plugins (and removed the built-in category functionality), I decided to try out Middleman. So far so good. Anyhoo, I have some code in my Jekyll site that looks for a string to text to then replace with HTML. Here's the relevant snippet:

```
<main class="main">
  {% if content contains "<!--/ ad /-->" %}
    {{ content | split:"<!--/ ad /-->" | first % }}
      {% include ad.html %}
    {{ content | split:"<!--/ ad /-->" | last % }}
  {% else %}
    {{ content }}
  {% endif %}
</main>
```

I was wondering if it is at all possible to do the same thing in Middleman.

**Comment by tdreyno** [comment]
Middleman templates are just Ruby, so pretty much anything is possible. Something like:

```
<% if content.include?("<!--/ ad /-->") %>
	<%= content.split("<!--/ ad /-->").first %>
	<%= partial "ad.html" %>
	<%= content.split("<!--/ ad /-->").last %>
<% else %>
	<%= content %>
<% endif %>
```

**Comment by NetOperatorWibby** [comment]
I currently have `yield` displaying my content. I thought I could just replace `content` in your code with `yield`, but I got a bunch of errors. Here is what I have right now:

```
<main class="main">
  <%= yield %>
</main>
```

**Comment by tdreyno** [comment]
yield returns a value, so just save it for later:

```
content = yield
```

**Comment by NetOperatorWibby** [comment]
Where would I put `content = yield`?

**Comment by tdreyno** [comment]
Before you need `content` for your splitting logic.

**Comment by NetOperatorWibby** [comment]
I feel like you're speaking in riddles and it's making me more confused.

I'm pretty sure I have to wrap `content = yield` in something, but I don't know what, nor where. Does it go in the same layout file, or somewhere else entirely? Do I keep my default ` <%= yield %>` line, or do away with it?

**Comment by tdreyno** [comment]
Yes, you must wrap Ruby in `<% %>` brackets inside templates.
Yes, it should remain in the layout file.
No, it should replace the current yield.

**Comment by NetOperatorWibby** [comment]
Okay, that's what I did before and it didn't work. Tried it again and got some errors. First, here's my code:

```
<main class="main">
  <% content = yield %>

  <% if content.include?("<!--/ ad /-->") %>
    <%= content.split("<!--/ ad /-->").first %>
      <%= partial "ad.html" %>
    <%= content.split("<!--/ ad /-->").last %>
  <% else %>
    <%= content %>
  <% endif %>
</main>
```

And, the error:

```
layouts/default.erb:19: syntax error, unexpected keyword_ensure, expecting keyword_end layouts/default.erb:23: syntax error, unexpected end-of-input, expecting keyword_end end;end;end;end ^
```

**Comment by tdreyno** [comment]
ah, `endif` is not a thing in Ruby. Use `end`. Bad copy & paste by me.

**Comment by NetOperatorWibby** [comment]
My experience in Ruby is purely limited to a few random things I learned at thoughtbot, and with using Jekyll. Thanks a lot for your patience and assistance!

For those looking for a similar solution sometime in the future, here is the resulting code:

```
<main class="main">
  <% content = yield %>

  <% if content.include?("<!--/ ad /-->") %>
    <%= content.split("<!--/ ad /-->").first %>
      <%= partial "partials/ad" %>
    <%= content.split("<!--/ ad /-->").last %>
  <% else %>
    <%= content %>
  <% end %>
</main>
```
