### ISSUE TITLE
Pass object to :local vars

### ISSUE THREAD

**Issue by zslabs** [middleman/middleman#1854]
Hi,
This may be more of a general Ruby question, but is it possible to pass an object of options to a partial?

    <%= partial "templates/partials/home", :locals =>
    {
      :announcement => {
        :shown => 'test'
      }
    } =%>

I'd expect to be able to use it like so, `<%= announcement.shown %>` but that does not work. If it is possible, that'd be a great piece to add to the docs for more complicated data structures.

**Comment by tdreyno** [comment]
It'll be `<%= announcement[:shown] %>` I believe.

**Comment by zslabs** [comment]
That's it, thank you very much!
