### ISSUE TITLE
Dynamic Pages -- Accessing data inside partials that call helpers

### ISSUE THREAD

**Issue by zslabs** [middleman/middleman#1856]
Hi,
The title; while a bit cryptic, speaks to what I'm attempting to solve that I'm having some trouble with.

I have the following pages dynamically created from a `yaml` file:

```
data.distros.each do |distro|
  proxy "/apps/#{apps.name.downcase.gsub(" ", "-").gsub(".", "-")}/index.html", "/templates/layouts/apps.html", :layout => "features", :locals => { :app => app }
end
```

Inside of the `/templates/layouts/apps.html` I can successfully grab the data using `app.title` for example. But, I would like to know how those local variables are stored within the scope of `current_page` potentially. I saw https://forum.middlemanapp.com/t/trying-to-test-for-local-variables-in-a-partial-but-cant-access-the-locals-method-in-a-helper/1851 but that went un-answered.  Thanks!

**Comment by tdreyno** [comment]
`locals` are stored as `current_page.metadata[:locals]`

**Comment by zslabs** [comment]
Thanks so much @tdreyno !

In-case anyone wants an example if you're passing down an object, the syntax for me ended up being `current_page.metadata[:locals][:app]['title']`

**Comment by tdreyno** [comment]
Should also be able to do:

`data:` instead of `locals:` and access via `current_page.data` without the weirdness of knowing the different between `:title` and `title`.

`current_page.data.app.title`

Locals are a very specific format for Template execution.

**Comment by zslabs** [comment]
Appreciate the workaround, but that does not appear to be working properly for me. I'm passing this in via a page helper for meta tags to generate the description, title, keywords, etc and when doing a check against if the data is available, it passes right by your workaround, but does work with the more "explicit" way of referencing it. Possibly a bug?

**Comment by tdreyno** [comment]
Not sure without seeing your actual code
