### ISSUE TITLE
Add documentation on how to condition on environment in layout/haml

### ISSUE THREAD

**Issue by vvo** [middleman/middleman#1861]
Could be cool to easily find how to do this:

```erb
    <% if environment?(:development) %>
    <%= javascript_include_tag :devlib %>
    <% else %>
    <script src="//cdn.jsdelivr.net/production.js/1/production.min.js"></script>
    <% end %>
```

I struggled finding this and did find it in the changelog file of middleman.

But I guess we should have some doc on this helper and show the common use case I put above.

What do you think?

Also to be updated: http://stackoverflow.com/questions/13786533/how-to-know-in-what-environment-the-code-runs

**Comment by tdreyno** [comment]
Looks like `environment` never got added to the template scope in v4. Fixed that. Old docs should work correctly now.

**Comment by vvo** [comment]
So who do you use this?

**Comment by tdreyno** [comment]
`<% if environment == :whatever %>`, basically, what is in that SO article

**Comment by vvo** [comment]
Thanks!
