### ISSUE TITLE
file.php.erb

### ISSUE THREAD

**Issue by Brixy** [middleman/middleman#1863]
Hi!

`file.php.erb` does not build a `file.php` file with recent versions (4.1.4). I _think_ it worked with 4.1.0.

Not sure, whether this behavior is intended or an issue.

Thanks!

**Comment by tdreyno** [comment]
What happens?

**Comment by Brixy** [comment]
Thank you, @tdreyno!

~~~
source/folder/index.php.erb --> build/folder/index/index.html

source file.php.erb --> build/file/index.html
~~~

**Comment by tdreyno** [comment]
Ah, looks like a problem with directory indexes. Are you expecting `index.php`?

**Comment by tdreyno** [comment]
Make sure you have

```
set :index_file, 'index.php'
```

**Comment by Brixy** [comment]
Thanks!

I had played with that option, but concretely I would like to generate just one single .php file

```
source/email/index.php.erb --> build/email/index.php
```

All other (index) files are static html files.

Is that still possible? It did work with older MM versions, but I am not quite sure, when this function was dropped.

**Comment by tdreyno** [comment]
Okay, then I would just disable directory indexes for this case.

```
page "/email/index.php", directory_index: false
```

Or generically,

```
page "*.php", directory_index: false
```

**Comment by Brixy** [comment]
Superb! That’s it.

Absolutely astonishing how thought-out middleman really is.

Thank you and happy easter.
