### ISSUE TITLE
Doesn't work middleman 4.1.5

### ISSUE THREAD

**Issue by kkotaro0111** [middleman/middleman#1864]
Middleman: 4.1.5
Ruby: 2.3.0 by rbenv
OS: OSX Yosemite

```shell
$ gem install bundler middleman
$ middleman init --skip-bundle
   (some questions are selected 'yes')
$ bundle install --path vendor/bundle
$ bundle exec middleman server
```
CONSOLE OUTPUT :
```shell
== The Middleman is loading
== LiveReload accepting connections from ws://192.168.1.51:35729
```

Then, I access to localhost:4567 by web browser, show 'ERR_CONNECTION_REFUSED' page.

Middleman 4.1.4 is working.

**Comment by kkotaro0111** [comment]
I try
```Gemfile
gem 'middleman', :git => 'https://github.com/middleman/middleman', :ref => '<commit id>'
```

before commit '3cbd9fd' is safe.
if change HEAD to commit '49da615' (Tag: v4.1.5) , does not work.

**Comment by tdreyno** [comment]
This is being caused by the number of files in `vendor/bundle`. Working on a fix now.

**Comment by johnnyshields** [comment]
I'm still getting

```
WebSocket connection to 'ws://192.168.1.2:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Even after upgrading to 4.1.6

**Comment by tdreyno** [comment]
Sounds like a livereload issue, this ticket is about the server stalling.

**Comment by johnnyshields** [comment]
Hmmm yeah true. Downgraded for the time being.
