### ISSUE TITLE
Middleman - Unknown switches ' --force-polling'

### ISSUE THREAD

**Issue by SofijaMilosavljevic** [middleman/middleman#1866]
I am working in Middleman for the first time. I started it correctly, I can see my project, but I can not see changes I have done in my HTML and CSS unless I quit and start again Middleman in my terminal (bundle exec middleman). I found out that I should type in bundle exec middleman --force-polling, so Middleman can automaticly see changes in my HTML and CSS, but when type that in my terminal, it shows me this: Unknown switches ' --force-polling'

What should I do? I would be very grateful if someone can help me.

Btw, I am working on Linux Ubuntu and I have Middleman 4.1.6 version

**Comment by tdreyno** [comment]
I believe it is not `--watcher-force-polling`.

`middleman server --help` should show the full list of options

**Comment by avdeev** [comment]
`--watcher-force-polling` isnt working for me
`--force-polling` from v3 is working

Ubuntu on Virtual Box with shared folders on Win10 host.

**Comment by tdreyno** [comment]
@avdeev On v4?

**Comment by vill** [comment]
Hi there. I have a similar problem, to see the changes I need to restart the Middleman server.
`bundle exec middleman server  --force-polling -l 5` It works great for Middleman v.3
`bundle exec middleman server --watcher-force-polling --watcher-latency=5` It does not work for Middleman v.4

Vagrant `1.7.2`

guest OS:
```
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
```

host OS:
```
System Version: OS X 10.9.5 (13F1096)
Kernel Version: Darwin 13.4.0
```

**Comment by tdreyno** [comment]
Hmm, @jsdalton, we have Middleman 4 running behind Vagrant working, right? Any input?

**Comment by jsdalton** [comment]
We've been using:

```
middleman server --force-polling --latency=1
```

on v4 and it works fine, running on a virtual machine via vagrant.

It's confusing because in parts of the codebase the option is referenced with "watcher" at the front, but I know the above is what we have used and what has worked for us,

**Comment by vill** [comment]
`ruby -v`
`ruby 2.3.0p0 (2015-12-25 revision 53290) [i686-linux]`

`gem list middleman`
```
middleman (4.1.8)
middleman-cli (4.1.8)
middleman-core (4.1.8)
```

`bundle exec middleman server --force-polling --latency=1`
**Unknown switches '--force-polling, --latency=1'**

`bundle exec middleman server --watcher-force-polling --watcher-latency=5` 

as @SofijaMilosavljevic said:

> I can not see changes I have done in my HTML and CSS unless I quit and start again Middleman in my terminal

**Comment by jsdalton** [comment]
Ah. Looks like the API got (perhaps inadvertently) changed with commit 1f3bf47e3c2179f9de2747e52abc75ffde1b450e. Formerly the server CLI command would map force_polling to watcher_force_polling. After that commit, `force-polling` and `latency` would no longer work.

**Comment by vill** [comment]
@jsdalton thank you for your answer, it helped me understand the problem, problems started from version `4.1.3` to version `4.1.2` everything works correctly on a virtual machine. I hope this issue will be fixed.

**Comment by tdreyno** [comment]
That's not good... Will fix ASAP.

**Comment by splattael** [comment]
@tdreyno Hey! I'm new to middleman and need to enable polling (Docker on Windows via VirtualBox. Don't ask *sigh*).

Is there a way to enable "force polling" other than CLI options (which is not working anymore)?

Any help is much appreciated :green_heart: :smile:

**Comment by tdreyno** [comment]
`--watch-force-polling` should work again. Update to the latest gem :)

**Comment by splattael** [comment]
@tdreyno Wooow, *that* was fast!! It totally works locally (Linux) and I will check it on the Docker setup tomorrow!

Thank you for the quick solution/help! :yellow_heart:

**Comment by vill** [comment]
`bundle exec middleman server --watcher-force-polling` works correctly.
`bundle exec middleman server  --watcher-force-polling --watcher-latency=2` returns the following:
```
== The Middleman is loading
E, [2016-06-01T08:24:25.474177 #5646] ERROR -- : run() in thread failed: undefined method `-' for "2":String
Did you mean?  -@:\n /home/vagrant/.rvm/gems/ruby-2.3.1/gems/listen-3.0.8/lib/listen/adapter/polling.rb:25:in `block (2 levels) in _run'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/listen-3.0.8/lib/listen/adapter/polling.rb:23:in `each'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/listen-3.0.8/lib/listen/adapter/polling.rb:23:in `block in _run'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/listen-3.0.8/lib/listen/adapter/polling.rb:21:in `loop'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/listen-3.0.8/lib/listen/adapter/polling.rb:21:in `_run'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/listen-3.0.8/lib/listen/adapter/base.rb:78:in `block in start'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6:in `block in add'\n\ncalled from:\n /home/vagrant/.rvm/gems/ruby-2.3.1/gems/listen-3.0.8/lib/listen/backend.rb:28:in
`start'
```
