### ISSUE TITLE
middleman creating README/index.html from README.md?

### ISSUE THREAD

**Issue by troyshu** [middleman/middleman#1867]
I first noticed this when building my project would throw errors related to a layout that references "current_page.data" (NoMethodError: undefined method `first' for nil:NilClass), then saw that it was trying to build a "README/index.html", which doesn't exist, only a README.md does. E.g., in the build output, I saw:

```
Request: /bower_components/fastclick/README/index.html
       error  build/bower_components/fastclick/README/index.html
```

Going to http://127.0.0.1:4567/bower_components/fastclick/README/index.html in development throws the same NoMethodError. 

Why is Middleman trying to find a README/index.html when there's only a README.md? What can I do to stop this? It seems like Middleman is supposed to prevent this from happening? https://github.com/middleman/middleman/blob/master/middleman-core/features/more-extensionless_text_files.feature

I'm on middleman/middleman-core 3.4.0, adding onto a previously started project's code, so maybe it's a gem version conflict somewhere...

**Comment by troyshu** [comment]
Added this to my config.rb after "activate :directory_indexes":

```
ignore /.*\/[\w,\s-]+\.md/ # ignore .md files
```

Still wondering why this happened in the first place with the .md files? And why apparently the previous contributors to the middleman project I'm working on never encountered this.

**Comment by tdreyno** [comment]
This confusion feature was removed in v4, so our currently releases don't have this bug.
