### ISSUE TITLE
`link_to` not working for same-named assets when :relative_links is true

### ISSUE THREAD

**Issue by balthisar** [middleman/middleman#1869]
As the title indicates, if I have this directory layout:

~~~ 
source/
   license.html
   archives/
      index.html
      license.html
~~~

When trying to link to `archives/license.html` from within `archives/index.html`, the `link_tag` helper returns the root level `license.html` file, e.g., in markdown (which uses the link_tag helper), `[local_license_file](license.md)` should return the relative file.

_This part is really strange:_ if I delete the `archives/license.html` file, the `link_tag` helper actually returns the correct link (but of course, there's now no file there to link to).

In `link_tag` it looks like `paths.rb:url_for` is ultimately returning the wrong "magic" file, but strangely, only if the correct file is there.

A workaround is to make sure no files have the same name, but this is kind of ugly.

**Comment by iwarner** [comment]
What happens if you throw another extension at it in your test

license.html.erb

Are they treated differently ?

Interested in this also as I have had the same issues before .

On Monday, 4 April 2016, Jim Derry <notifications@github.com> wrote:

> As the title indicates, if I have this directory layout:
>
> source/
>    license.html
>    archives/
>       index.html
>       license.html
>
> When trying to link to archives/license.html from within
> archives/index.html, the link_tag helper returns the root level
> license.html file, e.g., in markdown (which uses the link_tag helper),
> [local_license_file](license.md) should return the relative file.
>
> *This part is really strange:* if I delete the archives/license.html
> file, the link_tag helper actually returns the correct link (but of
> course, there's now no file there to link to).
>
> In link_tag it looks like paths.rb:url_for is ultimately returning the
> wrong "magic" file, but strangely, only if the correct file is there.
>
> A workaround is to make sure no files have the same name, but this is kind
> of ugly.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/middleman/middleman/issues/1869>
>


-- 
Sent from Gmail Mobile

**Comment by balthisar** [comment]
I'll close this. Oh, god, I feel so stupid for chasing this down all freaking day. _All_ day.

Preview server didn't force a trailing slash, so I was working on the wrong bloody directory all day.
