### ISSUE TITLE
Changing .rb file while Middleman running causes external pipeline to spawn another task

### ISSUE THREAD

**Issue by craigmdennis** [middleman/middleman#1870]
When using an external pipeline such as Gulp

1. `middleman serve`
1. Edit `config.rb`
1. Middleman seems to run the external_pipeline task again without cancelling the previous process

Example repo: https://github.com/craigmdennis/middleman-gulp-starter

I can tell that the original process is still running as browsersync moves to the next available port

Expected behaviour should cancel the process (like pressing CTRL + C in terminal) and then run the process again.

**Comment by tdreyno** [comment]
Agreed. Will look into it.

**Comment by tdreyno** [comment]
Wow... Ruby multithreading is a hellish place. Think I finally got a fix though.

**Comment by tdreyno** [comment]
Give that a look
