### ISSUE TITLE
asset_host + jQuery producing invalid javascript?

### ISSUE THREAD

**Issue by joshukraine** [middleman/middleman#1873]
I have a couple of MM4 projects which use Gulp in conjunction with the new external_pipeline. Both projects require jQuery. I've noticed that if I activate the `asset_host` feature in `config.rb` as outlined in the [Middleman docs](https://middlemanapp.com/basics/build_and_deploy), the javascript bundle generated by `middleman build` is invalid. (The error from eslint, for example, is `Parsing error: Unexpected token *` A similar error is displayed in the browser console in production.)

![screenshot 2016-04-07 08 55 53](https://cloud.githubusercontent.com/assets/615841/14341945/b11309b4-fc9e-11e5-92b3-19af5daa8b37.png)

The following two repos illustrate this issue. The first uses Webpack to bundle the js, the second uses Browserify. Both use Gulp and both require jQuery.

1. Webpack example: https://github.com/joshukraine/middleman-gulp-starter
2. Browserify example: https://github.com/joshukraine/mm4-example

I've [discussed this issue](https://github.com/craigmdennis/middleman-gulp-starter/issues/8) at some length with Craig Dennis (author of [middleman-gulp-starter](https://github.com/craigmdennis/middleman-gulp-starter)), and it would appear that the asset host URL is not being properly quoted in the bundled javascript.

![screenshot 2016-04-06 21 17 00](https://cloud.githubusercontent.com/assets/615841/14341977/eea63882-fc9e-11e5-9764-8a375a5ce27f.png)

If I remove the `asset_host` setting, the javascript bundle is valid. Also, if I don't require jQuery, the javascript bundle is valid. But if I combine the two, I get syntax errors. Any thoughts?

Thank you.

**Comment by joshukraine** [comment]
Video walkthrough illustrating steps to reproduce the issue: https://youtu.be/xRlU38q-QxU

Updated example repo with full instructions in README: https://github.com/joshukraine/asset-host-jquery-issue

**Comment by joshukraine** [comment]
It would appear this is related to https://github.com/middleman/middleman/issues/1780.

**Comment by joshukraine** [comment]
UPDATE: Found a possible workaround. Adding the `:rewrite_ignore` option to `config.rb` tells Middleman not to insert asset host URLs in specified file types.

```ruby
# config.rb

configure :build do
  activate :asset_host,
    :host => '//YOURDOMAIN.cloudfront.net',
    :rewrite_ignore => ["*.js"]

  # More configs...
end
```

Reference: 
- [middleman/middleman-core/lib/middleman-core/extensions/asset_host.rb](https://github.com/middleman/middleman/blob/c7a46181664bf47e5dd149932d2f0302e212030a/middleman-core/lib/middleman-core/extensions/asset_host.rb#L8)
- [middleman/middleman-core/lib/middleman-core/util.rb](https://github.com/middleman/middleman/blob/c7a46181664bf47e5dd149932d2f0302e212030a/middleman-core/lib/middleman-core/util.rb#L344)

**Comment by tdreyno** [comment]
Thanks. There's definitely a regex issue I need to look into

**Comment by tdreyno** [comment]
I can't reproduce with MM github master. Can you take a look?

**Comment by tdreyno** [comment]
Wait, nm, forgot to remove the ignore line

**Comment by tdreyno** [comment]
Okay, give master a shot now

**Comment by joshukraine** [comment]
@tdreyno Yep, working for me. Thanks for the fix!
