### ISSUE TITLE
Queryable Documentation

### ISSUE THREAD

**Issue by asecondwill** [middleman/middleman#1875]
On this page:

https://middlemanapp.com/advanced/sitemap/

there is a link to http://rubydoc.info/gems/middleman-core/Middleman/Sitemap/Queryable

Which 404's.  

Is there documentation somewhere for querying the sitemap? I'd like to do simple stuff like get all the pages in the /projects folder, with tag "featured" etc.

**Comment by tdreyno** [comment]
Ah, queryable is gone in v4. Those docs should be updated.

**Comment by asecondwill** [comment]
yikes! gone? is there a replacement system?

**Comment by tdreyno** [comment]
Yup, plain old Ruby works for every use-case and is more maintainable.

```
sitemap.where(path: "/site")
```

Becomes

```
sitemap.select { |r| r.path == "/site" }
```

**Comment by asecondwill** [comment]
ok, cool.  thank you.

**Comment by dannguyen** [comment]
@tdreyno: I think (?) you mean:

     sitemap.resources.select{ |r| r.path == '/hello'}

**Comment by tdreyno** [comment]
ah, yes. I did
