### ISSUE TITLE
Change `data` folder

### ISSUE THREAD

**Issue by akshayrawat** [middleman/middleman#1878]
We have a setup where we generate pages based on data files in the `data` folder. The data here changes often. We would like to use a canned `data` folder for tests (probably called something else) so that we can run a few basic functional tests.

I could not find a way of switching the `data` folder to another when running tests. Is this supported?

**Comment by Arcovion** [comment]
[`ENV['MM_DATA_DIR']` / `config[:data_dir]`](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/core_extensions/data.rb#L11)

**Comment by akshayrawat** [comment]
Got it. Thanks.
