### ISSUE TITLE
No access to helper methods when iterating in config.rb

### ISSUE THREAD

**Issue by bazzel** [middleman/middleman#1879]
Hi,

Using MM 4.1.6, when iterating through a list to create dynamic pages, I cannot access helper methods I've defined. Outside the loop they are accessible, so I don't think I've setup the helper inclusion the wrong way:

```ruby
# config.rb

require "helpers/i18n_helpers"
include I18nHelpers

  %i(nl en).each do |lang|
    data.website.news.each do |k, item|
      # my_i18n is defined in `helpers/i18n_helpers`
      proxy "#{lang}/#{I18n.t(:news, scope: :paths)}/#{my_i18n(item, :slug)}.html",
                'localizable/news-item.html',
                locals: { item: item },
                ignore: true,
                lang: lang
      #end
    end
  end
```

```
Error reloading Middleman: undefined method `i18n' for #<Middleman::CoreExtensions::Collections::StepContext:0x007fcf50029550>
```

**Comment by markets** [comment]
Probably related to https://github.com/middleman/middleman/pull/1876. Could you please try with v4.1.7?

**Comment by tdreyno** [comment]
This is a side effect of how loops are handled in v4. I'll take a look. Similar, but not identical to #1876
