### ISSUE TITLE
Cannot use `langs` in `config.rb`

### ISSUE THREAD

**Issue by bazzel** [middleman/middleman#1880]
Hi,

Using MM 4.1.6, I've activated I18n. It seems I only have access to the `langs` variable in templates, but why is it not accessible in `config.rb`?

```ruby
# config.rb

activate :i18n, mount_at_root: :nl, langs: [:nl, :en]

langs.each do |lang|
  # ...
end
```

```
undefined local variable or method `langs' for #<Middleman::ConfigContext:0x007f87bbe725a8> (NameError)
```

**Comment by tdreyno** [comment]
If you want to pass a var around, make it a var.

```
langs = [:nl, :en]

activate :i18n, mount_at_root: :nl, langs: langs

langs.each do |lang|
  # ...
end
```

**Comment by bazzel** [comment]
Thanks, this works for me.

(However, I was expecting the `langs` method (available in MM3) was built-in and accessible in `config.rb`.)

**Comment by tdreyno** [comment]
Ah, that was an accident in v3. It was intended to be exposed to templates, and the config was a side-effect in v3. Now, in v4, they have separate scopes.

I could add it back, but I don't think that appeared in any docs so I don't consider it a regression. And, that behavior is confusing (extensions magically adding methods after they are activated).

The following also would work:

```
extensions[:18n].langs
```

**Comment by iwarner** [comment]
Thomas

This no longer seems to work:

    extensions[:i18n].langs

I am also after a way to get the auto generated locales within the config without having to hardcode them to a variable.

Issue:
1. I have seven languages
2. In each locale file there is a collection of tweets, translated to the language
3. I want to create dynamic static pages for each of these 

So I need to loop over the 7 languages - pull out the tweets and then create the dynamic pages.

I believe doing this in the config proxy pages to be the best way

Any help appreciated.
