### ISSUE TITLE
page_classes uses underscore instead of spaces

### ISSUE THREAD

**Issue by GSI** [middleman/middleman#1881]
According to [the docs](https://middlemanapp.com/basics/helper_methods/#page-classes), `page_classes` should be separated by a space whereever there's a slash in the URL. That would be very handy.

Instead, underscores are used, which makes those classes quite useless on localized sites, as one would need to reference all languages separately in any CSS (`.en_foo .es_foo ...`).

**Comment by tdreyno** [comment]
Unfortunately, there isn't a good way to fix this. The classes are mapped to the URL so if there is a prefix, it will show up in both.

You could use Sass to make some simple selectors:

```

@each $lang in en, es, de {
  .#{$lang} {
    &_foo {
    }
  }
}

**Comment by GSI** [comment]
Hmm yes, I thought about generating the classes with spaces instead of underscores.

Then, if the URL was **/en/this/is/my-page.html**, one could reference very specifically using `.en.this.is.my-page { ... }`.

However, I understand that order is not considered, having it apply to **/en/is/this/my-page.html** too.

So, thanks for the Sass idea!
