### ISSUE TITLE
Documentation on asset_hash has been removed

### ISSUE THREAD

**Issue by coreyward** [middleman/middleman#1882]
Included in the significant fallout from replacing 1 opinionated asset pipeline with a half-dozen is the removal of the documentation for the `asset_hash` feature. The closest available documentation is now [this page](https://middlemanapp.com/advanced/external-pipeline/) that reads like a blog post.

**Comment by tdreyno** [comment]
When you say "asset_hash" do you mean "asset pipeline" (aka Sprockets)?

A v4 release of Sprockets is coming, we'll re-expose those docs once an official release has been made.

**Comment by coreyward** [comment]
I'm referring to the `asset_hash` directive that is part of the default middleman 4 build. I suspect that it is part of the "asset pipeline" behavior, yes. Middleman 4 is not RC or alpha, so published documentation ought to reflect that. The vast majority of users are not going to be familiar with the goings-on of development, and rely on the documentation to provide necessary communication.

**Comment by tdreyno** [comment]
`asset_hash` and the Rails Asset Pipeline are separate concepts with no relation. Their docs have been here (and remain) https://middlemanapp.com/advanced/improving_cacheability/#uniquely-named-assets

**Comment by coreyward** [comment]
Ah, okay, that wasn't clear (especially as the search autocomplete was directing me to Asset Pipeline).
