### ISSUE TITLE
:data key in a partial's :locals overrides the data variable

### ISSUE THREAD

**Issue by lachlanmcdonald** [middleman/middleman#1884]
I've noticed that calling a partial, whose `:locals` contains the `:data` key, will override the `data` variable within the partial (and replace access to any _data files_ previously stored in the variable):

```erb
<%= partial("test", :locals => {
  :data => 123
})%>
```

Then within the partial:

```<%= data %>```

Should output `#`, instead outputs `123`.

The reason why I'm trying to set `:data` is to pass `data-*` attributes directly to the Padrino helpers, i.e. `data-value` etc. I've also tried passing `:"data-value"` to `:locals` as well, but receive a different error:

```
RuntimeError at /
invalid locals key: :"data-attribute" (keys must be variable names)
```

Tested in 3.4.1 (can't switch to the 4.x branch since I still require Sprockets for now)

**Comment by lachlanmcdonald** [comment]
Realised you can use `self.data` in the partials as a workaround.

**Comment by tdreyno** [comment]
Hmm, best we could do is warn if there is a key overlap. Does that work?
