### ISSUE TITLE
Normalize.css version

### ISSUE THREAD

**Issue by nuflowx** [middleman/middleman#1890]
This is not really an issue, I was just wondering if it would be okay to bump the version being installed from `normalize.css v2.0.1` to `normalize.css v4.1.1`. Or is there a specific thought to be using v2.0.1?

**Comment by tdreyno** [comment]
Sounds great. You can make a PR here: https://github.com/middleman/middleman-templates-default

**Comment by nuflowx** [comment]
Made a PR, therefor closing here.

middleman/middleman-templates-default#6
