### ISSUE TITLE
Does middleman regenerates all pages when using 'build' ?

### ISSUE THREAD

**Issue by unes** [middleman/middleman#1893]

**Comment by tdreyno** [comment]
Yes, unless you use the `--glob` flag

**Comment by unes** [comment]
Here is the output in the console : 

```
   create  build/generic-page/index.html
   identical  build/elements/index.html
   updated  build/generic-page/index.html
   remove  build/css/ie9
```
If I have 100 pages, it's not good if they are going to be generated every time I use `middleman build` unless I modified the layout (e.g. modifying `generic.html.erb` implicates that all pages that have this layout will be regenerated). From what I saw in the console I think it doesn't generate them all, just what I modified.

**Comment by tdreyno** [comment]
Everything will be generated on every build. If the output is the same as the current file, it will say so.
