### ISSUE TITLE
Incompatiable with Rails 5.0 beta

### ISSUE THREAD

**Issue by bianjp** [middleman/middleman#1894]
`middleman-core` 4.1.7 (currently the latest) depends on `activesupport ~> 4.2`, while `rails 5.0.0.beta3` requires `activesupport 5.0.0.beta3`.

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    middleman (~> 4.1.7) was resolved to 4.1.7, which depends on
      middleman-core (= 4.1.7) was resolved to 4.1.7, which depends on
        activesupport (~> 4.2)
```

Any plan to make `middleman` compatiable with Rails 5?

**Comment by bianjp** [comment]
Sorry, seems middleman isn't used as Rails plugin.

**Comment by tdreyno** [comment]
We'll take a look once it comes out of beta.
