### ISSUE TITLE
Potential bug with environment and if development?

### ISSUE THREAD

**Issue by iwarner** [middleman/middleman#1895]
Hiya

Trying to use some env setting in my erb javascript files - constant.coffee.erb

I am simply at the moment printing out :

```
console.log ">>><%= environment %>"
```

Getting the return 

```
>>>#<Sprockets::CachedEnvironment:0x007f9b822ea688>
```

I do have configure :development do in my config.rb

Running - middleman (4.1.6)

I have also tried - <% if development? %> - this returns development? not not found
## 

Just tried the middleman sprockets expose helper also

```
activate :sprockets do | c |
    c.expose_middleman_helpers = true
end
```

to no avail

Many thanks

Ian

**Comment by stevenosloan** [comment]
Ah yeah, so in the sprockets context `environment` is going to refer to the sprockets env, which is why you're getting the cached environment class instance back -- I'll have to look and see what I can do for that as it is definitely confusing (and would probably cause some helpers to fail). You can get back to the app environment like this: `app.environment`. Also, it looks like `production?` & `development?` aren't exposed to the template context, but you can access them via app (like `app.development?`).

**Comment by tdreyno** [comment]
Just exposed those to the template, that was an oversight.

**Comment by iwarner** [comment]
Cheers will test from master Thomas - thanks

Regards

---

IAN WARNER
DryKISS Ltd
07780 435 329
ian.warner@drykiss.com
http://drykiss.com
LinkedIn : http://linkedin.com/in/iwarner

This email and any files transmitted are confidential and intended solely
for the use of the individual or entity to which they are addressed. If you
have received this email by error, please notify us immediately and
permanently delete it from your computer.

**Comment by stevenosloan** [comment]
@iwarner just a heads up, I've had to remove `#environment` from the middleman helpers exposed in middleman-sprockets --- there were some cases sprockets expected `#environment` to return the sprockets env https://github.com/middleman/middleman-sprockets/issues/114. `production?` and `build?` should both still be fine though.

**Comment by iwarner** [comment]
Cheers  will app.xxx still work ?

Let me test also - but it was a little edge case I was running before.

Thx

On Monday, 23 May 2016, Steven Sloan <notifications@github.com> wrote:

> @iwarner <https://github.com/iwarner> just a heads up, I've had to remove
> #environment from the middleman helpers exposed in middleman-sprockets
> --- there were some cases sprockets expected #environment to return the
> sprockets env middleman/middleman-sprockets#114
> <https://github.com/middleman/middleman-sprockets/issues/114>. production?
> and build? should both still be fine though.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/middleman/middleman/issues/1895#issuecomment-221081142>
>


-- 
Sent from Gmail Mobile

**Comment by stevenosloan** [comment]
Yeah, `app.xx` should work as well -- or hit the template context class directly with `mm_context.xx` (if expose_middleman_helpers is set)

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets, and this seems to stem from sprockets.

I'd suggest closing this issue, and if the problem resurfaces (or still exist) a new issue can be opened in the [middleman sprockets repo](https://github.com/middleman/middleman-sprockets/).
