### ISSUE TITLE
external_pipeline plugin doesn't add the assets to the sitemap

### ISSUE THREAD

**Issue by tiberiucorbu** [middleman/middleman#1896]
I have the following  configuration

```
activate :external_pipeline,
  name: :gulp,
  command: "npm run gulp",
  source: GULP_CONFIG['root']['dest'],
  latency: 1

```
Where `GULP_CONFIG['root']['dest']` points to `.tmp` path.
The files generated with the gulp in `.tmp` path is looks like so at the runtime: 
```
.
├── favicon.ico
├── images
│   └── middleman-logo.svg
└── stylesheets
    ├── site.css
    └── vendor
        └── materialize
            └── sass
                └── materialize.css
```
However in the sitemap these files are not shown, form what the [docs](https://middlemanapp.com/advanced/external-pipeline/) say my understanding is that it should : 

> Ember compiles this information to the test-app/dist folder, who's contents we merge into the Middleman sitemap.

------- 
My configuration is : 
OS : Linux 4.2.6-1-MANJARO
Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
Node : v5.6.0
Middleman: 4.1.7

**Comment by tdreyno** [comment]
That looks normal to me. Should work. If you visit `http://localhost:4567/__middleman` and inspect the sitemap, are they not present? Does building do anything different from server mode?

**Comment by tiberiucorbu** [comment]
No they are not present into the sitemap at http://localhost:4567/__middleman and http://localhost:4567/stylesheets/site.css throws a 404.

I've tried clearing the caches and temps (.tmp, .sass-cache), reinstalling the gems and the npm packages and still the same result. 

But after some more debugging I've found the path to this issue : It reproduces when you break a source file (syntax error) before the server is started. 

My procedure was as follows : 

1. break a source scss whit the middleman server stopped;
1. clear the destination files;
1. start the server;
1. check the destination css  -> 404 :thumbsup: because is broken;
1. stop the server;
1. correct the source scss;
1. start the server;
1. check the destination css -> 404 :thumbsdown:;
1. from this point on, nothing gets synced from my .tmp. Even though they are correctly generated;
1. touch config.rb and the issue goes away.

**Comment by tdreyno** [comment]
Where are the source files located? I take it you're compiling Sass with gulp instead of Middleman?

**Comment by tdreyno** [comment]
Also, should mention, it's up to your gulp command to watch their files for changes and re-compile to tmp.

**Comment by tiberiucorbu** [comment]
Yes I'm compiling the assets with gulp and what I'm trying to say is that gulp does it's job but middleman watcher hangs and stays that way when there is an error in the assets compiling. Even if the error is removed and the assets are correctly compiled afterwards.

The assets sources are in middleman source folders : stylesheets and javascripts, gulp whathes these and dumps a compiled version in a .tmp folder where middleman watches with external pipeline.

A gist showing the relevant files is here : https://gist.github.com/tiberiucorbu/687ff1117ce25326c70e8ab07886a8da

The project is a fork from : https://github.com/vigetlabs/gulp-starter

The issue reproduce whit the steps described in my previous comment.

**Comment by tdreyno** [comment]
If you run `npm run gulp` when the assets are in the error'd state, does it end the task or continue to watch and eventually fix itself?

**Comment by tdreyno** [comment]
I would also try moving your gulp sources into their own folder, outside `source`. You'll see that the docs referenced above do this as well, using `test-app` as a folder.

**Comment by tiberiucorbu** [comment]
yes, `npm run gulp` stays alive on a source crash started with middleman or on it's own.
Well, I'll keep in mind that it breaks in this particular constellation and I would try to move the sources into their own path, outside of middlemans source path.

Here is a short video describing the behavior :https://www.youtube.com/watch?v=sYCeu5r99uk

**Comment by tdreyno** [comment]
Wait, was moving the folder successful?

**Comment by tiberiucorbu** [comment]
Hey, long time no see. Sorry for the late response, I had other projects in the pipeline. 

I've tried it again , using an external folder, and seems to work fine, even after a scss file was corrupted.

Thanks for your help... and for the great middleman framework :+1:

**Comment by tdreyno** [comment]
You're very welcome
