### ISSUE TITLE
Access to request object

### ISSUE THREAD

**Issue by sebastianbarfurth** [middleman/middleman#1897]
Is there a way to access the request object inside the templates? I would like backend access to the request headers for conditionals. I'd prefer not to use JavaScript, and the request is certainly available to Middleman.

**Comment by sebastianbarfurth** [comment]
It seems the current_page object has some request data (particularly the content type) but not the rest of the headers.

**Comment by tdreyno** [comment]
There's a way, but it's not public and will be removed in a future version.

What are you trying to accomplish? Static sites shouldn't be relying on anything in the Middleman dev server.
