### ISSUE TITLE
how to share assets with multiple sites and allow "local" overrules?

### ISSUE THREAD

**Issue by rubytastic** [middleman/middleman#1902]
We have many sites build on middleman and would like to share our templates and assets with multiple sites; something like a central asset folder where all the basic foundation is stored.

Then we would like to overrule certain styles with a asset folder in the specific site;
what would be the best way to manage this in middleman? havent seen examples or this documented but perhaps version 4 does support this? Kind regards

**Comment by tdreyno** [comment]
There is a new feature in v4 called `import_path`. Basically you give it an absolute path to a folder, and it copies that to your project.

```
import_path "/Users/rubytastic/shared/assets"
```

These assets are static, they will not update if you change them (without restarting the server).

If you want to make them update-able (but slower), you can use `files.watch` instead:

```
files.watch :source, "/Users/rubytastic/shared/assets"
```

There is an additional `priority` option on `watch`, if you want to add an override, that means you want the stuff in `source` to run after the stuff in `assets`. So you could do something like: 

```
files.watch :source, "/Users/rubytastic/shared/assets", priority: -1
```

I think. This stuff isn't in heavy usage.

**Comment by rubytastic** [comment]
Thank you is this also possible with partials? 
Having some partials that are shared among multiple sites inside a shared/partials and same with layouts?

**Comment by tdreyno** [comment]
Yes, via the second option. `files.watch :source` will merge multiple folders into one hierarchy, Middleman doesn't know the different which one is comes from.

**Comment by tdreyno** [comment]
That said, not a ton of users use these features, so there may be bugs. Please report :)

**Comment by rubytastic** [comment]
Going to testdrive it thank you.
The files.watch :source, "/Users/rubytastic/shared/assets", priority: -1
with the correct path is not really working where should I place it inside the config.rb?

**Comment by tdreyno** [comment]
@rubytastic Try omitting the priority. You should be able to place a file in that path, say "test.html.erb" and see it when booting up the MM server at: http://localhost:4567/__middleman

**Comment by rubytastic** [comment]
@tdreyno 
I tried your suggestions doing inside the build :do block 

```
  files.watch :source, "/srv/_sites/_shared/assets"
  files.watch :source, "/srv/_sites/_shared/layouts"
  files.watch :source, "/srv/_sites/_shared/partials"
```

Then using     = partial "partials/_html/head"
Which is inside the /srv/_sites/_shared/partials folder but this failed with a not found exception.

In the __middleman configuration there is no mention of the paths; not sure if im doing it wrong hopefully you could verify this.

**Comment by tdreyno** [comment]
`:source` is analogous to the `source/` folder. So, just like `layouts` and `partials` are children of the `source/` folder, so should they be when watching a new folder. You probably want:

```
files.watch :source, "/srv/_sites/_shared"
```

Seems weird that you'd only want those available in build mode.

**Comment by maxa4e** [comment]
Does not work outside the build and server modes. 
I just include the files regularly with :partial then?

**Comment by tdreyno** [comment]
_should_

**Comment by tdreyno** [comment]
I don't think I've ever tested partial with multiple source folders

**Comment by rubytastic** [comment]
I just symlink them for now; it is not working at all sorry.
2nd argument it expects a hash or nill not a string so the syntax is not correct either.

**Comment by vvasabi** [comment]
Try:
```
files.watch :source, path: '/srv/_sites/_shared'
```

**Comment by vvasabi** [comment]
> I don't think I've ever tested partial with multiple source folders

I made a gem that provides shared partials to other projects, and I can confirm that it does work. 👍

**Comment by tdreyno** [comment]
Oh shit, I fucked up the example :(

**Comment by iwarner** [comment]
Was testing this today and it seems it will not work with partials - maybe the _ creates some issue

Using 

    files.watch :source, path: "/var/www/DryKiss/codeblender.io/public/source/atom", destination_dir: "partial/codeBlender"

the destination drive is prefixed to the partial call see the 1st receive - strange

Yields
<img width="249" alt="screen shot 2017-02-15 at 21 12 19" src="https://cloud.githubusercontent.com/assets/279251/22995613/790071de-f3c3-11e6-8035-568e5d321bdd.png">

I have a file called _address.haml - it should not appear in the sitemap - but its not callable with 

    = partial "address/address"

Receive

    No such file or directory @ rb_sysopen - partial/codeBlender/address/_address.haml

If I use 

    = partial "atom/address/address"

then I get 

    Error: Could not locate partial: atom/address/_address

So two different errors

**Test 2**

This works perfectly

    files.watch :source, path: "/var/www/DryKiss/codeblender.io/public/source/atom"
    = partial "atom/address/address"

So mixed bag really think the destination dir seems a bit buggy with partials will dig more into the code if I can understand it :) 

I use symlinks a lot also so would be great to flesh this out.

**Comment by vvasabi** [comment]
@iwarner I think the problem is that MM4 requires the full path to a partial file to be specified. Therefore, when you have:

```
files.watch :source, path: "/var/www/DryKiss/codeblender.io/public/source/atom", destination_dir: "partial/codeBlender"
```

The `address/address.html` partial file can be included using:

```
partial 'partial/codeBlender/address/address'
```

If you want to be able to omit certain prefix when including a partial, you can consider hacking the partial helper. See [this comment](https://github.com/middleman/middleman/issues/1963#issuecomment-234327083) for an example.

**Comment by iwarner** [comment]
Brad

Sorry this was unsuccessful also, I actually tried so many combinations

I simply get

    Error: Could not locate partial:
partial/codeBlender/address/_address.haml

Regards

---

IAN WARNER
DryKISS Ltd
07780 435 329
ian.warner@drykiss.com
http://drykiss.com
LinkedIn : http://linkedin.com/in/iwarner

This email and any files transmitted are confidential and intended solely
for the use of the individual or entity to which they are addressed. If you
have received this email by error, please notify us immediately and
permanently delete it from your computer.

**Comment by vvasabi** [comment]
@iwarner Yes, sorry, I deleted my comment after realizing it was not very relevant. I was indeed able to reproduce the issue you discovered, where a partial from `files.watch` could not be used, if `destination_dir` was set. Having an `_` prefix to a file did not result in an entry in the sitemap for me, however.

**Comment by KevinGlinski** [comment]
I ran into this today, thought I would share my setup in case anyone else found this in the future.  I did some debugging on it in middleman and in `middleman-core/lib/middleman-core/sources/source_watcher.rb` in the find method, after  `p = @directory + p if p.relative?`  p has a duplicate partials path ie /x/y/z/source/partials/partials/partial_file.erb.  I couldn't find a good way to stop that duplicate.

My solution was to setup a dir structure like this

common
  \source
      \partials
      \layouts
      \images
      \stylesheets
site1
  \source
      ... rest of site including specific layouts and partials

then in config.rb in site1  I have 
```
commonDirectory = File.join(File.dirname(__FILE__), "..", 'common')

if Dir.exists? commonDirectory
    files.watch :source, path: File.join(commonDirectory, "source")
    files.watch :data, path: File.join(commonDirectory, "data")

    require File.join(commonDirectory, "lib/config_helpers")
end

hope this helps the next person to find this
