### ISSUE TITLE
Colorized output in external pipelines

### ISSUE THREAD

**Issue by jessepollak** [middleman/middleman#1904]
I'm using `webpack` as an external pipeline and am trying to get the output to maintain the colors that webpack outputs when it is run by itself. 

I've found that the `io` from the Thread is read and logged [here](https://github.com/middleman/middleman/blob/4791e01f103f8bb600860b7519b33018ff40e5e3/middleman-core/lib/middleman-core/extensions/external_pipeline.rb#L61), but I'm not really sure where to look next.

Has anyone else had this issue and found a fix? Alternatively, could any of the maintainers point me in the right direction towards solving this issue?

Thanks!

## Current

![screenshot 2016-05-03 17 20 55](https://cloud.githubusercontent.com/assets/1097953/15002185/72302eb0-1153-11e6-9a24-3b30a14806ec.png)

## Desired

![screenshot 2016-05-03 17 20 33](https://cloud.githubusercontent.com/assets/1097953/15002192/79d9a038-1153-11e6-8a11-6a75b64ecdc6.png)

**Comment by tdreyno** [comment]
I have absolutely no idea how that stuff works. But happy to accept patches that can make this happen.

**Comment by jessepollak** [comment]
I dug into this more and I was wrong — Middleman/Ruby actually handles the colorized output perfectly. The issue was on the `webpack` side of things — the way it detects whether a terminal supports colorized output was returning false for the Thread being run in Middleman. To fix this, I was able to explicitly specify the `stats: { colors: true }` option.

Hope this helps someone else!

**Comment by subelsky** [comment]
can confirm @jessepollak's suggestion still works as of June 2019...thanks!!
