### ISSUE TITLE
Integrating frontend editor like medium-editor?

### ISSUE THREAD

**Issue by rubytastic** [middleman/middleman#1905]
What are the thoughts of integrating something like 
https://github.com/yabwe/medium-editor

Anyone integrated something like this or is there a plugin? 
Static site is very nice but the need to modify in the frontend is sometimes needed. 
With a solution above one could have best of both worlds

**Comment by tdreyno** [comment]
That's always the dream :)

Seems like hooking up the client-side part of that would be easy. I don't see where it posts the updated info back to a CMS, but that bit would need to write some files on disk for MM to see them.

Would be pretty easy to hook up with some Rack Middleware in dev mode.

**Comment by nikhgupta** [comment]
I assume we can create a Rack based app that handles the authentication and allows us to edit the on-disk files using a Markdown editor. Correct me if I am wrong?

Although, Rack based apps are mountable in Middleman, I created this extension: https://github.com/nikhgupta/middleman-apps which eases out this task, and allows mounted rack apps to run seemlessly in development/production mode.

If @tdreyno can confirm that this is indeed possible this way, I can begin working on such a Middleman extension. :)
