### ISSUE TITLE
[documentation] Consider using Algolia for a better UX ?

### ISSUE THREAD

**Issue by LukyVj** [middleman/middleman#1909]
Hey guys, first of all, I love Middleman, like everyone else here, at Algolia. 
As I tweeted you, I took the liberty to clone your documentation, to see how [Algolia's DocSearch](https://community.algolia.com/docsearch/) could improve the search experience. And honestly, I quite like it. 

I often hear people saying that your search engine is not as optimal as it should be, and I think you could make it way better, using Algolia :) 

Give it a try, and feel free to ping me back if you liked it! 

https://demo.algolia.com/middleman/

DEMO : 
![Instant Middleman GIF](http://puu.sh/oMSeF/ed3bc89676.gif)

— A fan of yours.

**Comment by tdreyno** [comment]
That is awesome. Only using the current solution because it was the easiest at the time. Would happily accept a PR for this.

Glad you're enjoying Middleman!

**Comment by LukyVj** [comment]
Hey @tdreyno !

Wonderful, I think I'll ping you really soon :)

**Comment by LukyVj** [comment]
So! Finally :) We're done with it! 
Expect a PR in the day! 

Cheers
