### ISSUE TITLE
Relative URLs with repeating "partials/header" in config.rb

### ISSUE THREAD

**Issue by beaulidden** [middleman/middleman#1913]
Hi guys. Weird one, but probably something I'm missing.

Like any Middleman project, I have a header and footer partial inside my config.rb

```
<body>
  <%= partial "partials/header" %>
  <%= yield %>
  <%= partial "partials/footer" %>
</body>
````

This is working fine on first-level pages, however I'm using relative URL's. With this in mind, how can HTML files sitting two or three levels deep in the site directory get to the right file if whatever is inside the `_header.erb` is only stepping up one level?

Here's some of my site directory structure to help explain:

```
source
-- events
   -- index.html
-- resources
  -- index.html
  -- library
    -- index.html
-- our-story
  -- index.html
```

So now, inside my `_header.erb` I have a `ul` that's setting my up top-nav:

```
<ul>
  <li class="dropdown">
      <a href="/"><div class="nav-link">About Us<i class="material-icons">arrow_drop_down</i></div></a>
      <ul class="drop-nav">
        <li><a href="../our-story/index.html">Our Story</a></li>
        <li><a href="../staff/index.html">Our Staff</a></li>
        <li><a href="../parish-council/index.html">Parish Council</a></li>
      </ul>
  </li>
  <li class="dropdown">
      <a href="#"><div class="nav-link">Ministries<i class="material-icons">arrow_drop_down</i></div></a>
      <ul class="drop-nav">
        <li><a href="../ministries/youth/index.html">Youth</a></li>
      </ul>
  </li>
  <li><a href="../events/index.html"><div class="nav-link">Outreach</div></a></li>
  <li><a href="../events/index.html"><div class="nav-link">Events</div></a></li>
</ul>
```

If I'm sitting on a third level page, then jump to a first level, the `../` sitting on most of those nav links isn't going to make the necessary jump.

Make sense? I'm finding it hard to describe this one. Anyway, if you have any hints, I'd love to hear them! Thank you kindly :)

**Comment by tdreyno** [comment]
If you refer to everything using an absolute path, like `/events/index.html`, then you don't have to worry about manually relativizing the links. Middleman has a feature which can take the absolute form and convert it to relative on-demand:

```
activate :relative_assets
```

**Comment by beaulidden** [comment]
Hi @tdreyno - thanks for that.

`activate :relative_assets` was already turned on. As a pure example, check out my current _header.erb

```
<header>
  <div class="content">
    <div class="wrapper">
      <div class="logo-link">
        <a href="/index.html"><img src="/images/logo-header.png" /></a>
      </div>
      <ul>
        <li class="dropdown">
            <a href="/"><div class="nav-link">About Us<i class="material-icons">arrow_drop_down</i></div></a>
            <ul class="drop-nav">
              <li><a href="/our-story/index.html">Our Story</a></li>
              <li><a href="/staff/index.html">Our Staff</a></li>
              <li><a href="/parish-council/index.html">Parish Council</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#"><div class="nav-link">Ministries<i class="material-icons">arrow_drop_down</i></div></a>
            <ul class="drop-nav">
              <li><a href="/ministries/youth/index.html">Youth</a></li>
              <li><a href="#">Kids</a></li>
              <li><a href="#">ReGen</a></li>
              <li><a href="#">Senior</a></li>
            </ul>
        </li>
        <li><a href="/events/index.html"><div class="nav-link">Outreach</div></a></li>
        <li><a href="/events/index.html"><div class="nav-link">Events</div></a></li>
        <li><a href="/services/index.html"><div class="nav-link">Services</div></a></li>
        <li><a href="../mission-and-vision/index.html"><div class="nav-link">Mission &amp; Vision</div></a></li>
        <li class="dropdown">
            <a href="#"><div class="nav-link">Resources<i class="material-icons">arrow_drop_down</i></div></a>
            <ul class="drop-nav">
              <li><a href="/resources/sermons/index.html"><div class="drop-nav-link">Sermons</div></a></li>
              <li><a href="/resources/library/index.html">FAC Library</a></li>
              <li><a href="/resources/2020-vision.html">2020 Vision Book</a></li>
              <li><a href="/resources/policies.html">Policies</a></li>
            </ul>
        </li>
        <li class="contact cf"><a href="/contact-us/index.html"><div class="nav-link">Contact Us</div></a></li>
      </ul>
    </div>
  </div>
</header>
```

To me, that looks like the way you've suggested is the correct form to follow. When I execute a `middleman-build` then go to the /contact-us/index.html page I'm sitting on this current URL:

`file:///Users/Beau/Documents/Repos/fac-build-2016/build/contact-us/index.html`

When I click 'Events' in the top-nav, I'm navigated here:

`file:///events/index.html`

Hopefully that describes my situation a bit more clearly. Any hints?

**Comment by beaulidden** [comment]
And yes, thinking clearly now, I should have pointed out that this is an issue **after I've done a middleman-build** when using files in the _build_ folder.

**Comment by tdreyno** [comment]
Can you post your `config.rb`?

**Comment by beaulidden** [comment]
Yep, here it is:

```
###
# Compass
###

# Change Compass configuration
# compass_config do |config|
#   config.output_style = :compact
# end

###
# Page options, layouts, aliases and proxies
###

# Per-page layout changes:
#
# With no layout
# page "/path/to/file.html", :layout => false
#
# With alternative layout
page "index.html", :layout => :layout_home
#
# A path which all have the same layout
# with_layout :admin do
#   page "/admin/*"
# end

# Proxy pages (https://middlemanapp.com/advanced/dynamic_pages/)
# proxy "/this-page-has-no-template.html", "/template-file.html", :locals => {
#  :which_fake_page => "Rendering a fake page with a local variable" }

###
# Helpers
###

# Automatic image dimensions on image_tag helper
# activate :automatic_image_sizes

# Reload the browser automatically whenever files change
# configure :development do
  # activate :livereload
# end

# Methods defined in the helpers block are available in templates
# helpers do
#   def some_helper
#     "Helping"
#   end
# end

set :css_dir, 'sass'

set :js_dir, 'javascripts'

set :images_dir, 'images'

# Build-specific configuration
configure :build do

  # For example, change the Compass output style for deployment
  activate :minify_css

  # Minify Javascript on build
  # activate :minify_javascript

  # Enable cache buster
  # activate :asset_hash

  # Use relative URLs
  activate :relative_assets

  # Or use a different image path
  # set :http_prefix, "/Content/images/"
end
```

**Comment by beaulidden** [comment]
Any thoughts @tdreyno ? Is this a bug on my end with, or some gem files messing up?

**Comment by beaulidden** [comment]
Bump. Sorry to be persistent team. I'm really struggling to figure this one out, and it's a **massive** blocker to getting this project out the door on time. If anyone has anything that may help me solve this issue, I'd really appreciate your help :) thank you so much! CC. @tdreyno

**Comment by iwarner** [comment]
Test with the link_to helper also, try these

    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
    <%= link_to "Sign in with Facebook", "auth/facebook", id: "sign_in" %>

There is also a

    # set :relative_links,   true

Try that at the top of your config

Also confirm whether you have intended behaviour in the preview server?

Also looking at the site through file protocol can have unxepected behaviour use Python simpleserver or PHP server commands if you have then on your comp to preview the build.

**Comment by beaulidden** [comment]
Hi @iwarner I'll get on this right away.

To answer some of your questions though: I've been doing a `bundle exec middleman build` and testing the build pages both on my machine locally, and also on uploading them to my web server. The issues still remain.

**Comment by beaulidden** [comment]
@iwarner I just included `# set :relative_links,   true` in my **config.rb** file, but am still experiencing the issue. Would be be out of place to include you on the repo so you can have a look at this from a code POV? I just can't see how this relative issue keeps persisting. Let me know if that's something you'd be interested in doing.

**Comment by iwarner** [comment]
Yes preview server = bundle exec middleman server

You on Mac or Win?
I CD to the build folder and run 

    python -m SimpleHTTPServer 8000

Remove the Hashbang

    set :relative_links, true

**Comment by beaulidden** [comment]
Cool. How about I take this offline from this thread, and email you form here? Is ian.warner@drykiss.com your preferred email address? I'll post back here once the solution is stumbled upon!

**Comment by iwarner** [comment]
I have tested the Source code

Preview works great and can navigate around the pages
Build and previewed in PHP local server - works great

Opening up in browser with file:// not work

So all in all I think this is fine - its how you are previewiing the build that is the issue

**Comment by tdreyno** [comment]
Sorry, all, I was at a conference with spotty Wifi for the last week.

In Ruby, a `#` is a comment. So adding `# set :relative_links, true` won't do anything. See what happens if you remove the `#` on that line.

**Comment by beaulidden** [comment]
Hi guys. Good news: success! However, I'm still baffled!

@tdreyno - yep, I removed the `#` in the config.rb. I've used Middleman in the past, so I definitely understand that we use hashbands to active comments in source code :)

@iwarner thanks for clearing that up. What you said basically triggered off something in my mind, which I now believe to have been the source of my frustration.

If you guys could help me understand this one, I'd be grateful! So, on my server (beauspeak.com) I have several websites sitting in the root directory (e.g. there's one in there for a **very old** website I did back in the day called Treadright Podiatry. It's sitting in it's own folder, with an index.html file and all relevant source files)

For testing this current build, I've been opening the FTP and dragging the contents of the build folder into one called 'fac-2016'. It's here that I've been running into the problem. Basically, after Ian's comments, I tried a new approach: dragging the build folder into the _root_ folder of the beauspeak.com directory and ta-da it worked!

So what's the problem? Is there something Middleman does that requires it to be at the root of every server? Sorry if this is a dumb blonde question!

**Comment by iwarner** [comment]
I see yes there is a setting in middleman also to set the root directory -
after the TLD

If say the root index is in a folder called blog you would have to declare
that folder in the middleman config

Basically your current setup required the index to be in root public folder

Tomorrow I will give you that setting :) tonight I am enjoying game of
thrones :)

On Monday, 23 May 2016, beaulidden <notifications@github.com> wrote:

> Hi guys. Good news: success! However, I'm still baffled!
>
> @tdreyno <https://github.com/tdreyno> - yep, I removed the # in the
> config.rb. I've used Middleman in the past, so I definitely understand that
> we use hashbands to active comments in source code :)
>
> @iwarner <https://github.com/iwarner> thanks for clearing that up. What
> you said basically triggered off something in my mind, which I now believe
> to have been the source of my frustration.
>
> If you guys could help me understand this one, I'd be grateful! So, on my
> server (beauspeak.com) I have several websites sitting in the root
> directory (e.g. there's one in there for a *very old* website I did back
> in the day called Treadright Podiatry. It's sitting in it's own folder,
> with an index.html file and all relevant source files)
>
> For testing this current build, I've been opening the FTP and dragging the
> contents of the build folder into one called 'fac-2016'. It's here that
> I've been running into the problem. Basically, after Ian's comments, I
> tried a new approach: dragging the build folder into the *root* folder of
> the beauspeak.com directory and ta-da it worked!
>
> So what's the problem? Is there something Middleman does that requires it
> to be at the root of every server? Sorry if this is a dumb blonde question!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/middleman/middleman/issues/1913#issuecomment-221103031>
>


-- 
Sent from Gmail Mobile

**Comment by beaulidden** [comment]
Ha-ha, sure thing. I understand those priorities ;) thanks man, really appreciate it.
