### ISSUE TITLE
Possible bug with relative paths and spaces

### ISSUE THREAD

**Issue by ProfBlack** [middleman/middleman#1914]
Problem: It appears that when a link includes a space, middleman will not make the path relative.

I frequently serve all kinds of different file types from my sites (which are all served in subdirectories, so I need relative links). It is very useful for me to be able to just dump the file in the site hierarchy, link to it from one of my markdown files and not have to worry about it. I just started to experiment with middleman and found that some of the files would get served properly and others would not. After much experimentation, it appears the problem is that some of the files have spaces in their names. If I remove the space, I get a relative link, if I add a space, I get an absolute link. 

This seems like a bug, but if this is desired behavior and there is some configuration option that would make this work, that would be great. [yes I could go through and rename all of the files to remove the spaces, but that would be a big pain and it isn't the 90's any more -- we should be beyond letting a piece of software dictate what I call my files by now]

**Comment by tdreyno** [comment]
I space is valid in a file name, but not in a URL. Can you try replacing with `%20` and see if that helps?

If not, I'll write some tests to see what's up

**Comment by ProfBlack** [comment]
Yes, putting the %20 in there makes it generate as a relative path. 

This would be one of the curious moments where technical details rear their ugly head in unfortunate ways. For me, the point of using a combination of markdown (kramdown) and a site generator is to not have to think about the details of html any more. My current (non-middleman) workflow has been working with these links because it seems every current browser I've tested has no problem converting spaces to %20 in the url. 

I would also note that making the link absolute instead of relative doesn't actually do anything to make it more valid. Perhaps instead of making this seemingly arbitrary choice, a better solution would be to insert %20s?

**Comment by tdreyno** [comment]
I think you're right, the solution is to insert `%20` if we see spaces on our end. I'll work on doing that.
