### ISSUE TITLE
Overriding CLI option defaults

### ISSUE THREAD

**Issue by mattwigham** [middleman/middleman#1917]
Hi there. We're setting up some new deploy scripts using MM 4's new environment support (so nice), and wondering if there's a built-in way to override CLI option defaults?

Specifically we'd like to change the default build environment from [production](https://github.com/middleman/middleman/blob/master/middleman-cli/lib/middleman-cli/build.rb#L13) to `staging` so our devs have to explicitly pass `-e production` to go live. Any help would be awesome, thanks!

**Comment by tdreyno** [comment]
I took a look and it doesn't look possible. We have a hacky thing with layouts called `:_default_layout` which gets resolved later to what is set by the user. Let me take a look at pushing the env setup down a little, see if I can get something like the following set up:

```
unless config[:cli_options]["environment"]
  set :environment, :staging
end
```

**Comment by tdreyno** [comment]
Okay, decided to do this via the current over-ride mechanism: ENV vars.

Added support for `dotenv` on master so if you have a `.env` file in your project root, you can default values. To default to staging:

```
MM_ENV=staging
```

**Comment by mattwigham** [comment]
Awesome, thanks @tdreyno!
