### ISSUE TITLE
Add support for Tilt 2

### ISSUE THREAD

**Issue by mfenner** [middleman/middleman#1920]
I am sure this has been discussed before, but I can't find the relevant Github issue. It would be great if middleman would support newer versions of Tilt than `1.4.1` by changing the relevant line in `middleman-core.gemspec` to `s.add_dependency('tilt', ['>= 1.4.1', '< 3.0'])`, the same as `padrono-helpers`. Tilt is currently at version `2.0.4`, and I am specifically interested in Pandoc support for markdown conversions that was added in `2.0.3`.

If it helps I can submit a pull request after fixing all tests.

**Comment by tdreyno** [comment]
We _were_ locked by Padrino not supporting it yet... didn't realize they had upgraded.

I would love a PR and can work with you if you encounter any weirdness.

**Comment by mfenner** [comment]
I think Tilt 2 support was added to Padrino in January: https://github.com/padrino/padrino-framework/issues/1789. Will try a PR, but I am sure I will need some help.

**Comment by mfenner** [comment]
Created pull request #1921. Most tests pass, but some markdown configuration options are not passed correctly. 

@tdreyno please have a look, and let me know what else you need.

**Comment by mfenner** [comment]
@tdreyno do you want me to fix the errors in the pull request #1921 first, or can you have a look now?

**Comment by tdreyno** [comment]
Closing in favor of #1921, moving comments over there.
