### ISSUE TITLE
Extending Proxy Extension

### ISSUE THREAD

**Issue by rmanoka** [middleman/middleman#1922]
Hello!

I wish to develop an android resource manager based on Middleman.  For this, I want to create a method `drawable` exposed to config with functionality similar to `proxy`.    The most straightforward object oriented way is to inherit from the `Middleman::Sitemap::Extensions::Proxies` class but it throws the following error (possibly because of how `ConfigExtension` renames methods).   Please let me know the reason for the error.

```
config.rb:

require 'middleman-core'
class DrawableProxies < ::Middleman::Sitemap::Extensions::Proxies

  expose_to_config :drawable

  DENSITIES = {
    "mdpi": 1.0,
    "ldpi": 0.75,
    "hdpi": 1.5,
    "xhdpi": 2.0,
    "xxhdpi": 3.0,
  }
  def drawable(drawable_path, options={}, densities=DENSITIES)
    proxy(drawable_path, drawable_path + "/dest", {})   # stub code
  end
end
```

Error from running `middleman build`

```
RVM/ruby-2.3.0/gems/middleman-core-4.1.8/lib/middleman-core/extension.rb:501:in `method': undefined method `drawable' for class `#<Class:0x00000004ed2b88>' (NameError)
        from RVM/ruby-2.3.0/gems/middleman-core-4.1.8/lib/middleman-core/extension.rb:501:in `block in initialize'
        from RVM/ruby-2.3.0/gems/middleman-core-4.1.8/lib/middleman-core/extension.rb:498:in `each'
        from RVM/ruby-2.3.0/gems/middleman-core-4.1.8/lib/middleman-core/extension.rb:498:in `initialize'
        from RVM/ruby-2.3.0/gems/middleman-core-4.1.8/lib/middleman-core/extension_manager.rb:66:in `new'
        from RVM/ruby-2.3.0/gems/middleman-core-4.1.8/lib/middleman-core/extension_manager.rb:66:in `activate'
        from RVM/ruby-2.3.0/gems/middleman-core-4.1.8/lib/middleman-core/extensions.rb:120:in `block in auto_activate'
        from /home/rajsekar/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/set.rb:306:in `each_key'
        from /home/rajsekar/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/set.rb:306:in `each'
        from RVM/ruby-2.3.0/gems/middleman-core-4.1.8/lib/middleman-core/extensions.rb:117:in `auto_activate'
        from RVM/ruby-2.3.0/gems/middleman-core-4.1.8/lib/middleman-core/extension_manager.rb:28:in `auto_activate'
        from RVM/ruby-2.3.0/gems/middleman-core-4.1.8/lib/middleman-core/extension_manager.rb:20:in `block (2 levels) in initialize'
```

**Comment by tdreyno** [comment]
You can utilize proxies without extending the feature. I'd suggest extending directly from `::Middleman::ConfigExtension`. You might use `proxy` as a template. There is some complicated stuff happening behind the scenes to work around Ruby issues, but basically commands in `config.rb` generate "Descriptors" which are just little objects that can be turned into a Resource later.

Like the proxy extension, you'd like to keep track of `drawable`s and turn them into ProxyResources when asked.

Make sense? I don't write very OO code, so I apologize if this is a bit indirect.

**Comment by rmanoka** [comment]
Hello,

I got it to work by adding `self.exposed_to_config = {}' at the beginning of the class declaration.  Like so:

```
class DrawableProxies < ::Middleman::Sitemap::Extensions::Proxies
  self.exposed_to_config = {}
  expose_to_config :drawable
end
```

Both Extension, and ConfigExtension use `class_attribute` (for declaring exposed_to_config), etc. from active_support/core_ext which does inherit by default.  In the present setting, if I extend from any of the existing extensions, it tries to register the config-helpers again.  `attr_accessor` may be better suited, I should ponder more on this.

PS:  Goes without saying but, Middleman is quite an elegant piece of code.

**Comment by tdreyno** [comment]
The niceness of top-level commands, like `expose_to_config`, means some hackiness has to happen. Those methods are technically static class methods at that point, so they can only access class attributes (which are shared and inherited, hence the issue). `expose_to_config` could also be called from `def initialize`, which would be more conceptually simple, but... less Ruby-y.
