### ISSUE TITLE
blog.new_article_template not found

### ISSUE THREAD

**Issue by ghost** [middleman/middleman#1923]
Hi all, I have the following:

```
activate :blog do |blog|
  blog.name = 'case'
  blog.prefix = 'case'
  blog.layout = 'case-layout'
  blog.new_article_template = 'source/templates/case-template.erb'
end
```

With the following structure:

<img width="342" alt="screen shot 2016-05-26 at 18 00 43" src="https://cloud.githubusercontent.com/assets/10046415/15583037/c994d3fc-236b-11e6-9988-7d747e8ff874.png">

but it gives me the error:

```
/Library/Ruby/Gems/2.0.0/gems/middleman-livereload-3.4.6/lib/middleman-livereload/reactor.rb:14: warning: toplevel constant Mutex referenced by Thread::Mutex
Could not find "source/templates/case-template.erb" in any of your source paths. Your current source paths are: 
/Library/Ruby/Gems/2.0.0/gems/middleman-blog-4.0.1/lib/middleman-blog/commands
Sebastians-MacBook-Pro:portfolio-test sebastiangraz$ 
```

Any pointers in the right direction?

Many thanks!

**Comment by tdreyno** [comment]
Looking at this (https://github.com/middleman/middleman-blog/tree/master/fixtures/custom-article-template-app), it seems that the template should be `.tt` and in the root, not source

**Comment by umbriel** [comment]
Hi tdreyno, thanks for looking into this

I tried putting the template.tt file in the root and link it. However I still get the same error. 

```
Could not find "case-template.tt" in any of your source paths. Your current source paths are: 
/Library/Ruby/Gems/2.0.0/gems/middleman-blog-4.0.1/lib/middleman-blog/commands

```
Looking at this issue on SO http://stackoverflow.com/questions/27180375/how-to-override-blog-template-generator-article-tt-in-middleman-blog-gem.

It seems that he was able to link it inside source, even using .erb instead of .tt so Im confused. There isnt much documentation on this.

**Comment by tdreyno** [comment]
Let me know if you find out. I don't really use blog, myself, so the code is pretty opaque to me too.

**Comment by xavdid** [comment]
Aha! I was having this same issue and found the solution in the [docs](https://forum.middlemanapp.com/t/article-template-issues/2277):

```ruby
blog.new_article_template = File.expand_path('source/templates/case-template.erb', File.dirname(__FILE__))
```

The `article` command is looking in the directory in which it resides (`lib/middleman-core/commands`) and understandably can't find any templates there. Giving the config an absolute url fixes the problem. 

If someone has commit access, the doc file to update is [here](https://github.com/middleman/middleman-guides/blob/master/source/basics/blogging.html.markdown) (or I can submit a PR).

**Comment by ashfurrow** [comment]
I was experiencing this issue and the solution from @xavdid worked for me, thanks!

**Comment by renich** [comment]
But this is a workaround. It is, hardly, solved. I hope you can fix this one since it's pretty basic functionality and a useful one as well.

**Comment by milos1731** [comment]
@xavdid Great help, thank you very much!
