### ISSUE TITLE
Request / Idea : build verbose... errors only - stop on error - dryrun

### ISSUE THREAD

**Issue by iwarner** [middleman/middleman#1924]
Thomas

Was thinking when building my now quite large CodeBlender - I often run into errors. I turn on verbose and then need to scroll up thousands of rows of verboseness to find these errors

Can we look at a command line flag that only shows errors on build? And maybe stops on first error?

Rsync has this DryRUN option for testing whether the command will be a success before actually doing it.

Cheers

Ian

**Comment by tdreyno** [comment]
When you say "only shows errors", do you mean it doesn't show anything that is not an error?

A no-parallel + fail on first error if a good idea. Web pack uses `--bail`, which I like.

**Comment by iwarner** [comment]
Hiya

Yeah verbose shows all positive and negative output
I would like another command that just shows negative - only verbose the
errors

Yes someone like bail would be great

Cheers

On Saturday, 28 May 2016, Thomas Reynolds <notifications@github.com> wrote:

> When you say "only shows errors", do you mean it doesn't show anything
> that is not an error?
>
> A no-parallel + fail on first error if a good idea. Web pack uses --bail,
> which I like.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/middleman/middleman/issues/1924#issuecomment-222328577>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AARC0-_C1CV6tv-HPcP0kYnZES0NuSdqks5qGKdsgaJpZM4IpEPF>
> .
>


-- 
Sent from Gmail Mobile

**Comment by kmanzana** [comment]
+1 for having a bail option on middleman build

**Comment by tdreyno** [comment]
`--dry-run` added here: https://github.com/middleman/middleman/commit/4c2b89bf41eff3818fd39d1f0da0940d7892625c
