### ISSUE TITLE
Slim::Embedded options being reset?

### ISSUE THREAD

**Issue by svicalifornia** [middleman/middleman#1925]
Using Middleman 4.1.8, I have this in my config.rb:

    require 'slim'
    require 'redcarpet'

    # ... 

    markdown_config = {
      :renderer            => CustomMarkdownRenderer,
      :fenced_code_blocks  => true,
      :autolink            => true
    }
    set :markdown_engine, :redcarpet
    set :markdown, markdown_config
    Slim::Embedded.set_options markdown: markdown_config

These custom options work fine with *.md files, but not with *.slim files.

When I inspect `Slim::Embedded.options` from a Ruby block in my Slim templates, I find that `Slim::Embedded.options[:markdown]` has been set to:

    :context=>#<#<Class:0x007f8728f42610>:0x007f872564d0f8 @app=#<Middleman::Application:0x70109242212760>, ...

Is Middleman reassigning `Slim::Embedded.options`? How can I prevent this so that Slim will use the Markdown options that I specify?

**Comment by svicalifornia** [comment]
I think I've traced this to middleman-core/renderers/slim.rb:

    class ::Slim::Template
      include SafeTemplate

      def initialize(file, line, opts, &block)
        if opts.key?(:context)
          context_hack = {
            context: opts[:context]
          }

          ::Slim::Embedded::SassEngine.disable_option_validator!
          %w(sass scss markdown).each do |engine|
            ::Slim::Embedded.options[engine.to_sym] = context_hack
          end
        end

Git history shows that this was added along with a test to verify that Slim-embedded Markdown would make use of Middleman's image and link helpers. However, it seems that the `context_hack` should have been merged into `Slim::Embedded.options[:markdown]` instead of replacing it.

Would you accept a pull request to fix this?

**Comment by tdreyno** [comment]
Closing in favor of the PR
