### ISSUE TITLE
YAML error when having dates as keys (upgrading to v4)

### ISSUE THREAD

**Issue by qqube** [middleman/middleman#1930]
This is may not be a bug, but it is at least an undocumented breaking change introduced in v4.

In my `data` dir I have YAML files that contain dates as key, for example:

```
2016-03-25:
  tag: seminar
  content: blah
```

With v3, everything were fine, but with v4, I got the following error:

```
YAML Exception parsing /home/.../data/news.yaml: undefined method `to_sym' for #<Date: 2016-03-25 ((2457473j,0s,0n),+0s,2299161j)>
Did you mean?  to_s
```

How can I revert to the previous behavior? (Of course, I can wrap all my dates into quotes, but I would appreciate to avoid that.)

**Comment by tdreyno** [comment]
You're using a date as a key? Didn't realize YAML would parse that into a date. Try wrapping it in quotes?

**Comment by qqube** [comment]
Yes, I don't know it is the best idea I've ever had, but I do. Of course, if I enclose it into quotes, but then it is not a date anymore, but a string.

**Comment by tdreyno** [comment]
Oh, you _want_ it to act as a date?

**Comment by qqube** [comment]
Yes I do. In v3, that used to work. I am just trying to find out if there is a way to make it work again or if I have to modify all my YAML files.

**Comment by tdreyno** [comment]
I think you'll have to modify the YAML files. There's code to do stuff like `data.news.stuff[0].tag` and it relies on each step being something that can chain like that (so it has to work with `to_sym`).

Simplest thing is probably to stringify the key, then add an actual Data type row in it's sub-content.

**Comment by ryanhageman** [comment]
Is this still an issue?

**Comment by leighmcculloch** [comment]
This is an issue for me too. I just tried updating an app to v4.2.1 and have experienced the same issue with integer keys, reported here #2238. Keys in YAML can be any type, they aren't bound to be strings. Integer keys definitely worked in v3 and that behavior has appeared to change in v4.

**Comment by tdreyno** [comment]
I’ll add this to the test suite

**Comment by tdreyno** [comment]
Fixed here: https://github.com/middleman/middleman/commit/1dc1611b70ed0d38532b355f88443bbc750cb54b

**Comment by leighmcculloch** [comment]
I ran the build against `4.2-stable` at that commit, and 💥 it works perfectly with integer keys. Thanks!!!

**Comment by tdreyno** [comment]
Great, waiting for an upstream release of Bundler to put out the point release officially.
