### ISSUE TITLE
rsync error: unexplained error (code 255)

### ISSUE THREAD

**Issue by chansuke** [middleman/middleman#1931]
I got this error when deploying.

```
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/io.c(453) [sender=2.6.9]
```

I can ssh into the server and I only modified the html code.

**Comment by tdreyno** [comment]
The core Middleman project does not use `rsync` so that error must be coming from somewhere else in your system.
