### ISSUE TITLE
Add option to fail on error minifying javascript.

### ISSUE THREAD

**Issue by kevincox** [middleman/middleman#1933]
Right now it is hard-coded that errors minifying javascript are ignored. I consider this a bad thing as I can easily not notice that the minification is not happening.

This is also dangerous because this often points to syntax errors that would be nice to catch at build time.

**Comment by tdreyno** [comment]
Yeah, seems like it should be hard coded to fail for sure. Where's this happening?

**Comment by kevincox** [comment]
https://github.com/middleman/middleman/blob/1581bfc27e53d71e36c37d2ecf4772e1923ba643/middleman-core/lib/middleman-core/extensions/minify_javascript.rb#L105

**Comment by tdreyno** [comment]
Awesome. I'll do this when I get a chance, but if you're got time for a PR it'll go even faster
