### ISSUE TITLE
CDN overwriting wrong URL

### ISSUE THREAD

**Issue by zslabs** [middleman/middleman#1934]
Hi,
I'm using the [Build and Deploy](https://middlemanapp.com/basics/build_and_deploy) docs for implementing CDN rewrites, but am noticing it's overriding a particular part in my Google Tag Manager inclusion script; the `HTTPS://MYCDN.COM/gtm.js` should just be `gtm.js`. Any tips on how I can avoid this? Thanks!

```
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=ID_HERE"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'HTTPS://MYCDN.COM/gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','ID_HERE');</script>
<!-- End Google Tag Manager -->
```

**Comment by zslabs** [comment]
🐛

**Comment by tdreyno** [comment]
Try adding `ignore: [/gtm\.js/]` to your asset_host config.

**Comment by zslabs** [comment]
Thanks, that fixed that one. What I'm actually noticing while looking in the `build/` directory is that it's replacing really odd things in JS files, like:

`var marginLeft = parseInt($tip.css('margin-left'), 10);`

to

`var marginLeft = parseInt(https://CDNURL/$tip.css('margin-left'), 10);`

**Comment by zslabs** [comment]
🐛

**Comment by zslabs** [comment]
Hi @tdreyno,
Did you have any other suggestions I could try to get around this? I haven't been able to past the aforementioned issues. Is `middleman-core/lib/middleman-core/extensions/asset_host.rb` the correct file to be looking in for the rewrite?
