### ISSUE TITLE
Proxy path error

### ISSUE THREAD

**Issue by zslabs** [middleman/middleman#1935]
After upgrading from 4.1.1 to 4.1.9, I'm getting the following error:

`RuntimeError: Path features/test/index.html proxies to unknown file templates/layouts/features.html.erb`

This was working fine in previous versions and wasn't sure if it might be related to https://github.com/middleman/middleman/issues/1846 but it's failing with only two resources in the data file. Thanks for any help!

Here's my snippet:

```
data.features.each do |feature|
  proxy "/features/#{feature.name.downcase.gsub(" ", "-").gsub(".", "-")}/index.html", "/templates/layouts/feature.html", :layout => "features", :locals => { :feature => feature}
end
```

**Comment by zslabs** [comment]
🐛

**Comment by tdreyno** [comment]
Can you share your full config and directory structure (`tree .`). A reproducible test case would be helpful as well

**Comment by zslabs** [comment]
Here's the `config.rb`:

```

**Comment by hayley** [comment]
@zslabs Were you able to solve this? If it's similar to the problem I ran into, you'll need to rename features.erb to features.html.erb to get it to work with the latest middleman v4.

**Comment by zslabs** [comment]
Hey @hayley,
Nope, unfortunately still getting path errors. I believe I've tried most every naming combination I can (.html, .html.erb, .erb) in both the actual filename and the proxy reference.

**Comment by zslabs** [comment]
Noticed that if I move the proxy layout files to a path outside of where they were previously `/templates/layouts` things seem to work okay. @tdreyno was this changed in newer versions or a possible bug?
