### ISSUE TITLE
Question - Under which URL is my Middleman Blog

### ISSUE THREAD

**Issue by AlexL777** [middleman/middleman#1936]
hello Developers,

I would like to work with the Middleman CMS and have installed it, according to your instructions. Unfortunately, I can not understand under what URL I can access the blog in the browser it?

I have the Middleman blog in my FTP account at /cms/middleman/Middleman-BLOG

Then there is the directory /source existent.

Now I do not understand where the blog is.

Can you possibly help me?

Thanks in advance.

P.S. yet see under https://liebrecht-projekte.de/cms/middleman/MIDDLEMAN-BLOG

But there is, unfortunately, nothing to find!

**Comment by tdreyno** [comment]
Middleman is not a CMS. It is a local ruby web server. It needs to be run locally to open a local preview URL. Copying it to a server won't work, unless that server is running the ruby web server or serving the compiled site from the `build` folder.
