### ISSUE TITLE
bundle exec rake mm:build not working

### ISSUE THREAD

**Issue by edenisn** [middleman/middleman#1945]
In my project on middleman (version 3.4.0) I have file .gitlab-ci.yml with content:

```
publish:
  script:
    - apt-get update && apt-get upgrade -y && apt-get install -y nodejs
    - bundle config build.nokogiri --use-system-libraries
    - bundle install --path vendor/bundle
    - bundle exec rake mm:clobber
    - bundle exec rake mm:build
    - bundle exec rake mm:deploy
```

After pushing it and run CI in docker container I have the error:

```
$ bundle exec rake mm:build
## Compiling static pages
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path': can't find executable bundle (Gem::Exception)
    from /usr/local/lib/ruby/site_ruby/2.1.0/rubygems.rb:298:in `activate_bin_path'
    from /usr/local/bin/bundle:22:in `<main>'
Build failed.
```

What's wrong? Thanks

**Comment by tdreyno** [comment]
Looks like bundler is missing. Try `gem install bundler` on your machine/server

**Comment by edenisn** [comment]
@tdreyno command: ```gem install bundler``` doesn't help. Error remained.

**Comment by tdreyno** [comment]
You should discuss with whoever setup your Rake setup. I suspect there are useful errors hidden behind that simple "Build failed" message.

**Comment by sandstrom** [comment]
@edenisn I think this question is a better fit for Stackoverflow or an IRC-channel. Unless you think this is an issue with middleman I'd suggest closing this issue.
