### ISSUE TITLE
Dependency Injection for Extension#manipulate_resource_list

### ISSUE THREAD

**Issue by charly** [middleman/middleman#1948]
Hi,

I started using middleman a couple of weeks ago and absolutely love it.

But one thing bothers me : `MyExtension#manipulate_resource_list` is concerned with the totality of the `resources` and breaks SRP quit badly.

For example in the Paginator of middleman-blog, the method needs to check:

- if resources belongs to the right blog,
- if locales are set or not,
- if a filter needs to be applied (in the TODO) etc.

This clearly should not be the paginator's concern !!! I mean... this is really bad !
So I understand, at least I assume, middleman extensions are build on the same idea rack middlewares are and each extension/middleware passes the whole set of resources/headers to the next...

So I don't have any out of the box solution, and I don't know if DI could be it in this case, but I would be interested to know if this problem has been spotted/addressed already, if there are plans or ways to solve it, and if not I would be happy to try to contribute.

Charly

**Comment by tdreyno** [comment]
It's definitely reached the edges of what the current approach can handle. I've been thinking about a multi-phase approach, but still having the current pipeline concept. We'll see.

**Comment by charly** [comment]
I found a [fork of aupajo's pagination extension](https://github.com/stefanoverna/middleman-pagination/commit/0ba77c757252b4c12a730f4ac9006fe8763334b5) that kinda got it right by setting the paginated collection in a proc and removing the burden of determining it inside the method.
````
# config.rb
activate :pagination do
  pageable_set :articles_en, "en/articles/index.html", 55, "p/:num" do |p|
    resources.select{|r| r.data.lang == "en"}
  end
end
```

Regarding a multi-phased approach I'd be curious to know what's in your mind. I'm tempted to say a routeur/controller division would be welcome (instead of stuffing everything in `config.rb`). It would stay a flow but it would clear the callback mess by stating what needs to come before and after in the lifecycle (I personally got rid of all callbacks in my rails apps). 

On the other hand that might be overkill....

**Comment by tdreyno** [comment]
Always happy to review a proposal. Most of our users don't need to get too in the weeds on stuff, but we always want to make APIs available to the power users to do complex things.

In v4 we tried to abstract collections out so things like pagination could be slightly easier to build, but it's still pretty complex and a little too magical.
