### ISSUE TITLE
middleman v4 - one file failing to build causes entire build directory to be wiped

### ISSUE THREAD

**Issue by hayley** [middleman/middleman#1951]
I'm in the process of trying to upgrade one of my sites from middleman v3 to the latest v4 and I'm running into an issue where my build directory is getting cleaned out at the end of every build. I think I've tracked this down to a single file failing to build. If I just remove that failing file, then build/ never gets wiped out.

Am I right that this line looks for _any_ file with a failure and if so, cleans out the **entire** build directory? Because that certainly seems to be what's happening.
https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/builder.rb#L140

I would assume that clearing out the entire build directory is not the intended behaviour. And for my project specifically, data is unpredictable and I'm often running into issues where X file will fail to build but the rest of the site will be fine, and it would be impractical for one file to cause the entire site update to fail (site is ultimately pushed to amazon s3 on every update).

**Comment by hayley** [comment]
Any chance anyone has had a chance to look at this? I actually have several projects that auto-build/auto-update and I don't feel comfortable moving forward with middleman v4 on them if it's a possibility that some bad data is going to cause files to get wiped out.

**Comment by hayley** [comment]
This is still an issue for me.

**Comment by tdreyno** [comment]
Hi @hayley, sorry to have missed this ticket for so long. That's really quite a terrible regression. I've changed things so the "cleaning" action (and the after_build) hooks only run for successful builds.

Would you be able to verify this against your project by pointing your `middleman` in your `Gemfile` to this repo temporarily.

```
gem "middleman", github: "middleman/middleman"
```

Once you confirm, I'll release this as `v4.2.0`

**Comment by hayley** [comment]
AWESOME. I can confirm this has taken care of the issue on the site I'm in the middle of upgrading to v4. Thanks so much!
