### ISSUE TITLE
Extension's `initialize` and `after_configuration` called twice

### ISSUE THREAD

**Issue by amirnissim** [middleman/middleman#1952]
Using Ruby 2.3.0 with Middleman 4.1.9
```
$ bundle show middleman
/Users/amirn/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-4.1.9
```

How to reproduce:
```zsh
middleman init mm_app
[snip]
cd mm_app
mkdir lib
curl -L https://git.io/vKqiH > lib/my_extension.rb
echo -e "require 'lib/my_extension.rb'\nactivate :my_extension\n$(cat config.rb)" >! config.rb

middleman server
MyExtension: init
MyExtension: after_configuration
== The Middleman is loading
MyExtension: init
MyExtension: after_configuration
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"
```

**Comment by jennasalau** [comment]
I'm getting this issue too with Ruby 2.3.1

As a work around I'm setting a static flag that i can check incase my code has already executed.

**Comment by tdreyno** [comment]
While confusing, I suggest making extensions pure or idempotent enough to handle this. Middleman can restart itself during dev, so it's possible things will be initialized even more times.

In this case, we load extensions twice on purpose. First so they can install global config options to the command line, then again for normal execution. I believe there is `app.config[:mode] === :config` you can check to see if it's the first run or the normal execution.

**Comment by mojavelinux** [comment]
I think the fact that middleman loads the config.rb twice on startup, and possibly reloaded during during development, should be clearly stated in the documentation. It's common for users to modify config.rb and that's a pretty important tidbit of information to know.
