### ISSUE TITLE
`asset_hash` option to keep copy with original filename

### ISSUE THREAD

**Issue by remko** [middleman/middleman#1954]
It would be nice to have an option for `asset_hash` that instructs it to also generate a copy with the original filename of a hashed asset (i.e. without the hash in the extension). Some of the reasons this can be handy:
- When you have asset files that are used on the website, but which you also would like to link from outside of the website to (and therefore would like to have a stable link). 
- When assets are linked from a (non-asset-hashed) page that is cached, even for shorter times, a new site upload will break this page if any of the linked hashes change; a fallback rule on the webserver that strips the hash from any resources if it can't find it can solve this, if the original files are still copied
- To work around #1953 , such that when assets are hashed afterwards, clients with outdated versions of referenced files don't get 404s.

**Comment by lifeiscontent** [comment]
@remko you can sort of already do this, but it's not baked in.

``` ruby
  activate :asset_hash do |config|
    config.ignore = [/^[a-zA-Z0-9\-\_]*\.(png|ico|svg)/] # ignore the files you want to 
  end
```

``` ruby
after_build do |builder|
  # Copy over the files you want to build
  [
    { src: "_favicon_template.svg", dst: "safari-pinned-tab.svg" }
  ].each do |file|
    src = File.join(config[:source], file[:src])
    dst = File.join(config[:build_dir], file[:dst])
    pathname = Pathname.new(dst)
    rel_path = if pathname.absolute?
      pathname.relative_path_from(Pathname.new(app.root)).to_s
    else
      pathname
    end
    IO.copy_stream(src, dst)
    builder.trigger(:created, rel_path)
  end
end
```
