### ISSUE TITLE
Webpack Hot Module Reloading (HMR)

### ISSUE THREAD

**Issue by svicalifornia** [middleman/middleman#1955]
I've looked into Middleman's interesting new `external_pipeline` feature. However, since it ingests external assets via the filesystem, it seems that this wouldn't work with Webpack Hot Module Reloading (HMR).

Is it possible for Middleman to execute and connect to Webpack's dev-server to get HMR updates from Webpack and feed them to Middleman's LiveReload? Or stated another way, is it possible to proxy HMR through Middleman to Webpack's dev-server?

**Comment by tdreyno** [comment]
I don't think so. Normally, I use webpack's watch mode, rather than web server. It's a black art to get HMR running normally, I'd suspect adding another layout would be very hard.
