### ISSUE TITLE
Access to helper methods in Thor task

### ISSUE THREAD

**Issue by mvonmaltitz** [middleman/middleman#1959]
I externalized helper methods into an own extension. They can successfully be used in the templates.
Now I would also like to apply them in custom tasks, but I do not know how to reference them:

```
#config.rb
...
require "lib/nethelpers"
```

```
#lib/nethelpers.rb
require "middleman-core"

Middleman::Extensions.register :net_helpers do
  NetHelpers
end
class NetHelpers < Middleman::Extension

  def initialize(app, options_hash={}, &block)
    super
  end

  helpers do
    #...
    def some_method

    end
    #...
end
```

```
#tasks/sanity_check.rb
module Middleman::Cli::Net
  class SanityCheck < Thor::Group
    include Thor::Actions

    def sanity_check
      app = Middleman::Application.new
      # app.data and app.sitemap work properly
      # internal helpers like app.link_to(...) also function
      # but how to call some_method?
    end
```
I already tried directly calling some_method, app.some_method, ...
I also tried to find some helper attribute of app, but I did not succeed.
The documentation also did not provide any promising hints for me.

Thank you very much in advance!

**Comment by tdreyno** [comment]
Most of the helpers execute in a template context and it's very difficult to use directly. However, there are some more generic util methods that might solve this specific problem:

```
::Middleman::Util.url_for(app, path_or_resource, options_with_resource)
```

https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/util/paths.rb#L148-L234
