### ISSUE TITLE
image_url helper not working?

### ISSUE THREAD

**Issue by lifeiscontent** [middleman/middleman#1964]
I'm trying to serve a full URL of an image in my middleman app.

when I call `image_url` in a view I receive this error.

```
undefined method `image_url' for #<#<Class:0x007ff580fbce80>:0x007ff58699ab50> Did you mean? image_alt image_tag
```

**Comment by lifeiscontent** [comment]
nvm, I realize now there is no way for middleman to know that information

**Comment by tomrutgers** [comment]
@nedzen You can simply use the built in `image_path(img)`
