### ISSUE TITLE
Referencing `current_page.data.layout` in an IF Statement

### ISSUE THREAD

**Issue by folo1988** [middleman/middleman#1965]
Trying to reference the layout of the current page does not work:

```
<%
  if current_page.data.layout == "alt_layout"
    @var = "x"
  elsif
    @var = "y"
  end
  %>
```

However, trying to do the same on a separate item of frontmatter does:

```
<%
  if current_page.data.x == "alt_layout"
    @var = "x"
  elsif
    @var = "y"
  end
  %>
```

Example YAML:

```

---
layout: alt_layout
x: alt_layout

---
```

**Comment by tdreyno** [comment]
If you print `current_page.data.x`, what is the value?

**Comment by folo1988** [comment]
Sorry for the late reply.

It is indeed 'alt_layout' when I do `<%= current_page.data.x %>`. 

I'm still a bit of a Ruby newb, is 'layout' something special? if I write `<%= current_page.data.layout %>` 'layout' gets the same syntax highlighting that 'gsub' does (I must have missed that when I first filed the issue).

**Comment by hello-jason** [comment]
I'm also experiencing this issue.

Trying the following does not work:

```slim
- unless current_page.data.layout == "my-layout"
  // does not work
```

However checking another frontmatter variable does work:

```slim
- unless current_page.data.body_class == "my-body-class"
  // works

**Comment by admhlt** [comment]
You may be able to use `current_page.options[:layout]` -- from my experience `layout` is considered an option and not metadata.

**Comment by hello-jason** [comment]
This is the fix: `current_page.options[:layout]`. Thanks @admhlt
