### ISSUE TITLE
[Question] How set the default dev server root

### ISSUE THREAD

**Issue by equinusocio** [middleman/middleman#1968]
Hi all, i don't know how to ask this, but i have a problem when i set
```ruby
activate :i18n, :mount_at_root => false
```

I have `it` and `en` languages where `it` should be the default one. When i run the middleman server there is a way to set `/it` as default path through the middleman conf? I mean when i open the `http://localhost` server it should be redirected to `http://localhost/it`

**Comment by vvasabi** [comment]
Although not a perfect solution, you can put this in `source/index.html` to achieve what you want:

```html
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="refresh" content="0; url=/it/" />
  </head>
  <body>
  </body>
</html>
```

**Comment by equinusocio** [comment]
Ah, right. Thanks

**Comment by stevenosloan** [comment]
You could create a tiny rack app to sit at "/" and redirect using `map` in config.rb.

```ruby
map "/" do
  run Proc.new { |env| ['302', {'Location' => '/it/'}, ['Moved']] }
end
```

**Comment by andreamoro** [comment]
Hi there,
Appreciate this is a bit older, but can you please illustrate the gems and the steps necessary to activate / create that rack app?
As I haven't done this stuff before, I'm not entirely sure the above code is all it is required.

Thanks

**Comment by stevenosloan** [comment]
Hey @andreamoro, I think it depends on what environment you want the redirect to happen. If you're just looking to have the redirect represented in development, you'd put the rack app in a `configure :development` block in `config.rb` like this:

```ruby
# config.rb
configure :development do
  map "/" do
    run Proc.new { |env| ['302', {'Location' => '/it/'}, ['Moved']] }
  end
end
```
It'll get used w/o any more activation steps.

If you're looking to do it out in production though, you'd need to check the docs for whatever server you are using ([Nginx](https://www.digitalocean.com/community/tutorials/how-to-create-temporary-and-permanent-redirects-with-apache-and-nginx#how-to-redirect-in-nginx), [Apache](https://www.digitalocean.com/community/tutorials/how-to-create-temporary-and-permanent-redirects-with-apache-and-nginx#how-to-redirect-in-apache), [Caddy](https://www.digitalocean.com/community/tutorials/how-to-create-temporary-and-permanent-redirects-with-apache-and-nginx#how-to-redirect-in-apache), etc)

**Comment by andreamoro** [comment]
Thanks @stevenosloan 
Can you point me out on some documentations out of there?

The above resolves in a redirection loop. Is the map ".." abiding to regular expression patterns?

Thanks

**Comment by stevenosloan** [comment]
mmm, yep you're totally right -- I definitely wasn't looking close enough at the behavior of that 😁

The [docs](http://www.rubydoc.info/github/rack/rack/Rack/Builder#map-instance_method) for rack aren't the best, but I think [this SO thread](http://stackoverflow.com/questions/41896691/what-is-map-matching-exactly-in-rack) explains what was going on pretty well. (tl; dr; `/` matches every route since every route starts with `/`)

w/o digging into the `map` docs too hard this is definitely possible w/ a small middleware (although bumping to a full featured rewrite gem ming be good too like [rack-rewrite](https://github.com/jtrupiano/rack-rewrite)).

So in `config.rb` you can:
```ruby
class RedirectRootToIt
  def initialize app
    @app = app
  end

  def call env
    if env["PATH_INFO"] == "/"
      ['302', {'Location' => '/it/'}, ['Moved']]
    else
      @app.call(env)
    end
  end
end

configure :development do
  use RedirectRootToIt
end
```

If you were going to use rack-rewrite it'd be

```ruby
require 'rack/rewrite'
use ::Rack::Rewrite do
  r301 '/', '/it/'
end
```

**Comment by andreamoro** [comment]
@stevenosloan fabulous. That works like a charm. What if I want to move the class outside the config.rb. Apologies for the silly question, but I'm still a newbie with Ruby.

**Comment by stevenosloan** [comment]
Oh no worries :)

I'll typical structure middleman projects like:

```
data/
lib/
source/
config.rb
```

Where any helpers, one-off classes, etc go into `lib`. So for this instance:

```
data/
lib/
|- redirect_root_to_it.rb
source/
config.rb
```

Where the `redirect_root_to_it.rb` has the `RedirectRootToIt` class, then in config.rb:

```ruby
require_relative "lib/redirect_root_to_it" # the file path relative to config.rb w/o .rb extension
use RedirectRootToIt
```

**Comment by andreamoro** [comment]
Great, added into the helpers folder. Appreciate is not an helper in that sense, but didn't fancy creating  another folder under the Middleman Project. Hopefully this should not create problems in the long term.

Aside from this one, and I appreciate going OT, have you run across a problem with the i18n module and the langs property? I'm trying to figure out how to get access to it on the after_build method without success.

**Comment by stevenosloan** [comment]
I've never used the i18n module, so I don't think I'll be too helpful there ;)
