### ISSUE TITLE
can i defer copying files from source to build until after template processing ?

### ISSUE THREAD

**Issue by thechile** [middleman/middleman#1978]
I would like to defer the copy of files in `source` directory into `build` directory till after the ERB files have been processed. Is this possible ?

Background info,

I have a site where the content of source directory is dynamic/varies bases on the `middleman build` run. So the erb template runs some ruby code that actually fetches static images into the source directory. From what i can tell the copy from `source` to the `build` directory happens before the template generation completes meaning anything places into source during build won't be copied.

In my example i have lots of images in `/home/dev/site_example/images/jpeg` but during build i only select a small handful of them to be used in the site. So ideally during build, those images are copied into `source/images` to then be copied to `build/images`. But i don't think this can be done since copy happens too early.

I can't put all images in source, as that'l waste time copying 100's unnecessary images to build.

At the moment i run this so fixup build with necessary images, but same as above.. this makes ALL images available to build. Not only the required ones. 

```
app.after_build do
  system "ln -s /home/dev/site_example/images/jpeg /home/dev/site_example/build/images/"
end
```

Many thanks

**Comment by tdreyno** [comment]
Our asset hashing code requires that static assets are copied before ERb so the templates can correctly figure out the hashed path (`/images/whatever-#{sha1 of build file contents}.jpg`).

If you have the logic for which images are needed in which builds, it seems like you could ignore the ones you don't need in `config.rb` and rename (if necessary) the correct ones to your desired location. Or, is it more dynamic than that?

**Comment by thechile** [comment]
so in my example i have a db/directory of 1000+ images. Every day the static page is generated, selecting only 50 of these to be shown in grid/tile layout for display. Each day rotating another 50 images.

So in the erb it selects that days 50 images and setups the html. What i'd like it to copy or symlink those selected 50 images into the source directory so on completion they are copied to the build target and ready to be packages and copied to final web server for hosting.

**Comment by tdreyno** [comment]
Right, you could keep your images outside of source, select them in `config.rb` and use `import_file FULL_SOURCE_PATH, OUTPUT_PATH` to move them into the build at run time. That same code in config could make a variable representing the chosen 50 and pass that into the template for rendering.

**Comment by thechile** [comment]
ok thanks, i understand what you mean. But since i don't use the asset hash feature on images.. instead of defining the variable in config.rb, during the erb generation can i define variables like an array that will store a list of the dynamically chosen image paths. Then in my  `app.after_build do` block i can loop through the images list and symlink them into the build dir ?

I can find several articles about accessing config.rb variables from templates but i can't find into on how to define variables within a template during build that will be accessible by config.rb within `after_build`.

**Comment by tdreyno** [comment]
It's a very bad idea to try to use template rendering as a means of accumulating data. For one, templates are renderer in parallel so you may have all kinds of thread/data-related problems. Templates are run in a sandboxed environment to discourage this kind of functionality.

I'm sure you can find a way to hack around it, but I strongly recommend refactoring so your data is at the top of your application and build/render is just a predictable output of pre-defined variables.

**Comment by thechile** [comment]
ok thanks for explaining, i'll do as you suggested and use import_file option. Thanks.
