### ISSUE TITLE
Middleman init not working

### ISSUE THREAD

**Issue by polytronix** [middleman/middleman#1980]
[polytronixglass copy (master)]$ middleman init
/Users/StephanieApril/.rbenv/versions/2.2.3/bin/middleman:23:in `load': cannot load such file -- /Users/StephanieApril/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.10/bin/middleman (LoadError)
       	from /Users/StephanieApril/.rbenv/versions/2.2.3/bin/middleman:23:in `<main>'

## Additional information

- Ruby version: 2.2.3p173
- Middleman version: middleman (3.4.1)
      coffee-script (~> 2.2)
      compass (>= 1.0.0, < 2.0.0)
      compass-import-once (= 1.0.5)
      execjs (~> 2.0)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-core (= 3.4.1)
      middleman-sprockets (>= 3.1.2)
      sass (>= 3.4.0, < 4.0)
      uglifier (~> 2.5)
    middleman-autoprefixer (2.7.0)
      autoprefixer-rails (>= 6.3.1, < 7.0.0)
      middleman-core (>= 3.3.3)
    middleman-core (3.4.1)
      activesupport (~> 4.1)
      bundler (~> 1.1)
      capybara (~> 2.4.4)
      erubis
      hooks (~> 0.3)
      i18n (~> 0.7.0)
      listen (~> 3.0.3)
      padrino-helpers (~> 0.12.3)
      rack (>= 1.4.5, < 2.0)
      thor (>= 0.15.2, < 2.0)
      tilt (~> 1.4.1, < 2.0)
    middleman-livereload (3.4.6)
      em-websocket (~> 0.5.1)
      middleman-core (>= 3.3)
      rack-livereload (~> 0.3.15)
    middleman-sprockets (3.4.2)
      middleman-core (>= 3.3)
      sprockets (~> 2.12.1)
      sprockets-helpers (~> 1.1.0)
      sprockets-sass (~> 1.3.0)
- OS version: El Captain

**Comment by sandstrom** [comment]
@polytronix I think this may be a better fit for StackOverflow. I'd suggest closing this ticket and asking there.
