### ISSUE TITLE
LiveReload doesn't work anymore

### ISSUE THREAD

**Issue by andreamoro** [middleman/middleman#1982]
## Expected behavior and actual behavior
Livereload shows item refreshed in the terminal window but an error in the browser

WebSocket connection to 'ws://192.168.1.66:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

## Steps to reproduce the problem (from a clean middleman installation)
start up the middleman server using bundle exec middleman server, change a page, sit down and (don't) relax.

## Additional information

- Ruby version: 2.0.0p648
- Middleman version: middleman 4.1.10, middleman-livereload 3.4.6
- OS version: OS X El Captain 10.11.6

**Comment by andreamoro** [comment]
Updating to the latest ruby 2.3.1 solves the problem. I guess this issue can be closed as there are no reasons to use an old version I guess.

**Comment by tdreyno** [comment]
We're marking Ruby 2.2 as the minimum in our next release.
