### ISSUE TITLE
Rails 5 Compatibility Error

### ISSUE THREAD

**Issue by mvastola** [middleman/middleman#1983]
So I'm assuming this is a rare (or at least largely unsupported) use case for middleman from my inability to find it documented, but I have a very simple Rails 5 app (I am using RoR entirely because I am most comfortable with it and I wanted to take advantage of sprockets and such) and I'd like to get my feet wet with middleman to automate the creation of a static version of that app. (If RoR and middleman are completely incompatible and this is a fool's errand, please let me know, but I figured there would be some way to do it since RoR sits on top of `rack`, which *is* compatible.)

At first I ran into the issue that `middleman-core` had a dependency of `activesupport ~> 4.2`, but -- upon seeing that this dependency was changed in cbad571 (#1967), I attempted to redirect my `Gemfile` to the master branch of this GH repo, assuming that would solve the issue. 

Unfortunately, however, I quickly hit another roadblock in that [`actionpack ~> 5.0.0.1`](https://github.com/rails/rails/blob/v5.0.0.1/actionpack/actionpack.gemspec#L24) has a dependency of `rack ~> 2.0` and the HEAD [`middleman-core`](https://github.com/middleman/middleman/blob/197093b36cf3e93ec0fc35f18e33dc6bff75e87c/middleman-core/middleman-core.gemspec#L23) specifically requires `rack >= 1.4.5, < 2.0`. 

Is there any way to either remove the upper limit on the rack version requirement, or else make it `< 3` to be in line with `rails`'s assumption that it won't change in a backward-incompatible way until at least the next major version increment? 

Thanks,
Mike

**Comment by tdreyno** [comment]
@mvastola I think that seems reasonable. We're pretty far down the line of dependencies. We needed Sinatra to support Tilt 2 to support Rack 2 :) The first two of those have been updated in the MM master branch, I think you're right about easing the rack requirement being the last step.

I really have no clue how backwards compatible rack 2 is. I'm also out of the country, traveling. Would you be able to do the early work of making a PR easing the dependency and seeing if the build breaks?

**Comment by mvastola** [comment]
@tdreyno PR Submitted. Travis is checking it now. Thanks.
