### ISSUE TITLE
link_to not working properly along with directory indexing

### ISSUE THREAD

**Issue by bertBruynooghe** [middleman/middleman#1985]
## Expected behavior and actual behaviour

`link_to` using `activate: activate :directory_indexes` and `set :relative_links, true` 
should create consistent links; it doesn't.
## Steps to reproduce the problem (from a clean middleman installation)

having a file `test.html.erb`

```
<%= link_to 'self', '/test' %>
```

 and having `activate :directory_indexes` and `set :relative_links, true` set in `config.rb`

creates following html: `<a href="/test">self</a>`, so no relative link.

'Fixing' the problem by changing the content of `test.html.erb` to

```
<%= link_to 'self', '/test/index.html' %>
```

creates wrong link: `<a href="./">self</a>`
## Additional information
- Ruby version:  2.1.6
- Middleman version: 4.1.10
- OS version: either on OSX and CentOS

**Comment by tdreyno** [comment]
So this is a file theoretically linking to itself?

**Comment by ryanhageman** [comment]
Is this still an issue?
