### ISSUE TITLE
Cannot view website on latest version of Chrome due to invalid certificate authority

### ISSUE THREAD

**Issue by Charlotteis** [middleman/middleman#1987]
## Expected behavior and actual behavior

Expected: Being able to use the website.
Actual: Cannot access the website.

## Steps to reproduce the problem (from a clean middleman installation)

- Be on the latest version of Chrome
- Try to go to https://middlemanapp.com

## Additional information

The error page I got from Chrome:

```
Attackers might be trying to steal your information from middlemanapp.com (for example,
passwords, messages or credit cards). NET::ERR_CERT_AUTHORITY_INVALID
```

<details>
middlemanapp.com normally uses encryption to protect your information. When Google Chrome tried to connect to middlemanapp.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be middlemanapp.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit middlemanapp.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.
</details>

**Comment by Charlotteis** [comment]
# Update

After deleting middlemanapp.com from Chromes list of insecure sites on `chrome://net-internals/#hsts` I now get told the security certificate is not good, but I can 'proceed anyway'. So at least I can view the site now!

**Comment by tdreyno** [comment]
I'll report to our web host.

**Comment by tdreyno** [comment]
They've fixed this.
