### ISSUE TITLE
Middleman-cli issue

### ISSUE THREAD

**Issue by lmvincent** [middleman/middleman#1988]
## Expected behavior and actual behavior
I upgraded my version of Ruby to 2.3.1 on Mac OS X 10.11.6. Everything installed well, including dependencies. However, when I went to use Middleman, my OS acted as if it had never been installed before. I re-installed using gem install middleman. Ever since, I have been unable to get Middleman working. I keep getting the error: 

Could not find proper version of middleman-cli (4.1.4) in any of the sources
Run `bundle install` to install missing gems.

Attempts to run bundle install result in error message:
Could not find middleman-cli-4.1.4 in any of the sources

## Additional information

- Ruby version: 2.3.1
- Middleman version: Cannot get a reading because of above error
- OS version: 10.11.6

**Comment by tdreyno** [comment]
Can you post your `Gemfile`?

**Comment by tdreyno** [comment]
Maybe delete `Gemfile.lock` and make sure `gem install bundler` succeeds. Then rerun `bundle install`?

**Comment by lmvincent** [comment]
Thanks for these options. It ended up being a dependency issue between ruby and ruby gems. It is now running properly. Thanks again.
