### ISSUE TITLE
No interpolation with yaml front matter

### ISSUE THREAD

**Issue by lifeiscontent** [middleman/middleman#1989]
I'm using I18n with middleman and I'm having trouble figuring out how I'm supposed to change the title of my page depending on the language.

is there an API for setting yaml front matter data from a ruby helper?

I've also notice that the `t` helper in the views doesn't do contextual i18n such as `t('.title')` being called in about/index.html and then the i18n lookup would be `about.index.title`

``` rb
module CustomerHelpers
  def dotterize(string)
    string.split(/\W/).slice(0..-1).join(".")
  end


  def t(*args, &block)
    results = if (/^\./ =~ args.first) != nil
      path = resource.target.gsub("localizable/", "").split(".").first
      super("#{dotterize(path)}.#{args.first}", *args.slice(1..-1))
    else
      super(args)
    end
  end
end
```

I've written a fix for this above, do you guys think something like this should be in middleman? Maybe I'm wrong, but the initial idea that I got of middleman is it was rails without the server. Is this thinking correct?

**Comment by tdreyno** [comment]
I hadn't seen contextual i18n. Seems clever. Do you have any links to documentation on that (probably from Rails). I'd be interested in supporting it.

**Comment by iwarner** [comment]
Hiya

Title as in Meta Title: in my locale - en.yaml - I have the following, some generic meta stuff, and some per page if I require it - I use a stub method - explained later:

More here: https://github.com/iwarner/CodeBlender-Middleman/tree/master/source/atom/meta

    # Meta
    meta :
        itemType         : "Website"
        publisher        : ""
        publisherAddress : ""
        rights           : "&copy; 2016, . All rights reserved."
        siteName         : ""

        index :
            author      : "Ian"
            description : ""
            title       : "Title here"
            type        : "website"

I have a meta.partial and this can work of three things - 1. Locale file, 2. Frontmatter and 3. Content_for (needed for proxy pages) - string is my own t method

i.e. :
    -# If there is meta tabs present then override the stub method
        - if current_page.data.meta
            - m = current_page.data.meta
       - else
           - m = "meta.#{ current_page.data.stub }"

    - title = current_page.data.meta ? m.title : :"#{ m }.title"

    -# Title
    %title= string( title )

So in a page I can do

    # Meta stub
    stub : index

or 
    ---
    meta :
        title       : "Search - CodeBlender"
    ---

or 

    -# Meta title
    - content_for :metaImage do
        = locals[ "title" ]
