### ISSUE TITLE
Sitemap doesn't use right path for resources in localizable folder

### ISSUE THREAD

**Issue by lifeiscontent** [middleman/middleman#1990]
## Expected behavior and actual behavior
**expected:**

resource has path `en/about/index.html`

**actual:**

resource has path `localizable/about/index.html`

## Steps to reproduce the problem (from a clean middleman installation)

1. Put html file in localizable folder
2. see path in sitemap resources.

## Additional information

- Ruby version: 2.3.0
- Middleman version: 4.1.10
- OS version: OSX 10.12

**Comment by tdreyno** [comment]
The `path` is the source of the file, not where it can be accessed. That would be `destination_path`.
