### ISSUE TITLE
Extension asset_hash breaks retina images

### ISSUE THREAD

**Issue by assimovt** [middleman/middleman#1991]
Looks like `asset_hash` extension does not support retina images. 

If I have an image named `foo.png` and `foo@2x.png`, the hashed result will be `foo-70a92df7.png` and `foo@2x-70a92df7.png`. Tho expected result is `foo-70a92df7@2x.png`.

**Comment by tdreyno** [comment]
There's nothing special about `@2x`, you should be able to point your CSS/JS at any file name if the retina-specific sizing is setup.

**Comment by assimovt** [comment]
Actually, there is. I am having a `@2x` version of an image and [this line of code](../blob/master/middleman-core/lib/middleman-core/extensions/asset_hash.rb#L96) does not support it. When I build the site, it does what I described above.

**Comment by assimovt** [comment]
@tdreyno Let me explain how I have it set up. I have a custom RedCarpet renderer that injects an attribute into an image tag to use [Retina.js](http://imulus.github.io/retinajs/). What this library is doing, is it swaps the images with `@2x` automatically. 

Now, this is a common practice to support retina images. I can't point them in CSS, because the pages are generated dynamically with the corresponding images.

So, why not we change [this line of code](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/extensions/asset_hash.rb#L96) to append digest before the `@?x` if it exists?

**Comment by tdreyno** [comment]
Looks like that library can be configured for different ways of finding renamed files: https://github.com/imulus/retinajs#manually-specifying-a-high-res-url
