### ISSUE TITLE
middleman init midlife-crisis

### ISSUE THREAD

**Issue by bretonio** [middleman/middleman#1992]
## Expected behavior and actual behavior

Reporting template, good idea!
Expected a successful initiation of the project with `middleman init midlife-crisis`
The error which yes, I know, is [not new](https://github.com/middleman/middleman/issues/1173), sorry:

``` sh
WARN: Unresolved specs during Gem::Specification.reset:
      rack (< 2.0, >= 1.4.5)
      activesupport (>= 3.1, ~> 4.2)
      ffi (>= 0.5.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/bretonio/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/resolver.rb:203:in `rescue in start': Bundler could not find compatible versions for gem "haml": (Bundler::VersionConflict)
  In Gemfile:
    frank was resolved to 1.0.12, which depends on
      haml (~> 3.0)

    middleman (>= 4.0.0) was resolved to 4.1.10, which depends on
      haml (>= 4.0.5)
```
## Steps to reproduce the problem (from a clean middleman installation)

Uninstall and `sudo gem install middleman`. 
Same error occurs. 
## Additional information

`rbenv which` returns

``` sh
/home/bretonio/.rbenv/versions/2.3.0/bin/middleman
```
- Ruby version: 2.3.0
- Middleman version: `middleman -v` returns error but see original error message
- OS version: Linux mintconditional47 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tdreyno** [comment]
Can you post the full log?

**Comment by bretonio** [comment]
Will do. As Ringo said in that Simpsons episode, sorry for the lateness of
my reply.
