### ISSUE TITLE
Cannot access data inside of proxy

### ISSUE THREAD

**Issue by zslabs** [middleman/middleman#1994]
## Expected behavior and actual behavior

To be able to access global `data` object within proxy function.
## Steps to reproduce the problem (from a clean middleman installation)

```
data['manifest'].each do |section|

  section[1].each_with_index do |hPage, index|
    proxy "/library/#{section[0]}/#{hPage}/index.html", "/library/templates/page.html", :layout => "library", :locals => { :section => section[0], :hPage => data.library[section[0]][hPage] }, :ignore => true
  end
end
```

`hPage` is empty.
## Additional information
- Ruby version: ruby 2.0.0p648
- Middleman version: 4.1.10
- OS version: 10.11.6 El Capitan

**Comment by nulltask** [comment]
Please try to invoke `proxy` inside of `after_configuration` block.

```ruby
after_configuration do
  # your code goes here
end
```

(Maybe it's a same issue: https://github.com/middleman/middleman/issues/1810#issuecomment-263795172)
