### ISSUE TITLE
i18n detect browser language

### ISSUE THREAD

**Issue by clstudio** [middleman/middleman#1997]
My config is:
`activate :i18n, :mount_at_root => false`

When I enter the Site at `/` I get:
```
File Not Found
 /
```

How can I make a detection of the browser language and redirect respectively
```
/ -> /en/
/ -> /de/
...
```

And at best that when a client selects a different language from the language menu, that is keeps this setting.

**Comment by tdreyno** [comment]
You'll need to write some Javascript client-side or use logic in your web host (nginx usually) to do the detection and redirection.
