### ISSUE TITLE
Article Subdirectories with Github Pages

### ISSUE THREAD

**Issue by aalvrz** [middleman/middleman#1998]
I am experiencing a situation similar to #818. I have a blog post `/posts/zenoss-renderers.html.markdown` with the following in my markdown:

`![Custom Renderer](/posts/2016-10-27-zenoss-renderers/zenoss_renderers2.png)`

Then I proceeded to create a directory with the name `2016-10-27-zenoss-renderers` and placed `zenoss_renderers2.png` inside.

When I test it locally using middleman server, I can see the image at the post's URL, as well as the blog's index URL.

However, when I deploy to Github pages, I can only see the image if I go to the article's page, but not from within the blog's index (which lists all the blog posts). I am confused since (if I am not mistaken) I am using an absolute path on the URL in my markdown.

Here is my **config.rb** file:

``` ruby
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false


set :date_format, '%a %b %d, %Y'

set :css_dir, 'css'
set :js_dir, 'js'
set :images_dir, 'img'

set :markdown_engine, :redcarpet
set :markdown, :fenced_code_blocks => true, :smartypants => true
set :haml, { ugly: true }

# Helper methods
helpers do

  def all_categories
    categories = []
    blog.articles.each do |article|
      category = article.metadata[:page][:category]
      categories.push(category) unless categories.include? category
    end
    return categories
  end

end

# Syntax Highlighting
activate :syntax

activate :blog do |blog|
  blog.prefix = "posts"
  blog.permalink = "{year}/{month}/{day}/{title}.html"
  blog.layout = 'article_layout'

  blog.tag_template = "tag.html"
  blog.calendar_template = "calendar.html"

  # Categories collection
  blog.custom_collections = {
    category: {
      link: '/categories/{category}.html',
      template: '/category.html'
    }
  }

  # Enable pagination
  # blog.paginate = true
  # blog.per_page = 10
  # blog.page_link = "page/{num}"
end

page "/feed.xml", layout: false

# Build-specific configuration
configure :build do
  activate :relative_assets

  set :relative_links, true

  activate :deploy do |deploy|
    deploy.build_before = true # runs build before deploying
    deploy.deploy_method = :git
    deploy.branch = 'master'
  end

  activate :directory_indexes
end
```
## Additional information
- Ruby version: 2.3.0
- Middleman version: 4.1.10
- OS version: Ubuntu 14.04 LTS

**Comment by veganstraightedge** [comment]
It is for me too

**Comment by tdreyno** [comment]
This is often due to posts being timestamped into the future. Local dev shows drafts, static builds do not.
