### ISSUE TITLE
Current Path 

### ISSUE THREAD

**Issue by sisihagen** [middleman/middleman#2002]
## Expected behavior and actual behavior
When I use normal pages like whatever/index.html all work perfectly, but with /blog/index.html nothing work. I become only the message:

`comparison of String with :current_path failed`

## Steps to reproduce the problem (from a clean middleman installation)

Install new middleman and middleman blog, take in blog a markdown file and then I become the trouble. Current Path failed, i run test with v2.3.1, v2.2.4 with version before I become message that rack need ruby 2.2. 

## Additional information

- Ruby version: 
2.3.1, 2.2.4

`
Environment

    Bundler   1.12.5
    Rubygems  2.4.8
    Ruby      2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
    GEM_HOME  /home/siefke/.rvm/gems/ruby-2.2.4
    GEM_PATH  /home/siefke/.rvm/gems/ruby-2.2.4:/home/siefke/.rvm/gems/ruby-2.2.4@global
    RVM       1.27.0 (latest)
    Git       2.10.2
    rubygems-bundler (1.4.4)

Bundler settings

    orig_path
      Set via BUNDLE_ORIG_PATH: "/home/siefke/.rvm/gems/ruby-2.2.4/bin:/home/siefke/.rvm/gems/ruby-2.2.4@global/bin:/home/siefke/.rvm/rubies/ruby-2.2.4/bin:/home/siefke/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0:/usr/games/bin:/home/siefke/.bin/scripts:/home/siefke/.node_modules/bin:/home/siefke/.gem/ruby/2.3.0/bin"
    orig_gem_path
      Set via BUNDLE_ORIG_GEM_PATH: "/home/siefke/.rvm/gems/ruby-2.2.4:/home/siefke/.rvm/gems/ruby-2.2.4@global"

Gemfile

    # If you do not have OpenSSL installed, change
    # the following line to use 'http://'
    source 'https://rubygems.org'
    
    # For faster file watcher updates on Windows:
    gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]
    
    # Windows does not come with time zone data
    gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
    
    # Middleman Gems
    gem 'middleman', '>= 4.0.0'
    gem 'middleman-blog'
    gem 'middleman-livereload', '>= 3.4.6'
    gem 'middleman-sprockets', '>= 4.0.0'
    gem 'middleman-autoprefixer', '>= 2.7.0'
    gem 'middleman-syntax'
    gem 'middleman-minify-html'
    gem "middleman-deploy", "= 2.0.0.pre.alpha"
    
    # sass
    gem 'bourbon', '~> 5.0.0.beta.6'
    gem 'neat', '~> 1.8'
    gem 'bitters', '~> 1.4'
    gem "sassc", "~> 1.8"
    
    # summarize
    gem 'nokogiri'
    
    # For feed.xml.builder
    gem "builder"
    
    # markdown engine
    gem 'redcarpet'
    
    #source 'https://rails-assets.org' do
    #  gem 'rails-assets-jquery', '2.1.1'
    #end

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        activesupport (5.0.0.1)
          concurrent-ruby (~> 1.0, >= 1.0.2)
          i18n (~> 0.7)
          minitest (~> 5.1)
          tzinfo (~> 1.1)
        addressable (2.5.0)
          public_suffix (~> 2.0, >= 2.0.2)
        autoprefixer-rails (6.5.1.1)
          execjs
        backports (3.6.8)
        bitters (1.4.0)
          bourbon (>= 5.0.0.beta.6)
          sass (~> 3.4)
          thor (~> 0.19)
        bourbon (5.0.0.beta.7)
          sass (~> 3.4.22)
          thor (~> 0.19.1)
        builder (3.2.2)
        coffee-script (2.4.1)
          coffee-script-source
          execjs
        coffee-script-source (1.10.0)
        compass-import-once (1.0.5)
          sass (>= 3.2, < 3.5)
        concurrent-ruby (1.0.2)
        contracts (0.13.0)
        dotenv (2.1.1)
        em-websocket (0.5.1)
          eventmachine (>= 0.12.9)
          http_parser.rb (~> 0.6.0)
        erubis (2.7.0)
        eventmachine (1.2.0.1)
        execjs (2.7.0)
        fast_blank (1.0.0)
        fastimage (2.0.1)
          addressable (~> 2)
        ffi (1.9.14)
        haml (4.0.7)
          tilt
        hamster (3.0.0)
          concurrent-ruby (~> 1.0)
        hashie (3.4.6)
        htmlcompressor (0.2.0)
        http_parser.rb (0.6.0)
        i18n (0.7.0)
        kramdown (1.12.0)
        listen (3.0.8)
          rb-fsevent (~> 0.9, >= 0.9.4)
          rb-inotify (~> 0.9, >= 0.9.7)
        memoist (0.15.0)
        middleman (4.1.11)
          coffee-script (~> 2.2)
          compass-import-once (= 1.0.5)
          haml (>= 4.0.5)
          kramdown (~> 1.2)
          middleman-cli (= 4.1.11)
          middleman-core (= 4.1.11)
          sass (>= 3.4.0, < 4.0)
        middleman-autoprefixer (2.7.0)
          autoprefixer-rails (>= 6.3.1, < 7.0.0)
          middleman-core (>= 3.3.3)
        middleman-blog (4.0.1)
          addressable (~> 2.3)
          middleman-core (>= 4.0.0)
          tzinfo (>= 0.3.0)
        middleman-cli (4.1.11)
          thor (>= 0.17.0, < 2.0)
        middleman-core (4.1.11)
          activesupport (>= 4.2, < 5.1)
          addressable (~> 2.3)
          backports (~> 3.6)
          bundler (~> 1.1)
          contracts (~> 0.13.0)
          dotenv
          erubis
          execjs (~> 2.0)
          fast_blank
          fastimage (~> 2.0)
          hamster (~> 3.0)
          hashie (~> 3.4)
          i18n (~> 0.7.0)
          listen (~> 3.0.0)
          memoist (~> 0.14)
          padrino-helpers (~> 0.13.0)
          parallel
          rack (>= 1.4.5, < 3)
          sass (>= 3.4)
          servolux
          tilt (~> 2.0)
          uglifier (~> 3.0)
        middleman-deploy (2.0.0.pre.alpha)
          middleman-core (>= 3.2)
          net-sftp
          ptools
        middleman-livereload (3.4.6)
          em-websocket (~> 0.5.1)
          middleman-core (>= 3.3)
          rack-livereload (~> 0.3.15)
        middleman-minify-html (3.4.1)
          htmlcompressor (~> 0.2.0)
          middleman-core (>= 3.2)
        middleman-sprockets (4.1.0)
          middleman-core (~> 4.0)
          sprockets (>= 3.0)
        middleman-syntax (3.0.0)
          middleman-core (>= 3.2)
          rouge (~> 2.0)
        mini_portile2 (2.1.0)
        minitest (5.9.1)
        neat (1.8.0)
          sass (>= 3.3)
          thor (~> 0.19)
        net-sftp (2.1.2)
          net-ssh (>= 2.6.5)
        net-ssh (3.2.0)
        nokogiri (1.6.8.1)
          mini_portile2 (~> 2.1.0)
        padrino-helpers (0.13.3.3)
          i18n (~> 0.6, >= 0.6.7)
          padrino-support (= 0.13.3.3)
          tilt (>= 1.4.1, < 3)
        padrino-support (0.13.3.3)
          activesupport (>= 3.1)
        parallel (1.9.0)
        ptools (1.3.3)
        public_suffix (2.0.3)
        rack (2.0.1)
        rack-livereload (0.3.16)
          rack
        rb-fsevent (0.9.8)
        rb-inotify (0.9.7)
          ffi (>= 0.5.0)
        redcarpet (3.3.4)
        rouge (2.0.6)
        sass (3.4.22)
        sassc (1.10.1)
          bundler
          ffi (~> 1.9.6)
          sass (>= 3.3.0)
        servolux (0.12.0)
        sprockets (3.7.0)
          concurrent-ruby (~> 1.0)
          rack (> 1, < 3)
        thor (0.19.1)
        thread_safe (0.3.5)
        tilt (2.0.5)
        tzinfo (1.2.2)
          thread_safe (~> 0.1)
        uglifier (3.0.3)
          execjs (>= 0.3.0, < 3)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      bitters (~> 1.4)
      bourbon (~> 5.0.0.beta.6)
      builder
      middleman (>= 4.0.0)
      middleman-autoprefixer (>= 2.7.0)
      middleman-blog
      middleman-deploy (= 2.0.0.pre.alpha)
      middleman-livereload (>= 3.4.6)
      middleman-minify-html
      middleman-sprockets (>= 4.0.0)
      middleman-syntax
      neat (~> 1.8)
      nokogiri
      redcarpet
      sassc (~> 1.8)
      tzinfo-data
      wdm (~> 0.1.0)
    
    BUNDLED WITH
       1.12.5
`

- Middleman version: 
$ middleman version
Middleman 4.1.11

- OS version: 
Linux, Gentoo, Kernel 4.8

My Github port for new project > https://github.com/sisihagen/webroot
My Github repo for old project > https://github.com/sisihagen/silviosiefke.de

Maybe help output of middleman build -verbose, i put in the mistake part

```
error  build/en/blog/index.html
comparison of String with :current_path failed
/home/siefke/.rvm/gems/ruby-2.2.4/gems/tilt-2.0.5/lib/tilt/template.rb:162:in `sort!'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/tilt-2.0.5/lib/tilt/template.rb:162:in `evaluate'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/file_renderer.rb:79:in `render'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/template_renderer.rb:184:in `_render_with_all_renderers'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/template_renderer.rb:147:in `block in render'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/util.rb:21:in `instrument'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/template_renderer.rb:146:in `render'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/sitemap/resource.rb:154:in `render'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/rack.rb:112:in `process_request'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/rack.rb:66:in `block in call'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/rack.rb:65:in `catch'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/rack.rb:65:in `call'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/lint.rb:49:in `_call'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/lint.rb:37:in `call'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/builder.rb:153:in `call'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/mock.rb:74:in `request'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/rack-2.0.1/lib/rack/mock.rb:56:in `get'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/builder.rb:230:in `block in output_resource'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/util.rb:21:in `instrument'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/builder.rb:223:in `output_resource'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:451:in `call'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:451:in `call_with_index'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:422:in `process_incoming_jobs'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:404:in `block in worker'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:395:in `fork'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:395:in `worker'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:386:in `block in create_workers'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:385:in `each'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:385:in `each_with_index'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:385:in `create_workers'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:327:in `work_in_processes'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/parallel-1.9.0/lib/parallel.rb:241:in `map'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/builder.rb:135:in `output_resources'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/builder.rb:129:in `output_files'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/builder.rb:71:in `block in run!'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/util.rb:21:in `instrument'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/builder.rb:70:in `run!'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-cli-4.1.11/lib/middleman-cli/build.rb:80:in `block in build'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-core-4.1.11/lib/middleman-core/util.rb:21:in `instrument'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-cli-4.1.11/lib/middleman-cli/build.rb:79:in `build'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/home/siefke/.rvm/gems/ruby-2.2.4/gems/middleman-cli-4.1.11/bin/middleman:72:in `<top (required)>'
/home/siefke/.rvm/gems/ruby-2.2.4/bin/middleman:23:in `load'
/home/siefke/.rvm/gems/ruby-2.2.4/bin/middleman:23:in `<main>'
/home/siefke/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/home/siefke/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

Silvio

**Comment by clstudio** [comment]
Same thing, I downgraded back to `4.1.10`

    comparison of String with :current_path failed

**Comment by sisihagen** [comment]
Tilt::SYMBOL_ARRAY_SORTABLE = false 

This in the config.rb fix it at moment. 

*https://forum.middlemanapp.com/t/comparison-of-string-with-current-path-failed/2422

**Comment by clstudio** [comment]
I saw that earlier and that didn't fix it for me
