### ISSUE TITLE
how to start middleman  automatically?

### ISSUE THREAD

**Issue by taroorat** [middleman/middleman#2003]
At centos7 like this:
[Unit]
Description=slate_server container

[Service]
Restart=always
WorkingDirectory=/home/slate
Environment=PATH=/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin
ExecStart=/usr/local/rvm/gems/ruby-2.3.0/bin/middleman server

[Install]
WantedBy=default.target

Then,the error like this:
Nov 08 14:36:22 hw001 middleman[43269]: /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'middleman-cli' (>= 0.a) among 16 total gem(s) (Gem::LoadError)
Nov 08 14:36:22 hw001 middleman[43269]: Checked in 'GEM_PATH=/.gem/ruby/2.3.0:/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0', execute `gem env` for more information
Nov 08 14:36:22 hw001 middleman[43269]: from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
Nov 08 14:36:22 hw001 middleman[43269]: from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
Nov 08 14:36:22 hw001 middleman[43269]: from /usr/local/rvm/gems/ruby-2.3.0/bin/middleman:22:in `<main>'
Nov 08 14:36:22 hw001 middleman[43269]: from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
Nov 08 14:36:22 hw001 middleman[43269]: from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Nov 08 14:36:22 hw001 systemd[1]: slate-server.service: main process exited, code=exited, status=1/FAILURE

**Comment by taroorat** [comment]
solved：

[Unit]
Description=slate_server container

[Service]

Restart=always
WorkingDirectory=/home/slate
ExecStart=/bin/bash -lc 'bundle exec middleman server'

[Install]
WantedBy=default.target

**Comment by sandstrom** [comment]
@taroorat sounds like you got it working, right? If so, would you mind closing this issue?
