### ISSUE TITLE
Issue Gardening 🌿 🌷 🌾

### ISSUE THREAD

**Issue by sandstrom** [middleman/middleman#2004]
@tdreyno I noticed there are quite a few open issues that could be closed. It makes the project feel more alive and a smaller number of issues helps keeping things focused and lean.

So I've tried to help by doing some issue gardening, writing comments and cataloguing some of the oldest issues.

I suggest closing these:

https://github.com/middleman/middleman/issues/983
https://github.com/middleman/middleman/issues/1111
https://github.com/middleman/middleman/issues/1172
https://github.com/middleman/middleman/issues/1213
https://github.com/middleman/middleman/issues/1227
https://github.com/middleman/middleman/issues/1231
https://github.com/middleman/middleman/issues/1263
https://github.com/middleman/middleman/issues/1282
https://github.com/middleman/middleman/issues/1299
https://github.com/middleman/middleman/issues/1306
https://github.com/middleman/middleman/issues/1316
https://github.com/middleman/middleman/issues/1330
https://github.com/middleman/middleman/issues/1340
https://github.com/middleman/middleman/issues/1353
https://github.com/middleman/middleman/issues/1361
https://github.com/middleman/middleman/issues/1387
https://github.com/middleman/middleman/issues/1390
https://github.com/middleman/middleman/issues/1430
https://github.com/middleman/middleman/issues/1446

Some with open questions (can be closed in ~1 week if unanswered):

https://github.com/middleman/middleman/issues/1166
https://github.com/middleman/middleman/issues/1217
https://github.com/middleman/middleman/issues/1396

***

**Obviously the decision is entirely up to you. If you disagree feel free to keep issues open, or even delete the comments I've made in these issues!** 😃

**Comment by tdreyno** [comment]
Thanks @sandstrom. Sorry, been under the gun at work for months... stuff like this really helps me quickly work through stuff.

**Comment by sandstrom** [comment]
@tdreyno Happy to help! Here is a second batch of new issues! ⛵️ 


I've commented in all of these and I think they can be closed right away:

https://github.com/middleman/middleman/issues/1544
https://github.com/middleman/middleman/issues/1547
https://github.com/middleman/middleman/issues/1551
https://github.com/middleman/middleman/issues/1552
https://github.com/middleman/middleman/issues/1553
https://github.com/middleman/middleman/issues/1553
https://github.com/middleman/middleman/issues/1556
https://github.com/middleman/middleman/issues/1566
https://github.com/middleman/middleman/issues/1569
https://github.com/middleman/middleman/issues/1576
https://github.com/middleman/middleman/issues/1585
https://github.com/middleman/middleman/issues/1594
https://github.com/middleman/middleman/issues/1606
https://github.com/middleman/middleman/issues/1609
https://github.com/middleman/middleman/issues/1612
https://github.com/middleman/middleman/issues/1639
https://github.com/middleman/middleman/issues/1643
https://github.com/middleman/middleman/issues/1673
https://github.com/middleman/middleman/issues/1690
https://github.com/middleman/middleman/issues/1693
https://github.com/middleman/middleman/issues/1703
https://github.com/middleman/middleman/issues/1724

These has some open questions (feel free to have a closer look and decide the best action):

https://github.com/middleman/middleman/issues/1722
https://github.com/middleman/middleman/issues/1726
https://github.com/middleman/middleman/issues/1729

**Comment by sandstrom** [comment]
ping @tdreyno (there is a second batch of issues in the comment above)

**Comment by sandstrom** [comment]
Here is a third batch of issues. Slowly working down the issue count. Of course closing all issues won't solve everything, but I think working down the issue-count to something manageable will make it a lot easier to focus energy.

I think removing sprockets was a good step. But that there are still room for further reductions/simplifications. That way, the core can provide the basics and special stuff can come through extensions.

### I'd suggest closing
https://github.com/middleman/middleman/issues/1447
https://github.com/middleman/middleman/issues/1461
https://github.com/middleman/middleman/issues/1483
https://github.com/middleman/middleman/issues/1486
https://github.com/middleman/middleman/issues/1503
https://github.com/middleman/middleman/issues/1520
https://github.com/middleman/middleman/issues/1523
https://github.com/middleman/middleman/issues/1536
https://github.com/middleman/middleman/issues/1750
https://github.com/middleman/middleman/issues/1757
https://github.com/middleman/middleman/issues/1773
https://github.com/middleman/middleman/issues/1776
https://github.com/middleman/middleman/issues/1780
https://github.com/middleman/middleman/issues/1783
https://github.com/middleman/middleman/issues/1784
https://github.com/middleman/middleman/issues/1788
https://github.com/middleman/middleman/issues/1797
https://github.com/middleman/middleman/issues/1799
https://github.com/middleman/middleman/issues/1801
https://github.com/middleman/middleman/issues/1804
https://github.com/middleman/middleman/issues/1807
https://github.com/middleman/middleman/issues/1810
https://github.com/middleman/middleman/issues/1811
https://github.com/middleman/middleman/issues/1824
https://github.com/middleman/middleman/issues/1827
https://github.com/middleman/middleman/issues/1828
https://github.com/middleman/middleman/issues/1834
https://github.com/middleman/middleman/issues/1840
https://github.com/middleman/middleman/issues/1841
https://github.com/middleman/middleman/issues/1848
https://github.com/middleman/middleman/issues/1859
https://github.com/middleman/middleman/issues/1865
https://github.com/middleman/middleman/issues/1883
https://github.com/middleman/middleman/issues/1885
https://github.com/middleman/middleman/issues/1889
https://github.com/middleman/middleman/issues/1895


### I asked a question
https://github.com/middleman/middleman/issues/1458
https://github.com/middleman/middleman/issues/1736
https://github.com/middleman/middleman/issues/1753
https://github.com/middleman/middleman/issues/1756
https://github.com/middleman/middleman/issues/1758

**Comment by eemi** [comment]
I´d suggest to also close #2069

**Comment by sandstrom** [comment]
@tdreyno I think most of the issues mentioned above will be hit by the stale bot.

But if any of them isn't, you can review them manually.
