### ISSUE TITLE
Directory already watched (listen error)

### ISSUE THREAD

**Issue by sandstrom** [middleman/middleman#2008]
I'm getting errors like this from guard/listen.

```
** ERROR: directory is already being watched! **

Directory: /Users/my-user/website/tmp/source_map_concat-output_path-zglQTS89.tmp/js

is already being watched through: /Users/my-user/website/tmp/source_map_concat-output_path-zglQTS89.tmp/js

MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
** ERROR: directory is already being watched! **

Directory: /Users/my-user/website/node_modules/broccoli-babel-transpiler/node_modules/babel-core

is already being watched through: /Users/my-user/website/node_modules/broccoli-babel-transpiler/node_modules/babel-core

MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
```

My guess would have been that either of these two lines should prevent it:
1. https://github.com/middleman/middleman/blob/604c0e2b5d2c17a4fee85f8fd80d62cacd1f1652/middleman-core/lib/middleman-core/sources/source_watcher.rb#L179
2. https://github.com/middleman/middleman/blob/604c0e2b5d2c17a4fee85f8fd80d62cacd1f1652/middleman-core/lib/middleman-core/sources/source_watcher.rb#L53 

*Out of curiosity, should those two lines be merged into a single list of ignored directories? They differ slightly.*

Any thoughts on what may cause this?

## Additional information

- Ruby version: 2.3.1
- Middleman version: 4.1.11
- OS version: macOS 10.11.6 (El Capitan)

**Comment by cveneziani** [comment]
I'm getting the exact same error.

```
== The Middleman is loading
        ** ERROR: directory is already being watched! **

        Directory: /home/my_user/website/source/assets/fonts/font-awesome

        is already being watched through: /home/my_user/website/node_modules/font-awesome/fonts

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
```

Things to know in my case, I created a symbolic link from `node_modules/font-awesome/fonts
` to `source/assets/fonts/font-awesome`. Is there a way to prevent this error or a better way to do so?

## Stack

- Ruby version: 2.3.3
- Middleman version: 4.2.0
- OS version: GNU/Linux Ubuntu 16.04

**Comment by LukyVj** [comment]
Up ☝️

**Comment by FooBarWidget** [comment]
I'm getting this error too, but it's complaining about the .pnp directory created by Yarn's [PnP mode](https://yarnpkg.com/lang/en/docs/pnp/).

**Comment by tdreyno** [comment]
I suspect this is always because of symlinks?

**Comment by tdreyno** [comment]
This is the ignored list: 

https://github.com/middleman/middleman/blob/186bfb9c266b0ffd3f0824a33c614fe9afd3cf5e/middleman-core/lib/middleman-core/sources/source_watcher.rb#L53
