### ISSUE TITLE
Redirect issue

### ISSUE THREAD

**Issue by maxiloc** [middleman/middleman#2011]
## Expected behavior and actual behavior

Redirect example from the doc is not working: 
```
redirect "/my/old/path.html", to: "/my/new/path.html"
```

but

```
redirect "my/old/path.html", to: "/my/new/path.html"
```

is working fine.

I dig a bit into the issue. 

It seems to come from here https://github.com/middleman/middleman/blob/7c968b9572923fd0f7fb176ca8e52a91727adf84/middleman-core/lib/middleman-core/sitemap/store.rb#L155
`request_path` is `my/old/path.html` but the key in `@ _lookup_by_destination_path` is `/my/old/path.html`

## Additional information

- Ruby version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
- Middleman version: 4.1.10

**Comment by matiasgarciaisaia** [comment]
Is there any legal use case for storing a non-normalized URL in both the `@_lookup_by_destination_path` and `@_lookup_by_path` hashes?

I don't see any user of that hash but the store itself. If we normalize the paths both when storing and accessing, then this bug should get fixed.

The only drawback is if there's any extension/customization that is [ab]using this feature to distinguish between both paths (`/my/path` and `my/path`), but [I don't think we want to care about that](https://xkcd.com/1172/).

If you're OK with the change, I'll do it.

**Comment by jesper-dk** [comment]
I can confirm that I'm still seeing this, on MM 4.2.1 on OSX 10.12 with Ruby 2.4.1.

**Comment by tdreyno** [comment]
@matiasgarciaisaia Seems like the `@_` prefix is screaming at anyone looking that this is a "private" variable. Should be safe to normalize both. Mind putting a quick PR up and see if it passes the test suite?

**Comment by sgnl** [comment]
Just ran into this. Thanks for reporting the issue!
