### ISSUE TITLE
Crash when a .ts file is present in source

### ISSUE THREAD

**Issue by iv-mexx** [middleman/middleman#2012]
## Expected behavior and actual behavior

I'm trying to use Typescript in a Middleman Project. Note: I **dont** want MM to process the typescript, in fact I've already got webpack as external pipeline working.

However, as soon as a file with file ending `.ts` is present somewhere in `source/`, Middleman crashes (at `build` and at `server`).: 

<details>
<summary>Stacktrace</summary>

```bash

/Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/typescript.rb:2:in `require': cannot load such file -- typescript-node (LoadError)
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/typescript.rb:2:in `<top (required)>'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:243:in `require'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:243:in `block in lazy_load'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:241:in `each'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:241:in `lazy_load'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:216:in `lookup'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:154:in `[]'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt.rb:48:in `[]'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:336:in `strip_extensions'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:324:in `record_file_change'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:265:in `block in update'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:264:in `each'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:264:in `update'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:212:in `poll_once!'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/sources.rb:241:in `block in poll_once!'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/sources.rb:241:in `each'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/sources.rb:241:in `reduce'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/sources.rb:241:in `poll_once!'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/core_extensions/file_watcher.rb:47:in `before_configuration'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `block in execute'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `execute'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/application.rb:283:in `initialize'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-cli-4.1.11/bin/middleman:51:in `new'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-cli-4.1.11/bin/middleman:51:in `<top (required)>'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/bin/middleman:23:in `load'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/bin/middleman:23:in `<main>'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

```

</details>

This occurs even if I try to ignore `.ts` Files in `config.rb`: 

```
# ignore typescripts
ignore /(.*)\.ts/
```

### Expected Behavior: 

Expected behavior would be for MM to just ignore the `.ts` File.

### Workaround

I'm currently working around this issue by just naming my Typescript files with `.tsx` instead of `.ts`.

## Steps to reproduce the problem (from a clean middleman installation)

* `touch source/javascripts/test.ts`
* `middleman build`
* Optional: Add `ignore /(.*)\.ts/` to `config.rb`
* 💥 

Note: As I've just discovered when gathering the version information, even `middleman version` crashes when the `test.ts` file is present.

## Additional information

- Ruby version: `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]`
- Middleman version: `Middleman 4.1.11`
- OS version: `macOS 10.12.1`

**Comment by iv-mexx** [comment]
As @tdreyno pointed out in #2010, installing the `typescript-node` gem fixes the problem, however I feel like ignoring the `.ts` files should prevent this since I'm using the external pipeline anyway...

**Comment by iv-mexx** [comment]
Hm, I see why the `ignore` does not work - it's because this all happens right **before** config is parsed: 

From the stack trace: `from /Users/markuschmelar/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.1.11/lib/middleman-core/application.rb:283:in `initialize'`

```
      # Before config is parsed. Mostly used for extensions.
      execute_callbacks(:before_configuration)
```

**Comment by c01nd01r** [comment]
IMHO, we need to allow users configure the watcher for ignore some files in config.rb or to configure Tilt from config.rb.
Because [this](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/preview_server.rb#L163-L174) looks like a workaround/trick/hack/etc...

**Comment by tdreyno** [comment]
That "hack" is just to avoid traversing insanely deep trees. The `listen` gem falls over itself.

Tilt must have added Typescript support recently... Can you post your full exception here? Wondering which extension is throwing that error

**Comment by c01nd01r** [comment]
@tdreyno 
typescript-node was installed.
<details>
  <summary>exception</summary>
<pre>
 $ middleman server
/Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/typescript.rb:2:in `require': cannot load such file -- typescript-node (LoadError)
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/typescript.rb:2:in `<top (required)>'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:243:in `require'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:243:in `block in lazy_load'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:241:in `each'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:241:in `lazy_load'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:216:in `lookup'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:154:in `[]'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt.rb:48:in `[]'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:336:in `strip_extensions'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:324:in `record_file_change'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:265:in `block in update'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:264:in `each'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:264:in `update'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:212:in `poll_once!'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/sources.rb:241:in `block in poll_once!'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/sources.rb:241:in `each'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/sources.rb:241:in `reduce'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/sources.rb:241:in `poll_once!'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/core_extensions/file_watcher.rb:47:in `before_configuration'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `block in execute'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `execute'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-core-4.1.11/lib/middleman-core/application.rb:283:in `initialize'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-cli-4.1.11/bin/middleman:51:in `new'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0@global/gems/middleman-cli-4.1.11/bin/middleman:51:in `<top (required)>'
	from /Users/c01nd01r/.rvm/rubies/ruby-2.3.0/bin/middleman:23:in `load'
	from /Users/c01nd01r/.rvm/rubies/ruby-2.3.0/bin/middleman:23:in `<main>'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
</pre>
</details>

**Comment by myrrlyn** [comment]
I've been using TypeScript for some time, but I don't have it in my `javascripts/` directory. Might that be your problem? I have my `tsconfig.json` set up to read from `source/typescripts/` and write to `source/javascripts`, and `middleman build` runs the `tsc` compiler as a before_build hook.

**Comment by nickgravelyn** [comment]
So I hit this issue today but my situation is a little different in that my .ts files aren't TypeScript, but are pieces of video data. Is there a way to get Middleman or Tilt to treat my .ts files as content (like a PNG) and just copy them over?

**Comment by tdreyno** [comment]
Looks like the mime type is already setup, but Tilt (the template handler) is trying to override and force it to be TypeScript.

```
      ".ts"        => "video/mp2t",
```

Try unregistering it from Tilt:

```
::Tilt.default_mapping.lazy_map.delete(".ts")
```

**Comment by nickgravelyn** [comment]
I tried adding that to the top of config.rb and it didn't make a difference. I have found that `.tsa` seems to be an acceptable extension for the [same format](https://en.wikipedia.org/wiki/MPEG_transport_stream) and that seems to avoid issues with TypeScript (.ts) and tab separated values (.tsv) extensions. I haven't yet tested on Netlify to ensure it comes with the correct mime type, though.

**Comment by oliverguenther** [comment]
One workaround is to simply move typescript out of the `source/` folder and let webpack compile it from somewhere else.

```
activate :external_pipeline,
         name: :webpack,
         command: build? ?
           "./node_modules/webpack/bin/webpack.js --bail -p" :
           "./node_modules/webpack/bin/webpack.js --watch -d --progress --color",
         source: ".tmp/dist",
         latency: 1
```

Middleman will pull in the entry points (assuming they're called `site.js` and `site.css`) from `.tmp/dist/site.js` `.tmp/dist/site.css`. In my case, I have a folder `./webpack` with the entrypoints.
