### ISSUE TITLE
Hook into Kramdown to add custom shortcodes

### ISSUE THREAD

**Issue by iwarner** [middleman/middleman#2013]
## Expected behavior and actual behavior

[[test]] shorcode renders the "test" kramdown custom decortator

Is there a way to hook into 
class Middleman::Renderers::MiddlemanKramdownHTML < ::Kramdown::Converter::Html

And provide custom shortcode generators

**Comment by tdreyno** [comment]
The markdown engines are swappable, so I'd suggest making your own class extended from either `Middleman::Renderers::MiddlemanKramdownHTML` or `Kramdown::Converter::Html` and telling MM to use that.

I think it'd be something like:

```
# Disable our markdown processing
set :markdown_engine, nil
```

then

```
::Tilt.prefer(YourClass, 'markdown')
```
