### ISSUE TITLE
Can't correctly install Middleman with Ruby 2.3.1 + bundler + Gemfile

### ISSUE THREAD

**Issue by wkoszek** [middleman/middleman#2021]
## Expected behavior and actual behavior

I use Middleman for my website: https://github.com/wkoszek/me
And I have the whole thing wired to Travis-CI: https://travis-ci.org/wkoszek/me/builds/181868721
I'm hitting weird issues: either with `middleman-cli` not getting loaded (you can see that in Travis link) or with a `middleman` command that doesn't have most subcommands.

BTW, I *think* a long time ago I could just do `gem "middleman"` and stuff would work. Since `middleman-cli` and `middleman-core` were introduced, I've had issues. I might be missing something obvious.

## Steps to reproduce the problem (from a clean middleman installation)

This will take a while, but if you build the Docker container, I think you should see the exact problem:

```
mkdir /tmp/wkoszek
cd /tmp/wkoszek
wget https://raw.githubusercontent.com/wkoszek/dockerfiles/master/wkoszek/me/Dockerfile
wget https://raw.githubusercontent.com/wkoszek/dockerfiles/master/wkoszek/me/entrypoint.sh
docker build -t wkoszek/me2 .
docker run -ti --entrypoint /bin/bash wkoszek/me2
```

After the last command you'll be inside of the container. Then I'm just trying to run `middleman`:

```
root@a94011ca0aaa:/me# bundle exec middleman
Commands:
  middleman help [COMMAND]          # Describe available commands or one specific command
  middleman sitemap_ping [options]  # Ping sitemaps
  middleman version                 # Show version

root@a94011ca0aaa:/me# bundle exec middleman build
Could not find command "build".
```

Looks like "build" command is not there at all. Not sure what's going on. This is weird.

On top of `Dockerfile` I declared Ruby 2.2.4 or 2.3.1. I get pretty much the same result.

## Additional information

- Ruby version: `ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]`
- Middleman version: `Middleman 3.4.1`
- OS version: `Linux a94011ca0aaa 3.16.0-49-generic #65~14.04.1-Ubuntu SMP Wed Sep 9 10:03:23 UTC 2015 x86_64 GNU/Linux`

**Comment by tdreyno** [comment]
Middleman 3? Is that on purpose? Can you post your `Gemfile` and `Gemfile.lock`?

**Comment by wkoszek** [comment]
@tdreyno My `Gemfile`:

```
# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman-cli"
gem "middleman-core"
gem "middleman-blog"
gem "middleman-blog-drafts"
gem 'middleman-blog-similar'
gem "middleman-minify-html"
gem "middleman-deploy"
gem "middleman-livereload"
gem "middleman-gh-pages"
gem "middleman-syntax"
gem 'middleman-imageoptim'
gem 'middleman-search_engine_sitemap'
gem 'middleman-sitemap-ping'
gem 'middleman-build-reporter'

# Let me do spellcheck development easily.
if ENV.include?("DEV") then
  File.delete("middleman-spellcheck")
  File.symlink("../middleman-spellcheck", "middleman-spellcheck")
  gem "middleman-spellcheck", '~> 0.9.2', :path => "middleman-spellcheck"
else
  gem "middleman-spellcheck", '~> 0.9.2',
	:git => "https://github.com/wkoszek/middleman-spellcheck.git",
	:branch => "nil_words_fix"
end

# HTML/CSS stuff.
gem 'bourbon'

# Testing
gem 'capybara'
gem 'selenium-webdriver'
gem "chromedriver-helper", "0.0.6"

# For feed.xml.builder
gem "builder", "~> 3.0"
gem 'rspec'		# spec/ requirement
gem 'rspec-core'	# spec/ requirement
gem 'poltergeist'
```

**Comment by wkoszek** [comment]
@tdreyno Does anything here look incorrect?

**Comment by wkoszek** [comment]
@tdreyno What I think happened here is: bundler goes and tries to figure out the lowest common denominator for all modules to work, and I've had these guys enabled:

https://github.com/minivan/middleman-spellcheck/blob/master/middleman-spellcheck.gemspec
https://github.com/ngs/middleman-blog-similar/blob/master/middleman-blog-similar.gemspec

This locked me into the 3.x Middleman. I think their dependency should be `>=`. I've removed them for now and with this `Gemfile`, I've upgraded to v4. This seemed to give me something that works.

But I think something is wrong anyway -- my previous `Gemfile` was de facto correct, yet gave me broken Middleman.

**Comment by tdreyno** [comment]
MM 3.x was released long before Ruby 2, much less 2.3, it seems pretty likely that the current Ruby landscape and code that old have become incompatible. We'll happily take PRs if there are uses stuck back in 3.x, but I've been using 4.x for almost 2 years now

**Comment by wkoszek** [comment]
@tdreyno Until I started to hit issues, I didn't know about `3.x` vs `4.x`. Users may not know the difference.

Plugins mentioned in the Middleman website still have requirements on `3.x`. If you happen to have some of them (and I do: `middleman-spellcheck` and `middleman-blog-similar`), Bundler will downgrade you to MM `3.x`.

Unclear what the good way to do this would be. Maybe the solution would be to just crash/throw big warnings when modules require `3.x`, so that we could catch them and fix them?

**Comment by blabassi** [comment]
@wkoszek @tdreyno Just for info MM 3.4.1 works with no issues on Ruby 2.3.1 (My team and I are currently using this version). So I guess the issue is more coming from extensions ?
