### ISSUE TITLE
Problems using content_for with Kramdown engine for content

### ISSUE THREAD

**Issue by itsjamie** [middleman/middleman#2022]
## Expected behavior and actual behavior

I would like to be able to use the content_for helper along with a markdown content file to move a Kramdown generated table of contents into another section of the layout.

I can name the file to parse the ERB block first, or to parse the section of markdown with the Kramdown parser, but I can't get the table of contents to be moved to the section I want in the layout.

```erb
<% content_for :toc do %>
* Will be replaced with the ToC
{:toc}
<% end %>
```

```erb
<div id="tcl">
      <%= yield_content :toc %>
</div>
<div class="content">
      <%= yield %> 
</div>
```

## Additional information

- Ruby version: Ruby v2.3.1
- Middleman version: 4.1.10
- OS version: macOS Sierra

**Comment by itsjamie** [comment]
If I'm missing another method of accomplishing this, like perhaps I'm able to access the Kramdown engine from inside the layout.erb to output the current page table of contents that would also be appreciated to know. Thank you!

**Comment by ryanhageman** [comment]
Is this still an issue?
