### ISSUE TITLE
Cannot access virtual machine preview server

### ISSUE THREAD

**Issue by H-enk** [middleman/middleman#2024]
I am running Middleman in a Virtual Machine (192.168.1.22) on a Windows 10 machine (192.168.1.10). How can I access the preview server from the Windows machine?

I tried to run `bundle exec middleman server -b 192.168.1.22`, but that did not work.

Also, I tried `activate :livereload, :host => "192.168.1.22", :js_host => "192.168.1.22"`, but that also resulted in:

`View your site at http://127.0.0.1:4567/`
`Inspect your site config at http://127.0.0.1:4567/__middleman`

As a workaround - to see what I am doing, I use `set :build_dir, '/opt/bitnami/apache2/htdocs'`

What am I missing?

**Comment by tdreyno** [comment]
`-h 0.0.0.0` will bind to all IPs, then you'll need to route a port into the VM from that VM's config.

**Comment by H-enk** [comment]
Thanks. But, it doesn't seem to work properly.

I ran `bundle exec middleman server -h 0.0.0.0`. That resulted in:

      Usage:
        middleman middleman:cli:server

      Options:
      -e, [--environment=ENVIRONMENT]
      -p, [--port=PORT]
            [--server-name=SERVER_NAME]                                  # The server name of preview server
            [--bind-address=BIND_ADDRESS]                                # The bind address of the preview server
            [--verbose], [--no-verbose]                                  # Print debug messages
            [--instrument], [--no-instrument]                            # Print instrument messages
            [--profile], [--no-profile]                                  # Generate profiling report for server startup
      -d, [--daemon], [--no-daemon]                                      # Daemonize preview server

      et cetera

In order to meet my deadlines I've switched to a Jekyll setup. I ran `bundle exec jekyll serve --host 0.0.0.0` and opened port 4000: `$ sudo ufw allow 4000`. I can access it OK from my Windows machine.

Maybe a look into the Jekyll code could help to make it work for Middleman? I am still interested in a solution, but with lo prio.

**Comment by tdreyno** [comment]
sorry, `--bind-address`, not `-h`

**Comment by H-enk** [comment]
Thanks, that did work: I got it running now!
