### ISSUE TITLE
Website docs are hard to navigate

### ISSUE THREAD

**Issue by mabraham** [middleman/middleman#2026]
## Expected behavior and actual behavior

Middleman website docs should have something like a table of contents and cross links between pages. It doesn't seem to have those on Android.

## Steps to reproduce the problem (from a clean middleman installation)

On Android the Docs link takes me to the installation page which has one link, for starting a new site, which had zero links. So I can't find out how to use Markdown pages unless I use the search box.

## Additional information

This report refers to the website not the repository.

**Comment by tysongach** [comment]
Hi @mabraham,

I merged in https://github.com/middleman/middlemanapp.com/commit/8c6ec458ce74ac38737a6a95d29194df946854f1 on the website, which restructured how the documentation navigation built. It should now be viewable on small screens.
