### ISSUE TITLE
Support for liquid v4.0.0

### ISSUE THREAD

**Issue by danielbayerlein** [middleman/middleman#2034]
At the moment the build brakes, because Middleman isn't compatible with `liquid` 4.0.0.

Changelog: https://github.com/Shopify/liquid/blob/master/History.md

**Comment by tdreyno** [comment]
Does liquid v3 still work? Can we just lock our Gemfile to that?

I don't think it' a good idea to forcefully upgrade our users to (what I assume is a backwards incompatible) major new version of liquid. Atleast until the holiday cobwebs and "dot zero" bugs are fixed.

**Comment by danielbayerlein** [comment]
With ( version ~> 3.0) f3bf478c2b5a4229ad6176bec85838c4cd153772 the build is successful.

With `liquid` 4.0.0:
```
Then I should see "Greetings"               # lib/middleman-core/step_definitions/server_steps.rb:90
  expected "Liquid error: internal" to include "Greetings" (RSpec::Expectations::ExpectationNotMetError)
  ./lib/middleman-core/step_definitions/server_steps.rb:91:in `/^I should see "([^\"]*)"$/'
  features/liquid.feature:6:in `Then I should see "Greetings"'
```

I'll try to debug the code.

**Comment by ryanhageman** [comment]
Is this still an issue?
