### ISSUE TITLE
Middleman with ember-cli halts standard middleman build

### ISSUE THREAD

**Issue by lcpriest** [middleman/middleman#2037]
#### Expected
Middleman with external_pipeline for ember-cli will have standard middleman routes and ember app will be served on subdirectory `/app/`.

#### Actual
Middleman with external_pipeline wipes out standard middleman build.

## Steps to reproduce the problem (from a clean middleman installation)
Example repo here: https://github.com/lcpriest/middleman-ember-test
1) `git clone git@github.com:lcpriest/middleman-ember-test.git` and skip to step 5

1a. add external_pipeline to middleman

```
activate :external_pipeline,
  name: :ember,
  command: "cd landing/ && ember #{build? ? :build : :serve} --environment #{config[:environment]}",
  source: "landing/dist/app",
  latency: 2
```

2. run `ember new landing`
3. change `environment.js` to update `rootURL: ''` to `rootURL: '/app/'`
4. Add `"output-path": "dist/app"`to `.ember-cli`

5. run `middleman server`

Given that a compiled ember app will also have an index.html, I put it into an `app/` subdirectory.

## Additional information

- Ruby version: 2.3.3
- Middleman version: 4.2.0
- OS version: 10.12.2

**Comment by tdreyno** [comment]
Sounds like you want the `source` to be `"landing/dist"`. You're expecting the build to include the `app` folder, right?

**Comment by lcpriest** [comment]
@tdreyno I probably shouldn't have used `app` as it's a bad example. The same thing with a random name like `other` productes the same results.
