### ISSUE TITLE
Middleman builds all localized files

### ISSUE THREAD

**Issue by pomartel** [middleman/middleman#2039]
I have a multilingual middleman site and each one is deployed on a separate domain. So my I18n extension is setup like this: `activate :i18n, :langs => [ TARGETTED_LOCALE ]`

Even if only one locale is specified, it will build and deploy all localized files, for example:
/localizable/privacy.de.html
/localizable/privacy.es.html
...

I also use a filter for the blog to only build the relevant blog articles this way:
```
activate :blog do |blog|
  blog.filter = proc { |article|
    article.tags.include? target.to_s
  }
end
```
Although the filter is working well, it also looks like it's building all blog articles, not just the filtered ones.

**Comment by tdreyno** [comment]
Can you try `:locales` instead of `:langs`?

**Comment by pomartel** [comment]
That doesn't change anything unfortunately. I've been trying to work around this issue using the `ignore` command but it doesn't seem to have any effect on the `localizable` folder. Even when I had `ignore "*.*"` on top of my `config.rb` file, it ignores all project files except those in the `localizable` folder. They are still built.

As for the blog, you had once recommended this to ignore some of the articles:
```
ready do
  blog.articles.each do |article|
    if !article.tags.include?(target.to_s)
      ignore article.path
    end
  end
end
```

In V4 I get an error since the `blog` variable can no longer be accessed from the config.

In any case, this is just a minor annoyance. It all works fine but it just takes a lot longer to deploy since Middleman building and deploying all files when I only need a small subset for each site.

**Comment by iwarner** [comment]
Correct the ignore command does not work inside the localizable folder ran several tests yesterday.

I dont think you need the localizable folder anymore - so simply remove it and the ignore commands will work. @tdreyno can you confirm this.

    # Build-specific configuration
    configure :development do

        # Ignore test file
        ignore "test.html"

        # Ignore test folder
        ignore "test/*"

        # Ignore international file
        # Does not work
        ignore "localizable/international.html"

        # Ignore a all folders in a folder except one
        ignore /blogs\/(?!test2)/

    end

**Comment by pomartel** [comment]
I tried removing the localizable directory and it doesn't seem to work with localized filenames.

So for example if I activate I18n for german:

```
activate :i18n, :langs => [:de]
```

Then the file `privacy.de.html.md` should render when accessing `/privacy`. This is not the case when I take the files out of the `localizable` dir.

There are really two issues here:
* Only the files for the specifed locales should be built.
* It should be possible to ignore files in the localizable folder.

As for the blog, I opened the issue in the Middleman-blog repo instead: https://github.com/middleman/middleman-blog/issues/332

**Comment by johnnyshields** [comment]
I've noticed the same issue affects localized dynamic templates with the `ignore: true`

**Comment by pomartel** [comment]
Thanks for the fix @johnnyshields! Just to wrap this up, this is snippet of code I use in my `config.rb` to ignore files not related to the current locale being built:
```
activate :i18n, :locales => [ current_locale ]
ignored_locales = all_locales - [current_locale]
ignored_locales.each do |locale|
  ignore "*.#{locale}.*"
end
```
`current_locale` and `all_locales` are just helper methods.
