### ISSUE TITLE
Default viewport meta tag is a bit hostile

### ISSUE THREAD

**Issue by danhalliday** [middleman/middleman#2047]
## Expected behavior and actual behavior

The default viewport meta tag created by Middleman is the following:

    <meta content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport">

Why is the scale fixed? This is not a good default for mobile users, as it means they can't pan to zoom.

## Steps to reproduce the problem (from a clean middleman installation)

- Create a new project with `middleman init foo`
- Take a look at `source/layout.erb`

## Additional information

- Ruby version: 2.3.1
- Middleman version: 4.2.1
- OS version: macOS 10.12.3

**Comment by tysongach** [comment]
I put a PR to fix this: https://github.com/middleman/middleman-templates-default/pull/7

**Comment by tysongach** [comment]
@danhalliday The PR above has been merged. Now when running `middleman init`, the viewport meta tag will be:

```html
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
```
