### ISSUE TITLE
Updated middleman - but JS/stylesheets now not working

### ISSUE THREAD

**Issue by beaulidden** [middleman/middleman#2051]
Hi guys. I noticed that when I ran a `gem list` commend, I saw `middleman (4.2.1, 3.4.1)` - so, in my repo I opened `Gemfile` and updated the gem accordingly:

From `gem "middleman", "~>3.4.1"`
To `gem "middleman", "~>4.2.1"`

After  a`bundle install` to double check everything was working, I successfully started things up via `bundle exec middleman` however, all my JS files/stylesheets aren't compiling. The files are *definitely* there, but Chrome is giving me a 404

`Failed to load resource: the server responded with a status of 404 (Not Found)   http://localhost:4567/sass/all.css`

Any hints?

**Comment by vvasabi** [comment]
A quick guess is that your files don’t have the full list of extensions. For example, a SASS file should be named `all.css.scss`. `all.scss` results in 404 in MM4.

**Comment by beaulidden** [comment]
Sure thing @vvasabi - so would this apply to every single `.scss` file? As an example; [here's a tree view of my stylesheets](https://imgur.com/a/XRgge). You're saying in order for things to compile properly, they'd all need `_<name>.css.scss` titles?

Thanks :)

**Comment by vvasabi** [comment]
Ones that are `@import`ed by Sass do not need the `.css` extension. Ones that are `<link />`ed do.

**Comment by beaulidden** [comment]
No luck. [Here's the output](https://imgur.com/a/eGeqi).

**Comment by vvasabi** [comment]
I don’t think vanilla Sass, which is what MM4 gives you, allows you to `@import` a folder like that. (MM4 removed a lot of things from the core.) Did that syntax work with MM3? If so, you may have to enable additional extensions to get the old behaviour back.

Alternatively, you can always `@import` individual files. If you use a third party library, there is a good chance that they provide a file that imports everything else for you.

**Comment by beaulidden** [comment]
Yep, the syntax seen above worked fine with MM3. I'll do some investigating and yes, if the * doesn't work, I'll just list out things individually :)

**Comment by beaulidden** [comment]
No luck. And now I've run into bigger issues. I'll close this off for now and open something else.

**Comment by andradei** [comment]
@vvasabi Renaming the file as `.css.scss` worked for me. Thanks.
