### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by tysongach** [middleman/middleman#2055]
Why is the [`middleman-minify-html`] extension not built-in like `minify_css` and `minify_javascript`?

[`middleman-minify-html`]: https://github.com/middleman/middleman-minify-html

**Comment by iwarner** [comment]
Maybe those are offered by Tilt or some other external package.

The preferred way is to now use Webpack or some other ecternal pipeline too.

**Comment by tdreyno** [comment]
It was always an esoteric feature that most devs didn't use, and honestly, it never saved enough kb to matter.

**Comment by iwarner** [comment]
I always use it :) any saved byte is always good :)

**Comment by tysongach** [comment]
@tdreyno Interesting. I just always felt it was weird to enable them all in `config.rb`, but only one needed me to manually add the extension itself. It’s more of a user experience issue when using Middleman (the path to “success” as a developer, i.e. enabling minification), and not a development problem (obviously it’s easy to add the gem).
