### ISSUE TITLE
Installed MM 3.4.1 but rbenv throwing an error

### ISSUE THREAD

**Issue by beaulidden** [middleman/middleman#2057]
After successfully installing MM 3.4.1 and doing a `bundle install`, I get the following error when I run the usual `bundle exec middleman`:

```
Beaus-MacBook-Pro:test beau$ bundle exec middleman
Expected string default value for '--instrument'; got false (boolean)
Expected string default value for '--reload-paths'; got false (boolean)
Expected string default value for '--instrument'; got false (boolean)
== The Middleman is loading
bundler: failed to load command: middleman (/Users/beau/.rbenv/versions/2.4.0/bin/middleman)
SyntaxError: /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap.rb:38: syntax error, unexpected keyword_do_block, expecting '}'
          layout: proc do |file, sitemap_app|
                         ^
/Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap.rb:38: syntax error, unexpected '|', expecting '='
t: proc do |file, sitemap_app|
                              ^
/Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap.rb:41: syntax error, unexpected '}', expecting keyword_end
        }, 'Callbacks that can exclude 
         ^
/Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap.rb:76: syntax error, unexpected keyword_end, expecting end-of-input
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:17:in `require'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:17:in `<top (required)>'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:124:in `require'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:124:in `new_app'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:31:in `start'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/cli/server.rb:89:in `server'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:72:in `method_missing'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:29:in `run'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:126:in `run'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:20:in `start'
  /Users/beau/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.1/bin/middleman:18:in `<top (required)>'
  /Users/beau/.rbenv/versions/2.4.0/bin/middleman:22:in `load'
  /Users/beau/.rbenv/versions/2.4.0/bin/middleman:22:in `<top (required)>'
```
By the looks of it I'm *assuming* I need to downgrade my version of Ruby, perhaps? I'm running `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`

Any help would be appreciated. Thanks :)

**Comment by iwarner** [comment]
@beaulidden As you are starting out with this - put your source code in a public github and link to this each time.

Seems you have some errors in your layout file - or have not declared one correctly so the auto magic is doing something strange.

**Comment by iwarner** [comment]
@beaulidden Also why are you on 3.x - 4 is the latest...

**Comment by beaulidden** [comment]
@iwarner sure thing re. public code.

I'm on 3.4.1 because the site I manage was built on 3.4.1 and I need to push some updates to it, urgently (2 weeks behind!) As you know, I've just finished battling with some issues with openssl and also some problems when I initially installed MM 4 and my stylesheets weren't loading for some reason.

So my rationale was to install 3.4.1, get things up and running, push the updates, then install MM 4 and get things working on that.

**Comment by beaulidden** [comment]
Okay code in the process of being pushed to the new Github repo :)

FYI the case above was me making a test folder and attempting a `middleman init` to see if stuff can get setup and working. Since posting I actually brought down the repo I'm wanting to access and work on/update and I'm now getting a problem with my JSON gem. I think it's because the default/system JSON gem is 2.0.2 and MM is wanting 1.8.3, so I'd need to downgrade. Not sure how to do that though!

**Comment by beaulidden** [comment]
Done: https://github.com/beaulidden/fac

**Comment by beaulidden** [comment]
But let me know if handling the CSS issue will be easy enough @iwarner because, if that's the case, I'll ditch this issue, update to MM 4, and we can go from there :) now that the code is up on the repo it'll be easier for guys like you to look at the source code and see where things may be going wrong!

**Comment by vvasabi** [comment]
I had no issue building the project using Ruby 2.3.1:
```
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

As such, I am suspecting that the problem came from Ruby 2.4. There have been patches to MM4 to make it Ruby 2.4 compatible, but MM3, no longer maintained, may not receive such fixes. So, please try downgrading Ruby to 2.3.1 and see if it will solve your issue.

**Comment by beaulidden** [comment]
Yep that did the trick @vvasabi thanks a lot :)

Now I can finally do my updates. After that I'm going to blow away both this outdated version of Ruby, and MM 3.4.1, and get everything working on MM4. Will let you guys know how I go.

Thanks again, also to you @iwarner :)
