### ISSUE TITLE
[ Algolia's docSearch ] Responsive

### ISSUE THREAD

**Issue by LukyVj** [middleman/middleman#2063]
Hi, 

Lucas Bonomi here, from www.algolia.com
I noticed your implementation of docsearch isn't fully responsive, 
Do you need some help to make it perfect :) ? 

Cheers!

**Comment by tdreyno** [comment]
@LukyVj That would be excellent. @tysongach has been working on some other responsive changes recently that might impact this on: https://github.com/middleman/middlemanapp.com

**Comment by tysongach** [comment]
Hi @LukyVj!

Yes, having the search be responsive would be fantastic. It’s been on my to-do list 😉 

I’ve found the current code implementation to be a bit cumbersome and confusing and was hoping to tidy that up while we’re at it. Altogether, the Sass for the search alone is nearly 750 lines of code 👻  Are these styles coming from somewhere, or are they written custom for middlemanapp.com?

**Comment by tysongach** [comment]
Ah, according to the [docsearch readme](https://github.com/algolia/docsearch#advanced-styling), it appears we dumped in the Sass source so we could customize it.

**Comment by LukyVj** [comment]
> I’ve found the current code implementation to be a bit cumbersome and confusing and was hoping to tidy that up while we’re at it.

I agree, this version's css is a bit overkilled, we plan to do a release in some time, with better css and better everything. 

Meanwhile, I would be glad helping you making it perfect.


Most of the styles are coming from [This file](https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.css)

Which is kind of mandatory, that being said, you can customize it easily, if you ever need help, just summon me!
