### ISSUE TITLE
Issue with file name resolution and Sitemap component

### ISSUE THREAD

**Issue by andreamoro** [middleman/middleman#2064]
## Expected behavior and actual behavior

In the middle of a WordPress to Middleman migration, I was after consolidating the html file with the images files under the same path. 

E.g. 

```/blog/category/post-name/index.html``` and
```/blog/category/post-name/test.gif```

So far I was almost able to get what I need, but the image files name is trimmed away and no matter how many files are within the folder, only one is shown as they all resolve into the root dir.

## Steps to reproduce the problem (from a clean middleman installation)

With the relative_path disabled in config.rb, I did create a subfolder in my /blog/subfolder named after the post-name, and added the images underneath. E.g. ```/blog/category/post-name/```
Then I referenced the images in the markdown code as follow 

```![Some Image](2015-04-02-london/test.gif) ```

I have effectively got what I want, however the rendered source code somehow trims away the file name, so the image asset can be recalled as ```/blog/category/post-name/```

However, if in the source code the name of the file is incorrectly spelt, the image will resolve in a 404 error.

The same happens in the middleman sitemap, thus meaning that no matters how many images are later included in the folder, only one is shown. 
In my case having two images, one test.gif and the other spinner.gif, I got the latter being displayed once, but after an update to middleman 4.2.1 (was 4.1.1) I got test.gif displayed. 

## Additional information

- Ruby version:  2.3.1p112
- Middleman version: 4.2.1
- OS version:  Mac OS X 10.11.6

**Comment by iwarner** [comment]
Hiya

This may belong in the blog repo then 

Also could you create a Mini repo that showcases this particular issue
