### ISSUE TITLE
relative links for the root url doesn't seem to work?

### ISSUE THREAD

**Issue by mehulkar** [middleman/middleman#2069]
## Expected behavior and actual behavior

If I define a `<%= link_to 'Home', '/' %>` like this (with `:relative_links` set to `true`) and deploy the build to a path that is not `/`, the link does not go to the subpath.

## Steps to reproduce the problem (from a clean middleman installation)

```bash
gem install middleman
middleman new site
cd site

# from a new middleman project
echo "<%= link_to 'Home', '/' %>" > source/index.html.erb

echo "set :relative_links, true" >> config.rb

# I don't think directory indices setting matters, but it's the
# config i'm using, just in case
echo "set :directory_indexes, true" >> config.rb

middleman build

# note start this from the middleman project root directory
# to simulate the website being at a subdir
python -m SimpleHTTPServer &

# go to the build at the subpath (`/build` is the `index` page)
open http://localhost:8000/build
```
You'll see that the "Home" link goes back to `/` instead of `/build` which is the relative home of the site.

## Additional information

- Ruby version: 2.3.1
- Middleman version: 4.2.1
- OS version: macOS Sierra

**Comment by eemi** [comment]
Instead of using '/' as path for your root, use '/index.html'. 

Ie:
<%= link_to 'Home', '/index.html' %>
