### ISSUE TITLE
Redcarpet doesn't render tables

### ISSUE THREAD

**Issue by minusfive** [middleman/middleman#2070]
## Expected behavior and actual behavior

When passed markdown tables like:
```markdown
| Header 1 | Header 2 |
|==========|==========|
| Value 1  | Value 2  |
```
And `config[:markdown_engine] = :redcarpet` is set, along with `config[:markdown] = {tables: true}` on `config.rb`, **output should be an HTML table**.

## Steps to reproduce the problem (from a clean middleman installation)

1. Set `config[:markdown_engine] = :redcarpet` and `config[:markdown] = {tables: true}` on `config.rb`.
2. Add markdown file with table markup as shown above.
3. No profit :(

I suspect it's an option whitelisting issue? Here are all my options set on `config.rb` if it helps:

```ruby
config[:markdown_engine]    = :redcarpet
config[:markdown]           = {
  smartypants: true,
  fenced_code_blocks: true,
  no_intra_emphasis: true,
  autolink: true,
  disable_indented_code_blocks: true,
  strikethrough: true,
  space_after_headers: true,
  superscript: true,
  underline: true,
  highlight: true,
  tables: true
}
```

## Additional information

- Ruby version: `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`
- Middleman version: `4.2.1`
- OS version: macOS Sierra `10.12.3`

**Comment by BigChief45** [comment]
I believe that table definition is incorrect. You must use hyphens instead:

```
| Header 1 | Header 2 |
|----------|----------|
| Value 1  | Value 2  |
```

**Comment by BigChief45** [comment]
I think this issue can be closed.

@iwarner
