### ISSUE TITLE
Could not find concurrent-ruby-1.0.5 in any of the sources

### ISSUE THREAD

**Issue by psaitu** [middleman/middleman#2071]
## Expected behavior and actual behavior
Running `middleman server` on a newly created project should run the server but instead it throws this error.
`Could not find concurrent-ruby-1.0.5 in any of the sources`
## Steps to reproduce the problem (from a clean middleman installation)
Create a new middleman project with `middleman init`
Run `middleman server`
## Additional information

- Ruby version: 2.3.1p112
- Middleman version: 4.2.1
- OS version: macOS 10.12.3

**Comment by tdreyno** [comment]
Does `bundle exec middleman server` make any difference?

**Comment by MicMicMon** [comment]
Run `bundle install` from within the directory.

**Comment by hackrzofheart** [comment]
Nothing will make it work unless you reinstall the metasploit-framework. I have been facing the issue for 1 week. I have personally tried and its running now. Run the following command in termux.

$ pkg upgrade && pkg install git && pkg install curl && pkg install wget && pkg install nmap && curl -LO raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh && chmod 777 metasploit.sh && ./metasploit.sh
