### ISSUE TITLE
Nested layouts via wrap_layout don't work with HAML

### ISSUE THREAD

**Issue by teejayvanslyke** [middleman/middleman#2072]
## Expected behavior and actual behavior

Given the default `layout.html.erb` inside `source/layouts`
And a new `page.html.haml` layout with the following markup:

```haml
- wrap_layout :layout do
  = yield
```

Using this layout on a page results in a blank page being rendered.

Per [this post on the Middleman forums](https://forum.middlemanapp.com/t/is-nested-layouts-broken-with-haml/1296), I tried replacing the layout with:

```haml
= wrap_layout :layout do
  = yield
```

(Note the `=`). Still no dice. Renders an empty page.

Using an ERB template in its place `page.html.erb` works fine.

## Additional information

- Ruby version: 2.4.0
- Middleman version: 4.2.1
- OS version: macOS Sierra

**Comment by mxlje** [comment]
ok, I just found this issue after almost giving up for the day trying to get this to work. I have an older Middleman app (v3.4.1) where this works perfectly. I started a new site today, using middleman v4.3.4 and I _cannot_ believe that this doesn’t work.

I can confirm that using a `.erb` layout file does indeed work.

**Comment by tdreyno** [comment]
@mxlje Can you make a small example repo with the failing case so I can help debug?
