### ISSUE TITLE
Tilt Requires Gems for Ignored Paths

### ISSUE THREAD

**Issue by fny** [middleman/middleman#2073]
## Expected behavior and actual behavior

I have a directory that I want to be ignored during the build process, but Middleman still attempts to load the required gem for Tilt for any special file extensions in the ignored folder.

## Steps to reproduce the problem (from a clean middleman installation)

Add a file with an extension that would require an added gem (e.g. LESS, TypeScript, LiveScript) and ignore the file. Then attempt to start a sever.

You'll get this error for whatever library tilt would require.

     `require': cannot load such file -- typescript-node (LoadError)
      from gems/tilt-2.0.7/lib/tilt/typescript.rb:2:in `<top (required)>'

https://github.com/fny/middleman_ignore_bug_example/commit/36267dcae6c6508f5b1e74fad152aa654686c998

## Additional information

- Ruby version: 2.4.0
- Middleman version: 2.4.1
- OS version: OS X 10.11

**Comment by juls** [comment]
This behavior is also described in #2012
