### ISSUE TITLE
middleman server: string.c:1075: str_new_frozen: Assertion `!(!(((struct RBasic*)((shared)))->flags&(RUBY_FL_USER1)))' failed.

### ISSUE THREAD

**Issue by stfnndrsn** [middleman/middleman#2075]
## Expected behavior and actual behavior

```
== The Middleman is loading
middleman server: string.c:1075: str_new_frozen: Assertion `!(!(((struct RBasic*)((shared)))->flags&(RUBY_FL_USER1)))' failed.
[1]    21784 abort (core dumped)  bundle exec middleman server
```

## Steps to reproduce the problem (from a clean middleman installation)
```
middleman init middleman 
cd middleman
echo 'gem "middleman-sprockets", "~> 4.1.0"' >> Gemfile
echo 'activate :sprockets' >> config.rb
bundle
bundle exec middleman server
```

## Additional information
- Ruby version: 
`ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`

- Middleman version: 
`middleman (4.2.1)`

- OS version: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

- Gemfile
```
gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem "middleman-sprockets", "~> 4.1.0"
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
```

**Comment by greggparrish** [comment]
It's a Ruby error.  Try using 2.3.1

**Comment by feargswalsh92** [comment]
@greggparrish  I am getting a similar error, I posted an issue about it #2079  ,but I AM using 2.3.1
any idea what gives? 
`Feargals-MacBook-Air:copyGoodMorning feargalwalsh$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
Feargals-MacBook-Air:copyGoodMorning feargalwalsh$ which ruby
/Users/feargalwalsh/.rvm/rubies/ruby-2.3.1/bin/ruby
Feargals-MacBook-Air:copyGoodMorning feargalwalsh$ 
'
