### ISSUE TITLE
Feature Request - Dead Link Checking by Default

### ISSUE THREAD

**Issue by JarLowrey** [middleman/middleman#2077]
I just [added this functionality](https://github.com/middleman/middleman/issues/902#issuecomment-293351039) using [HTML-Proofer](https://github.com/gjtorikian/html-proofer) to my own blog, and found a bunch of issues on a relatively small, simple site. I'd imagine most people would want this, but don't think of it/know it's available. Would it be possible to include an HTML-Proofer pass in `after_build` (rescuing errors to prevent workflow breaks) by default in the next version?

Downside: adds network calls and time to proof the build

Upside: significantly improves Middleman sites' quality by being on-by-default.

The downside of HTML-Proofer is that it checks the build instead of the source, so one error may appear multiple times (if, for example, a link was broken in the footer). There are many ways to create a link in source, so if someone made a new tool to check links in md and erb files it might not be as reliable. So it's a tradeoff but probably a necessary one.

**Comment by JTronLabs** [comment]
Or maybe a command line argument?

**Comment by iwarner** [comment]
I think this is best suited as an extension - https://middlemanapp.com/advanced/custom-extensions/

Certainly a useful tool.

**Comment by tdreyno** [comment]
Agreed
