### ISSUE TITLE
ERROR: Error installing middleman-core: middleman-core requires Ruby version >= 2.2.0

### ISSUE THREAD

**Issue by iamricky** [middleman/middleman#2078]
I keep getting the following error whenever I attempt to run `gem install middleman`:

```
ERROR:  Error installing middleman-core:
	middleman-core requires Ruby version >= 2.2.0.
```

I couldn't find an issue with this problem. Has anyone else run into this problem?

## Additional information

- Ruby version: `ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]`
- Middleman version: `middleman 3.3.12`
- OS version: `macOS Sierra v10.12.3`

**Comment by vvasabi** [comment]
> middleman-core requires Ruby version >= 2.2.0.
> Ruby version: ruby 2.1.2p95

You’ll need to install a newer Ruby version. You can do so via [RVM](https://rvm.io/) or [rbenv](https://github.com/rbenv/rbenv).
