### ISSUE TITLE
ignore: option not working with webpack

### ISSUE THREAD

**Issue by johnnyshields** [middleman/middleman#2080]
Using Middleman v4.2 (latest)

Currently I have in my project:

```
/sources/javascripts
/sources/stylesheets
```

I'm using Webpack to build the assets. I've noticed in my build output I get `/javascripts/` and `/stylesheets/` folders containing both the Webpack output assets (CORRECT) and the raw source files as compiled by Middleman, which I do NOT want.

If I set the `ignore:` option, it also ignores the Webpack output assets.

My workaround is to move my project files to:

```
/webpack/javascripts
/webpack/stylesheets
```

(i.e. outside the `/source/` folder) but it would be nice if `ignore:` didn't ignore Webpack.

**Comment by tdreyno** [comment]
The solution is to keep your web pack assets outside of the Middleman source folder. Alternatively you can ignore just the non-webpack input assets. So *.js or however you're able to differentiate the two. IIRC `ignore` takes a string, a regex or an anonymous function. So it's very customizable.

**Comment by johnnyshields** [comment]
So again the `ignore` option causes the webpack assets to be excluded from the build, because they also match the regex.

Separate folder is fine for now.

**Comment by tdreyno** [comment]
Right, any `external_pipeline` file is treated identically to any other middleman file when it comes to ignoring or proxying, etc. They are all just paths representing data which can be ignored.
