### ISSUE TITLE
blog pagination and i18n locale in index.html.erb

### ISSUE THREAD

**Issue by clstudio** [middleman/middleman#2088]
On `index.html.erb` you have to use `page_articles` instead of `blog.local_articles`

```
activate :blog do |blog|
    blog.permalink = "{lang}/{title}.html"
    blog.sources = "posts/{lang}/{year}-{month}-{day}-{title}.html"
    blog.tag_template = "tag.html"
    blog.calendar_template = "calendar.html"
    blog.paginate = true
    blog.per_page = 10
end
```

Trying to achieve:
on URL /en/ only paginate only articles from 'en' locale
on URL /de/ only paginate only articles from 'de' locale
...

Any ideas?

- Ruby version: 2.4.1
- Middleman version: 4.2.1
- OS version: OSX

**Comment by iwarner** [comment]
Hiya

Please re-create here - https://github.com/middleman/middleman-blog
Please also provide a repository also with this test in place

I have had issues myself also : https://github.com/middleman/middleman-blog/issues/242
