### ISSUE TITLE
Inbuilt XML Sitemap

### ISSUE THREAD

**Issue by ParthKolekar** [middleman/middleman#2091]
Middleman already builds a HTML sitemap. In honor of the DRY principal, I believe that there should be a inbuilt option to use generate a XML sitemap as well. The external plugins work great, but they are essentially adding a layer of repetition when running middleman in server mode. This ought to be just the case in dev environment, and the built prod lacks the sitemap in the first place.... But I believe that this should be a feature. Maybe in middleman/middeleman-blog if not a part of middleman/middleman. 

I could help doing this one if the concept / idea agrees with the design philosophy.

**Comment by tdreyno** [comment]
`core` has slim functionality by design. Adding an external plugin should only really be 2 lines (1 in bundle, 1 in config).

**Comment by ParthKolekar** [comment]
That was not the point. I feel that such a feature belongs in the core.

I believe you feel differently, so I will be sticking to using a plugin.
