### ISSUE TITLE
Contacting the developer

### ISSUE THREAD

**Issue by kagarmoe** [middleman/middleman#2092]
## Expected behavior and actual behavior
On `https://middlemanapp.com/support/` the text reads "Help support open source development by _contracting_ the developer to improve your project", when perhaps you mean "**contacting** the developer."

**Comment by vvasabi** [comment]
I think it was intentional. In order to sustain the development of this project and make a living, developers do need paid-for client projects. :smile:

**Comment by kagarmoe** [comment]
Possibly, but perhaps not. It isn't clear from this page.

**Comment by tdreyno** [comment]
I think the headline is fairly clear. "Paid Consultation & Development"
