### ISSUE TITLE
What is the purpose of NO_CONTRACTS?

### ISSUE THREAD

**Issue by axilleas** [middleman/middleman#2094]
This is more of a question than a bug report.

We're [investigating](https://gitlab.com/gitlab-com/www-gitlab-com/issues/1265) why our build times are big and the `NO_CONTRACTS=true` variable came up in the discussion, which indeed makes some difference. I found that the only relevant file is  [`middleman-core/contracts.rb`](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/contracts.rb), but not sure what it does.

The only reference I found was [in the forum](https://forum.middlemanapp.com/t/performance-middleman-4-vs-middleman-3/2046).

It seems this is not documented anywhere, I'd be happy to provide a PR to the docs when I understand what that does :)

---

PS. If you want to test with our repo, it's here https://gitlab.com/gitlab-com/www-gitlab-com/tree/master.

**Comment by Arcovion** [comment]
See the [contracts](https://github.com/egonSchiele/contracts.ruby) gem. It's used to add type signatures to certain methods [e.g. here.](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/extensions/cache_buster.rb#L19)
That file overrides and clears the gem's classes so no type checking is performed - they're only used internally, but the ENV option could do with a mention in the docs.
The option is there purely for speed; ignoring the contracts improves build times.

**Comment by axilleas** [comment]
Thanks :) As I was searching, I found out this video where it's explained https://youtu.be/WFEFKFBXIUM?t=19m49s. I believe we can close this issue now. I'll open a PR in the docs repo.
