### ISSUE TITLE
Sass source maps not being generated in development

### ISSUE THREAD

**Issue by 75th** [middleman/middleman#2096]
I have the exact same problem as reported in #1775, but the solution found there doesn't apply to my setup. No source maps are being generated, and I'm not using Sprockets. `/__middleman` reports `:sass_source_maps = true`. [Here's my config](https://gist.github.com/75th/5c361ecf2923a61f63a236bf571de954).

- Ruby version: `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin13]`
- Middleman version: 4.2.1
- OS version: macOS 10.12.5

**Comment by egermani** [comment]
Same deal for me -- did you happen to figure this one out, 75th?

I'm also using Webpack to compile Javascript, but I assumed that Middleman handled the Sass on its own.
