### ISSUE TITLE
Documentation and Icons licensed under CC BY 3.0

### ISSUE THREAD

**Issue by maxmacera** [middleman/middleman#2102]
In the PACKAGE: middleman-core 3.4.1
at the URL: https://github.com/middleman/middleman/blob/v3.4.1/middleman-core/fixtures/twitter-bootstrap-app/source/twitter-bootstrap-ebc6935/less/tests/css-tests.html
I found the following sentence: 
**_<p>Code licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>. Documentation licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
        <p>Icons from <a href="http://glyphicons.com">Glyphicons Free</a>, licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
      </footer>_**
-----------------------------
QUESTION: because I did not find any DOCUMENTATION and ICONS files in the Package middleman-core 3.4.1,   I please ask you to tell me where DOCUMENTATION and ICONS are. Perhaps are they downloaded at running time?

**Comment by tdreyno** [comment]
What?
