### ISSUE TITLE
what should a pdf generator extension look like?

### ISSUE THREAD

**Issue by josephholsten** [middleman/middleman#2104]
At the moment, I'm manually starting middleman server and using a rake task wrapping princexml to generate a pdf for a couple of pages in my site.

I'd love to move this properly into an extension, but I'm not sure exactly how this should look.

Should this build on the external pipeline? What would it look like to specify that a pdf should be generated from one of the HTML files?

Should this be an after_build step like in [middleman-book-template:extensions/book.rb# generate_pdf!](https://github.com/gettypubs/middleman-book-template/blob/master/extensions/book.rb#L55)? Would a server be running at that point? Again, how should a user specify that a pdf should be generated?

**Comment by egardner** [comment]
The solution we came up with for this was to use Middleman v4's [environment](https://middlemanapp.com/basics/upgrade-v4/#environments-and-changes-to-configure-blocks) features. So to build a PDF of the site using this template you'd run `bundle exec middleman build -e pdf` setting the environment to PDF.

This does the following in the extension you linked to here:
1. Builds the site normally using the `pdf` environment, allowing you to write conditional statements in your templates if you need to which only apply to print for example.
2. Then the `after_build` hook gets called, and I use that to call the custom `generate_pdf!` method you reference. This is really just a wrapper to call Prince from the CLI but it also generates a list of pages to provide as an argument.

This approach is totally compatible with an external pipeline for assets (I'm doing that in a project now that is in a private repo, but I can probably throw some code samples here if there is something specific you want to see).

And as mentioned above, in your templates, you can include conditional statements for different environments. So for print-only code, if you are using Haml or ERB you can test:

 ```ruby
- if environment? :pdf
  .my-print-element
- else
  .my-normal-element
```

It's been a while but I wrote about developing this extension [here](http://egardner.github.io/posts/2015/building-books-with-middleman/). I've used some version of this approach to build a [series of digital publications](http://www.getty.edu/publications/digital/digitalpubs.html) at the Getty, and it has worked well. The code for some of these books has been open-sourced here on GitHub too in case that is helpful.

Good luck!
