### ISSUE TITLE
Faster build times [up to 18x(?)]

### ISSUE THREAD

**Issue by dtorres** [middleman/middleman#2105]
With the current version of middleman, a build of my website will take 76 seconds.
Through some experimentation I've come to a (hasty I might add) patch that does the exact same build in 4 seconds

The patch is here:
https://github.com/dtorres/middleman/commit/6d9b38216e7d225e6bf75fa49218d3f5cfe3be26

Some notes:
- Currently middleman triggers parallel rendering but due to lock in Rack (I assume, I haven't thoroughly looked at how Rack works) all the benefits are rendered useless
- Disabling concurrency in the current version shaves off 1 or 2 seconds
- The machinery in Rack as is, accounts for the majority of build time.
- Looking at how the builder and rack client works, it simply calls the render method in the resource, then the builder only uses the status code to know if the build succeeded.
- With that in mind, the same can be achieved by knowing that if any errors occur during the build call, they will be caught by the catch in the builder class so it seems safe to directly call the render method.
- The current process adds a seemingly unnecessary lookup. resource.path -> rack -> sitemap.find_by_path -> resource.

Also, this is an issue instead of a PR because..
a) the patch is unworthy
b) I am unsure if there are dragons laying ahead I haven't encountered in my testing. Maybe from this issue a better solution can be reached

**Comment by dtorres** [comment]
Ran https://gitlab.com/gitlab-com/www-gitlab-com with and without the patch in my machine
- With:
`bundle exec middleman build --verbose  584.70s user 10.09s system 308% cpu 3:13.03 total`
- Without:
`bundle exec middleman build --verbose  780.24s user 37.19s system 311% cpu 4:22.20 total`

**Comment by tdreyno** [comment]
There is this old PR I made to replace all pieces of code relying on Rack to allow this kind of improvement: https://github.com/middleman/middleman/pull/1900

At the time, it was just after v4, so it seemed bad to break compatibility. Maybe it's time to bring that in, add something like this patch and get some great performance benefits.

**Comment by iwarner** [comment]
This would be a major victory if we can speed up the build, its a big issue with many would be adopters, they are swayed to other platforms based on build speed.

I will run this patch on my own setups now and see if there are any issues. Im glad to see GitLab running the blog as I want to make sure it compatable with that.

Will report back on findings. @dtorres Can you create a pull request for this also based on some of the work from @tdreyno thread also ?

**Comment by iwarner** [comment]
Hiya @dtorres and @tdreyno 

I tested this on my Deliveroo builds - few hundred articles

With
```
gem 'middleman-core', git: 'https://github.com/middleman/middleman.git', branch: 'master'
gem 'middleman-cli', git: 'https://github.com/middleman/middleman.git', branch: 'master'
site=foodscene.deliveroo.nl npm run build  178.43s user 4.90s system 263% cpu 1:09.46 total
site=foodscene.deliveroo.nl npm run build  181.18s user 4.96s system 253% cpu 1:13.32 total
site=foodscene.deliveroo.nl npm run build  182.48s user 5.29s system 239% cpu 1:18.25 total
```
and with the patch
```
gem 'middleman-core', path: '/var/www/Middleman/middleman'
gem 'middleman-cli', path: '/var/www/Middleman/middleman'
site=foodscene.deliveroo.nl npm run build  173.87s user 4.82s system 250% cpu 1:11.23 total
site=foodscene.deliveroo.nl npm run build  171.08s user 4.10s system 261% cpu 1:06.87 total
site=foodscene.deliveroo.nl npm run build  176.67s user 4.06s system 263% cpu 1:08.66 total
```
So I do not see a noticeable difference in build times

Seems the site rendered correctly with the patch which is good though.

Let me know if you want me to run instruments / profile on the above. I use Webpack also which takes 7 seconds.

**Comment by dtorres** [comment]
@iwarner Seeing your results prompt me to test some more and found that by removing Rack, as a side effect I stopped the pipeline that was actually taking time and preventing the multithreading from working.

Long story short, I had minify_javascript activated. deactivating it took me back to the ~4 seconds of build time with the current middleman release. (Along the journey I did some PRs for middleman-blog)

I will take a look at rewriting the minify_javascript extension to behave nicely but in the meantime... @tdreyno is it possible to put somewhere that using "minify_javascript" is strongly discouraged?

**Comment by tdreyno** [comment]
`minify_javascript` requires a JS runtime and the communication between ruby and that are just awfully slow :(

@dtorres I'm okay with updating the docs site to mention the poor performance and updating the default template (https://github.com/middleman/middleman-templates-default) with a callout.

If you know your platform and installed tools, it's probably fastest to add the cli for some of the popular minifiers and shell out to them directly `after_build`. 

`\`uglifyjs -- build/site.js > build/site.min.js\``

**Comment by iwarner** [comment]
We could look at mini_racer now instead of ruby_racer which is a bugger to install, based on lots of previous comments on here.

@dtorres - I minify JS through webpack, but use the minify_html plugin of middleman.
So I assume the tests I did would still stand in this case.

I will deactivate minify_html and test again then.

Will check out the blog PRs
