### ISSUE TITLE
include option in the config files

### ISSUE THREAD

**Issue by maru3l** [middleman/middleman#2106]
It's should be nice to have a `include: []` variable in the `config.rb` where we can specified some files we went to be copy in the build.

I'm publishing my web site on Netlify and I need to copy the `_headers` (it's the http headers configuration file for Netlify) to the build folder.

**Comment by tdreyno** [comment]
Hi @maru3l, anything in the source folder should be copied. Try copying the file into that location and it should appear in the build folder.

That said, the `_` prefix is special to Middleman and sometimes ignored since it signals a "partial" file

**Comment by maru3l** [comment]
Yes the file is ignore because of the `_`. It's why I was suggestion this work around.

**Comment by tdreyno** [comment]
You could try this command:

```
import_file File.expand_path("_headers", root), "/_headers"
```

Where the original `_headers` is at the root of your projecr

**Comment by maru3l** [comment]
It's working, thanks

**Comment by wrburgess** [comment]
This is not working for me at all, using:

```
ruby "2.4.3"
gem "middleman", "4.2.1"
```

I'm adding this line to my `config.rb` file:  `import_file File.expand_path("_headers", root), "/_headers"`

But I'm not seeing the `_headers` file moved to the `/build` directory after a re-build.

When I push to Netlify (same goal as the original issue creator) I get an error on the Netlify side, too:

`2:44:13 PM:        error  build/_headers`

Any ideas?

**Comment by wrburgess** [comment]
So, I stand corrected. I moved the `_headers` file from `source` root to project root (as you specified) and it did work on Netlify.

It doesn't seem to copy the file to the local `build` directory, but that matters less to me.

**Comment by michrome** [comment]
If the `_headers` file is in the `source` directory then use this in your `config.rb`:

```ruby
import_file File.expand_path("_headers", config[:source]), "/_headers"
```
