### ISSUE TITLE
middleman: command not found

### ISSUE THREAD

**Issue by onknows** [middleman/middleman#2112]
## Expected behavior and actual behavior
After installation I expect middleman command to exist. It doesn't

## Steps to reproduce the problem (from a clean middleman installation)
Ubuntu 16.04. Rbenv 1.1.1. Ruby 2.2.4 try

`gem install middleman`

Or try

`bundle install`

and then 

`middleman --version`

This shows something like

> middleman: command not found

## Additional information

- Ruby version: 2.2.4
- Middleman version: 4.2.1
- OS version: Ubuntu 16.04

**Comment by meowsus** [comment]
There's something wrong with your $PATH. Run `rbenv init` and make sure you follow the instructions.

**Comment by AfricanProgrammer** [comment]
THank you worked for me

**Comment by ur5us** [comment]
As a RVM user, `gem pristine middleman-cli` worked for me after cleaning up old `middleman` gem releases.

**Comment by Valerz** [comment]
@meowsus thanks! worked for me.
