### ISSUE TITLE
directory_indexes generate duplicated content in Google Console

### ISSUE THREAD

**Issue by Wooobee** [middleman/middleman#2114]
Hi,

I activated `:directory_indexes` for my website.

So now a site is reachable under:
 `/foo/index.html and `
`/foo`

So this is bad for some SEO reasons and Google Console shows me that I have duplicated content on my page.
Therefore I created a robots.txt to prevent google from indexing the .html pages.

```
User-Agent: *
Allow: /

User-Agent: *
Disallow: /*/index.html$

User-Agent: *
Disallow: /index.html$
```

Still some analytics tools tell me that is considered as duplicated content and I should use 
`<meta name="robots" content="noindex">`

Any suggestions or advice.
Best Manuel

**Comment by eemi** [comment]
You could use canonical URLs (https://support.google.com/webmasters/answer/139066?visit_id=1-636401750649320547-4089590398&hl=en&rd=1)

Add this in your template (change domain to suit your situation)

`<link rel="canonical" href="https://www.yoursite.com/<%= current_page.destination_path.gsub('index.html','') %>"/>`

**Comment by Wooobee** [comment]
thanks @eemi that helped me a lot.
In this post also found a different solution: https://forum.middlemanapp.com/t/when-making-dynamic-pages-with-local-data-is-it-possible-to-add-dynamic-content-to-the-frontmatter/1231/13

I added to config.rb
`set :url_root, 'https://www.example.de'`

and I added to my header:
`<link href="<%= config.url_root %><%= current_page.url %>" rel="canonical" />`

Best Manuel
