### ISSUE TITLE
Build only changed files

### ISSUE THREAD

**Issue by aviramga** [middleman/middleman#2122]
Hi Team,

I was wondering if there is a way to build only the files that update instead of re-running the whole build process every time. Our currently build time is around 20 minutes which is horrible for us.
We are using V3 of middleman (and from what I've read V4 doesn't present any significant performance improvements so no point for upgrading)

Thanks for your help!

**Comment by iwarner** [comment]
You can glob a single file, but if you use the blog or related files then it will not cascade to these.

https://github.com/middleman/middleman/issues/327
