### ISSUE TITLE
extensions.rb:86:in `load': Unknown Extension: autoprefixer.

### ISSUE THREAD

**Issue by hovancik** [middleman/middleman#2123]
Hi guys, 

I have gem called middleman-github-deploy and I have error in my tests, that I have no idea how to fix. 

To make debugging easier, I have put latest changes in here: https://github.com/hovancik/middleman-github-deploy/tree/feature/middleman-4.2 , so the ruby is > 2.2 and middleman is > 4.2

PR is here:  https://github.com/hovancik/middleman-github-deploy/pull/10

I have test running on travis, that give me an error:

```
/home/travis/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.2.1/lib/middleman-core/extensions.rb:86:in `load': Unknown Extension: autoprefixer. Check the name and make sure you have referenced the extension's gem in your Gemfile. (RuntimeError)
from /home/travis/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.2.1/lib/middleman-core/extension_manager.rb:51:in `activate'
from /tmp/mgd-Zesy/config.rb:4:in `evaluate_configuration!'
from /home/travis/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:329:in `instance_eval'
from /home/travis/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:329:in `evaluate_configuration!'
from /home/travis/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:286:in `initialize'
from /home/travis/.rvm/gems/ruby-2.2.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `new'
from/home/travis/.rvm/gems/ruby-2.2.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `<top (required)>'
from /home/travis/.rvm/gems/ruby-2.2.0/bin/middleman:23:in `load'
from /home/travis/.rvm/gems/ruby-2.2.0/bin/middleman:23:in `<main>'
from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

The test (test.sh) is really simple: 

I create new middleman project with `no | middleman new mgd-XXXX`, run `bundle install`, install my gem from source and then try running it. What my gem is trying to do is `middleman build`, which fails with error mentioned above. 

The gemfile of generated middleman project can be seen in test, and is: 

```
source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
```

I'm really lost here, so any ideas welcome.

**Comment by tochman** [comment]
I'm not sure if this is relevant, but I had a similar problem with running RSpec locally. My fix was requiring AutoPrefixer to my `spec_helper`

```
require 'middleman-autoprefixer'
```

**Comment by hovancik** [comment]
The error shows when I run `middleman build`, which is callled inside `test.sh`, not in specs, but thanks for the idea.

**Comment by andradei** [comment]
Have you solved your problem? I have the same issue with the `sprockets` gem.

**Comment by hovancik** [comment]
hi there, nope.

**Comment by tdreyno** [comment]
Sorry, I'm not following the original issue. Can you restate it?

Does `bundle exec middleman build` work? It's possible your script shell isn't passing along some context.

A plain init and build should be working fine, it's in the test suite.

**Comment by andradei** [comment]
In my case, `bundle exec middleman build` did not work. I my case I completed removed `sprockets`.

**Comment by tdreyno** [comment]
Sprockets or `middleman-sprockets`?

**Comment by andradei** [comment]
Both, actually. But I should have also said that the project I was assigned to maintain hadn't been updated in some 3 years.

**Comment by tdreyno** [comment]
@andradei Can you make a new ticket for this, with your actions and expectations. config.rb and Gemfile are also very helpful

**Comment by andradei** [comment]
@tdreyno I'll do it as soon as I have more time to gather the info. Thanks for the willingness to help.

**Comment by hovancik** [comment]
Well, I wish I could solve this, but doesn't look like it :)
