### ISSUE TITLE
Replacement for Compass

### ISSUE THREAD

**Issue by danielfriis** [middleman/middleman#2124]
## Expected behavior and actual behavior

Since Compass is no longer actively maintained, now might be the time to switch to another solution. Most recent version of bootstrap `4.0.0.beta2` depend on sass `>= 3.5.2`, but Middleman depends on sass `< 3.5` due to Compass:

````
middleman (= 4.2.1) was resolved to 4.2.1, which depends on
      compass-import-once (= 1.0.5) was resolved to 1.0.5, which depends on
        sass (< 3.5, >= 3.2)
````

## Steps to reproduce the problem (from a clean middleman installation)

`Gemfile`

````
source 'https://rubygems.org'

gem 'bootstrap', '4.0.0.beta2'
gem 'middleman', '4.2.1'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
````

`bundle install`

## Additional information

- Ruby version: `2.4.0p0`
- Middleman version: `4.2.1`
- OS version: `Mac OS 10.13`

**Comment by jalberto** [comment]
Why is htis clsoed, is already resolved?
