### ISSUE TITLE
RubyGems out of sync

### ISSUE THREAD

**Issue by danielfriis** [middleman/middleman#2125]
Including Middleman in Gemfile as normally, has dependency to `compass-import-once = 1.0.5`:

`gem 'middleman', '4.2.1'`

But including from git instead is up-to-date with no dependency to Compass:

`gem 'middleman', '4.2.1', git: "https://github.com/middleman/middleman.git"`

I.e. the gemspec files are different.

**Comment by danielfriis** [comment]
Realized that I was looking on non-released code. Waiting for #2050 to be released.

´ compass-import-once´ depends on ´sass <3.5´, while ´bootstrap 4.0.0.beta2´ depends on ´sass >= 3.5`

**Comment by cseelus** [comment]
@danielfriis How did you solve Bootstrap beta2 integration? Using middleman from Github gives me [this error](https://github.com/middleman/middleman/issues/2126).

**Comment by danielfriis** [comment]
@cseelus I referenced the 8e6aba9 commit, like this:

````
gem "bootstrap", "4.0.0.beta2"
gem "middleman", git: "https://github.com/middleman/middleman.git", ref: "8e6aba9"
````

**Comment by cseelus** [comment]
Thanks for the commit# @danielfriis, the [current master doesn't work](https://github.com/middleman/middleman/issues/2126) for me and others.

**Comment by danielfriis** [comment]
Same for me. That's why I'm referencing a older commit.
