### ISSUE TITLE
Make the build green

### ISSUE THREAD

**Issue by mojavelinux** [middleman/middleman#2129]
This issue is to track the job of making the build green again.

Currently, the builds are failing in Travis CI across the board:

https://travis-ci.org/middleman/middleman

As of right now, it's not possible to verify whether new features are bug or regression free since the results get lost in the noise of the standing failure. We need to fix this so that we can start accepting new features and releasing again.

**Comment by mojavelinux** [comment]
It might be a good idea to disable rubocop until we can get the tests to pass. Once the tests are passing, then we can work through the rubocop violations.

**Comment by mojavelinux** [comment]
It seems like the 2.5 build is failing because RVM can't find a candidate to install.

```
Requested binary installation but no rubies are available to download, consider skipping --binary flag.

Gemset '' does not exist, 'rvm ruby-2.5.0 do rvm gemset create ' first, or append '--create'.

The command "rvm use 2.5.0 --install --binary --fuzzy" failed and exited with 2 during .
```

Perhaps we can disable that job until we have the test passing on the released versions of Ruby.

**Comment by tdreyno** [comment]
Cool, just disabled 2.5.0

**Comment by tdreyno** [comment]
I'll try to dig in on this over the holiday.

**Comment by ferrisoxide** [comment]
Hey, problem may have been resolved in RVM now, see: https://github.com/rvm/rvm/commit/320608f1be1025c97ca1af7fdce43b7c0eb0c654

**Comment by strika** [comment]
The build is passing right now, so this issue can probably be closed.

**Comment by mojavelinux** [comment]
I agree!

(Though I'll note that the build is failing on ruby-head because it can't install bundler, but that's not on the critical path).
