### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by mattolson** [middleman/middleman#2137]
Can you please cut a new release? I am trying to get the latest bootstrap working with middleman, but there is a conflict over the sass version. In 8e6aba9d44f40d47352b41e89475c2ed92b93807, the dependency on compass was removed, which solves my problem, but this forces me to use a gitref instead of an actual release in my Gemfile. I am trying to create a project template, and git refs are incompatible with the code generation from a template. All in all, cutting a new release would solve my issue. Thanks!

**Comment by iwarner** [comment]
Would this help

simply pointing to master?

    # Middleman core
    # @see https://github.com/middleman
    gem 'middleman-core', git: 'https://github.com/middleman/middleman.git', branch: 'master'
    gem 'middleman-cli', git: 'https://github.com/middleman/middleman.git', branch: 'master'

**Comment by mattolson** [comment]
If I try to generate a project using a template that does this, the generated Gemfile changes it to `gem 'middleman', '~> 4.2'`

**Comment by iwarner** [comment]
Yes I understand that, did you try what I suggested?

**Comment by mattolson** [comment]
I'm sorry, I made a mistake. I was using a local project template, but hadn't checked in my latest changes to the Gemfile, which is why I wasn't getting the latest changes in the generated project. So to answer your question, yes that does work for me. Thanks!
