### ISSUE TITLE
Uninitialized constant Opal::Processor

### ISSUE THREAD

**Issue by numanosk** [middleman/middleman#2139]
## Expected behavior and actual behavior
Hi everyone,

All of a sudden, all my middleman commands give me this error message :

`
/Users/numajequier/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/tilt-2.0.8/lib/tilt/mapping.rb:246:in eval': uninitialized constant Opal::Processor (NameError)
Did you mean?  Process 
`

I installed `opal gem` just beforehand since I had a previous error message trying to lauch middleman commands: 

`/Users/numajequier/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/tilt-2.0.8/lib/tilt/mapping.rb:243:in require': cannot load such file -- opal (LoadError)
`

Does anyone have an idea how to fix it ?

Thank you in advance

## Steps to reproduce the problem (from a clean middleman installation)
Commands like : 
`middleman server`
`middleman -v`
`...`

## Additional information

- Ruby version: 2.3.5
- Middleman version: cannot verify it
- OS version: Sierra 10.12.6

**Comment by grantspeelman** [comment]
using `gem 'opal', '~> 0.10.5'` seemed to fix it for me

**Comment by tdreyno** [comment]
This happens if you try to "render" ruby files as templates by having them in source.

**Comment by matiaskorhonen** [comment]
I don't have any `.rb` files in `source`, but I do have some `.builder` files (for atom/RSS feeds), those shouldn't require Opal, should they?
