### ISSUE TITLE
Extensions: Is there a way to a callback when the server reloads?

### ISSUE THREAD

**Issue by johnnyshields** [middleman/middleman#2145]
Is there a way to a callback when the server reloads as a result of a file change? Would be nice to have `before_reload` and `after_reload`

I see callbacks before_configuration, before_build, etc.

I worked around this by adding:

```
    def manipulate_resource_list(resources)
      call_my_code
      resources
    end
```

**Comment by tdreyno** [comment]
You mean the entire server has to restart because of a ruby config or library file change?

That would be done like so, in the constructor of your extension:

Either call another method called `reload!` in your extension:

```
  def initialize(app, config={}, &block)
    super
    app.reload(&method(:reload!))
  end
```

Or use a block:

```
  def initialize(app, config={}, &block)
    super
    app.reload do
      # something
    end
  end
```

**Comment by johnnyshields** [comment]
@tdreyno I'd like the callback to trigger in both this case **and** when an individual file changes (without reloading the whole server)

**Comment by tdreyno** [comment]
```
app.files.on_change(:source, &method(:do_something))
```

Will call back on source file changes. There is also a `:data` option for data files. Combining those with the above and using the `&method` form should allow you to point all listeners at a single callback.
