### ISSUE TITLE
Importing gem assets through external pipeline (Webpack)

### ISSUE THREAD

**Issue by bastienrobert** [middleman/middleman#2151]
Before I installed Webpack and external pipeline using Webpack, I used Sprockets to import assets from a Gem to JS and CSS main file : `//= require async-image` and it works well.

Since I've setup the external pipeline, I'm not able to use Sprockets, it returns the following error in my JS console : `NoMethodError: undefined method 'start_with?' for nil:NilClass on line 113 of Users/bastien/.rvm/gems/ruby-2.3.1@global/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb) at application.js:1.`

Here's what I do :
- Clean Middleman install
- Import sprockets and my gem `middleman-async-image`
- It works perfectly
- Init npm
- Install the following dependencies:
```
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.26.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "css-loader": "^0.28.5",
    "extract-text-webpack-plugin": "^3.0.0",
    "node-sass": "^4.5.3",
    "postcss-loader": "^2.0.6",
    "sass-loader": "^6.0.6",
    "sinon": "^3.2.1",
    "style-loader": "^0.18.2",
    "webpack": "^3.5.5"
```
- Add these lines to `config.rb`:
```
activate :external_pipeline,
  name: :webpack,
  command: build? ? "npm run build:assets" : "npm run start:assets",
  source: ".tmp/webpack_output",
  latency: 1
```
- And setup the webpack.dev.config.js:
```
const path = require('path');

module.exports = {
  devtool: 'cheap-module-eval-source-map',
  entry: {
    all: path.join(__dirname, '/source/javascripts/index.js')
  },
  output: {
    path: path.join(__dirname, '.tmp/webpack_output'),
    filename: 'javascripts/[name].js'
  },
  resolve: {
    modules: [
      path.join(__dirname, 'source'),
      'node_modules'
    ]
  },
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: [
          { loader: 'style-loader', options: { sourceMap: true } },
          { loader: 'css-loader', options: { sourceMap: true } },
          { loader: 'postcss-loader', options: { sourceMap: true } },
          { loader: 'sass-loader', options: { sourceMap: true } }
        ]
      },
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        use: ['babel-loader']
      }
    ]
  }
};
```
- Relaunch my local server
- The error message is display in the JS console

I just want to import my JS and CSS files from my Gem to my application.css.scss and all.js. That's it.

Additional informations:

Ruby 2.4 - Middleman 4 - MacOS 10.13.2

**Comment by tdreyno** [comment]
Webpack does not have access to ruby files. If you want packaged asset dependencies, some npm packages do this and can be imported by Webpack.

**Comment by bastienrobert** [comment]
So any way to use external pipeline and middleman sprockets ?
