### ISSUE TITLE
How do execute the build command from a ruby script within the same ruby environment?

### ISSUE THREAD

**Issue by reidcooper** [middleman/middleman#2152]
Right now I have a custom ruby script that does my building pipeline and I currently execute middleman's build command by 

`system('bundle exec middleman build')`

However, I want to have access to the ruby scope (in memory here) without spinning out a new OS process, which means I do not have access to constants etc, within middleman.

How can I trigger the build command via my ruby script? It seems like I just need to require this file, `middleman-cli-4.2.1/lib/middleman-cli/build.rb`and execute the command like `Middleman::Cli::Build.new([]).invoke(:build)` or whatever. Not sure.

Any suggestions? Would be nice to have an API to be able to execute the build process without a CLI.

**Comment by tdreyno** [comment]
Check out the `::Middleman::Builder` class. 

https://github.com/middleman/middleman/blob/master/middleman-cli/lib/middleman-cli/build.rb#L109-L133
