### ISSUE TITLE
missing " " after middleman build

### ISSUE THREAD

**Issue by x-ch4mp-x** [middleman/middleman#2155]
I have code: 

<%= image_tag '/images/avatar/ch4mp.jpg', width: '90', height: '90', alt: 'Ch4mp' %>

on localhost it generated what I expected:
img src="images/avatar/ch4mp-fe9540c0.jpg" width="90" height="90" alt="Ch4mp"

however, after middleman build:
img src="images/avatar/ch4mp-fe9540c0.jpg" width=90 height=90 alt=Ch4mp

- Ruby version: 2.4 or 2.5
- Middleman version: 4.2.1
- OS version: linux

**Comment by reidcooper** [comment]
Perhaps try `:width => "90"`

**Comment by mojavelinux** [comment]
This looks like a minification optimization. What extensions do you have active in your build step?

**Comment by x-ch4mp-x** [comment]
you can use this new syntax with ruby 2.4 and later.

@reidcooper I tried that also, doesn't work.

**Comment by x-ch4mp-x** [comment]
@mojavelinux 

  activate :minify_html
  activate :minify_css

https://github.com/x-ch4mp-x/ch4mp.com/blob/master/config.rb

**Comment by mojavelinux** [comment]
> activate :minify_html

I guarantee you that's what's changing it. This is perfectly valid HTML. But it's optimized for computers, not humans.

**Comment by mojavelinux** [comment]
Honestly, I recommend against minifying html. There's absolutely no value in doing it and it can introduce problems. Just gzip your content on the server (which is the default for most web hosts like GitHub Pages).

**Comment by x-ch4mp-x** [comment]
@mojavelinux you were right, thank you!

**Comment by iwarner** [comment]
Hiya you can set options for the minification in the config also

please see below what I do

```
  # Minimise HTML
  # https://github.com/middleman/middleman-minify-html
  activate :minify_html do |html|
    html.remove_quotes = false
  end
```

Follow link to see full options
