### ISSUE TITLE
Process.fork is not supported by this Ruby

### ISSUE THREAD

**Issue by snowchime** [middleman/middleman#2160]
## Expected behavior and actual behavior
Hello - I just wanted to note first that my middleman project builds and displays successfully, but with a later version of middleman I now receive a warning during the build. I wanted to check to see if you know what is causing it "Process.fork is not supported by this Ruby"

## Steps to reproduce the problem (from a clean middleman installation)
On windows 7, from gem 'middleman', '~>4.0.0'   to  gem 'middleman', '~>4.2.1'  I get the warning above.

## Additional information

- Ruby version:  ruby 2.2.4
- Middleman version:  middleman 4.2.1
- OS version:  Windows 7

**Comment by toro705** [comment]
Any advance on this?

**Comment by tdreyno** [comment]
That is just a warning issue. It means your build may be slower, but you can ignore it.
