### ISSUE TITLE
Noob Question: Reference CSS files

### ISSUE THREAD

**Issue by pcabrera83** [middleman/middleman#2171]
## Expected behavior and actual behavior
Reference CSS File

## Steps to reproduce the problem (from a clean middleman installation)
`<%= stylesheet_link_tag "stylesheets/css/bundle" %>`
File Name: `bundles.css.scss`

## Additional information
I created my own CSS file and cannot load it in the DOM

- Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
- Middleman version: Middleman 4.2.1
- OS version: macOS High Sierra Version 10.13.4

**Comment by tdreyno** [comment]
Is `bundles.css.scss` in `src/stylesheets/css/`?

**Comment by pcabrera83** [comment]
yes, checkout my repo: https://github.com/pcabrera83/patcabrera.com

**Comment by tdreyno** [comment]
Try:

```
<%= stylesheet_link_tag "css/bundle" %>
```

Middleman is already aware of where CSS lives.
