### ISSUE TITLE
Is it possible to store layouts outside of the source directory?

### ISSUE THREAD

**Issue by supsup** [middleman/middleman#2172]
In MM3 you could store layouts anywhere often I stored them at the root level, now it seems in MM4 you have to store them inside the source directly only.  Is there a way to override this?
I like to keep my source folder as a separate git repo, and I don't want layouts in that repo.

**Comment by tdreyno** [comment]
They have to be in a source folder, but, you can add multiple system paths to be considered as sources.

```
files.watch :source, path: "/my/other/source/folder/on/disk"
```
