### ISSUE TITLE
Compatibility with SASS 3.5?

### ISSUE THREAD

**Issue by the-mimeoplasm** [middleman/middleman#2177]
## Expected behavior and actual behavior
I'm trying to use the latest SASS version because I'm using [col-start] for grid-templates, which cannot compile unless using SASS 3.5 or higher.

Does anyone know a workaround to this or when Middleman will provide an update? 

## Steps to reproduce the problem (from a clean middleman installation)
I'm using a clean Middleman version, fresh out the box.

## Additional information

- Ruby version: 2.4
- Middleman version: 4.2
- OS version: High Sierra

Related: #2165

**Comment by SnijderC** [comment]
Can't compile Bootstrap 4 with sass `<3.5.x`.

**Comment by tdreyno** [comment]
The library specified `>= 3.4`. Seems like you should be able to specify 3.5 in your gemfile and it'd work?
