### ISSUE TITLE
Documentation passing locals (to nested) partial

### ISSUE THREAD

**Issue by nicholasshirley** [middleman/middleman#2182]
I was following along with the [documentation on partials](https://middlemanapp.com/basics/partials/), but I was getting undefined when trying to pass a local variable. The partial is composed like this:

In view
`<%= partial "shared/component/component" %>`

shared/component/_component.html.erb

```
<div>
   ...markup...
  <%= partial "shared/component/thing", locals: { local_thing: "a string" } %>
  ...markup
</div>

```

shared/component/_thing.html.erb

```
<div>
  <%= local_thing %> should display here, but doesn't
</div>
```

This returns undefined variable or method `local_thing`.

To make this render, it needs to be called like this in shared/component/_thing.html.erb

```
<div>
  <%= locals[:local_thing] %> should display and now it does
</div>
```

This [SO post](https://stackoverflow.com/a/26539738/6769558) helped me figure it out.

<s>Is this because the partial is nested?</s> If so is it worth updating the documentation? I would be happy to do a PR for it if so.

Edit: I found the same behavior without nested partials. The only thing I haven't been able to do is include partials the way that the docs say to.

**Comment by tomrutgers** [comment]
What does your folder structure look like? 
Is `shared` a folder in `source` or in `source/partials`?

Try putting `_thing.html.erb` in `source/partials/shared/components/` and call it with
`<%= partial "partials/shared/component/thing", locals: { local_thing: "a string" } %>`

**Comment by nicholasshirley** [comment]
Turns out it was my fault with some mangled syntax :(

I just re-wrote and I'm able to pass locals in any of the following ways:

```
<%= thing %>
<%= :thing %>
<%= locals[:thing] %>
```

Thank you to all the maintainers & contributors! Being able to do simple static sites in ERB has been great :)
