### ISSUE TITLE
Middleman error on Codeship

### ISSUE THREAD

**Issue by henriqueutsch** [middleman/middleman#2185]
Hi,
How to fix a bug?
I have a difference between build in local machine and codeship

When middleman generate a build folder in codeship
create build/Agenda/index.html

When middleman generate a build in local machine
create build/agenda/index.html

This script can fix this.
cd build
for i in $( ls | grep [A-Z] ); do mv -i $i `echo $i | tr 'A-Z' 'a-z'`; done
mv blog Blog
cd ..

## Additional information

- Ruby version: 2.4.3
- Middleman version: 4.2.1 
- OS version:

**Comment by tdreyno** [comment]
This depends on the case sensitivity between your OS and also how git works.

Always using lowercase is the simplest. It's likely Codeship is Linux, your local dev is Mac OS or Windows.
