### ISSUE TITLE
In 4.3.0.rc.1, middleman server isn't run correctly

### ISSUE THREAD

**Issue by elct9620** [middleman/middleman#2187]
## Expected behavior and actual behavior

`middleman server` is running correctly.

## Steps to reproduce the problem (from a clean middleman installation)

Simple run `middleman init` and try to run `middleman server` then, I got this error message.

```
undefined method `run' for Middleman::PreviewServer:Class
```

1. Middleman 4.2.1 is working correctly
2. Middleman 4.3.0.rc.1 the `preview_server.rb` is `require 'rack'` correct, and can found `Rack` class, but it didn't see any method `run` in this file.

I also try to compare 4.2.1 and 4.3.0.rc.1, but I cannot find any clue relate to this error.
https://github.com/middleman/middleman/compare/v4.2.1...v4.3.0.rc.1

## Additional information

- Ruby version:  2.5.1
- Middleman version: 4.3.0.rc.1 
- OS version: macOS High Sierra 10.13.6

**Comment by tdreyno** [comment]
@elct9620 Do you have an example repo online I could pull to see this behavior?

**Comment by elct9620** [comment]
@tdreyno No, I just create a new project, and it happened.

**Comment by svoop** [comment]
Same here with identical setup and the following Gemfile:

```
source 'https://rubygems.org'

gem 'middleman', '= 4.3.0.rc.1'
gem 'middleman-autoprefixer', '~> 2.7
```

**Comment by erikdahlstrand** [comment]
Same problem here. Middleman 4.3.0.rc.2, Ruby 2.5.0 and a brand new Middleman site.

**Comment by tdreyno** [comment]
Thanks for the reports, tracked it down.
