### ISSUE TITLE
When will middleman 4.3.0.rc.2 drop on RubyGems?

### ISSUE THREAD

**Issue by motevets** [middleman/middleman#2194]
Hello middleman mainainters,

First, @tdreyno, thank you very much for merging in #2190. I also noticed that you bumped the version to 4.3.0.rc.2 in 64a65a73. What is the process, and when can we expect this to be released to RubyGems?

Thanks!

**Comment by tdreyno** [comment]
Done, sorry for the delay.

**Comment by tisba** [comment]
It's a bit confusing, since https://github.com/middleman/middleman/blob/master/CHANGELOG.md seems to be out of date.

middleman 4.3.1 seems to be the latest, officially released version. Yet I'm missing changes from https://github.com/middleman/middleman/pull/2149. It looks like the commit got lost somehow?

**Comment by tdreyno** [comment]
The former 4.3.0 beta became 5.0.x due to SemVer reasons. I can cherry-pick `master` changes to the stable `4.x` branch if anything got missed. I've just done that for the above commit. Let me know if there are others before I do a 4.3.2 for you.

**Comment by tisba** [comment]
Ah okay. Maybe you can update the CHANGELOG to reflect this? This would be very helpful 💕 

Anyhow, I was trying to figure out why I still got the `Haml::TempleEngine: Option :outvar is invalid` warning even after the update. As far as I can tell this is the only thing I'm aware of that I "need".

**Comment by tdreyno** [comment]
Done, 4.3.2 is out.

**Comment by tisba** [comment]
Awesome, thanks a lot!

**Comment by aandis** [comment]
Changelogs are still out of date though. Hard to figure out what's new with version `4.3.3`

**Comment by tdreyno** [comment]
https://github.com/middleman/middleman/blob/4.x/CHANGELOG.md
