### ISSUE TITLE
Internal Server Error not compiling/recognizing SCSS after Ruby version update

### ISSUE THREAD

**Issue by rkretch91** [middleman/middleman#2196]
## Expected behavior and actual behavior
I am getting an Internal Server Error that isn't registering my main.css.scss sheet. This only happened when I updated my ruby versions, and now any of my middleman applications with scss in it are not working. However, my non SCSS applications still run. 

## Steps to reproduce the problem (from a clean middleman installation)
I made a clean middleman installation and ran it on my local server and even then with no changes, there was a 500 Internal Server Error not recognizing the stylesheet. 

## Additional information

- Ruby version: 2.4.4
- Middleman version: 4.2
- OS version: High Sierra

**Comment by rkretch91** [comment]
Pretty new with MM and Ruby, so not sure if listing my local gems is helpful:
`activesupport (5.0.7)
addressable (2.5.2)
ast (2.4.0)
autoprefixer-rails (8.6.5)
backports (3.11.4, 3.11.3)
bigdecimal (default: 1.3.2)
bootstrap-sass (3.3.7)
builder (3.2.3)
bundler (1.16.5, default: 1.16.2)
byebug (10.0.2)
coderay (1.1.2)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
colored (1.2)
compass-import-once (1.0.5)
concurrent-ruby (1.0.5)
contracts (0.13.0)
did_you_mean (1.1.0)
diff-lcs (1.3)
dotenv (2.5.0)
erubis (2.7.0)
execjs (2.7.0)
faraday (0.15.3)
fast_blank (1.0.0)
fastimage (2.1.4, 2.1.3)
ffi (1.9.25)
font-awesome-sass (5.3.1)
haml (5.0.4)
hamster (3.0.0)
hashie (3.6.0, 3.5.7)
hub (1.12.4)
i18n (0.7.0)
io-console (default: 0.4.6)
jaro_winkler (1.5.1 x86_64-darwin-17)
jquery-middleman (3.1.2)
json (default: 2.0.4)
kramdown (1.17.0)
listen (3.0.8)
memoist (0.16.0)
method_source (0.9.0)
middleman (4.2.1)
middleman-autoprefixer (2.9.0)
middleman-blog (4.0.2)
middleman-cli (4.2.1)
middleman-core (4.2.1)
middleman-sprockets (4.1.1)
middleman-syntax (3.0.0)
mini_portile2 (2.3.0)
minitest (5.11.3, 5.10.1)
multipart-post (2.0.0)
net-sftp (2.1.2)
net-ssh (5.0.2)
net-telnet (0.1.1)
nokogiri (1.8.4)
octokit (4.12.0)
openssl (default: 2.0.7)
padrino-helpers (0.13.3.4)
padrino-support (0.13.3.4)
parallel (1.12.1)
parser (2.5.1.2)
power_assert (0.4.1)
powerpack (0.1.2)
pry (0.11.3)
pry-byebug (3.6.0)
psych (default: 2.2.2)
ptools (1.3.5)
public_suffix (3.0.3, 3.0.2)
rack (2.0.5)
rainbow (3.0.0)
rake (12.3.1, 12.0.0)
rb-fsevent (0.10.3)
rb-inotify (0.9.10)
rdoc (default: 5.0.0)
redcarpet (3.4.0)
rouge (2.2.1)
rspec (3.8.0)
rspec-core (3.8.0)
rspec-expectations (3.8.1)
rspec-mocks (3.8.0)
rspec-support (3.8.0)
rubocop (0.59.1)
ruby-progressbar (1.10.0)
rubygems-update (2.7.7)
sass (3.4.25)
sassc (1.12.1)
sawyer (0.8.1)
servolux (0.13.0)
sprockets (3.7.2)
temple (0.8.0)
test-unit (3.2.3)
thor (0.20.0)
thread_safe (0.3.6)
tilt (2.0.8)
tzinfo (1.2.5)
uglifier (3.2.0)
unicode-display_width (1.4.0)
xmlrpc (0.2.1)`

**Comment by elea** [comment]
Don't know if the Ruby upgrade is the cause, but I also have a fresh out of the box Middleman install that won't recognize stylesheets.

Am running Ruby 2.4.1 and here's my fun Gemfile:
gem 'middleman', '~> 4.2'  
gem 'middleman-autoprefixer', '~> 2.7'  
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]  
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]  
gem "middleman-blog", "~> 4.0"  
gem "middleman-livereload", "~> 3.4.3"  
gem 'middleman-deploy', '~> 2.0.0.pre.alpha'

**Comment by tdreyno** [comment]
If you run the build with `--verbose` it will show the full error message. Please post that here.

**Comment by elea** [comment]
In the console, it says: "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" for site.css (which is named site.css.scss under the stylesheets folder).

And this is the error log:
```
== Request: /
== Finishing Request: index.html (0.01s)
== Request: /stylesheets/site.css
== Finishing Request: stylesheets/site.css (0.01s)
== Request: /javascripts/site.js
== Finishing Request: javascripts/site.js (0.0s)
[2019-02-08 11:49:51] ERROR RuntimeError: JavaScriptCore runtime does’t support ES6. Please update or replace your current ExecJS runtime.
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/autoprefixer-rails-9.4.7/lib/autoprefixer-rails/processor.rb:154:in `runtime'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/autoprefixer-rails-9.4.7/lib/autoprefixer-rails/processor.rb:37:in `process'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-autoprefixer-2.10.0/lib/middleman-autoprefixer/extension.rb:81:in `prefix'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-autoprefixer-2.10.0/lib/middleman-autoprefixer/extension.rb:72:in `process'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-autoprefixer-2.10.0/lib/middleman-autoprefixer/extension.rb:58:in `call'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/lint.rb:49:in `_call'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/lint.rb:37:in `call'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:153:in `call'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/handler/webrick.rb:86:in `service'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
	/Users/elea/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
== LiveReload browser connected
LiveReload Browser URL: {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.0.8"}
```

**Comment by tdreyno** [comment]
```
ERROR RuntimeError: JavaScriptCore runtime does’t support ES6. Please update or replace your current ExecJS runtime.
```

**Comment by tdreyno** [comment]
JSC is the built in runtime on Macs. I guess its not cool enough for ES6? You can switch this, for example you could use a bundled JS runtime:

In your Gemfile:

```
gem 'mini_racer', platforms: :ruby
```

**Comment by elea** [comment]
Not clear on what runtime conflicts are or why they're happening, but the fix works and I now have compiling stylesheets again. Thank you!

**Comment by tdreyno** [comment]
Tracking this here: https://github.com/middleman/middleman-autoprefixer/issues/36

**Comment by jltml** [comment]
# Fixing CSS/SCSS links/compilation after Big Sur (macOS 11) update
Hi! Just writing this here in case anyone else has the same issue as me — this is my first time ever commenting on an issue, so apologies if this reopens it when it's not supposed to be reopened or anything like that. After I upgraded to Big Sur, I was able to get Middleman working again with `bundle install`, but all my CSS just vanished from my local server; I got a bunch of internal server & unable to find local resource errors, etc. I found this issue and attempted to bundle with mini_racer, but then got a bunch more errors relating to v8 (it would build native extensions and finally fail 10 minutes in). I finally fixed it by referring to [this issue](https://github.com/rubyjs/libv8/issues/305) on libv8: specifying [sq_mini_racer](https://rubygems.org/gems/sq_mini_racer/versions/0.2.4.sqreen2) instead of normal mini_racer (so `gem 'sq_mini_racer', '~> 0.3.1', platforms: :ruby` in my Gemfile) apparently uses updated darwin20 binaries, whereas mini_racer still uses darwin19 binaries (or something; I don't really know what I'm talking about & am very new to all this).

Additionally, I [installed depot_tools](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up), specifying its path in my .zhsrc with `export PATH="/Users/[username here]/bin/depot_tools:$PATH"`, but I'm unsure whether that's necessary or not.

Thanks! Sorry this is so long; I just thought the more detailed the better.

**Comment by tdreyno** [comment]
Thank you for adding this information. I won't have access to Big Sur to test for another month or so, but will keep this in mind.
