### ISSUE TITLE
Don’t build certain pages

### ISSUE THREAD

**Issue by andreamoro** [middleman/middleman#2198]
## Expected behavior and actual behavior
Expected not to build certain pages.
Currently get page templates being built as pages even though they are not part of the sitemap structure.

## Steps to reproduce the problem (from a clean middleman installation)
I’ve created a custom template for the blog tags (config.rb line ```blog.tag_template = "content/blog_tag.#{locale}.html"```) so to create an index page for each of the tags listed in my articles.

In the built version I get a build/blog_tag folder generated along with all the index files to cover the total number of articles and tags. Pages in this case are in mixed order (I can see this from the title tag that shift randomly).

Appending the ignore: true in the frontmatter was in theory supposed to get this page/template being ignored, but this is not the case.

## Additional information

- Ruby version:  2.5
- Middleman version:  4.2.1
- OS version: Mac OS X

**Comment by tdreyno** [comment]
Can you restate the issue, I can't quite follow.

Where does `locale` come from?

**Comment by andreamoro** [comment]
@tdreyno ```locale``` is just a local array I created to contains my languages so I can initialise the blog with a do each. Nothing special. 

The issue is with the template tag, contained in the content directory that is being generated. 
Should I move that file outside the content directory, perhaps in a template folder?

**Comment by tdreyno** [comment]
I believe the file is auto-ignored, but you could try over-specifying the ignore.

```
ignore "content/blog_tag.#{locale}.html.erb"
```

So, you're booting up middleman with a specific locale specified? Or it's initializing the blog extension in a loop?

**Comment by tdreyno** [comment]
Can you post your `config.rb` please

**Comment by andreamoro** [comment]
```
# Per-page layout changes
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

###
# Helpers
###
helpers do
  # Additional Helpers method have been defined in the /helpers/ folder so they are 
  # automatically registered when Middleman loads 
end
### 
# End Helpers #
###

# Methods defined in the helpers block are available in templates
set :locales, [:en, :it] 

activate :i18n, :mount_at_root => false, :templates_dir => "content", :locales => config[:locales]

activate :autoprefixer do |config|
  config.browsers = ['last 2 versions', 'Explorer >= 9']
end

set :markdown, auto_ids: false
set :markdown_engine, :kramdown
set :markdown, :fenced_code_blocks => true, :smartypants => true

activate :syntax, :line_numbers => true

config[:locales].each_with_index do | locale |
  activate :blog do | blog |
    blog.name = "blog" + locale.to_s;
    #blog.sources = locale.to_s + '/blog/{year}-{month}-{day}-{engtitle}.html'
    blog.prefix = locale.to_s + '/blog'
    blog.permalink = "{category}/:permalink"
    
    blog.layout = "Blog-inner"
    blog.preserve_locale = true
    blog.summary_separator = /(READMORE)/
    blog.summary_length = 350
    blog.generate_day_pages = false
    blog.generate_month_pages = false
    blog.generate_year_pages = false#

    blog.paginate = true
    blog.per_page = 3
    blog.page_link = (locale.to_s == 'en' ? "page" : "pagina") + "-{num}"

    blog.taglink = "/{tag}/index.html"
    #blog.tag_template = "content/blog_tag.#{locale}.html"
    blog.tag_template = "content/tag.html"
  end
end

#custom options
$blog_comments_depth = 5
$blog_comments_per_page = 5 
$bloc_recent_posts = 6

# Directory_indexes has to be activated after the blog
activate :directory_indexes

require "helpers/seo"
activate :seo_support

require 'helpers/readingT'
activate :reading_time

configure :development do
  activate :livereload, :apply_js_live => false, :apply_css_live => false
  set :protocol, "http://"
  set :host, Middleman::LiveReloadExtension.config.host
  #set :port, 80

  set :blog_dir, 'blog' 
  set :css_dir, 'css'
  set :js_dir, 'js'
  set :images_dir, 'images'
  
  ##### BETTER ERROR #####
  require "better_errors"
  require "binding_of_caller"

  set :show_exceptions, true
  config.consider_all_requests_local = true
  use BetterErrors::Middleware
  BetterErrors.application_root = __dir__
  ##### END BETTER ERROR #####

  #activate :asset_hash
  
  # This is the module created to redirect to 
  # the English version of the site for development purposes
  require_relative "helpers/RedirectDevelopment" 
  # the file path relative to config.rb w/o .rb extension
  use RedirectRootToDefaultFolder

#  files.watch :source,
#    path: File.expand_path("./source/content/images/_blog"),
#    destination_dir: config[:images_dir]
end

# Build-specific configuration
configure :build do
  set :protocol, "https://"
  set :host, ("www.andreamoro." << (I18n.locale.to_s == "en" ? "co.uk" : "it"))
  #set :port, 80

  set :blog_dir, 'blog' 
  set :css_dir, 'css'
  set :js_dir, 'js'
  set :images_dir, 'images'

  ignore '*blog_tag*'
  
  # For example, change the Compass output style for deployment
  activate :minify_css

  # Minify Javascript on build
  activate :minify_javascript

  # Minify HTML
  activate :minify_html 
end

after_build do 
  # Rename blog image folders
  config[:locales].each_with_index do | locale |
    RemapImagesDir(locale)
  end 

# activate :rsync do |rsync|
#    rsync.production_server = "myapp.com"
#    rsync.staging_server = "staging.myapp.com"
#    rsync.path = "/path/to/middleman/app/on/servers"
#    rsync.user = "rsync_user"#

#    # Optional:
#    rsync.rsync_flags, "--compress --archive --delete -v"
#  end
end
```

**Comment by andreamoro** [comment]
In any case, the ignore function doesn't seem to be respected. As you can see from the image below  middleman sitemap - the file is parsed and a directory with its content is generated.

![image](https://user-images.githubusercontent.com/5256583/46785633-a4199900-cd32-11e8-8c16-e576307d8159.png)

I had to put the following though, as the line you suggested with the "locale" variable was throwing an exception while the server was starting.

```
ignore "content/blog_tag.en.html.erb"
ignore "content/blog_tag.it.html.erb"
```

**Comment by tdreyno** [comment]
Wondering if it's actually the `i18n` extension reading and rendering those tags, not the blog auto-ignore. I don't remember the precedence of the two extensions, but maybe try flipping the order of their initialization. That way the page will be auto-ignored before `i18n` gets its hands on it.

Maybe an output path ignore for good measure at the end:

```
ignore "*/blog_tag/*"
```

**Comment by andreamoro** [comment]
@tdreyno thank for the hint. 

Moving the i18n declaration under the blog statement works up to a certain degree. Yes the page is no longer shown, but then even the blog content disappear completely ... and in any case the tag pages are not shown :(

Any chance to investigate this a bit?

It will be frustrating creating an helper to delete a directory that should not be created in first instance?

**Comment by tdreyno** [comment]
There are a lot of edge cases here. Multiple blogs layered over each other, rather than siblings, localization being half controlled in blog and half in i18n, and the difficulty Middleman has communicating between two separate extensions.

If you, or others, discover the root of this bug, we'll happily merge it. 

I acknowledge that this is an annoying bug, but for now, I suggest writing a cleanup script to run after build and remove the incorrect html files. The `after_build` hook can facilitate this.

**Comment by andreamoro** [comment]
Is this something I created somehow. Because I tried to get as close to the guidelines as possible, but had several issues.
If you see my first post on mm it's three years ago. Couldn't get a site published since then cause I can't get what I need :(
