### ISSUE TITLE
`config.rb` runs twice

### ISSUE THREAD

**Issue by polyethylene1and2** [middleman/middleman#2200]
Not sure if this is a bug or by design, but Middleman loads `config.rb` twice when running the server and building a site. Currently this leads to errors in my site.
This can be replicated directly after running `middleman init`.
- Ruby version: 2.5
- Middleman version: 4.3.0.rc2

**Comment by tdreyno** [comment]
That's expected. I can run even more than that during dev, it's re-evaluated on certain structural and data changes. Sounds like you're running code that generates side-effects in the config?

**Comment by polyethylene1and2** [comment]
Ah ok, I've been setting up data structures that get duplicated when `config.rb` is run twice - I'll put that code somewhere in `lib/`. Thanks

**Comment by tdreyno** [comment]
@polyethylene1and2 If you've got a code sample, let me know. Might be fine in config with a couple tweaks.
