### ISSUE TITLE
i18n + proxy

### ISSUE THREAD

**Issue by xiazhaoyang** [middleman/middleman#2201]
## Expected behavior and actual behavior

I am trying to create dynamic pages for contents in my site  in which I use i18n to create different language pages, but it seems the example for creating dynamic pages in document doesn't work for i18n , do you have any idea how to make it work ? Thank you !

Below is how I coded in my project:

# config.rb

data.someting.each do |name|
  proxy "/projects/#{name}.html", "/projects/show.html", :locals => { :project => name }
end

# Files

 +-- ...
  +-- locales
  |   --- en.yml
  |   --- cn.yml
  +-- source
  |   +-- images
  |   +-- javascripts
  |   +-- layouts
  |   +-- localizable
  |   |   +-- index.html.erb
  |   |   +-- index.es.html.erb
  |   +-- projects
  |   |   --- show.erb
  |   +-- stylesheets
  +-- ...

## Additional information

- Ruby version: 2.5
- Middleman version: 4.0 
- OS version: Mac OS 10.13.6

**Comment by tdreyno** [comment]
What is the expected behavior?

**Comment by xiazhaoyang** [comment]
I'm trying to create dynamic pages for each product page, which should be generated by the template file 'show.html.erb', and it will generate 'en/product/name-1.html', 'en/product/name-2.html', 'es/product/name-3.html' ...

**Comment by xiazhaoyang** [comment]
> What is the expected behavior?

Hi,Thomas

I'm trying to create dynamic pages with different languages for each product page, which should be generated by the template file 'show.html.erb', and it will generate 'en/products/name-1.html', 'en/products/name-2.html', 'es/products/name-1.html', 'es/products/name-2.html' .... What I'm wondering is that what should I do with the config.rb? What I have did in config.rb doesn't work.

```
data.someting.each do |name|
  proxy "/projects/#{name}.html", "/projects/show.html", :locals => { :project => name }
end
```

**Comment by tdreyno** [comment]
I'm afraid proxies and i18n don't play well together. For now, you have to wire it up yourself: https://github.com/middleman/middleman/blob/9002d0258c06f2124c488d0e3f7cb518954e8ab1/middleman-core/features/i18n_preview.feature#L265-L269

That said, this seems like a pretty common use case. I'll think about what kind of refactors would allow localizable proxies to work.

**Comment by tdreyno** [comment]
Do you have a file at `source/projects/show.html.[template extension]`?

**Comment by xiazhaoyang** [comment]
> Do you have a file at `source/projects/show.html.[template extension]`?

Yes, source/projects/show.html.erb

I'm wondering where does "langs" comes from?  I didn't see this object in my document.

**Comment by tdreyno** [comment]
you should customize that list to the locales you are using. They should be symbols, not strings.

**Comment by aarondufall** [comment]
I'm also trying to use both i18n and proxy together, but I'm running into a different issue that I think may have something to do with the ignore option.

Config.rb
```
["a", "b"].each do |ref|
  langs.each do |lang|
    proxy("/#{lang}/#{ref}/hello_world.html", "localizable/hello_world.html", locals: { ref: ref }, locale: lang, ignore: true)
  end
end
```

I get the following error
```
== Finishing Request: es/a/hello_world.html (0.13s)
      create  build/es/a/hello_world.html
       error  build/hello_world.html
undefined local variable or method `ref' for #<#<Class:0x007ffaaf049780>:0x007ffaacc17f38>
```

**Comment by tdreyno** [comment]
Yeah, it looks like it's still rendering a copy of `localizable/hello_world.html` without any config. Can you try placing that file at the root of `source` instead of in `localizable`. Since we're basically recreating the functionality with proxy, we can avoid having the built in system try to do it twice.

**Comment by benfurber** [comment]
I don't suppose anyone has made progress on this that they can share could they please?

Could I loop through the data without using the proxy?
