### ISSUE TITLE
Time in data file fails to load with 4.3.0.rc.2 and above

### ISSUE THREAD

**Issue by skublics** [middleman/middleman#2225]
## Expected behavior and actual behavior
In the `data` folder I have a `.yml` file that includes fields for time.
This file loads properly with middleman version 4.2.1 and 4.3.0.rc.1 but when I upgrade to 4.3.0.rc.2 it fails with the following error `YAML Exception parsing /Users/skublics/..... Tried to load unspecified class: Time`.

## Steps to reproduce the problem (from a clean middleman installation)
1. Create file called `blog.yml` in the data folder
2. Add the following content to `blog.yml`
```
---
- entry_id: 123
  published: 2018-11-14 15:12:00.000000000 Z
  updated: 2018-11-15 13:46:58.000000000 Z
  url: https://google.com
  title: Foo bar
```
3. Start middleman 
4. Notice the exception

## Additional information
- Ruby version: 2.3.3
- Middleman version: 4.3.0.rc.2 and above
- OS version: macos

**Comment by tdreyno** [comment]
It seems like this might be the same issue: https://stackoverflow.com/questions/32730275/the-date-time-format-will-be-auto-converted-by-yaml-load-from-2-0

I'm going to switch from `safe_load` to `load`, which is what `load_file` uses anyways.

**Comment by leighmcculloch** [comment]
👏 I think switching to `load` should be fine here, given that data is typically local YAML files and not files from external parties or users of a website.
