### ISSUE TITLE
`bin/setup` fails because of Bundler incompatibility

### ISSUE THREAD

**Issue by keiranking** [middleman/middleman#2240]
## Expected behavior and actual behavior

Running `bundle install` on a fresh install fails because of Bundler incompatibility:
```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    middleman-aria_current was resolved to 0.1.0, which depends on
      middleman-core (~> 4.2) was resolved to 4.2.1, which depends on
        bundler (~> 1.1)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.1)', which is required by gem 'middleman-core (~>
4.2)', in any of the sources.
```

@tysongach pointed out that [this commit](https://github.com/middleman/middleman/commit/c6898b8c28757f356951447918307faba5f00836) would resolve the issue if it were added to the `4.2-stable` branch. 

## Steps to reproduce the problem (from a clean middleman installation)

1. Install/Upgrade Bundler to 2.0 or greater (`gem install bundler`)
1. Make sure you have Bundler 2.0 or greater (`bundler version`)
1. Follow middleman install instructions

## Additional information

- Ruby version: 2.5.3 
- Middleman version: 4.2.1 
- OS version: macOS 10.14.2

**Comment by tdreyno** [comment]
Yup, tracking this here: https://github.com/middleman/middleman/pull/2227

Waiting for CI build, then publishing `v4.3.0`

**Comment by tdreyno** [comment]
https://rubygems.org/gems/middleman/versions/4.3.0
