### ISSUE TITLE
Middleman server reload taking longer  Grunt.js renders CSS from Sass faster than Middleman can display it

### ISSUE THREAD

**Issue by mayank-bansal-e1781** [middleman/middleman#2243]
i have a middleman repo where i use grunt as middleman external pipe line for scss to  compile to css,
i am using grunt watch as a watcher to run sass task on any scss file change, but the time grunt-sass
 takes is 4.5s and when i again reload the page , chrome show 2min for TTFB ,
i do not know how exactly middleman server request internally so any help to debug the issue.

**Comment by tdreyno** [comment]
Middleman serves the output dir of grunt directly as static, should be very quick. Can you post your config?
