### ISSUE TITLE
Relative links do not work

### ISSUE THREAD

**Issue by veganstraightedge** [middleman/middleman#2247]
# Expected behavior and actual behavior

## Expected

I expect `link_to` + `relative: true` and/or `set :relative_links, true` in `config.rb` to generate links prefixed with `../` between nested pages. 

## Actual

It doesn't. All links are generated as relative to site root links, `/foo` instead of `../foo`.

# Steps to reproduce the problem (from a clean middleman installation)

I have built a simple test case illustrating this from a clean middleman installation. I have also written a detailed README explaining what I did, what I expect, what actually happens.

https://github.com/veganstraightedge/middleman-relative-links-test-case

If I misunderstand this feature or am using it wrong, please let me know. 

# Additional information

- Ruby 2.5.3
- middleman (4.3.2)
- middleman-aria_current (0.1.1)
- middleman-autoprefixer (2.10.0)
- middleman-cli (4.3.2)
- middleman-core (4.3.2)
- middleman-data_source (0.8.1)
- middleman-gh-pages (0.4.1, 0.4.0, 0.3.1)
- middleman-livereload (3.4.6)
- middleman-sprockets (4.1.1)
- middleman-syntax (3.0.0)
- macOS Mojave (10.14)

Thanks!

**Comment by tdreyno** [comment]
When referencing paths internal to Middleman, full names should be used:

Rather than:

```
<%= link_to "Bar", "/bar" %>
```

Try:

```
<%= link_to "Bar", "/bar/index.html" %>
```

The `relative: X` attribute is only to do the opposite of `set :relative_links`. So if the set is true, then you can disable inline and visa versa.

**Comment by veganstraightedge** [comment]
Changing this:

<%= link_to "Bar", "/bar" %>

to this:

`<%= link_to "Bar", "/bar/index.html" %>`

fixed it.

Thank you @tdreyno.

***

I think it's probably worth adding a clarifying note about that in the `link_to` docs, because it appeared to be fine to use `/foo` with `link_to` until I needed relative links.
