### ISSUE TITLE
Redirects do not work

### ISSUE THREAD

**Issue by veganstraightedge** [middleman/middleman#2248]
## Expected behavior and actual behavior

I'm trying to redirect one URL to another.

In my `config.rb`:

```ruby
redirect '/bar', to: '/foo'
redirect '/bar/index.html', to: '/foo/index.html'
```

Neither of these work.

## Expected

When I go to `/bar` or `/bar/index.html`, I should be redirect to `/foo` or `/foo/index.html` and see the view that's in `/foo/index.html`.

## Actual

When I go to `/bar` or `/bar/index.html`, I see the view that's in `/bar/index.html`.

## Steps to reproduce the problem (from a clean middleman installation)

Test case repo from a clean middleman installation:

https://github.com/veganstraightedge/middleman-redirect-test-case

## Additional information

- Ruby 2.5.3
- middleman (4.3.2)
- middleman-aria_current (0.1.1)
- middleman-autoprefixer (2.10.0)
- middleman-cli (4.3.2)
- middleman-core (4.3.2)
- middleman-data_source (0.8.1)
- middleman-gh-pages (0.4.1, 0.4.0, 0.3.1)
- middleman-livereload (3.4.6)
- middleman-sprockets (4.1.1)
- middleman-syntax (3.0.0)
- macOS Mojave (10.14)

**Comment by tdreyno** [comment]
Can you try:

```
redirect 'bar/index.html', to: 'foo/index.html'
```

Are you saying both files are present? I'd remove `bar/index.html` from disk since it should replaced with the redirect to the "real" file `foo/index.html`

**Comment by veganstraightedge** [comment]
Ok. I deleted `source/bar` from disk.

https://github.com/veganstraightedge/middleman-redirect-test-case/commit/a5ce85d04282f6da4ec984dbaff1376d917efc77

When the redirect is:

`redirect 'bar', to: 'foo'`

I get a page of HTML in plaintext page:

```html
              <html>
                <head>
                  <link rel="canonical" href="foo" />
                  <meta http-equiv=refresh content="0; url=foo" />
                  <meta name="robots" content="noindex,follow" />
                  <meta http-equiv="cache-control" content="no-cache" />
                </head>
                <body>
                </body>
              </html>
```

But when the redirect is:

`redirect 'bar/index.html', to: 'foo/index.html'`

I get the expected behavior. 
`/bar` redirects to `/foo`.


***

So I think the take aways are:

- Redirects **should not** have leading slashes in their `from` or `to` strings. 

    ❌ `redirect '/bar/index.html', to: '/foo/index.html'`

- Redirects **should** be from file to file. 

    ✅`redirect 'bar/index.html', to: 'foo/index.html'`

- Redirects **should not** refer to just the path

    ❌ `redirect '/bar', to: '/foo'`
    ❌ `redirect 'bar', to: 'foo'`

    _EVEN IF_ you have `activate :directory_indexes` in your `config.rb`


Thanks @tdreyno!

**Comment by tdreyno** [comment]
Thanks @veganstraightedge, I'll take a look at making those docs clearer.

**Comment by gonzunigad** [comment]
Great final explanation.  redirect 'bar/index.html', to: 'https://google.com' worked for me too.
