### ISSUE TITLE
Replacing SASS with SASSC to Gemfile, doesn't Just Work™

### ISSUE THREAD

**Issue by veganstraightedge** [middleman/middleman#2250]
# Expected behavior and actual behavior

## Expected

1. Change `sass` to `sassc` in `Gemfile
2. `bundle`
3. `middleman`
3. This warning would go away:

```
== Sprockets will render css with ruby sass
   consider using Sprockets 4.x to render with SassC
```

## Actual

1. Change `sass` to `sassc` in `Gemfile
2. `bundle`
3. `middleman`
4. `require': cannot load such file -- sass (LoadError) `

https://gist.github.com/veganstraightedge/f56127f84bdefc4bed00a2547d168b38

# Steps to reproduce the problem (from a clean middleman installation)

See above.

# Additional information

- Ruby version:  ruby 2.5.3p105
- Middleman version:  middleman (4.3.2)
- OS version: macOS Mojave (10.14)

# Gemfile

```ruby
source 'https://rubygems.org'

ruby '2.5.3'

# Middleman
gem 'middleman'
gem 'middleman-aria_current'
gem 'middleman-autoprefixer'
gem 'middleman-data_source'
gem 'middleman-syntax'
gem 'middleman-gh-pages'
gem 'middleman-sprockets'
gem 'middleman-livereload'

# Templating engines
gem 'kramdown'
gem 'rubypants'

# CSS
gem 'sassc'

# Syntax highlighting
gem 'rouge'

# Slugs
gem 'sterile'

# For resource pluralization, etc
# activesupport/lib/active_support/inflector/inflections.rb
gem 'activesupport'

# Windows Support
if Gem.win_platform?
  gem 'wdm'
  gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
end

group :development do
  gem 'html-proofer'
end
```

**Comment by tdreyno** [comment]
Middleman 4.3.2 is fully embracing sassc. You don't need it in your Gemfile, it is the only option.

This looks like an issue with `middleman-sprockets`, I suggest reporting this issue over there: https://github.com/middleman/middleman-sprockets

**Comment by veganstraightedge** [comment]
Do I need `middleman-sprockets` to use `.scss` files in my `stylesheets` directory

**Comment by tdreyno** [comment]
No

**Comment by tdreyno** [comment]
I wonder if the 4.3 release broke the current sprockets, if so, we should patch sprockets soon. You're right, that's unexpected

**Comment by komor72** [comment]
Sprockets are not needed for Sass, but are needed for simplest-case JS integration (`//= require`). Well, I’m pretty sure that many folks are using Middleman without other sophisticated toolchain elements like Bower/Webpack etc, just throw in Sass, JS and make use of templating features of Middleman. I use it this way. So broken Middleman-Sprockets are no-good. 😔 Is there some other way to use this simplest-case scenario? I mean JS-contatenation and minification inside Middleman, using `//= require` in `js.all` and `activate :minify_javascript`. The Sass part works okay for now: compiling, minification, Autoprefixer integration – all this works after correct upgrading to MM 4.3.3 and installing proper gems.

**Comment by jimmycuadra** [comment]
I can confirm that middleman-sprockets breaks sass compilation once the sassc gem is added to the app's Gemfile. The sass files are output to the browser unprocessed. If I remove middleman-sprockets from my Gemfile (and remove the option from the middleman config file), the sass is processed as expected.

**Comment by pinheadmz** [comment]
I also had to remove middleman-sprockets from my project due to a sassc issue. I was finally able to get the CSS to "compile" but now my javascript is not being processed. 

So with `middleman-sprockets ~>4` my CSS doesnt work: https://github.com/slatedocs/slate/issues/1197#issuecomment-635489124

and WITHOUT middleman-sprockets, the CSS works but the JS doesn't...

Gemfile:
```
ruby '>=2.3.1'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~>4.3.7'
gem 'middleman-syntax', '~> 3.0.0'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem 'middleman-livereload'
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.4.0'
gem 'nokogiri', '>= 1.8.5'
gem 'rack', '>= 2.0.6'
gem 'sprockets', '~>3'
```

all.js -- this file is now being rendered as completely empty.
```
//= require ./all_nosearch
//= require ./app/_search
```

**Comment by komor72** [comment]
I solved this problem by using a gulp-part of this template: [https://github.com/tarikkavaz/Middleman-Boilerplate](tarikkavaz/Middleman-Boilerplate) (thanks Tarık). Easy to implement, even if you don’t use `npm` & friends. Just first follow the instructions to install `npm` system, then use the gulp files from the template and gulp part of the `config.rb`.
