### ISSUE TITLE
Middleman V4 Windows OS

### ISSUE THREAD

**Issue by Valerz** [middleman/middleman#2252]
Can someone confirm that Middleman version 4 doesn't work on any version of Windows? 
Seems that therubyracer is the cause as a middleman dependency that stops it from working?

- Ruby version: 2.5.3
- Middleman version: 4.3.2
- OS version: Windows 8.1

**Comment by tdreyno** [comment]
`therubyracer` is not included by default. If someone on your team has added it to the `Gemfile`, you can mark that specific dep as not supporting windows.

You can see an example here in our default new project template where we mark some deps as only being useful on windows: https://github.com/middleman/middleman-templates-default/blob/master/template/Gemfile#L5
