### ISSUE TITLE
after_build doesn't run anymore?

### ISSUE THREAD

**Issue by andreamoro** [middleman/middleman#2257]
## Expected behavior and actual behavior
I am fairly confident that this was running before as I built a custom helper to do some file manipulation.
However, not sure since when, the after_build block in the config.rb file doesn't seem to run anymore (no custom output in terminal)

## Additional information

- Ruby version: 2.5
- Middleman version: 4.3.3 
- OS version: OS X 10.14

**Comment by tdreyno** [comment]
Using Ruby 2.5.3, on OS X 10.14.3 and with Middleman 4.3.3, I was able to use the following config.rb:

```
after_build do
  $stderr.puts "*" * 500
end
```

And see the output on successful build. What are you seeing?

**Comment by andreamoro** [comment]
Actually it turned out that build on error don't let the after_build method to run at all. 
I was not aware of that.

Sorry for raising the ticket.

**Comment by andreamoro** [comment]
@tdreyno have a doubt though. Always in the config.rb, the after_build I've a reference to a function defined in an external module. Again this was working, but now I got an error message saying that the module is not defined anymore.

```
after_build do
  # Rename blog image folders
  puts "remapping images"
  RemapImagesDir('.it')
 ....
```

module defined in helpers/Utility.rb as such

```
module Utility
    def RemapImagesDir(locale)
```

I just saved in the helpers folder for practical reasons, so I don't expect the module to register itself, but certainly to be "seen" pretty much like other modules that are used inside templates and pages.
Should I register as an extension?

Also, why, in the after_build method the config[:variable] are not longer accessible?

Thanks



  #config[:locales].each_with_index do | locale |
  #  RemapImagesDir(locale)
  #end

**Comment by tdreyno** [comment]
`helpers` are for template helpers, I would suggest using the `lib` folder for arbitrary modules. And they will need to be `require`d from config and accessed like any other Ruby `module`.

That said, it sounds like that is unrelated to `config` not being available inside `after_build`?

Can you make a clean test case for this?

**Comment by andreamoro** [comment]
I've moved the module into the ```lib``` folder as suggested and registered / recalled in this way.

```
after_build do
  puts "remapping images"
  require "lib/Utility"
  helpers Utility
  RemapImagesDir('.it')
```

But I still get the same error. I'm sure the module was working before ... but don't know up to which version. I tested even on a new template
