### ISSUE TITLE
coffeescript files not being compiled

### ISSUE THREAD

**Issue by jots** [middleman/middleman#2259]
## Expected behavior and actual behavior
coffeescript files get compiled to javascript
## Steps to reproduce the problem (from a clean middleman installation)
put coffeetest.js.coffee or coffeetest.coffee in javascripts directory
if I run `middleman build` it does compile and place coffeetest.js in build/javascripts directory but it doesn't do it in the source directory (I'm using livereload and would like to see the changes immediately in the browser).
js version of file is never created.
## Additional information

- Ruby version: 2.5.1p57
- Middleman version:  4.3.3
- OS version: Ubuntu 16.04.4 LTS

**Comment by tdreyno** [comment]
Sounds like you want to use Middleman in "server" mode, not build. The livereload extension should notice the change and notify the browser correctly. If it doesn't please report that on that repo: https://github.com/middleman/middleman-livereload
