### ISSUE TITLE
Contract gem slowdown middleman by a lot

### ISSUE THREAD

**Issue by brodock** [middleman/middleman#2261]
## Expected behavior and actual behavior

In a big middleman installation, the Contract gem is a difference of waiting a couple of seconds or some minutes before `middleman server` can start taking requests.

## Steps to reproduce the problem (from a clean middleman installation)

Try out with `http://gitlab.com/gitlab-com/www-gitlab-com/`

```
middleman server
```
and
```
export NO_CONTRACTS=yes && middleman server
```

## Additional information

- Ruby version: 2.5.3
- Middleman version: 4.3.3 
- OS version: Mac OS Mojave

**Comment by tdreyno** [comment]
This is known and why the `NO_CONTRACTS` exists. 

In v5, they will be defaulting to off. This is the ticket where we're tracking getting gitlab on v5: https://github.com/middleman/middleman/issues/2228

**Comment by smcgivern** [comment]
@brodock also note that we set `NO_CONTRACTS=true` in our `.gitlab-ci.yml` 😃 

https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/.gitlab-ci.yml#L9

**Comment by brodock** [comment]
@smcgivern yeah, I figured out that eventually, but still, when running on local machine that is not automatically set.

**Comment by shaunakv1** [comment]
@tdreyno 
is there a way to set NO_CONTRACTS=true equivalent from the `config.rb` for middleman 4?

**Comment by tdreyno** [comment]
No, because Ruby has already started up by the time config.rb is read.
