### ISSUE TITLE
deps.yml is not written when --only-changed is set

### ISSUE THREAD

**Issue by smcgivern** [middleman/middleman#2262]
## Expected behavior and actual behavior

In https://github.com/middleman/middleman/issues/2228#issuecomment-475685216, I said:

> Can we clarify what flags people should use in CI? Ideally I'd just run `--only-changed --track-dependencies` on every single build, and use the presence or otherwise of `deps.yml` to tell Middleman whether it's a full build or not

Running `middleman build --track-dependencies --only-changed` on the Middleman master branch does not write `deps.yml`.

Running `middleman build --track-dependencies` does write it.

It would be convenient to have one set of options that will do either. Otherwise we have to update our build scripts to check for `deps.yml` and set `--only-changed` depending on whether it exists or not.

**Comment by tdreyno** [comment]
Sounds reasonable. I'll make `--only-changed` essentially not exist if `deps.yml` doesn't exist yet.

**Comment by smcgivern** [comment]
@tdreyno is there any way I can help with this?

**Comment by tdreyno** [comment]
This is the block which handles that logic: https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/builder.rb#L58-L90

**Comment by smcgivern** [comment]
Thanks. It seems the issue is: https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/builder.rb#L125-L127

This deliberately doesn't write the file if no vertices were invalidated, but in the case where the file didn't exist initially, we kind of want to create the file anyway. I've had a bash at that in https://github.com/smcgivern/middleman/commit/840f7f3ff2b3c3c37307a763845605a554556aab but I've only tested it for my case so far.

**Comment by tdreyno** [comment]
I think that makes sense
