### ISSUE TITLE
On changed file the source watcher loads all files with the same extension

### ISSUE THREAD

**Issue by tkarsist** [middleman/middleman#2273]
If file is changed, especially .haml file the middleman --instrument will show "possible change" also for all other haml-files. This makes reloading really slow. If livereload is used a change in .haml-file can take minutes for livereload to refresh. 

I removed "valid_updates |= related_updates" line from sourcer_wather.rb and made local gem and now it seems lightning fast. 

Is there some specific reason that all same type files should be marked as changed?

The 3.x middleman haml livereload is seconds and default 4.x livereload is minutes. 

## Additional information

- Ruby version: 2.6
- Middleman version: 4.3.3
- OS version: Mac&Linux

**Comment by tdreyno** [comment]
This is necessary since in some templating languages, all files of the same type can be included in each other. A change to one could change the render of all the others. Haml does not provide us a dependency graph to know if its safe not to reload all the files.

However, if you want to open a ticket or PR on the live reload repo (https://github.com/middleman/middleman-livereload), I'd be okay with an option to disable that behavior.

**Comment by tkarsist** [comment]
I tested that our partials live-reloaded normally even when the "related updates" where disabled. I changed the partial file and the file that referenced to the partial reloaded.

I can create a ticket to the middleman-livereload but the code (source_watcher.rb) is part of middleman-core. 

Should I create it still to the middleman-livereload -repository? (I don't have proper PR because I just commented one line of code away, not neat solution).

**Comment by tdreyno** [comment]
Ah, so it's unclear whether that "minutes" of wait time are in Middleman or live reload then?

If you disable live reload, do you get the same wait time?

**Comment by tkarsist** [comment]
I did some timed tests (3 timed runs for each).

SImple HAML change is made and it is timed from the logs when the operation is complete.

--- Scenario: Middleman 4.3.3 ---
* No livereload: 10,5 seconds 
* Livereload enabled: 2min 58 seconds

--- Scenario: Middlema 4.3.3 and "valid_updates |= related_updates" line from sourcer_wather.rb commented away---
* No livereload: 8 seconds
* Livereload enabled: 11 seconds

So it is slow only for livereload. It is slightly slower also without livereload (8s vs 10s). Based on the logs there is some prosessing happening when it tries to livereload all "possibly changed files" (in the project there is 533 haml files).

**Comment by tdreyno** [comment]
Ah, that volume of changes makes sense for the timing. 

Okay, let me think about making that `valid_updates |= related_updates` optional on the middleman side AND allowing extensions to pick whether they want it or not.

**Comment by tkarsist** [comment]
The optional related updates would be great option to have in the product.

By the way: Middleman has been great product. We've been using it since 2013. In our workflow it is the master for css & js production code, the component markup (html/haml) is then implemented on top of proper CMS (millions of articles). In 2013 it was ahead of time! :)

**Comment by tdreyno** [comment]
@tkarsist Thanks! Glad to hear it. Definitely good to hear stuff, especially performance, from our mid-size users.

Got a little branch you could try out above
