### ISSUE TITLE
Dev server really slow when updating CSS

### ISSUE THREAD

**Issue by marinarose92** [middleman/middleman#2277]
## Expected behavior and actual behavior
Hi guys, I'm newish to Middleman and I love it so far. One issue I'm having is that reloading the page after a simple CSS change takes up to 15 seconds and it's really slowing me down. I'm wondering if you can give me any tips on speeding up the process?

## Steps to reproduce the problem (from a clean middleman installation)
Just changing a simple property like font size will take about 15 seconds to load.

## Additional information
I am using the following gems:
```
gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', github: 'porada/middleman-autoprefixer'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
gem 'middleman-blog'
gem 'nokogiri'
gem 'redcarpet'
gem 'middleman-syntax'
gem 'kramdown'
gem 'middleman-deploy', github: 'middleman-contrib/middleman-deploy', branch: 'master'
gem 'middleman-search_engine_sitemap'
gem 'middleman-compass'
gem 'middleman-livereload'
gem 'middleman-gh-pages'
gem 'sassc'
```

- Ruby version: 2.6.1
- Middleman version: 4.2
- OS version: Ubuntu 18.04.2 LTS

**Comment by tdreyno** [comment]
Is it slow if you manually click refresh in the browser or is it live reload acting slow?

If you run `middleman server --verbose --instrument` it will print out a ton of timing information that can be helpful.

I'd also need to look at your `config.rb`. 

I'm curious about `autoprefixer` not coming from the official gem?

Some attempts you could make are:

* disable autoprefixer and live reload and check the performance.
* Upgrade to the latest Middleman 4.3.x release, in case this is already fixed.

**Comment by marinarose92** [comment]
I disabled livereload which more than halved the load time. Now I can actually refresh a lot faster. I have fixed the autoprefixer to come from the official source but have yet to update Middleman. I am pretty confident that disabling livereload was the culprit. 

Autoprefixer is slow and I could probably get away with disabling it but I wont for now, until I get a better handle on exactly why (or if) I need it.

**Comment by tdreyno** [comment]
Internally, autoprefixer tries to find the fasted javascript environment (it's written in JS), so its performance can depend on which one it found.

If you can, add:

```
gem "therubyracer"
```

To your Gemfile and see if that helps with autoprefixer performance.
