### ISSUE TITLE
How to solve CORS issue

### ISSUE THREAD

**Issue by sibinx7** [middleman/middleman#2283]
How to bypass CORS issue. I tried rack-cors, but i don't know how to configure it.

```
require 'rack/cors'
use Rack::Cors do
  allow do
    origins '*'
    resource '*',
             headers: :any,
             methods: [:get, :options]
  end
end
```

This give error `uninitialized constant Middleman::Rack::Cors` error. I follow this tutorial and gotsame error [rack-middleware](https://middlemanapp.com/advanced/rack-middleware/)

- Ruby version: 2.6.2
- Middleman version: 4.3.2
- OS version: Windows

**Comment by tdreyno** [comment]
Try `use ::Rack::Cors` instead, with those preceding colons.

However, I can't see why you would need CORS for a local dev server?

**Comment by sibinx7** [comment]
@tdreyno 
Thanks for your help. It now working.
