### ISSUE TITLE
`middleman init` in v5 creates Gemfiles that require middleman v4

### ISSUE THREAD

**Issue by gioele** [middleman/middleman#2284]
The `Gemfile` generate by `middleman init` should point to the same version of middleman that is creating it. This is not the case in v5.

## Expected behavior

    $ middleman version
    Middleman 5.0.0.rc.1
    $ cat Gemfile | grep middleman
    gem 'middleman', '~> 5.0'

## Actual behavior

    $ middleman version
    Middleman 5.0.0.rc.1
    $ cat Gemfile | grep middleman
    gem 'middleman', '~> 4.2'

## Steps to reproduce the problem (from a clean middleman installation)

    $ middleman init test
    $ cat test/Gemfile | grep middleman

## Additional information

- Ruby version: 2.6.2
- Middleman version: 5.0.0.rc.1
- OS version: Ubuntu 16.04

**Comment by tdreyno** [comment]
Good ticket. Thank you. We'll get on it.

**Comment by tdreyno** [comment]
Okay, so, right now it likely won't work. I could make the default force a `rc` or prerelease version for now, but I'd hate for that to get left behind in someone's project.

I'll make sure when 5.0 final is released that this is part of the launch checklist.
