### ISSUE TITLE
Localizating with Slate

### ISSUE THREAD

**Issue by ZeProf2Code** [middleman/middleman#2285]
## Expected behavior and actual behavior
Expected behavior: be able to use t(:key) in /source/localizable/index.html.md
Actual behavior: it's not being translated (it stays "t(:key)" in the web browser)

## Steps to reproduce the problem (from a clean middleman installation)
Activate i18n
Create the locales folder with some translations
Move /source/index.html.md to the /source/localizable/index.html.md
Try to use i18n helper
See that it isn't working

## Additional information

- Ruby version: ruby 2.6.3p62 (2019-04-16 revision 67580)
- Middleman version: 4.2.1
- OS version: Windows 10 1903-18922.1000

**Comment by ZeProf2Code** [comment]
(I just updated to the latest middleman, still not working...)

**Comment by tdreyno** [comment]
Markdown does not run arbitrary code by default. If you want to use Ruby helps in a Markdown file, rename it with a `erb` extension (for example `index.html.md.erb`) and use the ERb format for calling methods: `<%= t(:key) %>`

**Comment by ZeProf2Code** [comment]
Thank you it works perfectly for index.html.md file but if I add `.erb` to files in the `includes` folder it doesn't work. Any ideas?

**Comment by tdreyno** [comment]
What is the `includes` folder and in which way does it "not work"

**Comment by ZeProf2Code** [comment]
https://github.com/lord/slate/wiki/Using-Includes

**Comment by ZeProf2Code** [comment]
Fixed

**Comment by linxux** [comment]
@ZeProf2Code Hi, how to fix the `translation missing` under `includes` folder?
