### ISSUE TITLE
Error building ffi-1.11.1 in Alpine 3.10

### ISSUE THREAD

**Issue by noraj** [middleman/middleman#2293]
## Expected behavior and actual behavior

- Expecting: Executing middleman after install works.
- Actual behavior: https://github.com/ffi/ffi/issues/719

## Steps to reproduce the problem (from a clean middleman installation)

See dockerfile in https://github.com/ffi/ffi/issues/719

## Additional information

- Ruby version: 2.6.3
- Middleman version: 4.3.5
- OS version: Alpine 3.10

**Comment by noraj** [comment]
```diff
+ FROM ruby:2.5.7-alpine3.10
- FROM ruby:2.6.3-alpine3.10
```

Works with ruby 2.5.7

**Comment by tdreyno** [comment]
Definitely on the Docker side of things.

**Comment by noraj** [comment]
You don't think this is due to ffi not supporting ruyb 2.6 ?
