### ISSUE TITLE
i18n + partials

### ISSUE THREAD

**Issue by paulatgh** [middleman/middleman#2295]
## Expected behavior and actual behavior  
I want to use the i18n to implement the customization of the `title` in the template file. 
example:
`/locales/en.yml`
```
en:
    borrow_banner_tit: "title words"
```
`/source/localizable/page.html.erb`
```
---
title: t(:borrow_banner_tit)
description: "description words balabala"
---
<div class="main-container borrow">
    <section class="imagebg pb-52" style="background: url(<%= image_path "hero-apartment-preview.jpg" %>);">
        <div class="lazy-image-holder" data-src="<%= image_path "borrowpage-banner@2x.jpg" %>"></div>
        <div class="container pt-5">
            <div class="row align-items-center">
                <div class="col-12 col-sm-8 col-md-9 col-lg-8 pd-2">
                    <h1 class="bold heroic-slogans col-xl-8 pl-0 col-lg-10 col-md-9">
                    <%= t(:borrow_banner_tit)%>
```

Expected behavior:  
```
<html lang=en>
<head>
<title>title words</title>
```

Actual behavior:  
```
<title>t(:borrow_banner_tit) </title>
```
![image](https://user-images.githubusercontent.com/48198634/66545493-692c8a00-eb6d-11e9-863e-37fad7af6bda.png)

## Steps to reproduce the problem (from a clean middleman installation)
1. create layouts and use partials
2. create locales contents

### files
.
├── Gemfile
├── Gemfile.lock
├── README.md
├── config.rb
├── gulpfile.js
├── locales
│   ├── cn.yml
│   └── en.yml
├── middleman-gulp
│   ├── Gemfile
│   ├── Rakefile
│   ├── features
│   ├── lib
│   └── middleman-gulp.gemspec
├── package.json
├── scripts
│   ├── s3_website_config.json
│   └── set_s3_redirects.sh
└── source
    ├── fonts
    ├── images
    ├── javascripts
    ├── layouts
    ├── localizable
    ├── news
    ├── static
    └── stylesheets
- Ruby version: 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
- Middleman version: 4.2
- OS version: Mac 10.14.6

**Comment by tdreyno** [comment]
That seems completely reasonable, but isn't currently how the front matter works. It isn't processed so it cannot contain variables or method calls.

For now, I think the `yield_content` and `content_for` helpers will get you close: https://middlemanapp.com/basics/helper-methods/#output-helpers

I think we could begin processing front matter as Erb, which would allow variables. Let me think on it.

**Comment by paulatgh** [comment]
Thanks
