### ISSUE TITLE
middleman doesn't handle HTTP/2.0

### ISSUE THREAD

**Issue by noraj** [middleman/middleman#2298]
## Expected behavior and actual behavior

In depth troubleshooting with slate using middleman https://github.com/slatedocs/slate/issues/1149

## Steps to reproduce the problem (from a clean middleman installation)

1. `middleman init test`
2. `cd test`
3. `touch source/test.html.md && printf %s '![](https://i.imgur.com/kwZFyk8.jpg)' > source/test.html.md`
4. `bundle exec middleman server`
5. open `http://127.0.0.1:4567/test.html` with a web browser

![image](https://user-images.githubusercontent.com/16578570/67047537-cb1f5d80-f132-11e9-971b-7ac7bcfd2756.png)

## Additional information

- Ruby version: 2.6.0p0
- Middleman version: 4.3.5
- OS version: ArtchLinux

## Working case

Build and use a HTTP 2.0 ready web server or use web browser without web server.

1. `bundle exec middleman build`
2. `firefox build/test.html`

**Comment by tdreyno** [comment]
Not sure I follow. Your browser should be able to load remote assets from HTTP1 and HTTP2?

**Comment by noraj** [comment]
If you read https://github.com/slatedocs/slate/issues/1149 you saw I'm using the last version of Firefox that of course can handle HTTP/2.0 and I can can load the picture either directly or when using an HTTP 2.0 ready server, only with middleman serving the page is not working.

**Comment by johny** [comment]
It works fine if you're using `http://localhost:4567/test.html` protocol, only when you access local site via `127.0.0.1` then the browser blocks the request. 

I'm not really sure if this is an issue with middleman at all. Keep in mind, the `403` response code is actually sent by imgur in this case.
