### ISSUE TITLE
installation failure: unknown switches

### ISSUE THREAD

**Issue by baezanat** [middleman/middleman#2300]
## Expected behavior and actual behavior
I installed middleman using gem install middleman, and I can see the gem listed in my local gem list as follows:

`middleman (4.3.5)
middleman-cli (4.3.5)
middleman-core(4.3.5)`

but when I enter `middleman -v` I get
`Unknown switches "-v"`

If I enter `middleman --version` I get
`Unknown switches "--version"
Did you mean? "--verbose"`

## Steps to reproduce the problem (from a clean middleman installation)
I installed rbenv and then ruby 2.6.3 (set to global default)
then I ran `gem install ruby-dev`
and then `gem install middleman`
then i entered `middleman -v` to check that the installation was successful but I got back 
`unknown switches "--version"`

## Additional information
`which middleman` returns `home/.rbenv/shims/middleman`  
`which ruby` returns `home/.rbenv/shims/ruby`  
I'm running ruby version 2.6.3 by default on Ubuntu 18.04

- Ruby version: 2.6.3 (whith rbenv)
- Middleman version: 4.3.5
- OS version: Not OS but Ubuntu 18.04

**Comment by tdreyno** [comment]
The command is `middleman version`, no hyphens.

**Comment by baezanat** [comment]
Thanks so much! Glad there was no real error!
