### ISSUE TITLE
Slate - CssSyntaxError: /stylesheets/screen.css:5:1: Unknown word

### ISSUE THREAD

**Issue by prawen** [middleman/middleman#2302]
Hello All,

I have just stared using slate and they use middleman and see you as contributors in their list. I hope this is the forum to ask my question. In case this is not the place, please let me know.

I'm trying to build the static content to host apidocs on a webserver. But I'm getting below error.

``` 
bundle exec middleman build --clean
== Sprockets will render css with SassC
CssSyntaxError: /stylesheets/screen.css:5:1: Unknown word
3 | 
@import
 'variables';
4 | 
@import
 'icon-font';

    5 | //
    @import
    'rtl'; // uncomment to switch to RTL format | ^ 6 | 7 | /*

bundler: failed to load command: middleman (/home/praveen/.rbenv/versions/2.6.5/bin/middleman)
ExecJS::RuntimeError: CssSyntaxError: /stylesheets/screen.css:5:1: Unknown word
3 | 
@import
 'variables';
4 | 
@import
 'icon-font';

    5 | //
    @import
    'rtl'; // uncomment to switch to RTL format | ^ 6 | 7 | /*

Input.error ((execjs):60175:16)
Parser.unknownWord ((execjs):62409:22)
Parser.other ((execjs):62014:12)
```

- Ruby version: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
- Middleman version: 
gem middleman ~>4.3
gem middleman-syntax ~> 3.0
gem middleman-autoprefixer ~> 2.7
gem middleman-sprockets ~> 4.1
- OS version: Ubuntu Server 16.04

I hope I have provided enough information. Please let me know if you need any additional details.

**Comment by jinixx** [comment]
got the same error, any updates?

**Comment by tpobozy** [comment]
same here

**Comment by DarthShmev** [comment]
Same here

**Comment by VisionaireStudioSimon** [comment]
Got the same error. Fixed it by removing `middleman-sprockets` and `sass` and `activate :sprockets` from my `config.rb`. But it unfortunately breaks the js requires. Maybe it's time to move to nodejs.

**Comment by tomrutgers** [comment]
@VisionaireStudioSimon You can abandon sprockets with the [external pipeline](https://middlemanapp.com/advanced/external-pipeline/). I've put together a [webpack starter](https://github.com/tomrutgers/middleman-webpack) that has all the essentials.

**Comment by paladini** [comment]
Having the same problem here, guys. There's any workaround? I tried what @VisionaireStudioSimon suggested, however it did not work for me. Using Ubuntu 19.10 here.

I don't get your suggestion, @tomrutgers , can you explain?

**Comment by tomrutgers** [comment]
@paladini I'm not sure what the issue is, but it's caused by `middleman-sprockets`. That's a gem that takes care of importing assets like javascript (eg. `#= require bootstrap`) and sass files (eg `@import bootstrap;`). If you remove `middleman-sprockets` the error goes away, but you won't be able to import assets through the asset pipeline. 

Instead, you can set up an external asset pipeline: https://middlemanapp.com/advanced/external-pipeline/. The webpack starter I posted above is an example of such a workflow.

**Comment by Voxoff** [comment]
Just in case google directs anyone from slate with the error message. You can temporarily avoid the problem by downgrading middleman-sprockets. (I found migrating slate to webpack v time consuming). 

Hope it helps whilst a solution is found.

**Comment by aep** [comment]
> @VisionaireStudioSimon You can abandon sprockets with the [external pipeline](https://middlemanapp.com/advanced/external-pipeline/). I've put together a [webpack starter](https://github.com/tomrutgers/middleman-webpack) that has all the essentials.

thanks, that's helpful. although i'm really confused by it. if middleman requires webpack anyway now whats the advantage of using middleman versus just webpack? webpack requires incredible effort to manage due to frequent breaking changes

**Comment by ulidtko** [comment]
My understanding: the `CssSyntaxError` is thrown by gem SassC, which supposedly replaces gem `sass` — but as we can see, not quite completely.

The workaround for me was to update to Slate 2.4.0, which brings in `gem 'sass'` into Gemfile, and so `middleman-sprockets` works again, albeit with EOL warning about Sass.

middleman/middleman-sprockets#132 has similar discussion. But the `::Sprockets::Autoload::Sass = ::SassC` hack from there didn't work for me, no idea why.

**Comment by ulidtko** [comment]
@stale nope, undo.

**Comment by tomrutgers** [comment]
Not stale

**Comment by mavaddat** [comment]
Slatedocs are dead. Long live [mermade/reslate](https://github.com/mermade/reslate).
