### ISSUE TITLE
Configure different root in build for CDN

### ISSUE THREAD

**Issue by sathishmanohar** [middleman/middleman#2304]
I need to configure bunny CDN in middleman. So the expected behavior for me is, in development mode, static assets should be like `<link rel="stylesheet" href="/stylesheets/lity.min-c73bcc62.css"  />` and during build, it should switch to `<link rel="stylesheet" href="https://mylink.b-cdn.net/stylesheets/lity.min-c73bcc62.css"  />` I am trying to achieve that with the below code

    # In config.rb
    configure :development do
      config[:static_root] = "/"
    end
    
    configure :build do
      config[:static_root] = "https://dmtick.b-cdn.net/"
    end
    
    helpers do
      def static_asset(asset_path)
        config[:static_root] + asset_path
      end
    end
    
    # In views
    <script src="<%= static_asset "stylesheets/lity.min.css" %>"></script>

There are two problems I face
1. For some reason, middleman doesn't allow forward slash "/" to be used in a string inside config.rb. If I use "something" in development mode it works. However, if I use "/" to represent the root directly it gets skipped.
2. Although it works in build, it doesn't respect the asset hash directive and just generates `<link rel="stylesheet" href="https://dmtick.b-cdn.net/stylesheets/lity.min.css"  />`

How do I configure CDN provided root and get the workflow right with middleman.

**Comment by tdreyno** [comment]
I believe you want `asset_host`, not `static_root`: https://middlemanapp.com/basics/build-and-deploy#production-asset-hashing-cdn-configuration

**Comment by Kjir** [comment]
I'm closing this issue since there is an answer with a solution to the problem. Please re-open if there are other outstanding issues.
