### ISSUE TITLE
Middleman server doesn’t live reload helpers

### ISSUE THREAD

**Issue by danhalliday** [middleman/middleman#2306]
## Expected behavior and actual behavior

When using separate helper files (eg. `helpers/formatting_helpers.rb`), Middleman’s server doesn’t reload them when changed.

I would expect to be able to work on helpers and be able to edit them and see the changes reflected in my browser after Middleman has reloaded.

A compounding problem is that when I’m working on a helper I end up quitting Middleman and restarting many times using `ctrl-c` on the terminal, and often Middleman doesn’t exit cleanly and the server is left dangling so I have to keep running `killall ruby` (or similar) to get it to start again. I also never seem to be able to get the `livereload` extension working reliably so it’s possible I have some other underlying issue — I’ve given up on it for a few years now.

## Steps to reproduce the problem (from a clean middleman installation)

- Create a new project
- Add a separate helper file (eg. `helpers/formatting_helpers.rb`)
- Add a helper method
- Use the helper method in a template
- Start server
- Observe helper output
- Modify helper method
- See `The Middleman has reloaded` message in console
- Reload page, or wait for reload if using `livereload`
- Observe helper output is not updated

## Additional information

- Ruby version: `ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]`
- Middleman version: `middleman (4.3.5)`
- OS version: `macOS Catalina 10.15.2 (19C57)`

**Comment by andreamoro** [comment]
Ditto. The verbose notice the file changed on my end, but no effects.
