### ISSUE TITLE
“Unresolved or ambiguous or specs” for Rack gem

### ISSUE THREAD

**Issue by markwyner** [middleman/middleman#2308]
## Expected behavior and actual behavior
When I run commands like “middleman” or “middleman build” I expect Middleman to execute the command without warnings or errors. Currently, when I run one of these commands, I receive a warning about the Rack gem:

```
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      rack (>= 1.4.5, < 3)
      Available/installed versions of this gem:
      - 2.0.8
      - 1.6.8
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
```
Running “gem cleanup rack” appears to resolve the issue, returning the following:

```
Cleaning up installed gems...
Clean up complete
```

However, running the aforementioned Middleman commands again yields the same warning.

## Steps to reproduce the problem (from a clean middleman installation)

1. Type the “middleman” command to start the Middleman server

## Additional information

- Ruby version: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
- Middleman version: 4.3.5
- OS version: 10.15.2 (19C57)

## Gem List

*** LOCAL GEMS ***

activesupport (5.0.7.2)
addressable (2.7.0)
autoprefixer-rails (9.7.3)
backports (3.15.0)
bigdecimal (default: 1.4.1)
bundle (0.0.1)
bundler (2.1.2)
celluloid (0.16.0)
chunky_png (1.3.10)
cmath (default: 1.0.0)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
concurrent-ruby (1.1.5)
contracts (0.13.0)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
dotenv (2.7.5)
e2mmap (default: 0.1.0)
em-websocket (0.5.1)
erubis (2.7.0)
etc (default: 1.0.1)
eventmachine (1.2.7)
execjs (2.7.0)
fast_blank (1.0.0)
fastimage (2.1.7)
fcntl (default: 1.0.0)
ffi (1.11.3)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
haml (5.1.2)
hamster (3.0.0)
hashie (3.6.0)
hike (1.2.3)
hitimes (1.2.6)
hooks (0.4.1)
http_parser.rb (0.6.0)
i18n (0.9.5)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (default: 2.1.0)
kramdown (1.17.0)
listen (3.0.8)
logger (default: 1.3.0)
matrix (default: 0.1.0)
memoist (0.16.2)
middleman (4.3.5)
middleman-autoprefixer (2.10.1)
middleman-cli (4.3.5)
middleman-core (4.3.5)
middleman-livereload (3.4.6)
middleman-sprockets (3.5.0)
minitest (5.13.0)
multi_json (1.13.1)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
padrino-helpers (0.13.3.4)
padrino-support (0.13.3.4)
parallel (1.19.1)
power_assert (1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.3)
rack (2.0.8, 1.6.8)
rack-livereload (0.3.17)
rack-test (0.6.3)
rake (12.3.2)
rb-fsevent (0.10.3)
rb-inotify (0.10.1)
rdoc (default: 6.1.2)
rexml (default: 3.1.9)
rss (default: 0.2.7)
rubygems-update (3.1.2)
sass (3.4.25)
sassc (2.2.1)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
servolux (0.13.0)
shell (default: 0.7)
sprockets (2.12.4)
sprockets-helpers (1.1.0)
sprockets-sass (1.3.1)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
temple (0.8.2)
test-unit (3.2.9)
thor (1.0.1)
thread_safe (0.3.6)
thwait (default: 0.1.0)
tilt (2.0.10, 1.4.1)
timers (4.0.4)
tracer (default: 0.1.0)
tzinfo (1.2.6)
uber (0.0.15)
uglifier (3.2.0)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)

## Gem Env

RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.2
  - RUBY VERSION: 2.6.5 (2019-10-01 patchlevel 114) [x86_64-darwin19]
  - INSTALLATION DIRECTORY: /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/markwyner/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /Users/markwyner/.rbenv/versions/2.6.5/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/markwyner/.rbenv/versions/2.6.5/bin
  - SPEC CACHE DIRECTORY: /Users/markwyner/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/markwyner/.rbenv/versions/2.6.5/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-19
  - GEM PATHS:
     - /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0
     - /Users/markwyner/.gem/ruby/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/markwyner/.rbenv/versions/2.6.5/bin
     - /usr/local/Cellar/rbenv/1.1.2/libexec
     - /Users/markwyner/.rbenv/shims
     - /Users/markwyner/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /sbin
     - /usr/sbin

I would love any advice on cleaning up this Rack gem warning. Thank you much in advance.

**Comment by markwyner** [comment]
Actually, yes. When I start the server that way the warning doesn't appear. Is there a reason I would want to use this command over simply "middleman"? And even though I'm not seeing the warning, it seems like it's still an issue that I'm just masking. Perhaps I don't understand. Are you able to elaborate on this?

**Comment by tomrutgers** [comment]
@markwyner `bundle exec middleman` executes the middleman version specified in your gemfile. `middleman` executes the systemwide installed version. You might have multiple instances of MM installed on your machine. The only way of knowing for sure that you're using the right one as specified in your gemfile is by using `bundle exec`.

**Comment by markwyner** [comment]
That's really useful information. Thank you. I use Middleman for multiple projects on my machine. But would one project try to reference the install from another one, when they're in different directories on my machine? Or, is there a way for me to see if I have an overarching instance installed? I'd like to clean that up.

**Comment by tomrutgers** [comment]
You can run `gem list | grep middleman` to see all the versions you have installed. To remove old version use `gem cleanup middleman` or `gem uninstall middleman` to choose which versions to delete.
