### ISSUE TITLE
rack.rb:89: warning: URI.unescape is obsolete

### ISSUE THREAD

**Issue by lraboteau** [middleman/middleman#2312]
## Expected behavior and actual behavior
No logs on after the server is starting

== The Middleman is loading
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"
/Users/johndoe/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.5/lib/middleman-core/rack.rb:89: warning: URI.unescape is obsolete
/Users/johndoe/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.5/lib/middleman-core/util/paths.rb:36: warning: URI.unescape is obsolete

## Steps to reproduce the problem (from a clean middleman installation)
Init and serve a new project with ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]

## Additional information

- Ruby version: 2.7.0p0
- Middleman version: 4.2
- OS version: Mac OS 10.15.3

**Comment by tdreyno** [comment]
Fixed here, but not yet released: https://github.com/middleman/middleman/pull/2303

You'll need to use the stable branch for now: https://github.com/middleman/middleman/tree/4.x

Or downgrade to Ruby 2.6 for now

**Comment by jacobat** [comment]
Still not quite fixed in latest 4.x:

```
/.../ruby/2.7.0/bundler/gems/middleman-e8cf86f3e335/middleman-core/lib/middleman-core/util/paths.rb:36: warning: URI.unescape is obsolete
```

**Comment by alexandru-calinoiu** [comment]
Yeah getting that when updating to ruby 2.7

**Comment by noraj** [comment]
Any news for the 2.7 switch ?

**Comment by jubishop** [comment]
for anybody interested I have this ugly hack to ignore these:

```
bundle exec middleman build &> output.txt; cat output.txt | grep -v URI; rm output.txt
```

**Comment by alexanderadam** [comment]
> for anybody interested I have this ugly hack to ignore these

…or simply override the affected places:

```ruby
# until this is fixed https://github.com/middleman/middleman/issues/2312
Middleman::Util.module_eval do
  module_function

  def normalize_path(path)
    return path unless path.is_a?(String)

    # The tr call works around a bug in Ruby's Unicode handling
    WEBrick::HTTPUtils.unescape(path).sub(%r{^/}, '').tr('', '')
  end
end

Middleman::Rack.class_eval do
  # https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/rack.rb#L90
  def process_request(env, req, res)
    start_time = Time.now

    request_path = WEBrick::HTTPUtils.unescape(env['PATH_INFO'].dup)
    if request_path.respond_to? :force_encoding
      request_path.force_encoding('UTF-8')
    end
    request_path = ::Middleman::Util.full_path(request_path, @middleman)
    full_request_path = File.join(env['SCRIPT_NAME'], request_path) # Path including rack mount

    # Run before callbacks
    @middleman.execute_callbacks(:before)

    # Get the resource object for this path
    resource = @middleman.sitemap.find_resource_by_destination_path(request_path.gsub(' ', '%20'))

    # Return 404 if not in sitemap
    return not_found(res, full_request_path) unless resource && !resource.ignored?

    # If this path is a binary file, send it immediately
    return send_file(resource, env) if resource.binary?

    res['Content-Type'] = resource.content_type || 'text/plain'

    begin
      # Write out the contents of the page
      res.write resource.render({}, rack: { request: req })

      # Valid content is a 200 status
      res.status = 200
    rescue Middleman::TemplateRenderer::TemplateNotFound => e
      res.write "Error: #{e.message}"
      res.status = 500
    end

    # End the request
    logger.debug "== Finishing Request: #{resource.destination_path} (#{(Time.now - start_time).round(2)}s)"
    halt res.finish
  end
end

```

**Comment by jubishop** [comment]
thanks. But I don't want to do that I'd rather wait for an actual fix than patch in all that code.

**Comment by b1tb4ng** [comment]
@tdreyno, I admit I don't know the gem build process, but it looks like the fix for this issue is in [master](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/rack.rb) as of [dead1c3](https://github.com/middleman/middleman/commit/dead1c3f2a38535fa8a51b137fe19b56b8a3ff0a), but it's not in the [4.x branch](https://github.com/middleman/middleman/blob/4.x/middleman-core/lib/middleman-core/rack.rb). Do you build the gems from the 4.x branch? Since it was committed to master in Dec. 2019 but not to the 4.x branch, is that why there is still an issue when using 4.3.10 and Ruby 2.7.1?

```
/Users/bb/.gem/ruby/2.7.1/gems/middleman-core-4.3.10/lib/middleman-core/util/paths.rb:36: warning: URI.unescape is obsolete
```

```
# gem info middleman-core

*** LOCAL GEMS ***

middleman-core (4.3.10)
    Authors: Thomas Reynolds, Ben Hollis, Karl Freeman
    Homepage: http://middlemanapp.com
    License: MIT
    Installed at: /Users/bb/.gem/ruby/2.7.1

    Hand-crafted frontend development
```

**Comment by tdreyno** [comment]
@b1tb4ng You're right. Backported. v4.3.11

**Comment by mandrean** [comment]
```
$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin18]
$ middleman version
Middleman 4.3.11
$ bundle version
Bundler version 2.1.4 (2020-01-05 commit 32a4159325)
```

I'm still getting a bunch of these:

> `~/.rvm/gems/ruby-2.7.2/gems/middleman-core-4.3.11/lib/middleman-core/builder.rb:232: warning: URI.escape is obsolete`

**Comment by marcoms** [comment]
This still isn't fixed for me either. I get lots of this error with Ruby 2.7.2:

```
<homedir>/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/middleman-core-4.3.11/lib/middleman-core/extensions/asset_hash.rb:90: warning: URI.escape is obsolete
```

**Comment by tnir** [comment]
@tdreyno Will you release 4.3.12 to include #2383 to resolve two other warnings @mandrean and @marcoms pointed out? (https://github.com/middleman/middleman/issues/2312#issuecomment-717282210 & https://github.com/middleman/middleman/issues/2312#issuecomment-737167356)
