### ISSUE TITLE
File prepended with the . are ignored by the i18N language module?

### ISSUE THREAD

**Issue by andreamoro** [middleman/middleman#2317]
## Expected behavior and actual behavior
Irrespective of the name of the file, if a language is within the path, the file has to be processed as usual

## Steps to reproduce the problem (from a clean middleman installation)
Create two `.htaccess.<lang1>.erb` and `.htaccess.<lang2>.erb` file and add a very simple partial to import something from somewhere else. You will notice the import works as expected meaning that the .erb extension and the file are recognised by the compiler. 
However on the build folder you will get both the files with the lang extension in place and not a single plain file as expected.

## Additional information

- Ruby version: 
- Middleman version: 
- OS version:

**Comment by tdreyno** [comment]
And the files are in the `localizable` folder?

**Comment by andreamoro** [comment]
Yes, they are in same place like the any others.

below my config.rb snippet

```
set :locales, [:en, :it] 
activate :i18n, :mount_at_root => false, :templates_dir => "content", :locales => config[:locales]
```

and files are in source/content

![image](https://user-images.githubusercontent.com/5256583/78342004-e5da7700-7598-11ea-849c-a6f56533183e.png)

* please ignore the fact in this screenshot there is no more the lang in between. Had to solve quickly and I created an IF condition inside the file checking for the `I18n.locale`
