### ISSUE TITLE
Activating relative and hashing for assets gives absolute path for woff2

### ISSUE THREAD

**Issue by MasterOdin** [middleman/middleman#2318]
See https://github.com/MasterOdin/middleman-woff2-test for a test repository that is as minimal as I could make it with the observed bug.

## Expected behavior and actual behavior

When building a site with relative and hashing activated for assets and using the `font-url` method of `scss`, all fonts except the `woff2` one are properly pathed, but that one remains as an absolute path.

Expected:
```
  src: url("../fonts/roboto-regular-webfont-da39a3ee.eot");
  src: url("../fonts/roboto-regular-webfont-da39a3ee.eot?#iefix") format("embedded-opentype"), url("../fonts/roboto-regular-webfont-da39a3ee.woff") format("woff"), url("../fonts/roboto-regular-webfont-38dbad01.woff2") format("woff2"), url("../fonts/roboto-regular-webfont-da39a3ee.ttf") format("truetype"), url("../fonts/roboto-regular-webfont-da39a3ee.svg#robotoregular") format("svg");
```

Actual:
```
  src: url("../fonts/roboto-regular-webfont-da39a3ee.eot");
  src: url("../fonts/roboto-regular-webfont-da39a3ee.eot?#iefix") format("embedded-opentype"), url("../fonts/roboto-regular-webfont-da39a3ee.woff") format("woff"), url("/fonts/roboto-regular-webfont-38dbad01.woff2") format("woff2"), url("../fonts/roboto-regular-webfont-da39a3ee.ttf") format("truetype"), url("../fonts/roboto-regular-webfont-da39a3ee.svg#robotoregular") format("svg");
```

from https://github.com/MasterOdin/middleman-woff2-test/blob/master/build/stylesheets/site-9535cdcb.css

## Steps to reproduce the problem (from a clean middleman installation)

What I did:
1. middleman init
1. add font folder of roboto webfonts
1. set font_dir config variable
1. activate relative assets
1. activate asset hashing
1. add all the `font-url`s to the included `scss` file.
1. `bundle exec middleman build`

## Additional information

- Ruby version: 2.7.1
- Middleman version: 4.3.6 
- OS version: macOS 10.14.6

**Comment by pwim** [comment]
Though I was able to confirm this issue in 4.2, when I changed your example project to point to Middleman's master branch (the unreleased 5.0 version), it appears to be resolved.
