### ISSUE TITLE
Update ActiveSupport Gem Version in Middleman 4.3.6 to Fix MemCacheStore Security Vulnerability

### ISSUE THREAD

**Issue by Henryvw** [middleman/middleman#2326]
## Expected behavior and actual behavior
When I do the simple gem install of middleman it installs Middleman 4.3.6, which has a gem dependency pinned to ActiveSupport 5.0.7.2, which has a security vulnerability: https://github.com/advisories/GHSA-2p68-f74v-9wc6.

## Steps to reproduce the problem (from a clean middleman installation)
- Run `gem install middleman` and let it install version 4.3.6
- Push to GitHub
- GitHub will warn you that you have a security dependency

## Additional information
https://github.com/advisories/GHSA-2p68-f74v-9wc6.
- Ruby version: 2.6.2

- Middleman version: 4.3.6 
- OS version: OS X 10.15.4

**Comment by leighmcculloch** [comment]
I have opened #2327 to fix this issue. It looks like the maximum version limit on the activesupport version might have been introduced by accident. See PR for details.

**Comment by leighmcculloch** [comment]
@tdreyno Thanks ofr merging #2327 so quickly. Would it be possible to get a patch release out so that the fix for this issue is available for updates all round?

**Comment by tomrutgers** [comment]
Excellent solution @leighmcculloch, the Github security warnings were all over the place today 😅.  +1 for a patch release.

**Comment by tdreyno** [comment]
Published as v4.3.7

**Comment by Henryvw** [comment]
Thank you so much! I should have just made a PR myself for this. Will do that next time
