### ISSUE TITLE
Reloading of data files doesn't work for dynamic pages in Middleman 5.0 (master)

### ISSUE THREAD

**Issue by pwim** [middleman/middleman#2329]
## Expected behavior and actual behavior

I'm running the preview server for a Middleman app that defines proxy pages from data files. When I change the data files, these pages aren't updated unless I restart the preview server.

## Steps to reproduce the problem (from a clean middleman installation)

Suppose I have the following in `data/people.yaml`

```yaml
- name: Tom
  bio: A jolly fellow
```
and the following in `config.rb`

``` ruby
data.people.each do |person|
  proxy "/#{person.name.parameterize}.html", "/person.html", locals: { person: person }
end
```

and the following in `person.html.erb`

```erb
<h1><%= person.name %></h1>
<%= person.bio %>
```

When I start the preview server, and visit `http://localhost:4567/tom.html`, I see the dynamic page. If I change the value of `bio` in `data/people.yaml`, and reload the page, there isn't any change; however, in Middleman 4, the newest value of `bio` would be shown.

This issue appears to be limited to proxy pages. If I have an template where I iterate through all data, for example the following, reloading works properly.

```erb
<% data.people.each do |person| %><%= person.name %><% end %>
```

## Additional information

- Ruby version: 2.7.1p83
- Middleman version: 5.0.0 via master branch
- OS version: macOS 10.15.4

**Comment by tdreyno** [comment]
Some of the VERY magical machinery that made this work in MM4 was removed. It was overkill. What should happen in this case is a full reboot of the dev server (rather than the old fancy bit). I believe this should just be tracking down the place where we handle restarting the server on certain file changes. I'll dig in

**Comment by pwim** [comment]
Thanks! Doing a full reboot when data changes would be highly appreciated, and probably solve some a related issue I'm having that's specific to some custom code in my app.

**Comment by tdreyno** [comment]
This is the code which controls the reload process: https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/preview_server.rb#L151-L178

As you might expect, things are a bit busy right now. I will attempt to dig in, but that may give you a head start.

**Comment by pwim** [comment]
We could extend `match_against` to include the `data_dir` like the following:

``` ruby
match_against = [
  /^config\.rb$/,
  %r{^environments/[^\.](.*)\.rb$},
  %r{^lib/[^\.](.*)\.rb$},
  %r{^#{config[:helpers_dir]}/[^\.](.*)\.rb$},
  %r{^#{config[:data_dir]}/[^\.](.*)\.(yml|yaml|json)$}
]
```

However, this approach would create an implicit coupling between the preview server and the data extension. By defining it as an extension, it seems like that was something you were striving to avoid.

The other approach would be to have the data extension itself trigger the `:reload` event. This way, while they'd still be coupled, the extension would implicitly be dependent on the preview server, which is perhaps a nicer strategy.

**Comment by tdreyno** [comment]
I agree with the more evented approach. Sorry, I don't spend enough time deep in the codebase to have it all in my head right now.

As a minor aside, data dir can nest indefinitely. Doing the change in the data extension should allow that to "just work" as opposed to a regex
