### ISSUE TITLE
Unknown Extension: autoprefixer when creating blog

### ISSUE THREAD

**Issue by Duartemartins** [middleman/middleman#2347]
## Problem

I created a new blog using `middleman init MY_BLOG --template=blog`, but when I try to start the server I get the following error message:

```
from /Users/duarte/.rvm/gems/ruby-2.7.1/gems/middleman-core-4.3.7/lib/middleman-core/extension_manager.rb:51:in `activate'
/Users/duarte/.rvm/gems/ruby-2.7.1/gems/middleman-core-4.3.7/lib/middleman-core/extensions.rb:86:in `load': Unknown Extension: autoprefixer. Check the name and make sure you have referenced the extension's gem in your Gemfile. (RuntimeError)
```
Any idea what could be the problem? This happens any time I use the middleman command on VSCode.

## Additional information

- Ruby version: 2.7.1
- Middleman version: 4.3.7
- OS version: MacOS 10.15.6

**Comment by tdreyno** [comment]
Can you share your Gemfile?

**Comment by ggarron** [comment]
I am using Ruby 2.6 as 2.7 gave me errors.

**Comment by Duartemartins** [comment]
> Can you share your Gemfile?

```
source 'https://rubygems.org'

# Middleman Gems
gem 'middleman', '~> 4.2'
gem 'middleman-blog'

gem 'redcarpet', '~> 3.3', '>= 3.3.3'

# For feed.xml.builder
gem 'builder', '~> 3.0'

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby, :x64_mingw]

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw, :x64_mingw]
```

**Comment by JoshuaWoodsdev** [comment]
Looks like it's the active prefex gem, its deprecated... best we can do is wait for a middleman update, patch or use webpacker....?

**Comment by Duartemartins** [comment]
Seems to have worked for me now. Unsure what changed.

**Comment by tdreyno** [comment]
Updated the template to include the gem, please try now.

**Comment by Duartemartins** [comment]
Yes it works now, thank you.
