### ISSUE TITLE
Allow Middleman to "live" with another Rack-app

### ISSUE THREAD

**Issue by ghost** [middleman/middleman#235]
I would like to suggest shifting the Middleman paradigm slightly. I like to use Middleman to generate the static parts of the websites I build which generally live in /serverpath/app/public or the "public" folder in my rack-enabled apps. As of now, I generally have two "apps" (one being my Middleman site), as far as development is concerned. Then when they are both done I "combine" them together by putting everything from the Middleman "build" folder into the public folder of my other Rack-based app.

I believe that integrating the Middleman structure into a structure that could live together with a Rails, Sinatra, etc app during development and after, without any conflicts, would be a great idea. Also, if the Middleman structure could go a step further and complement the rack-based-app structure by generating a site into ../public by default and maybe setting up its own folder (namespace) for configuration files, source files, etc. it would make Middleman more useful. I think in doing so, the same quality of software for people who only want to use Middleman for a static site can be maintained.

I haven't yet tried this but it seems to me that the most obvious conflict will be my config.ru file. The scattering of configuratino files is also messy. Other than that I think I can set it all up. However, I think the smartest defaults for Middleman to have would be those that allow it to live with another app.

Thank you.

**Comment by joost** [comment]
Also see #1394.
