### ISSUE TITLE
Does project have some plan/milestone, so I can help it to reach to v5?

### ISSUE THREAD

**Issue by le0pard** [middleman/middleman#2352]
Hello.

I am using middleman in bunch of my projects and decided to help it. 

Is it have some plan/milestone, so I can select tasks and help with them, so project continues to bloom and reach to v5 version?

Thanks

**Comment by tdreyno** [comment]
Actually, v5 has been ready to ship for a long time. The big issue is that I, personally, do not have time in my schedule to support a large launch (lots of new tickets, tweets and doc changes). I've been hoping to find time in my schedule to support it, but clearly this has been a very strange year for everyone.

Happy to continue to discuss how we could facilitate a smooth launch.

Post-v5.0, I want to really push the docker support (https://github.com/middleman/middleman-docker) to make it easier for folks to use (getting Ruby on PCs is always difficult).

**Comment by le0pard** [comment]
@tdreyno ok. In this case will try to help with tickets, docs and Docker.

**Comment by le0pard** [comment]
BTW, about docker. 

Also possible approach to ship middleman in this same way, as doing vagrant - https://github.com/hashicorp/vagrant . They had the same issue to ship it as gem, because many people don't know how to install Ruby and invalid Ruby also lead to issues. So we can just create packages for different systems.
