### ISSUE TITLE
Error on Middleman Sitemap Debug page after new frozen_string_literal added

### ISSUE THREAD

**Issue by westonganger** [middleman/middleman#2369]
The `frozen_string_literal` comment was added to this file: `middleman-core/lib/middleman-core/meta_pages/sitemap_resource.rb`

It causes the following error on the sitemap debug page`/__middleman/sitemap/`

```
FrozenError at /__middleman/sitemap/
can't modify frozen String: ""
```

**Comment by tdreyno** [comment]
Thanks for flagging, we'll take a look

**Comment by tdreyno** [comment]
Fixed here: https://github.com/middleman/middleman/commit/e9d4cdcd2b5665bcfd0ab27c0a230c8b4fa82693
