### ISSUE TITLE
Tips for updating extensions to v4?

### ISSUE THREAD

**Issue by jagthedrummer** [middleman/middleman#2374]
Hey there, I'm trying to update an extension to v4 and am having trouble finding any info about the upgrade path for extensions.

I have the test suite for the extension working with `3.4.1` and if I try to take a baby step to `4.0.0` I can't even get gems to install. If I go to `4.3.8` I can get everything to install but all the tests fail, some seemingly due to changes in the extension structure, and some seemingly because the `middleman` command is missing(?!?).

Can somebody point me towards docs for this and/or offer any tips about the process?

**Comment by jagthedrummer** [comment]
I was finally able to get `4.0.0` to install with this combo of gems:

```ruby
  spec.add_dependency "middleman-core", "~> 4.0.0"

  spec.add_dependency("mini_magick", ["~> 3.7.0"])
  spec.add_dependency "fastimage", "~> 1.8"

  # To make sure that we don't have any collisions with sprockets
  spec.add_dependency "middleman-sprockets", "~> 4.0.0"

  # Seems that we need to include middleman proper as a dev dependency
  # in order to have the middleman command available for tests
  spec.add_development_dependency "middleman", "~> 4.0.0"

  spec.add_development_dependency "bundler", "~> 1.5"
  spec.add_development_dependency "capybara", "~> 2.5.0"
  spec.add_development_dependency "cucumber", "~> 2.0"
  spec.add_development_dependency "aruba",    "~> 0.14.0"
  spec.add_development_dependency "byebug"
```

**Comment by tdreyno** [comment]
Our template is here, but all it really does is rely on core: https://github.com/middleman/middleman/blob/master/middleman-cli/lib/middleman-cli/templates/extension/gemspec

If that doesn't work out of the box, let me know and I can add some more specific gems to that

**Comment by jagthedrummer** [comment]
If it'll help anybody in the future, here's the change set for upgrading my extension from v3 to v4. https://github.com/Octo-Labs/middleman-automatic-clowncar/pull/10
