### ISSUE TITLE
Can't initialize a project with Ruby 2.7.0 and middleman 4.3.9

### ISSUE THREAD

**Issue by spilth** [middleman/middleman#2375]
### Expected

```
❯ middleman init wastelandwarfare
# Project is created...
```

### Actual

```
❯ middleman init wastelandwarfare
Traceback (most recent call last):
	4: from /Users/brian/.rbenv/versions/2.7.0/bin/middleman:23:in `<main>'
	3: from /Users/brian/.rbenv/versions/2.7.0/bin/middleman:23:in `load'
	2: from /Users/brian/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/middleman-cli-4.3.9/bin/middleman:3:in `<top (required)>'
	1: from /Users/brian/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/brian/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- middleman-core/profiling (LoadError)
```

## Steps to reproduce the problem (from a clean middleman installation)

- install rbenv
- install ruby 2.7.0 via rbenv
- set rbenv shell to 2.7.0

## Additional information

- Ruby version:  2.7.0
- Middleman version: 4.3.9 
- OS version: macOS 10.15.5

**Comment by jubishop** [comment]
I have this problem as well.  cannot load middleman-core/profiling

**Comment by jubishop** [comment]
@spilth got any workaround at the moment you care to share?

**Comment by spilth** [comment]
No work around except giving a different static site tool a try.

**Comment by jubishop** [comment]
ah.  I already use this one.  I went ahead and uninstalled and went back to middleman 4.3.8 which does work.  @spilth

**Comment by JoshuaWoodsdev** [comment]
MIddleman seems to have been having alot of bugs lately

**Comment by jubishop** [comment]
I'm sure they'll address this soon.  4.3.8 was working for me just fine and still is.  I'll just wait until this is closed before updating.

**Comment by tdreyno** [comment]
Probably going to have to revoke this version. First time deploying from a windows box, I think it may have somehow missed some files. I'll dig in tomorrow. In the meantime, point the ole Gemfile at 4.3.8

**Comment by oliverguenther** [comment]
Can confirm that 4.3.9 is causing this issue. Pinning the version at 4.3.8 resolves it

**Comment by tdreyno** [comment]
Okay, fixed. 4.3.10 is good to go. It was an issue with the git setup on the windows machine that was publishing.
