### ISSUE TITLE
YAML front matter in HAML templates not preserved if in comments

### ISSUE THREAD

**Issue by infews** [middleman/middleman#2385]
## Expected behavior and actual behavior

YAML front matter inside a HAML template multi-line comment is ignored at site build time.

```haml
#- 
  ---
  title: 404 Not Found
  sitemap_ignore: true
  ---
```

In this case, the title and the sitemap_ignore data is not populated to `current_page.data`.

## Steps to reproduce the problem (from a clean middleman installation)

- Pick a template
- Convert to HAML
- Put the YAML front matter in a comment
- `middleman build`

## Justification

- IDE's treat YAML in some template files as syntax errors (definitely HAML, possibly others)
- The front_matter_parsing gem expects the data in comments
- The individual YAML can be commented out inside the front matter if need be for debugging, etc.

## Additional information

- Ruby version:  2.6.5
- Middleman version: 4.2.1
- OS version: MacOS Catalina

**Comment by tdreyno** [comment]
The frontmatter parser is no aware of template language specific syntax. The non-commented and indented format should work, but you are right that it may frustrate your syntax highlighting or linting.

The deliminators (`---`) are configurable. I _may_ be possible to get them to work, but I expect the extra indentation will frustrate the yaml parser.

Perhaps something like:

```
config[:frontmatter_delims][:yaml] << ["#-\n   ---", "  ---"]
```

Could work.

**Comment by infews** [comment]
How do you feel about this concept, though? I don't see much consensus about whether front-matter should be commented or not. About 50/50.

But the [front matter parser][gem] requires the YAML to be in comments, else it doesn't find it. Note, I used this gem in a different project earlier this week.

[gem]: https://github.com/waiting-for-dev/front_matter_parser

**Comment by tdreyno** [comment]
I had not seen this gem before. Seems reasonable and its always nice to not have to write that logic when there is a nice gem for it, but it would also be very backwards incompatible with existing projects.

 Let me think about what it might take to make this happen given our current code. Might be able to add some more deliminator combinations

**Comment by tdreyno** [comment]
Okay, took a very naive approach at this on master and added some tests. Look at that commit and see if the tests look like what you're thinking. I can backport to the stable release if so.

**Comment by infews** [comment]
Yes, this looks like what I'm thinking. Thanks!
