### ISSUE TITLE
TOML support for front matter and data files

### ISSUE THREAD

**Issue by marcoms** [middleman/middleman#2402]
It would be great if [TOML](https://toml.io) was supported for the above since it can be much less verbose than JSON without the ambiguity and strictness of YAML (i.e. no tabs allowed). Not that this should be the main motivator, but Hugo also [supports this](https://gohugo.io/content-management/front-matter/).

**Comment by tomrutgers** [comment]
TOML is supported, actually: https://www.netlifycms.org/docs/configuration-options/#extension-and-format

**Comment by tdreyno** [comment]
Seems like a good idea, I'll see what I can do

**Comment by tdreyno** [comment]
@marcoms Point your Gemfile at the github `4.x` branch and let me know if that works for you.

**Comment by marcoms** [comment]
Thanks for working on this! I updated my gemfile like so:

```
gem 'middleman', github: 'middleman', branch: '4.x'
```

But when changing my front matter to TOML I get `TOML Exception parsing (file path).html.erb`, and I'm pretty sure it's valid:

```
+++
title = "TOML Example"
+++
```

**Comment by tdreyno** [comment]
Okay, confirmed and found the issue/typo. Please bundle update and try again

**Comment by marcoms** [comment]
Front matter and data files seem to work perfectly now 👍

**Comment by tdreyno** [comment]
Great, I'll get a minor stable version out
