### ISSUE TITLE
Preview server has poor performance for sites with many resources  

### ISSUE THREAD

**Issue by pwim** [middleman/middleman#2418]
I'm using the main GitHub branch, though I think this issue isn't necessarily related to that.

I noticed that editing a single file causes the entire resource list to be rebuilt:

https://github.com/middleman/middleman/blob/d30cb7afe61853b11c121a93226c9a3a25240621/middleman-core/lib/middleman-core/sitemap/extensions/on_disk.rb#L45-L49

My site has 459 resources (according to `ready { puts sitemap.resources.to_a.size }` ).  When I change a single template file, it takes several seconds for all the sitemap manipulators to be run:

```
== Requesting resource list rebuilding: touched_file
== Rebuilding resource list
== Running manipulator: sitemap_ondisk (0)
== Instrument (sitemap.manipulator): 158.719ms
{:name=>:sitemap_ondisk}
== Running manipulator: sitemap_endpoint (0)
== Running manipulator: sitemap_proxies (0)
== Instrument (sitemap.manipulator): 804.403ms
{:name=>:sitemap_proxies}
== Running manipulator: sitemap_redirects (0)
== Running manipulator: sitemap_ignore (0)
== Running manipulator: sitemap_import (1)
== Running manipulator: routing (10)
== Instrument (sitemap.manipulator): 136.452ms
{:name=>:routing}
== Running manipulator: front_matter (20)
== Instrument (sitemap.manipulator): 233.641ms
{:name=>:front_matter}
== Running manipulator: blog_blog1_articles (50)
== Instrument (sitemap.manipulator): 575.0269999999999ms
{:name=>:blog_blog1_articles}
== Running manipulator: blog_blog1_tags (50)
== Instrument (sitemap.manipulator): 404.429ms
{:name=>:blog_blog1_tags}
== Running manipulator: directory_indexes (100)
== Running manipulator: sitemap_move_files (101)
== Running manipulator: collections (110)
== Running manipulator: routing (130)
== Instrument (sitemap.manipulator): 119.467ms
{:name=>:routing}
== Instrument (sitemap.update): 2474.872ms
{:reasons=>[:touched_file]}
```

Given this, it's frustrating slow to work on my site's templates.

**Comment by tdreyno** [comment]
Definitely seems odd that so much time is being spent in `sitemap_proxies` and `blog.`

Mind posting your `config.rb`?

**Comment by pwim** [comment]
I investigated this a bit more, and it looks like sitemap.update takes twice the time to update in middleman 5 as it did in 4.

My config.rb has a bunch of custom extensions, which may be part of the reason why my site takes exceptionally long to update. However, even this simple `config.rb` demonstrates the issue.

``` ruby
# config.rb
activate :blog

500.times do |i|
  proxy File.join("/#{i}", "index.html"), "index.html"
end
```

<details>
<summary>middleman 4's sitemap.update takes 981ms</summary>
<pre><code>== Requesting resource list rebuilding: touched_file
== Rebuilding resource list
== Running manipulator: sitemap_ondisk (0)
== Running manipulator: sitemap_endpoint (0)
== Running manipulator: sitemap_proxies (0)
== Instrument (sitemap.manipulator): 76.467ms
{:name=>:sitemap_proxies}
== Running manipulator: sitemap_redirects (0)
== Instrument (sitemap.manipulator): 32.825ms
{:name=>:sitemap_redirects}
== Running manipulator: sitemap_ignore (0)
== Instrument (sitemap.manipulator): 40.888ms
{:name=>:sitemap_ignore}
== Running manipulator: sitemap_import (1)
== Instrument (sitemap.manipulator): 75.575ms
{:name=>:sitemap_import}
== Running manipulator: routing (10)
== Instrument (sitemap.manipulator): 70.92099999999999ms
{:name=>:routing}
== Running manipulator: front_matter (20)
== Instrument (sitemap.manipulator): 410.66ms
{:name=>:front_matter}
== Running manipulator: blog_blog1_articles (50)
== Instrument (sitemap.manipulator): 164.411ms
{:name=>:blog_blog1_articles}
== Running manipulator: sitemap_move_files (101)
== Instrument (sitemap.manipulator): 32.132ms
{:name=>:sitemap_move_files}
== Running manipulator: collections (110)
== Instrument (sitemap.manipulator): 43.95ms
{:name=>:collections}
== Running manipulator: routing (130)
== Instrument (sitemap.update): 981.302ms
{:reasons=>[:touched_file]}
</code></pre>
</details>

<details>
<summary>middleman 5's sitemap.update takes 1799ms</summary>
<pre><code>== Requesting resource list rebuilding: touched_file
== Rebuilding resource list
== Running manipulator: sitemap_ondisk (0)
== Running manipulator: sitemap_endpoint (0)
== Running manipulator: sitemap_proxies (0)
== Instrument (sitemap.manipulator): 645.12ms
{:name=>:sitemap_proxies}
== Running manipulator: sitemap_redirects (0)
== Running manipulator: sitemap_ignore (0)
== Running manipulator: sitemap_import (1)
== Running manipulator: routing (10)
== Running manipulator: front_matter (20)
== Instrument (sitemap.manipulator): 415.058ms
{:name=>:front_matter}
== Running manipulator: blog_blog1_articles (50)
== Instrument (sitemap.manipulator): 734.7719999999999ms
{:name=>:blog_blog1_articles}
== Running manipulator: sitemap_move_files (101)
== Running manipulator: collections (110)
== Running manipulator: routing (130)
== Instrument (sitemap.update): 1799.064ms
{:reasons=>[:touched_file]}
</code></pre>
</details>

I also did some very rudimentary benchmarking of how the time to update grows as the number of proxy pages does:

proxy pages | middleman 4 | middleman 5
-|-|-
10| 38ms| 45ms
100|398ms | 585ms
1000| 1688ms | 2943ms

So it seems in both versions, any middleman site with a large number of proxy pages is going to be frustratingly slow.

**Comment by tdreyno** [comment]
That benchmark is a great place for me to start. There's also the `--instrument` flag which may reveal more data on where time is being spent.

**Comment by pwim** [comment]
I actually did run `bundle exec middleman server --verbose --instrument`. Maybe it wasn't obvious, but the output is hidden behind a `<details>` tag in [my previous comment](https://github.com/middleman/middleman/issues/2418#issuecomment-751424412).

Basically, it looks like sitemap_proxies, middleman blog, and front_matter each take about a single millisecond per proxied page. So I think the first thing to look at is if we can make any of those more operations more efficient.

Also, in my app, I managed to make things a bit more efficient by removing middleman-blog in favour of my own homebrewed solution that puts the articles in data files (something I'd been wanting to do anyways). This got it down to 1677ms from 2474ms. Switching to Ruby 3.0 also improved things noticeably, taking it down to 955ms. Updates still aren't as fast as I'd like them to be, but it's approaching an acceptable level (though I suppose the scalability issue is still there, and as I add more pages, it will slow down again).

**Comment by tdreyno** [comment]
Question about the above, does that test case actually have blog content or is it taking 734.7719999999999ms to run that step even with an empty blog?

**Comment by pwim** [comment]
The config.rb is literally all there is, besides what is generated with `middleman new`, so there's no pages for the blog.

**Comment by tdreyno** [comment]
Which file are you editing to trigger the recalculation? I'm changing layout and index and it doesn't trigger a new sitemap calculation?

**Comment by pwim** [comment]
Just so we're on the same page, I've pushed my middleman app here: https://github.com/pwim/middleman-speed-test.

Setup:

```
git clone https://github.com/pwim/middleman-speed-test.git
cd middleman-speed-test 
bundle exec middleman server --verbose --instrument
```

When I run `touch source/index.html.erb`, the sitemap is recalculated.

**Comment by tdreyno** [comment]
I can't reproduce that on Windows or Docker linux, but I'll explore it on my Mac tomorrow.

I did, however, find another fun bug. Whenever the server restarts (due to config change), its not fully disposing of the old config. So for each config change, the manipulators for each extension are run 1 more time. I cannot tell yet if they are running in alternate universes (unused old environments that aren't being used, but can still log) or if they are causing every extension to re-register and run each time.

Thanks for the report

**Comment by pwim** [comment]
I am on a Mac, so it could indeed be related to that. Though unless I'm misunderstanding something, the comment implies that if the sitemap isn't being regenerated in other environments when a file is changed, that could be a bug:

https://github.com/middleman/middleman/blob/d30cb7afe61853b11c121a93226c9a3a25240621/middleman-core/lib/middleman-core/sitemap/extensions/on_disk.rb#L45-L49

**Comment by tdreyno** [comment]
Indeed, that would be a huge issue :) While I work mostly on a Mac, I've started using my PC for side-projects and OSS for precisely this reason. Its pretty brutal how bad most OSS is on PC

**Comment by pwim** [comment]
Digging into the performance issue a bit more,  rebuilding the sitemap triggers [`ProxyDescriptor#execute_descriptor`](https://github.com/middleman/middleman/blob/d30cb7afe61853b11c121a93226c9a3a25240621/middleman-core/lib/middleman-core/sitemap/extensions/proxies.rb#L37). This eventually triggers [`ResourceListContainer#add_cache`](https://github.com/middleman/middleman/blob/c617c2c16534e4628f86b0400554636bf1a2b723/middleman-core/lib/middleman-core/sitemap/resource_list_container.rb#L56). 

The `add_cache` method appears to take about 1ms to run on a `Middleman::Sitemap::ProxyResource` (about 0.5ms for a Middleman::Sitemap::Resource). The method itself is doing a bunch of things, none of which by themselves appear to be causing a bottleneck. So at least to me, there's no obvious simple refactoring.

**Comment by tdreyno** [comment]
I changed how the sitemap works in v5. It was linear manipulators (reducers, but hey, we got here first :), but I thought I had found some ways to parallelize that and make it smart... I probably just shot myself in the foot or ran things twice.

Its also possible our data structure (::Hamster::SortedSet) is slow with large numbers of items. Maybe its sorting or looking for collisions in an odd way.

**Comment by pwim** [comment]
Awesome, thanks for your help! This has gotten my sitemap to update in under 100ms, which will make development pleasant again.

**Comment by tdreyno** [comment]
Thank you very much for both the ticket and the test case.
