### ISSUE TITLE
Migration from MM4 to MM5 for fully i18nized site

### ISSUE THREAD

**Issue by svoop** [middleman/middleman#2433]
@tdreyno This is a followup to the mail exchange we had some days ago.

I'm trying to migrate some sites which have all their pages translated to various languages. They don't have a `localizable` directory (as suggested by [the guide](https://middlemanapp.com/advanced/localization/)), but use the source directory itself in the activation in `config.rb`:

```ruby
activate :i18n, templates_dir: '.', locales: %i(en de)
```

This works fine on MM4 but breaks on MM5. To illustrate, I've stripped one site down to the bare scaffold, prepped the `Gemfile` for both middlemen and then built with both to `build-mm4` and `build-mm5` and put it all [in this debugging repo](https://github.com/svoop/mm4to5). The result of the two builds is quite different.

[build-mm4](https://github.com/svoop/mm4to5/tree/main/build-mm4):
```
/index.html
/contact/index.html

/de/index.html
/de/contact/index.html
```

[build-mm5](https://github.com/svoop/mm4to5/tree/main/build-mm5):
```
/index.en.html
/index.de.html

/contact/index.de.html
/contact/index.en.html
```

Is this a bug or am I doing something wrong here? Thanks a bunch for your help!

**Comment by tdreyno** [comment]
Does placing them inside the localizable folder fix this? I would say that the code does not expect that folder to be the root (and therefore the parent of other folders)

**Comment by svoop** [comment]
Indeed, this fixes the issue.

Feels weird though having to put the entire site into yet another nesting.

Why is the `template_dir` necessary at all? From my non-dev POV, an easier way to use `i18n`:

```
# The primary locale is built into the root dir:
# activate :i18n, locales: %i(en de)

source/index.en.html
source/foo/index.en.html

build/index.html
build/foo/index.html
```

```
# Other locales are built into their path-namespace:
# activate :i18n, locales: %i(en de)

source/index.de.html
source/foo/index.de.html

build/de/index.html
build/de/foo/index.html
```

```
# Templates which are not scoped to a locale are used for every locale unless a scoped one is overriding this:
# activate :i18n, locales: %i(en de fr)

source/index.html
source/index.fr.html

build/index.html      # from source/index.html
build/de/index.html   # from source/index.html
build/fr/index.html   # from source/index.fr.html
```

I'll poke around a little in `i18n.rb`, but maybe you can give me a hint if or why I bark up the wrong tree. :smile:

**Comment by tdreyno** [comment]
The template directory predates the file format you are using, with the locale in the file name.

Then there are partials or files where the html is identical, it just gets run with different strings so the file wouldn’t have a locale in its name.

**Comment by svoop** [comment]
@tdreyno 

IC, the two ways to do i18n are quite obvious looking at the 6b88e315 refactoring by @iblue. This is also the commit which by fixing bugs "breaks" my approach to do i18n by use of file extensions only.

Now, I've played around a little and created a commit which introduces `options[:templates_dir] = false` to not use a templates directory at all but expect all files to use extensions like `index.en.html` for i18n:

https://github.com/svoop/middleman/commit/4ece3c55c63418ca4a814bbc843acf79db711a29

There are no additional tests and no PR yet, I'd like to get your opinion and maybe the opinion of @iblue beforehand.

(Btw, it might be possible to reduce the added complexity e.g. by refining `File#join`, but I take from you silencing Rubocop `Metrics/MethodLength` that you prefer readability over fragmentation in places, so I kept all things encapsulated in `i18n.rb`.)

**Comment by tdreyno** [comment]
I'd merge that (with tests)

**Comment by svoop** [comment]
@tdreyno I've added the tests, just checking something on my site before creating the PR.

**Comment by svoop** [comment]
@tdreyno Works like a charm on Ruby 3 and builds the sites really fast, way cool! Thanks a lot for these improvements! 🥇 (No need to be jealous of Hugo anymore.)
