### ISSUE TITLE
Helpers are loaded twice

### ISSUE THREAD

**Issue by svoop** [middleman/middleman#2435]
Apparently, custom helpers are loaded twice which triggers warnings e.g. if the helper defines a constant.

To demo, check out this simple site: https://github.com/svoop/mm4to5

It features a [helper with a demo constant `FOO`](https://github.com/svoop/mm4to5/blob/main/helpers/html_helpers.rb). Building the site yields the following:

```
/mm4to5/helpers/html_helpers.rb:3: warning: already initialized constant HtmlHelpers::FOO
/mm4to5/helpers/html_helpers.rb:3: warning: previous definition of FOO was here
== Locales: en, de (Default en)
      create  build/__assets/stylesheets/main-739c7a9c.css
      create  build/__assets/javascripts/main-051b651f.js
      create  build/contact/index.de.html
      create  build/index.en.html
      create  build/index.de.html
      create  build/contact/index.en.html
Project built successfully.
```

As a workaround, `FOO ||= :bar` will silence the warning, but obviously, it's just an ugly hack. :smile:

**Comment by tdreyno** [comment]
I can confirm this is happening. There is a reason, but its not a great one.

The CLI runs config first so it has awareness of plugins.

Then the server runs it again to boot the server.

I'll have a think and see if there is a solution.
