### ISSUE TITLE
5.0.0.rc.1: "mail_to" helper not working due to missing Rack::Utils

### ISSUE THREAD

**Issue by svoop** [middleman/middleman#2436]
The `mail_to` helper (supplied by padrino-helpers-0.14.4) and maybe others don't work anymore because it uses `Rack::Utils` to build the query and as of 5.0.0.rc.1, Rack is not loaded when building a site:

```
uninitialized constant Rack::Utils
/Users/foo/.gem/ruby/3.0.0/gems/padrino-helpers-0.14.4/lib/padrino-helpers/asset_tag_helpers.rb:147:in `mail_to'
__assets/elements/buttons/_social.erb:19:in `__tilt_18140'
```

As a workaround, adding `require "rack"` to config.rb fixes the issue.

**Comment by tdreyno** [comment]
Mmm. Gotta love dependency management in Ruby.  We can add that rack require near the padrino require

**Comment by svoop** [comment]
@tdreyno I've created a PR which fixes the problem for me, however, not sure whether it covers all possible cases: #2437

**Comment by svoop** [comment]
Merci!
