### ISSUE TITLE
image hash path not updating for some files

### ISSUE THREAD

**Issue by myster-t** [middleman/middleman#2438]
## Expected behavior and actual behavior

i have two files, identical code (with different titles, one is `index` other is `faq`):
```
---
layout: webflow
title: "index"
---
<img src="images/Logo.svg" loading="lazy" alt="" class="image">
<%= image_tag 'Logo.svg', class: 'image' %>
```

one is `index.html.erb` the other is `faq.html.erb`, but for some reason the `index.html.erb` displays the logo twice (this is expected) and the second file (`faq.html.erb`) only display the logo once (the image_tag generated logo). why is it that normal img tags' src paths aren't updated with asset_hashes on non-index pages?

this is same for middleman server and build

## Additional information

- Middleman version: 4.3.11
- OS version: mac 10.15

**Comment by tdreyno** [comment]
Can you post your test project?
