### ISSUE TITLE
[Chore] 4.3.11 git tag & changelog

### ISSUE THREAD

**Issue by noraj** [middleman/middleman#2446]
Git tag 4.3.11 (15 September 2020) seems missing.

- git tags https://github.com/middleman/middleman/tags
- 4.3.11 on rubygems https://rubygems.org/gems/middleman/versions/4.3.11

By the way the [CHANGELOG](https://github.com/middleman/middleman/blob/master/CHANGELOG.md) is missing any version between 4.3.4 and 4.3.11.

**Comment by tdreyno** [comment]
They are on the 4.x branch. https://github.com/middleman/middleman/blob/4.x/CHANGELOG.md

**Comment by tnir** [comment]
> git tags https://github.com/middleman/middleman/tags

@tdreyno We still are not able to see the tag for 4.3.11.

**Comment by tdreyno** [comment]
Pushed

**Comment by tnir** [comment]
Thank you ❤️
