### ISSUE TITLE
`Concat` not working with HAML

### ISSUE THREAD

**Issue by jacoblockard99** [middleman/middleman#2454]
## Expected behavior and actual behavior

I am trying to use `concat` in Middleman, however it appears to do nothing when using HAML. Note that it does work when using ERB.

## Steps to reproduce the problem (from a clean middleman installation)

1) Generate a new Middleman project with `middleman new Example`.
2) Create `helpers/custom_helpers.rb` with the following contents:
```ruby
module CustomHelpers
  def some_helper
    concat 'Hello'
  end
end
```
3) Add the `haml` gem to the Gemfile and run `bundle install`.
4) Create `source/test.html.haml` with the following contents:
```haml
- some_helper
```
5) Start the development server (with `bundle exec middleman`) and browse to `/test.html`.

The result is an empty page, even though "Hello" should have been outputted.

## Additional information

- Ruby version: 2.7.2
- Middleman version: 4.3.11
- OS version: Ubuntu 20.04.2

**Comment by tomrutgers** [comment]
Try `= some_helper`

**Comment by jacoblockard99** [comment]
`= some_helper` works. Why is it though that `<% some_helper %>` works in ERB (instead of `<%= some_helper %>`), but `- some_helper` doesn't?

**Comment by jacoblockard99** [comment]
Also, I discovered that to get the behavior I wanted I could use `haml_concat` instead. Why doesn't `concat` work the same way?

**Comment by tomrutgers** [comment]
In ERB, the correct syntax is actually `<%= some_helper %>` as well. I think it's better to raise these questions over at the [official haml repo](https://github.com/haml/haml.), as they address language differences rather than Middleman specific features.
