### ISSUE TITLE
css 404 error after build

### ISSUE THREAD

**Issue by elizaplowden** [middleman/middleman#2463]
Hi there, 

I'm building my first middleman site and am experiencing some issues with the stylesheet link. The css was running before, but after running 'bundle exec middleman build', I am getting a 404 in the stylesheets. I've added a default to the config.rb file, tried changing the file names etc but nothing seems to be working. 

Any advice? I'm struggling a lot.

Thanks!

**Comment by tomrutgers** [comment]
Can you share your repository?

**Comment by tdreyno** [comment]
Hi @elizaplowden If you can record your process, it might be easy to quickly figure out the cause.

**Comment by elizaplowden** [comment]
https://github.com/elizaplowden/attomo

Here is the link to the repo. 
It is a Middleman template with some basic html/css while I was learning to use Dato CMS. The integration was working and the app was running fine locally until I ran the build command. I believe my files are named correctly and the stylesheet is linked properly in layout.erb. I commented out the minify_css activation in config.rb and also added 'set :css_dir, 'stylesheets'' in the hope that this might fix the issue, but it didn't.

Thank you so much for your help! I'm really stuck.

**Comment by tdreyno** [comment]
Can you try commenting out any line that says "sprockets" including Gemfile and config.rb

**Comment by htmlboy** [comment]
@tdreyno I'm not sure the issue I've found is related to this one, but a clean middleman install won't build the CSS file. It throws the following error messages:

`DEPRECATION WARNING: autoprefixer-rails was deprected.
TypeError: Cannot read property 'version' of undefined
`

Disabling autoprefixer in the config.rb file actually fixes the problem (well, the CSS compiles):

```
# activate :autoprefixer do |prefix|
#   prefix.browsers = "last 2 versions"
# end
```

**Comment by tdreyno** [comment]
@htmlboy Looks like I need to publish a new version of middleman-autoprefixer. Until then, you can point your Gemfile at git

```
gem "middleman-autoprefixer", github: "middleman/middleman-autoprefixer"
```

**Comment by noraj** [comment]
Fixed by:

```diff
-gem 'middleman-autoprefixer', '~> 2.10'
+gem 'middleman-autoprefixer', '~> 3.0'
```

**Comment by noraj** [comment]
By doing this update

```
  * middleman (newest 4.4.0, installed 4.3.11, requested ~> 4.3) in group "default"
  * middleman-autoprefixer (newest 3.0.0, installed 2.10.1, requested ~> 2.10) in group "default"
  * middleman-livereload (newest 3.4.7, installed 3.4.6) in group "development"
```

I had a lot of `TypeError: Cannot read property 'version' of undefined` errors and the CSS was not built anymore while reviewing the CHANGELOGs no breaking changes were announced about that.

The previous message I put fixed the issue but also this is a good idea if you plan to use ruby 3.0.x:

```diff
-gem 'middleman', '~> 4.3'
+gem 'middleman', '~> 4.4'
```

**Comment by noraj** [comment]
unstale

**Comment by noraj** [comment]
unstale

**Comment by nabrown** [comment]
I am also having an issue with autoprefixer. I'm using ruby version 3.1.0p0, and just installed Middleman and initted a new project. My gemfile reads:

```
source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby, :x64_mingw]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw, :x64_mingw]
```

And when I run the `build` or `server` commands, the CSS doesn't compile unless I comment out `autoprefixer`. The error output is:

```
error  build/stylesheets/nora-brown-design.css
TypeError: Cannot read properties of undefined (reading 'version')
...
```

How can I get autoprefixer working?

**Comment by bandogora** [comment]
unstale
