### ISSUE TITLE
Load plain text or markdown files from data folder

### ISSUE THREAD

**Issue by joapuiib** [middleman/middleman#2464]
This is not an issue, but a question.

I know that Middleman automatically loads the contents of `.json` or `.yml` [data files](https://middlemanapp.com/advanced/data-files/) that exist in the `/data` folder.

Is there any way to load the contents of __any__ `.txt` or `.md` file inside this folder?

I found this [extension](https://github.com/stevenosloan/middleman-data_source), but I don't see how I can achieve this.

## Example
Given this structure and the following files:
```
data/
├── foo.yml
└── bar.txt
```
- `foo.yml`:
```yaml
text: "I can load this text."
```
- `bar.txt`
```text
I want to load this text.
```

I can access `data.foo.text` and retrieve `I can load this text.`

I want to access `data.bar` and retrieve `I want to load this text.`

Thanks in advance!

**Comment by tdreyno** [comment]
You can actually do this with the yaml data itself:

https://github.com/middleman/middleman/blob/master/middleman-core/fixtures/nested-data-app/data/examples/withcontent.yaml

Put some Yaml inside a  `---` block at the top, what comes after will be available as text as `data.foo.postscript`

Which, if markdown, can be run through a filter to render to html

https://github.com/middleman/middleman/blob/master/middleman-core/fixtures/nested-data-app/source/extracontent.html.haml.erb

**Comment by joapuiib** [comment]
That's a nice alternative.

The only problem is that the files that I try to load are shared among other people and I can't modify them.

More precisely, I'd like to load data from this [repository](https://github.com/joapuiib/problemes-programacio), that contains programming problems. I'm trying to follow the [ICPC problem format](https://clics.ecs.baylor.edu/index.php?title=Problem_format).

For each problem([example](https://github.com/joapuiib/problemes-programacio/tree/master/AirContamination)), I have:
* `problem.yaml`: Contains problem metadata. This is loaded properly.
* `enunciat.md`: Problem description.
* `tests/`: Directory that contains several test cases in plain text:
  * `foo.in`: Input
  * `foo.out`: Expected output

**Comment by tdreyno** [comment]
This is probably the closest. There is a raw data API: https://github.com/middleman/middleman/blob/48c97b22ff25e22a2533fb5b4128337b5a97e080/middleman-core/fixtures/basic-data-app/config.rb

So do your data fetching, loading and parsing in config.rb, then pass them to the data store. They should be accessible like local files in your templates.

**Comment by joapuiib** [comment]
> You can actually do this with the yaml data itself:
> 
> https://github.com/middleman/middleman/blob/master/middleman-core/fixtures/nested-data-app/data/examples/withcontent.yaml
> 
> Put some Yaml inside a `---` block at the top, what comes after will be available as text as `data.foo.postscript`
> 
> Which, if markdown, can be run through a filter to render to html
> 
> https://github.com/middleman/middleman/blob/master/middleman-core/fixtures/nested-data-app/source/extracontent.html.haml.erb

I followed your previous suggestion and it's working :)

The only thing that doesn't work and I don't understand is the `:markdown` statement used in:
https://github.com/middleman/middleman/blob/master/middleman-core/fixtures/nested-data-app/source/extracontent.html.haml.erb

I have the following data and .erb code:
* __data/problems/problem1.yml__:
```yaml
---
name: Problem 1
---
## H2 test
- Hello __world__!
```

* Code snippet from __problem1.html__:
```erb
<% problem = data.problems.problem1 %>
<div class="problem-container">                 
    <h1><%= problem.name %></h1>  # This works
    :markdown  
      <%= problem.postscript.gsub("\n", "\n\s\s") %> # This doesn't
</div>
```

The problem I have is that the content in postscript isn't rendered.

Thanks in advance.

**Comment by tomrutgers** [comment]
I'm using a markdown helper as a workaround:
```
def markdown(content)
     Tilt['markdown'].new { content }.render
  end
```

data ('plain' yml)
```
story: >-
  ## Heading
```

Usage:
```
<%= markdown product.body %>
```

You could place your gsubs in the helper itself, even.

**Comment by joapuiib** [comment]
I managed to do it using a helper as well:

* In __config.rb__:
```ruby
helpers do 
  def markdown(text=nil)
    text ||= yield
    return Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true).render(text)
  end
end
```

* Then in __problem1.html__:
```erb
<% problem = data.problems.problem1 %>
<div class="problem-container">                 
    <h1><%= problem.name %></h1>  # This works  
    <%= markdown problem.postscript.gsub("\n", "\n\s\s") %> # Now this works too
</div>
```

Even so, I'm still intrigued about the `:markdown` syntax used in: 
https://github.com/middleman/middleman/blob/master/middleman-core/fixtures/nested-data-app/source/extracontent.html.haml.erb

**Comment by 666nei** [comment]
statistics_text = db.get_db_stats(is_markdown=True)
        site_file.write('## Statistics\n\n')
        site_file.write(statistics_text
