### ISSUE TITLE
Allow users to use Active Support 6.1 in Middleman 4.x

### ISSUE THREAD

**Issue by tnir** [middleman/middleman#2479]
## Expected behavior and actual behavior

While #2462 relaxed the Active Support version to 6.0.x, we still are not able to use Active Support 6.1.x with Middleman 4.3.x. Active Support 6.1 is mandatory to use Middleman with Ruby 3.0.

## Additional information

- Ruby version: 3.0.1
- Middleman version: 4.3.x (`4.x` branch) 
- OS version: Ubuntu 20.04 LTS, but not limited to it

**Comment by tdreyno** [comment]
Done here: https://github.com/middleman/middleman/commit/ad2c0900f17b8edc8ac4a584433b4bf77c769f5a

**Comment by olleolleolle** [comment]
Does this close this issue?

**Comment by tnir** [comment]
@olleolleolle Thanks for reminding me. Closing.

**Comment by tnir** [comment]
Middleman 4.4.0 now supports for Active Support 6.1

cf. https://rubygems.org/gems/middleman-core/versions/4.3.11/dependencies and https://rubygems.org/gems/middleman-core/versions/4.4.0/dependencies
