### ISSUE TITLE
[Proposal] Made External Pipeline primary tool for CSS/JS handling

### ISSUE THREAD

**Issue by le0pard** [middleman/middleman#2522]
Middleman is very flexible static site generator. It allow to render md to html, or erb to xml or json. And I think it is what it should focus and be major benefit for this. It should not do job about JS/CSS, only help to some tool, which will do this.

My proposal: 

 - remove primary dependency from `coffee-script`, `uglifier`, `execjs`, `sassc` gems (leave them as dev deps with renderer tests)
 - Leave sass and coffee script renderers, but require this gems only if this renderer used (so person will need add `sassc` gem in Gemfile if needed `sass` renderer from middleman)
 - Improve docs about usage js/css builders with "External Pipeline"
   - Usage with `webpack` + `webpack-assets-manifest`
   - Usage with  `vite` (we have https://github.com/ElMassimo/vite_ruby )
   - Usage with `parsel.js`
   - Usage with `snowpack`
   - ... maybe more...
- If we want, we can add assets helpers with support manifest json from build systems (example: https://github.com/rwpod/rwpod.github.io/blob/www/lib/rwpod_helpers.rb#L12-L52)

So in config we will have:

```ruby
set :external_pipeline_manifest, '.build/manifest.json'

# later in templates

<%= assets_manifest_path 'application.js' %>
<%= assets_manifest_path 'app', 'js' %> # if json manifest is nested
<%= javascript_manifest_tag 'app', 'js' %> # if json manifest is nested
<%= stylesheet_manifest_tag 'app', 'css' %> # if json manifest is nested
```

So need to here what do you think @tdreyno ?

**Comment by tdreyno** [comment]
I think that is a very good idea. With sprockets long dead and the fact that we already have tooling for integrating with arbitrary CLI tools, this could drastically simplify the project.

**Comment by le0pard** [comment]
Thanks @tdreyno . Will work on PRs
