### ISSUE TITLE
Dynamic page variables don't get encoded

### ISSUE THREAD

**Issue by razzeee** [middleman/middleman#2535]
## Expected behavior and actual behavior
Variables in the config.rg should be replaced with url encoded variants or there should be something in the guide about that.
I think it was working with the (very) old middleman, but I updated that codebase earlier and seem to have missed the regression.
https://github.com/flatpak/flatpak.github.io/blob/source/config.rb#L20

1. Goto https://flatpak.org/setup/
2. Hover the cat in the bottom left
3. The link has a `/` and ` ` that should have been escaped

## Additional information

- Ruby version: 3.0.2 (just tested this local, the linked repo is on 2.6.5)
- Middleman version:  Whatever `gem "middleman", "~> 4"` grabs
- OS version:  Fedora 35 (The server runs Fedora 30)

**Comment by razzeee** [comment]
This is still valid or should it have been patched in a newer version?

**Comment by tdreyno** [comment]
@stale reopen

**Comment by tdreyno** [comment]
Has not been patched. If I understand your issue, I _think_ it is working as designed. Can you explain the issue in more depth?

**Comment by razzeee** [comment]
I basically think I need `i.name` here https://github.com/flatpak/flatpak.github.io/blob/source/config.rb#L20 to be url encoded. But as that was a drive by migration I did on that project, I don't really have much ruby knowledge and the guides at that time didn't seem to help.

**Comment by tdreyno** [comment]
Ok. So that line is creating a file on disk with that name, it must be encoded as a valid file name, but not necessarily be url encoded. If you need that additional change to the file name, I would suggest adding the encoding to that loop inside the string template.

I think the Erb one is acceptable

```
require "erb"
::ERB::Util.url_encode(i.name)
```

**Comment by razzeee** [comment]
Doesn't seem to fix the url for me handling for me. How would you handle a website with a link that has this for e.g.? `Pisi GNU/Linux` I think I need both the handling in the proxy statement and a haml implementation to link it.

**Comment by tdreyno** [comment]
You can also use "page ids" to give refer to links in a more programmatic way: 

In config

```
require "erb"
proxy "/#{::ERB::Util.url_encode(SOMETHING)}.html", '/page.html', id: "custom_id"
```

In Haml:

```
= link_to "Link title", "custom_id"
```

Could be a database id, array index, etc

**Comment by razzeee** [comment]
I guess I'll just bite the bullet and go through the trouble and add a slug property to all the data :/

**Comment by razzeee** [comment]
Thanks for trying to help :)
