### ISSUE TITLE
Lorem.image link to placehold.it doesn't work

### ISSUE THREAD

**Issue by jbpfran** [middleman/middleman#2540]
### Expecting
In a .haml file I want to put a placeholder with `lorem.image` with the following:
`= image_tag lorem.image('128x128')`
I'm expecting an image sized 128x128.

### Actual
I'm getting nothing.
The HTML is correctly generated
`<img src="http://placehold.it/128x128">`
However the image can't be loaded.
The browser can't access the page "http://placehold.it/128x128"

## Additional information

- Ruby version: 2.7.2
- Middleman version: 4.4.2
- OS version: macOS 10.13.6

**Comment by tdreyno** [comment]
Looks like that service is no longer available. Would accept suggestions for alternatives. https://www.placecage.com/ probably isn't for everyone

**Comment by markets** [comment]
Maybe https://placehold.co? They accept custom sizes, colors, fonts, ...

**Comment by markets** [comment]
unstale!

@tdreyno as we already commented out a couple of times, the v5 is a bit uncertain at this point, but for those kind of fixes, in which branch should they be fixed (v4 or v5)? Probably more people have the same doubt about contributing in MM.

**Comment by tdreyno** [comment]
@markets v4 is probably the quickest way to get a PR released

**Comment by markets** [comment]
@tdreyno we can close this one, the service seems to be available again: https://placehold.it/128x128
