### ISSUE TITLE
How to solve "failed to load command: middleman" on M1?

### ISSUE THREAD

**Issue by BigXia** [middleman/middleman#2543]
## Steps to reproduce the problem (from a clean middleman installation)
Follow the doc step by step, but got error after run:

[192:test] docker run --rm --name slate -v $(pwd)/build:/srv/slate/build -v $(pwd)/source:/srv/slate/source slatedocs/slate build

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
bundler: failed to load command: middleman (/usr/local/bundle/bin/middleman)
/usr/local/bundle/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:69:in `initialize': Function not implemented - Failed to initialize inotify (Errno::ENOSYS)
        from /usr/local/bundle/gems/listen-3.0.8/lib/listen/adapter/linux.rb:31:in `new'
        from /usr/local/bundle/gems/listen-3.0.8/lib/listen/adapter/linux.rb:31:in `_configure'
        from /usr/local/bundle/gems/listen-3.0.8/lib/listen/adapter/base.rb:45:in `block in configure'
        from /usr/local/bundle/gems/listen-3.0.8/lib/listen/adapter/base.rb:40:in `each'
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/22040380/159781323-bff281b1-8b51-4155-902c-8dd0ca08b479.png">

## Additional information

- Ruby version: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
- Middleman version: 
- OS version: 12.2 
- M1 macbook pro
<img width="949" alt="image" src="https://user-images.githubusercontent.com/22040380/159777980-f78c9c8d-de55-4ddf-a694-cfe5acc2ffa9.png">

**Comment by tdreyno** [comment]
This is an issue either with slate, their docs or how docker works on the M1. Please report to the slate project.
