### ISSUE TITLE
Relative urls in url_for helper in I18n localized site

### ISSUE THREAD

**Issue by joapuiib** [middleman/middleman#2550]
## Expected behavior and actual behavior
- Having a localized site, configured with:
```ruby
activate :i18n, :langs => [:ca, :en, :es]
```
- Having a image in `source/folder1/images/pic1.png` that will output to `/folder1/images/pic1.png`

- Having a localized page in `source/folder1/test.en.html.md.erb` that will output to `/en/folder1/test.html` with the content:
```md
<% url = url_for "./images/pic.png" %>
<% link_to url do %>
    <img alt="screenshot" src="<%= url %>"/>
<% end %>
``` 
The previous snipped is rendered as:
```html
<a href="./images/pic.png">
    <img alt="screenshot" src="./images/pic.png">
</a>
```
As the page is built in `/en/folder1/test.html`, it is looking for the image in `/en/folder1/images/pic.png`, which doesn't exist.
### Questions
- Is it possible to output a absolute link from a relative link? I've tried to set `:relative_links => false` in `config.rb` or `:relative => false` in the helper without success.
- Is it possible that the `url_for` accepts relative links in the source path, not the build path? This should take into account that the target object might be built into another directory structure than the source structure.
- How can I override the `url_for` method? Doing so will affect other helpers such `link_to`?

I'm having trouble including images/links from localized templates using relative links. 

Thanks.

**Comment by joapuiib** [comment]
I've looking at the `url_for` helper implementation in https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/util/paths.rb#L189-L210.

The helper tries to find a `resource` by building a relative url from `current_resource`. The problem that I have is that `current_resource` is localized (ProxyResource) and has the localized url prefix, so it doesn't find the image resource.

```ruby
this_resource = options_hash[:current_resource]
url_path = Pathname(uri.path)
current_source_dir = Pathname("/#{this_resource.path}").dirname
url_path = current_source_dir.join(url_path) if url_path.relative?
resource = app.sitemap.by_path(url_path.to_s)
```

I would like to build the relative url from the target resource, using `current_resource.target_resource` instead of `current_resource`.

I've tried to override `options_hash[:current_resource]` in the helper call, with no luck.
```ruby
<%= url_for "images/pic.png", :current_resource => current_resource.target_resource, :relative => false %> 
```
# Question
- Can I override this behavior? How can I do it?

Thanks in advance.

**Comment by tdreyno** [comment]
Thank you for the debugging and code samples. Let's see if we can find a solution.

I think the behavior of url_for in this case is not obvious. I can see this use-case, I can also see a project with localized assets wanting the other behavior.

So, first, are absolute paths out of the question? Are you utilizing hashing or CDNs which require relative paths (and all the renaming/resolution logic)?

If so, would adding an option to prefer one of the two types of resolution work? Right now we default to current_resource, but if that were configurable, would that help? Keeping the default behavior, which live sites are likely reliant on, and adding an option for the alternative behavior would be my preferred approach

**Comment by joapuiib** [comment]
I have solved this with the following user defined helper method:
```ruby
  def url_for(path_or_resource, options_hash = ::Middleman::EMPTY_HASH)
      resource = current_resource
      resource = resource.target_resource if resource.instance_of? Middleman::Sitemap::ProxyResource
      options_with_resource = {}.merge!(options_hash).merge!(current_resource: resource)
      ::Middleman::Util.url_for(app, path_or_resource, options_with_resource)
  end
```

But I can also see the problem with localized assets.

I think the best solution could be to let the user override the resource `url_for` is tied to with the `:resource` option, swapping the order in this line:
```ruby
options_with_resource = {}.merge!(options_hash).merge!(current_resource: current_resource)
```
to:
```ruby
options_with_resource = {}.merge!(current_resource: current_resource).merge!(options_hash)
```
in:

https://github.com/middleman/middleman/blob/a2910b4d91644899f2efc702a28e3508d369bf76/middleman-core/lib/middleman-core/core_extensions/default_helpers.rb#L211-L217

**Comment by tdreyno** [comment]
Agree. I'll likely rename it from `current_resource` to `relative_to_resource`

**Comment by tdreyno** [comment]
https://github.com/middleman/middleman/pull/2567

**Comment by tdreyno** [comment]
On v4 branch. Use github in Gemfile for now. Will get a release out when a couple more features have landed
