### ISSUE TITLE
Release plan v4.4.3?

### ISSUE THREAD

**Issue by tnir** [middleman/middleman#2562]
https://github.com/middleman/middleman/compare/v4.4.2...4.x Any maintainer has a plan for v4.4.3?

**Comment by tnir** [comment]
@tdreyno Any blocker?

**Comment by markets** [comment]
Would be nice to finish this one #2541. So we'll be able to use Ruby 3.1+ on MM4.

**Comment by tnir** [comment]
Don't think so. As #2541 will break the API compatibility, if we are using SemVer 2.0.0, we should bump the major like 5.0 and cannot stay with 4.x 👀 . What do you think?

**Comment by markets** [comment]
hmm 🤔 are you sure #2451 breaks API? As per PR description it shoudn't ... 

In case it breaks, then yes, that PR should target `master` instead of `4.X`.

**Comment by le0pard** [comment]
master (which is v5) support ruby 3.1.

```
gem 'middleman', github: 'middleman/middleman'
gem 'middleman-core', github: 'middleman/middleman'
```

**Comment by markets** [comment]
@tnir v4.4.3 was just released by @tdreyno! I think we can close this issue now
