### ISSUE TITLE
i18n url_for doesn't produce correct link when "mount_at_root: false"

### ISSUE THREAD

**Issue by phvega** [middleman/middleman#2594]
## Expected behavior and actual behavior

`config.rb`:

```rb
activate :i18n, :langs => [:en, :es], :mount_at_root => false
```

Given this config and some localized template, e.g.: `localizable/path.html.erb`, using `url_for`/`link_to` helpers result in wrongly generated links.

Let's say we have to get the "path" page link:

```erb
<%= url_for"/path.html", locale: :en %>
```

This would generate `/path.html` in master branch instead of `/en/path.html` as it should be (this is correct for `4.4.3` version) because the path can not be translated into a proper reference so it returns `path.html`. This bug was introduced in #2263 (tested with commit previous to the merged one) with a new lookup table implementation. In this example, the table, which I printed modifying middleman source code, would be:

```json
{
  "/en/path.html": {
    "en": "/en/path.html",
    "es": "/es/path.html"
  },
  "/es/path.html": {
    "en": "/en/path.html",
    "es": "/es/path.html"
  }
}
```

## Steps to reproduce the problem (from a clean middleman installation)

Clone this [test repository](https://github.com/phvega/mnt_at_root-test) and modify `mount_at_root` option between `:en`/`:es` and `false` to see the different links generated.

## Additional information

- Ruby version: ruby 2.6.8p205 (2021-07-07 revision 67951) [x86_64-linux]
- Middleman version: `5.0.0.rc.1` (and `master`)
- OS version: Ubuntu 20.04.1

**Comment by guillerodriguez** [comment]
I confirm that the issue is fixed.
