### ISSUE TITLE
Allow users to use rack 3.0

### ISSUE THREAD

**Issue by tnir** [middleman/middleman#2606]
## Expected behavior and actual behavior

Allows users to use rack 3.0, which was released months ago https://github.com/rack/rack/pull/1940

## Steps to reproduce the problem (from a clean middleman installation)

n/a

## Additional information

- Ruby version: 3.2.0
- Middleman version: 5.0.0.rc.2
- OS version: n/a

**Comment by markets** [comment]
@tnir Do you think it will be ok to just allow (`< 4`) Rack 3.0 here?

https://github.com/middleman/middleman/blob/3812b031b6313ade4622c01f95ca154f36e09fb7/middleman-core/middleman-core.gemspec#L23

**Comment by tdreyno** [comment]
Why would this be useful to allow? Users do not interface with Rack directly and could have unintended differences from what is expected.

**Comment by markets** [comment]
Yeah, that's right! Apart from "keep deps up to date", I don't see any other reason, maybe @tnir has an idea?

**Comment by tnir** [comment]
Until now I did not know #2695 did address the problem. Thanks @dependabot!
