### ISSUE TITLE
i18N works w/ erb but not Slim

### ISSUE THREAD

**Issue by cekvenich2** [middleman/middleman#2618]
## Expected behavior and actual behavior
Slim is less verbose than erb. Erb works and generates localized html. But slim produces this error at build time:

undefined method `hello' for "translation missing: es.no key":String

Of course, the strings are there since erb works.

## Steps to reproduce the problem (from a clean middleman installation):
I made example repo:
https://gitlab.com/cekvenich2/middlemanapp-slim-template and it has a full stack trace there.

The working (erb) and b0rked (Slim) files are next to each other here:
https://gitlab.com/cekvenich2/middlemanapp-slim-template/-/tree/main/source/localizable

## Additional information
- Ruby version:  3.2
- Middleman version: Latest 
- OS version:  Linux

**Comment by tdreyno** [comment]
`.t` is still a function call, I'd expect the slim to be like below?

```
= I18n.t(:hello)
```

**Comment by tdreyno** [comment]
@vic-cekvenich you can submit templates here: https://github.com/middleman/middleman-directory
