### ISSUE TITLE
Middleman init fails because of i18n version

### ISSUE THREAD

**Issue by markwyner** [middleman/middleman#2638]
## Expected behavior and actual behavior
When I run `middleman init` I expect to create a new middleman instance. The command throws an error and the instance is not created.

## Steps to reproduce the problem (from a clean middleman installation)
1. Run `middleman init` from any directory.

## Additional information

- Ruby version:  -01 revision 67812) [x86_64-darwin19]
- Middleman version: 4.4.3, 4.4.2
- OS version: macOS 13.3.1 (22E261)

A list of my middleman gems:
middleman (4.4.3, 4.4.2)
middleman-autoprefixer (3.0.0, 2.10.1)
middleman-cli (4.4.3, 4.4.2)
middleman-core (4.4.3, 4.4.2)
middleman-livereload (3.4.7)
middleman-sprockets (4.1.1, 3.5.0)

My i18n gems:
i18n (1.13.0, 1.6.0)

If I run `middleman init` I receive an error (shown below). If I try to uninstall i18n-1.6.0 so middleman can use i18n-1.13.0, I am warned that middleman-core relies on 1.6.0. So I’m being told that middleman depends on 1.6.0 but that I can’t create a middleman instance without activating 1.13.0.

Any ideas on how to fix this? Thanks in advance.

```
The i18n gem is not available. Please add it to your Gemfile and run bundle install
Traceback (most recent call last):
	37: from /Users/markwyner/.rbenv/versions/2.6.5/bin/middleman:25:in `<main>'
	36: from /Users/markwyner/.rbenv/versions/2.6.5/bin/middleman:25:in `load’
	35: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/middleman-cli-4.4.3/bin/middleman:15:in `<top (required)>'
	34: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require’
	33: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require'
	32: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.3/lib/middleman-core.rb:13:in `<top (required)>‘
	31: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require'
	30: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require’
	29: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/middleman-core-4.4.3/lib/middleman-core/util.rb:1:in `<top (required)>'
	28: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:148:in `require’
	27: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:148:in `require'
	26: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/all.rb:3:in `<top (required)>‘
	25: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require'
	24: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require’
	23: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support.rb:27:in `<top (required)>'
	22: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require’
	21: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require'
	20: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/dependencies/autoload.rb:3:in `<top (required)>‘
	19: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require'
	18: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require’
	17: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/inflector/methods.rb:3:in `<top (required)>'
	16: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require’
	15: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require'
	14: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/inflections.rb:3:in `<top (required)>‘
	13: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require'
	12: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require’
	11: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/inflector/inflections.rb:4:in `<top (required)>'
	10: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require’
	 9: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require'
	 8: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/i18n.rb:7:in `<top (required)>‘
	 7: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require'
	 6: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:96:in `require’
	 5: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/i18n-1.6.0/lib/i18n.rb:3:in `<top (required)>'
	 4: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:116:in `require’
	 3: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:116:in `each'
	 2: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `block in require’
	 1: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
/Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:2285:in `check_version_conflict’: can’t activate i18n-1.13.0, already activated i18n-1.6.0 (Gem::LoadError)
```

**Comment by tdreyno** [comment]
Can you post the Gemfile that was generated as well? or did it fail before that?

**Comment by markwyner** [comment]
I can’t show a gem file because I can’t even generate a middleman instance. So no directory and no gemfile. For additional reference, this same error happens whether I use `middleman init` or `middleman init [folder-name]`.

**Comment by markwyner** [comment]
I have a lot of different systems running on my Mac, some Middleman but many others as well. I don’t know enough about your request to know if that would affect my other environments. I suspect that it will, in which case I’m leery about moving down that path.

As an interim solution I duplicated a clean v3 Middleman install and upgraded it by changing the version in the Gemfile and running bundle install/update. That at least got me rolling with a current version of Middleman. But that’s not sustainable.

Any thoughts on how that clean gem set would impact my projects globally on my machine?

**Comment by markwyner** [comment]
In my original message I mentioned the version conflict but didn’t provide the exact message. I thought it prudent to follow-up on that.

The command `middleman init` yields the following error:

`/Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:2285:in `check_version_conflict’: can’t activate i18n-1.13.0, already activated i18n-1.6.0 (Gem::LoadError)`

The command `gem uninstall i18n –version 1.6.0` yields the following warning:

```
You have requested to uninstall the gem:
i18n-1.6.0

middleman-core-4.4.3 depends on i18n (~> 1.6.0)
middleman-core-4.4.2 depends on i18n (~> 1.6.0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]
```

So the install is trying to activate 1.13.0 but can't because 1.6.0 is activated. But middleman-core relies on 1.6.0.

**Comment by tdreyno** [comment]
@markwyner gemsets are designed exactly for that use case. they separate dependencies for different contexts so your projects don't collide like the error above. This is a failing of ruby gems that Bundler can solve, but since bundler can't be in place until after init this can still happen.

**Comment by markwyner** [comment]
Oh, okay. So how do I create a clean environment in my new directory that’s isolated only to that directory? I’ll be happy to try that out.

**Comment by tdreyno** [comment]
@markwyner bundler will automatically handle that for you once the project is initialized. the gemset is just to give you a clean environment to run `middleman init` and avoid conflicts with other ruby projects that are installed globally

**Comment by markwyner** [comment]
Understood, thank you. I just don’t understand how to start with a clean environment. You said:

“Can try from a clean environment using a new rvm gemset: https://rvm.io/gemsets/basics”

I don’t know how to do this. If that’s beyond your level of support, that’s fine. Just asking because I don’t know how to do this.

Thanks for working with me on this. I’ve been using Middleman for many years and I’ve never had an issue. I use it for all of my sites.

**Comment by markwyner** [comment]
I actually didn’t have rvm installed. I installed it on my machine and then tried running middleman init in a new directory, per your request. It threw the following error:

```
Traceback (most recent call last):
	2: from /Users/markwyner/.rbenv/versions/2.6.5/bin/middleman:25:in `<main>'
	1: from /Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:282:in `activate_bin_path’
/Users/markwyner/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:263:in `find_spec_for_exe': can't find gem middleman-cli (>= 0.a) with executable middleman (Gem::GemNotFoundException)
```

What’s worse. When I tried to start middleman in an unrelated project I was asked to run `bundle install`. When I did, it failed. It was installing until here:

```
Installing activesupport 6.1.6
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

Then this:

```
1 error generated.
make: *** [binder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/markwyner/.rvm/gems/ruby-3.0.0/gems/eventmachine-1.2.7 for inspection.
Results logged to /Users/markwyner/.rvm/gems/ruby-3.0.0/extensions/x86_64-darwin-22/3.0.0/eventmachine-1.2.7/gem_make.out

An error occurred while installing eventmachine (1.2.7), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.2.7' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  middleman-livereload was resolved to 3.4.7, which depends on
    em-websocket was resolved to 0.5.3, which depends on
      eventmachine
```

Now I can’t run middleman at all. Any suggestions to fix this?

**Comment by markwyner** [comment]
I’ve spent a good deal of time researching this online but can’t find a solution. And currently I am unable to run middleman at all. I can’t create a middleman instance or run any of the projects I’ve been using.

**Comment by markwyner** [comment]
I was able to find a solution for installing new instances. Using ruby 3.0.6 I am able to run `middleman init`. However, my existing Middleman projects still throw the errors above. It continues to get hung up on that eventmachine gem.

Do you have any advice or warnings for running a clean install of Middleman (since that’s working) and then moving my exiting project files (source, data, and config.rb) into the new Middleman project? It seems like working in the clean installs is the best path forward.

**Comment by AlexB52** [comment]
That issue is annoying. 
Here is how I worked around it based on the discussion above @markwyner if you want to run a new middleman project. 
It requires `Docker` installed on your machine. 
The idea is to create a clean ruby environment to run the middleman init command.

1. Go to where you want to create the new middleman project and run 
```bash
docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app ruby:3.0 bash
```

2. Once in the docker container do these
```bash
# Install middleman
  gem install middleman 

# Setup node
# based on https://github.com/nodesource/distributions#ubuntu-versions

  apt-get update
  apt-get install -y ca-certificates curl gnupg
  mkdir -p /etc/apt/keyrings
  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  NODE_MAJOR=20
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" |  tee /etc/apt/sources.list.d/nodesource.list

# Install nodejs
  apt-get update
  apt-get install nodejs -y

# Create your project
  middleman init my-new-project

# Exit the container
  exit
```

You can now exit the container and go from there in your terminal.
