### ISSUE TITLE
 Missing Thor class for invoke middleman:generator

### ISSUE THREAD

**Issue by voytee** [middleman/middleman#2666]
## Expected behavior and actual behavior

 `Missing Thor class for invoke middleman:generator` raised when doing `middleman init`

## Additional information

- Ruby version: 3.2.2
- Middleman version: 4.5.0
- OS version: OSX

**Comment by tdreyno** [comment]
Can you try on 4.5.1?

**Comment by voytee** [comment]
> Can you try on 4.5.1?

```gem install middleman -v 4.5.1
ERROR:  Could not find a valid gem 'middleman' (= 4.5.1) in any repository```

Seems like 4.5.1 is not available through ruby gems and I do not see 4.5.1 TAG on the repo

**Comment by voytee** [comment]
Also checked with `5.0.0.rc.1` but with this one you'll get other error:

```uninitialized constant Haml::Options```

**Comment by tdreyno** [comment]
4.5.1 is definitely on rubygems: https://rubygems.org/gems/middleman/versions/4.5.1

**Comment by arashm** [comment]
When doing `gem install middleman`, rubygems installs the `4.5.0` version. Forcing the version also fails. 

```
─$ gem install middleman -v 4.5.1
ERROR:  Could not find a valid gem 'middleman' (= 4.5.1) in any repository
ERROR:  Possible alternatives: beans-middleman, branchable_cdn_assets-middleman, capistrano-middleman, capistrano-middleman-presentation, capistrano-middleman2, contentful-middleman-pages, contentful_middleman, ember-middleman, fdt_middleman_tools, font-awesome-middleman
```

It could be rubygems issue though.

**Comment by nicolas-brousse** [comment]
I've got the same error. By using an older version of `thor` (`1.2.2`) instead `1.3.0` the `middleman init` command works.

**Comment by heyrocker** [comment]
Any updates on this? I also am having this problem and can't get 4.5.1 to install.

**Comment by tdreyno** [comment]
Seems like 474 people have successfully installed 4.5.1
<img width="994" alt="Screenshot 2023-11-15 at 10 05 20" src="https://github.com/middleman/middleman/assets/233/745fab7b-7dc2-4615-8a17-88de6272a03f">

I may just have to republish and hope that ruby gems stops being confused

**Comment by markets** [comment]
@tdreyno I successfully installed the v4.5.1 release for my projects under Ruby 3.2. 

I miss the git tag in the repository, they are useful to compare changes between versions: https://github.com/middleman/middleman/tags. 

Not sure how is your current release process, but just in case, _Bundler_ provides a very easy command to release gems (it builds the gem, push the tags and push to RubyGems automatically):

    > rake release
