### ISSUE TITLE
Link_to helper

### ISSUE THREAD

**Issue by BadMinus** [middleman/middleman#303]
There is a way to add class if page is current page?
Like that:
`link_to "SomePage", somepage_path, :class => current_page`

Now I only can hide or show link if it current or not by

`link_to "SomePage", somepage_path, :if => :current`

**Comment by joallard** [comment]
Here's a lazy implementation I made on the fly:

```rb
  def current_page?(page)
    current = current_resource.url.gsub('/', ' ').strip
    target = page.gsub('/', ' ').strip

    current == target
  end
```

I'll try to propose the addition to the standard helpers in a PR when I get the time.

**Comment by tysongach** [comment]
Here’s a new gem for marking up a current link with `aria-current` (which you can then use to style off of): https://github.com/thoughtbot/middleman-aria_current
