### ISSUE TITLE
Individual file builds

### ISSUE THREAD

**Issue by frason** [middleman/middleman#327]
is it possible to do individual file builds in Middleman i.e. 'middleman build FILENAME'

**Comment by pgcd** [comment]
Just a quick note: 
    middleman build --glob="FILENAME"
removed all the other files from the build directory, instead of simply updating the one I wanted. Dunno if that's by design/desirable, but it definitely wasn't what I expected.

**Comment by vvasabi** [comment]
@pgcd I believe you can add `--no-clean` flag to stop Middleman from removing files in the build directory.
