### ISSUE TITLE
Relative links on "build" with link_to helper?

### ISSUE THREAD

**Issue by ervasive** [middleman/middleman#368]
How can we link pages with each other in relative way within generated projects. Currently the "link_to" helper doesn't computes relative urls, which would be very helpful.

The use case:

Project can have its structure with files in base folder and some subfolders as well. Let's imagine that all these files shares for example navigation partial.
When middleman generates project into static HTML, these pages aren't properly connected in relative way (by relative I mean ../ reference to parent folder).

Here is [an example](http://dl.dropbox.com/u/4639259/example.zip)

Cheers

**Comment by aaromnido** [comment]
Sorry, I'm using 3.3.12 and I cant get the correct path into a subdirectory for images. For the resto of the assets the path is ok.
I get this URL for images:
"/images/dummy-image-01-6457c7c6.png"
When I need:
"images/dummy-image-01-6457c7c6.png"

I have this setting into build block:
activate :relative_assets

And outside the build block:
set :relative_links, true

Whats wrong?

**Comment by tdreyno** [comment]
are you using an image helper like `image_tag`?

**Comment by aaromnido** [comment]
Yes, but in a wrong way. I just discover it:
<%= tag :img, :src => "/images/dummy-slideshow-color.png" %>

I let in this way (without slash) and Boom!!:
<%= tag :img, :src => "images/dummy-slideshow-color.png" %>

Thanks tdreyno, with your help I could find it.  ;-)

**Comment by tdreyno** [comment]
Should use: `<%= image_tag "dummy-slideshow-color.png" %>`

**Comment by aaromnido** [comment]
Much better and much simple! ;-)
Thanks tdreyno,

**Comment by haydenk** [comment]
If you want to do it with link_to as well, I was able to work around it with:

`= content_tag :a, 'Home', :href => 'index.html'`
