### ISSUE TITLE
Output Helpers: Can I create an anchor tag with an image as its content?

### ISSUE THREAD

**Issue by jannisg** [middleman/middleman#383]
Hi,

I've been reading through the Padrino API and its output helpers and most importantly the asset tag helpers but I cannot figure out how to code something that would result in:

``` html
<a href="index.html" class="logo">
    <img src="imagesrc.png" />
</a>
```

Currently my trials have been these, all of which resulted in Ruby errors:

``` erb
<%= link_to "index.html", :class => 'logo', image_tag 'imagesrc.png' %>

<%= link_to image_tag 'imagesrc.png', "index.html", :class => 'logo' %>

<%= link_to "index.html", :class => 'logo', &image_tag 'imagesrc.png' %>
```

The Padrino docs say something about `&block` for setting the content but I can't figure out how to implement this into my template.

Any help would be much appreciated.

Thanks!

**Comment by ckizer** [comment]
I can't get this example working with HAML and middleman

**Comment by stevenosloan** [comment]
Hey @ckizer, those examples were in erb, for haml I believe this should work

```haml
= link_to "http://example.com" do
  .your_html_here
```
