### ISSUE TITLE
Switch back to Webrick from Thin

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman#406]
We switched to Thin because, for some reason, using Webrick responses would get mixed up and requests for one file would return another! However, Thin is an extra dependency, and EventMachine is busted for Window right now and can't really be installed correctly. Switching back to Webrick would make things much easier for Windows users.

**Comment by lilijreey** [comment]
I Use middleman 4 How switch web server to thin?

**Comment by tdreyno** [comment]
Use Thin via `config.ru`: https://github.com/middleman/middleman-templates-default/blob/master/optional/config.ru

**Comment by lilijreey** [comment]
@tdreyno How change the config.ru switch to thin. I not know, Can you help me. Give me a answer?

**Comment by tdreyno** [comment]
Read the docs: http://code.macournoyer.com/thin/usage/

```
thin start -R config.ru
``

**Comment by lilijreey** [comment]
@tdreyno Thanks a lot :+1:
