### ISSUE TITLE
config.ru not working anymore

### ISSUE THREAD

**Issue by zimbatm** [middleman/middleman#447]
In the 3.0 branch, the Middleman.server seems to have disappeared but you still have the option to `middleman init NAME --rack`.

It would be great to have an alternative for heroku hosting.

**Comment by SteveBenner** [comment]
For the sake of posterity, please note that it is officially recommended ***NEVER*** to use

```ruby
require 'rubygems’
```

An explanation for this can be found [on the RubyGems website](http://guides.rubygems.org/patterns/#requiring-rubygems).
