### ISSUE TITLE
/source folder organisation

### ISSUE THREAD

**Issue by stevenringo** [middleman/middleman#453]
Is there anyway to organise the source folder such that assets, layouts/partials and content are separated?

Instead of say:

```
├── advanced
├── community
├── extensions
├── getting-started
├── images
├── javascripts
├── layouts
├── metadata
├── stylesheets
└── templates
```

I think it would be better to have say:

```
├── assets
│   ├── images
│   ├── javascripts
│   └── stylesheets
├── layouts
├── pages (or views)
│   ├── advanced
│   ├── community
│   ├── extensions
│   ├── getting-started
│   ├── metadata
│   └── templates
└── partials
```

Having content folders intermingled with layouts and stylesheets etc seems "messy".

Having it the current way as a default is fine, but if there's anyway to configure it like this, I would be happy pedant.

Thanks.

**Comment by chrishough** [comment]
@Arcovion follow up question, does your solution work with directory indexes? so your pages directory migrates the pages to the root of the site, but does it create a folder with an index.html in them?

**Comment by chrishough** [comment]
Never mind! For future peeps using @Arcovion solution, make sure you activate directory indexes after the dir manager:
```ruby
activate :dir_manager
activate :directory_indexes```
