### ISSUE TITLE
--rack and rackup issues

### ISSUE THREAD

**Issue by wenzowski** [middleman/middleman#540]
When generating a new project using Middleman 3.0.0,

```
middleman init <name> --rack 
```

the default generated config.ru contains

```
require 'rubygems'
require 'middleman'

run Middleman.server
```

which causes Middleman to be launched differently with `$ rackup` than with `$ bundle exec middleman server`. 

This results in issues when running Middleman from Rack. In the default example the filesystem watcher is not loaded, so a server restart is required on every change. An even more severe example is demonstrated by [attempting to use the bootstrap-sass gem](https://github.com/ent-io/middleman-twitter_bootstrap) where bootstrap works beautifully with `$ middleman` but doesn't even appear to be in the load path via `$ rackup`.

**Comment by SteveBenner** [comment]
For the sake of posterity, please note that it is officially recommended ***NEVER*** to use

```ruby
require 'rubygems’
```

An explanation for this can be found [on the RubyGems website](http://guides.rubygems.org/patterns/#requiring-rubygems).
