### ISSUE TITLE
cleaner url's /about/ vs /about.html

### ISSUE THREAD

**Issue by haywoood** [middleman/middleman#55]
Is there a way to do this currently?

If this is too superficial a request in the project's current form, I apologize in advance...

Was just wondering, thank you! 

Ryan

**Comment by swift502** [comment]
To anyone coming across this in 2020.
If you just need to use clean urls with dev server, nowadays there's a `directory_indexes` option, which can be enabled selectively for development, and effectively solves the pretty url issue.

```
configure :development do
    activate :directory_indexes
end
```
