### ISSUE TITLE
Middleman 3.0 requires manual server restart for any change in config.rb or middleman-blog

### ISSUE THREAD

**Issue by hershmire** [middleman/middleman#595]
I've been working on getting a few of my projects upgraded from Middleman 2.0 to Middleman 3.0 and have noticed that I now need to manually restart the `middleman server` whenever I make a change in config.rb. 

I'm also noticing this issue when my project is using middleman blog 3.0 – whenever I make a change to any file within the middleman project, all my blog content disappears and I need to manually refresh the server. Any non-blog related content seems to remain cached and doesn't updated until a manual refresh of the server too.

I can't imagine this is the expected result since Middleman 2.0 auto updated with zero lag time. I noticed this post about [middleman server speed issues on Windows](https://github.com/middleman/middleman/issues/529) and was curious if this issue is somewhat related.

I'm seeing the issue on both OSX 10.8.1 and 10.7.xx. I'm running ruby-1.9.3-p194 on both. As a side note, I even created a fresh Middleman-Blog site via `middleman init MY_BLOG_PROJECT --template=blog` to see if this also produced this issue and it did.

Any areas I should troubleshoot?

**Comment by jmar910** [comment]
I'm experiencing this same issue @benjaminwood . Seeing the same thing where CSS and JS files are updated, but the template files are not updating and require a server restart. I am not using live reload, just refreshing the page manually. Still not seeing template changes unless I do a manual server restart. 

OS X 10.10.1
Ruby 2.0.0-p598

**Comment by jmar910** [comment]
to add, the --force-polling flag works for me to correct the issue. As @benjaminwood mentioned, this isn't a long term solution, but will use it in the meantime. Hope this helps identify the issue.
