### ISSUE TITLE
Localized blogs

### ISSUE THREAD

**Issue by davidwkeith** [middleman/middleman#634]
We have an international site with a blog, we would like to be able to do one of the following:
1. output the same blog for each locale, wrapping a localized header and footer around the English content
2. **[ideal]** Output multiple blogs, one for each locale, that way we can localize blog posts, or have different blog posts for each locale if appropriate.

Currently we are building out the localized site with an `:en` only blog, but the blog posts need to be placed outside of the `/source/localizable/` directory in order to build properly, as such we have located them in `/source/posts/` but are running into a race condition with I18n, where the blog header and footer get localized in the last language processed. This means we have a lot of failed builds where the blog headers and footers are in the wrong language.

We could take out the localization calls for now by making a non-localizable header and footer, but we really want the header and footer localized so the user is not unexpectedly on the US English version of the site when they view a blog post.

**Comment by sisihagen** [comment]
How to do that now just to multilingualism? I wrote the language in the corresponding files, I have set the language in the filename, but everything does not seem to work.
