### ISSUE TITLE
Localizing (i18n) the layout

### ISSUE THREAD

**Issue by joallard** [middleman/middleman#654]
The templates appear to be localizable, but the layout doesn't. I don't know if this is by design or not.

On a small test, using French as the primary language and using an `I18n.t` tag in the layout, the tag remains in English.

**Comment by shunfan** [comment]
You can simply move layout folder into the localizable, and it will work.

**Comment by eaigner** [comment]
Any update on this? I still cant localize layouts.

**Comment by joallard** [comment]
What do you mean by "localize layouts"? On the topic, see #924, #1390, #1466

**Comment by eaigner** [comment]
I mean #1643
