### ISSUE TITLE
Partials fail for .js.erb files when building

### ISSUE THREAD

**Issue by jtara** [middleman/middleman#671]
Partials called from a .js.erb file fail when building, with an error message in the generated file.

They do not fail when running the Middleman server.

This is the entire content of the generated file:

`throw Error("NoMethodError: undefined method`sub' for nil:NilClass\n (in /Users/jon/workspace/rivertrails/www/source/js.maps.js.erb")`

There is no error in the Middleman build log, even with --verbose.

I did a test where I removed all of my partial calls, and it generated fine. As soon as I try to use any partial, I get this failure. i.e. I created a partial that does nothing - simply includes a one-line comment, and it fails in the same way.

`<%= partial :test %>`
## _test.js.erb

`/* This is a test */`

**Comment by Sinetheta** [comment]
I guess this is back `middleman-sprockets (3.4.2)` and using `/source/javascripts/denpendency.coffee.erb` results in `error  build/javascripts/contact/denpendency.html`

**Comment by tdreyno** [comment]
@Sinetheta Not sure I follow. Can you open a new ticket with a full bug report

**Comment by Sinetheta** [comment]
Sure @tdreyno, the bug is that using erb templating on an asset causes a build error. The workaround is adding the file to your ignore list.

```rb
ignore 'javascripts/denpendency.coffee.erb'
```

I'll file a ticket when I get a chance.
