### ISSUE TITLE
Disable Sass debug_info automatically on build?

### ISSUE THREAD

**Issue by benfrain** [middleman/middleman#706]
I have debug info in Sass using the following in my config.rb:

`config.sass_options = {:debug_info => true}`

However, I'd like to disable this automatically on build. Whilst this `activate :minify_css` overrides the Compass output style as desired it doesn't remove the debug info and nesting `config.sass_options = {:debug_info => false}` produces an error.

e.g.

```
# Build-specific configuration
configure :build do
  # For example, change the Compass output style for deployment
  config.sass_options = {:debug_info => false}
  activate :minify_css
end
```

Anyway to achieve this?

**Comment by philippm** [comment]
@bholis's solution raises an `ArgumentError` in Middleman 3.4.1, but is very close to the solution. Here's what worked for me:

```ruby
configure :development do
  compass_config do |config|
    config.sass_options = {:debug_info => true}
  end
end
```

**Comment by tdreyno** [comment]
Yeah, looks like he typo'd the `configure` command

**Comment by bhollis** [comment]
To be fair I think I typed it from memory directly into GitHub.

**Comment by philippm** [comment]
@bhollis: apologies if my comment came across the wrong way -- your suggestion saved me considerable time so I'm much obliged! I just thought I'd share the corrected version for future travellers to this page.
