### ISSUE TITLE
Need to add additional paths for sprockets

### ISSUE THREAD

**Issue by joeytrapp** [middleman/middleman#749]
Is there a way to add more paths in the config.rb. I have submodules loaded outside of the javascripts directory that contain js files that I'll require.

Is there something similar to rails: 

``` ruby
config.assets.paths << Rails.root.join("app", "assets", "flash")
```

**Comment by dd-monsoon** [comment]
Very useful @audionerd, thanks a lot!

**Comment by maxmeyer** [comment]
See https://middlemanapp.com/advanced/asset_pipeline/ for a more uptodate way.
