### ISSUE TITLE
Request: Concatenate Javascript on build

### ISSUE THREAD

**Issue by wibron** [middleman/middleman#757]
It would be handy to have all Javascripts concatenated while building the site.

**Comment by fcubria** [comment]
You can combine Sprockets with erb templates, too. For example, you may have these three files:
1. **main.js**
With this code:
*//= require _core*
*javascript code*
2. **_core.js.erb**
With this code
*js code*
*<%= partial "main" %>*
*more js code*
3. **_main.js.erb**
*js code*
**main.js** will include the code inside **_core.js.erb**, and **_core.js.erb** will include the code inside **_main.js.erb**.
At the end you will have only one file, **main.js** with all the scripts concatenated. Using templates you can include the code anywhere in your file, not only at the beginning.
