### ISSUE TITLE
To run middleman on cloud9 IDE you need to set -o $IP but is not accepted has CLI argument

### ISSUE THREAD

**Issue by piermariacosina** [middleman/middleman#759]
In cloud9 you get a VM with console to run a rack application like or Rails you have to set the -p $PORT and -o $IP , both Sinatra and Rails has this argument in the CLI but middleman did not recognise the -o  is there a way to change the IP where middleman run? or the -o can be exposed has an argument in the CLI?

**Comment by rupakg** [comment]
Update:

Once you have the Middleman server up and running the command in the terminal:

``` $ middleman -h $IP -p $PORT ```

The url for accessing the site is: ```https://<project>-<username>.c9.io/```

PS: **Please note that the url has a '-' instead of a '.'**

**Comment by misterorion** [comment]
For those currently on Middleman 3.3.12, apparently the `-h` flag isn't supported. You'll need to be on 3.3.11 or lower.

I had to change 3.3.12 to 3.3.11 in the site's `Gemfile`:

`gem "middleman", "~>3.3.11"`

Then I ran `bundle install` again in the site directory and started middleman with the usual command: 

`$ middleman -h $IP -p $PORT`

**Comment by tdreyno** [comment]
Definitely a bug. The flag is still there, but maybe it's not working correctly :(

**Comment by makzan** [comment]
I'm using 3.3.12 and I don't need to use `-h` to make it works on C9.

Just set the port:

```
$ middleman -p $PORT
```

Then the site is available at: `https://<project>-<username>.c9.io/`

**Comment by misterorion** [comment]
Yep, just upgraded to 3.3.12 and can confirm it works without `-h` on C9.

Thanks, makzan.

**Comment by slavajacobson** [comment]
Doesn't work anymore?

**Comment by makzan** [comment]
I'm now using `middleman server -b $IP -p $PORT` in cloud9 IDE.

**Comment by howardjw** [comment]
Confirming on middleman 4.1.9 'middleman server $IP -p $PORT' works on C9

**Comment by BabakRafian** [comment]
Thanks @howardjw , confirming  'middleman server $IP -p $PORT' works on C9.

**Comment by tejasmanohar** [comment]
```
pdgruby:~/workspace/slate (master) $ middleman server 0.0.0.0 -p 8080                                                                                                                         
== The Middleman is loading
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"
```

The output doesn't seem to be right?
