### ISSUE TITLE
Setting content type on extensionless proxy

### ISSUE THREAD

**Issue by joefiorini** [middleman/middleman#821]
I'm using Middleman in a large Javascript client calling into an API that doesn't use extensions on it's API endpoints (using the accept header instead). I need to stub out this API endpoint in my Middleman app. In `config.rb` I do:

``` ruby
proxy "/api/resource", "/fixtures/resources.json"
```

If I visit `/api/resource` in a browser the file gets rendered with `content-type: text/html`. This breaks jQuery.ajax since it won't properly parse the json. Is it possible to configure the response content-type in the page's frontmatter or the call to proxy?

Thanks!
Joe

**Comment by jgn** [comment]
If you're deploying to, say, Github pages, I don't think you can configure your server to server particular headers. So it might help to be able to specify content_type: on a redirect?
