### ISSUE TITLE
LESS stylesheets with @import'ed stylesheets aren't updating during development

### ISSUE THREAD

**Issue by conrad-vanl** [middleman/middleman#843]
When I work on LESS stylesheets that are `@import`'ed into another LESS stylesheet, the parent stylesheet doesn't seem to update when I refresh the browser - I have to modify the parent stylesheet in order for it to pickup the changes in the `@import`'ed stylesheet:

```
# File tree:
stylesheets:
  _modules:
    some-module.less
 site.css.less
```

``` CSS
/* Site.css.less */
@import "_modules/some-module"
```

```
    middleman (3.0.13)
      middleman-core (= 3.0.13)
      middleman-more (= 3.0.13)
      middleman-sprockets (~> 3.0.8)
    middleman-core (3.0.13)
      activesupport (~> 3.2.6)
      bundler (~> 1.1)
      listen (~> 0.7.3)
      rack (~> 1.4.1)
      rack-test (~> 0.6.1)
      rb-fsevent (~> 0.9.3)
      thor (~> 0.15.4)
      tilt (~> 1.3.6)
```

I am on windows (mingw), running Ruby 1.9.3

**Comment by shaunakv1** [comment]
Having the same issue. Was there any resolution on this ?

**Comment by bjankord** [comment]
Ran into this issue, ended up following this write-up to get it things working: http://spin.atomicobject.com/2013/10/31/detecting-less-changes-middleman/

Note Justin's comment on that post about needing to Update:
```
class LessWatcher < ::Guard::Guard
```
to
```
 class LessWatcher < ::Guard::Plugin
```

**Comment by tdreyno** [comment]
Which version, guys?

**Comment by bjankord** [comment]
Seeing the issue in v3.4.1.

**Comment by tdreyno** [comment]
Can you check v4?
