### ISSUE TITLE
Navigation using i18n and link_to

### ISSUE THREAD

**Issue by mariosant** [middleman/middleman#850]
I have successfully activated i18n module and now I am trying to build a navigation menu like the following example (in HAML):

    %ul
       %li
         = link_to I18n.t(:home), sitemap.find_request_by_path("/index.haml")

The problem of that, is that the generated link points always to /index.html.
How could I make it point to the localised target? For example /en/index.html or /de/index.html.

Keep in mind that I have also a mounted at root locale. /index.html is always french for example.

**Comment by acjay** [comment]
Would be great if the `link_to` helper was aware of the `i18n` `:path` option

**Comment by tdreyno** [comment]
Do you have more details on that option, @acjay

**Comment by acjay** [comment]
You mean, how I would expect it to work? I guess it would be great if you could do `link_to '/path/to/article'` where the path is either relative to `source/` or `source/localizable`, and the `link_to` helper interpolated the locale into the path wherever the `activate :i18n` ` :path => "/langs/:locale/"` and `:mount_at_root =>  #whatever`

**Comment by tdreyno** [comment]
Hey @acjay, I added this: https://github.com/middleman/middleman/commit/9de1f16f3b7cccf95fbf0407c7b7c4a7b19f8543

Point your app towards the github `v3-stable` branch and let me know how that feels.

**Comment by acjay** [comment]
@tdreyno It doesn't seem to be working for me.

In my config.rb, I have: `activate :i18n, :path => "/articles/:locale/", :mount_at_root => false`

Then for an article in `source/localizable/my-article/index.html` the url would be `/articles/en/my-article/`.

I'm trying to do `link_to 'Article', '/articles/my-article/index.html', :en`, but it returns `"<a href=\"/articles/my-article/index.html\">Article</a>"`

But I could be misunderstanding how it's supposed to work.

**Comment by tdreyno** [comment]
The target path should be the unlocalized path: `/my-article/index.html`. Does that make sense?

**Comment by acjay** [comment]
@tdreyno Ah gotcha, my mistake. That seems to work as expected. A couple things: 

- `link_to` should probably pass on `options` and `html_options` objects to `super`
- It would be great if this worked for `url_for`, as well. If so, I could get around the previous point by manually templating my `a` element

**Comment by tdreyno** [comment]
Good points, @acjay. Will expand.

**Comment by AbelToy** [comment]
While I love local-aware `link_to`, this kind of breaks the code for me if I need extra arguments to the `a` tag (such as `class`) or I need to pass a block (if I need an image link, for example). I can't afford to upgrade to 3.3.13 until this is fixed :(

**Comment by tdreyno** [comment]
Damn, shocked this didn't get caught by the test suite :(

Yanked 13. @AbelToy Can you please check `v3-stable` to see if I fixed this correctly this time?

**Comment by AbelToy** [comment]
Arguments work fine now :D, although blocks are giving a SyntaxError to me, but it's probably my fault.

I'm using something like:

```erb
<li><%= link_to('English', current_path_without_locale, :lang => :en, :class => :testing) do %>
  <img src="test.png" />
<% end %></li>
```

It's probably my mistake, I'm a little bit out of practice with Ruby atm.

**Comment by tdreyno** [comment]
Should work. I'll add more tests

**Comment by AbelToy** [comment]
Also, and this is more an extra than anything, using both `hreflang` and `lang` attributes for links pointing to different language pages is common. While I can easily specify `hreflang` (maybe it could be added by default? Though this is something that should be discussed / thought about), I currently can't add a `lang` attribute to the `a` tag, because it's "intercepted" by the i18n `link_to` helper.

**Comment by tdreyno** [comment]
How about `:i18n =>` for our interception?

**Comment by AbelToy** [comment]
That would work for me! Or `:locale =>`, both would be more than fine :)

**Comment by acjay** [comment]
`locale` also has the advantage of matching the directory where the localization files are stored. I guess it's probably more technically correct too, since the codes need not correspond to language codes specifically. Pretty psyched for this!

**Comment by tdreyno** [comment]
Okay, please try from `v3-stable`. Works for both url_for and link_to (and any helpers which use url_for internally).

**Comment by acjay** [comment]
@tdreyno This is working great for me! Thanks for implementing this!

For `current_page`, is there a built-in way to get the canonical unlocalized path? Right now, I'm doing `current_page.proxied_to.sub(/^localizable/, '')`, but that feels pretty dirty :)

Also, on a somewhat unrelated note, kind of a newb question. I'm interested in using this in production right away for implementing an article translation selector on my site, but as this has a version bump, my `gem "middleman-fontcustom", "~>0.2.0"` dependency is no longer cool as it's pinned to middleman 3.3.0. Is there way to override this without forking that gem?

**Comment by tdreyno** [comment]
I can add a helper for "unlocalized root path"

Definitely a bug in `middleman-fontcustom`. That means it also won't work in v4. I'd suggest submitting a ticket when them.

**Comment by AbelToy** [comment]
Welp, I found another issue. Any path pointing to `index.html` won't be localized, even if `locale` is explicit.

So, `link_to 'About', '/about.html'` will be correctly localized depending on the locale of the current page or the explicit one if set, while `link_to 'Home', '/index.html'` won't work. The same with something like `link_to 'Projects', '/projects/index.html'`, that one wouldn't be localized either.

**Comment by acjay** [comment]
Interesting. It's working for me just fine with `/my-article/index.html` with `activate :i18n, :path => "/articles/:locale/", :mount_at_root => false`. What options are you using?

**Comment by AbelToy** [comment]
I'm using `:mount_at_root => true`, so that's probably the cause :P

**Comment by tdreyno** [comment]
@AbelToy Thanks, will write more tests :)

**Comment by acjay** [comment]
Not sure, but this may not be respecting the `set :relative_links, true` option

**Comment by tdreyno** [comment]
@acjay You'd be right, this is shortcutting without running through that step.

**Comment by acjay** [comment]
Any chance of that part working? I'm luckily serving my pages from the domain root in production, but this isn't the case for my preview setup. I can, of course, hack around this though. Although, at that point, I may as well generate all my alternate language URLs by regex from the current page :/

**Comment by tdreyno** [comment]
yeah, we'll make it work... just need some time to work on it :)

**Comment by tdreyno** [comment]
Fixed the issues discussed above. @acjay & @AbelToy, can you test?

**Comment by AbelToy** [comment]
Everything works for me now, yay! Thank you very much!

**Comment by philippbecker** [comment]
After the latest commits regarding to this issue I'm confronted with a strange behavior of the *asset helper tags*. They only work when I use absolute paths. It seems to be that my custom set directories for assets will not be delivered to the helper tags.

**config**
```
set :relative_links, true
set :css_dir, 'assets/css'
```

**layout**
`= stylesheet_link_tag 'main'`

**error msg**
```
RuntimeError at #{url}
"No resource exists at #{url}" if relative
/middleman-core/lib/middleman-core/util.rb: in url_for, line 188
```

**Comment by tdreyno** [comment]
Ahhh... It's trying to localize CSS paths! Nice find. More tests and commits incoming.

**Comment by tdreyno** [comment]
Ok, @philippbecker, should be resolved.

**Comment by acjay** [comment]
Appears to be working as expected with relative URLs. I can dig it! Let me know if you add the helper to current page to get the nominal path without the "localizable/" part, but that's much less of a big deal.

**Comment by acjay** [comment]
BTW, thanks, this is really awesome

**Comment by tdreyno** [comment]
`current_page.locale_root_path`

**Comment by philippbecker** [comment]
I can confirm that @tdreyno, the issue is resolved. Many thanks for the fast reply!

**Comment by tdreyno** [comment]
Awesome! As soon as we finalize #1528, we'll push out `v3.4.0`

**Comment by iwarner** [comment]
Hiya

I do not think this works with linking to Proxy pages.

-# Test link - should prepend language
= link_to "Home link proxy", "/index.html", locale: locale
= link_to "Home link proxy", "/", locale: locale
= link_to "Promotions category proxy", "/promotions.html", locale: locale

I proxy an index from another folder

    proxy "#{ directory }index.html", "localizable/blog/blog.html",  ignore: true, lang: locale

But also for blog collections :

        # Custom collections
        blog.custom_collections = {

            # Category
            category: {
                link:     "#{ path }{category}.html",
                template: "template/category.html"
            }

The same result is that it just links to root folder

Cheers

**Comment by bhollis** [comment]
Hi @iwarner, I think in general it's easier to track problems if they're filed as a new issue, rather than as a comment to a closed issue. With regards to what you're describing, the number one most useful thing you can do to help with a bug is to provide an example Middleman project that exhibits the bug, or even better, a PR with a new test case that proves the problem.

**Comment by iwarner** [comment]
@bhollis Good point - I have created a new middleman build for this actually so will put up on Github ASAP. Thanks for your reply to my email btw.

For reference I am combatting the above with the following code in config.rb

    # Loop through the locales
    # @todo Do I need the ready code here try without
    locales.each_with_index do | locale, index |

        ##
        # Ready hook
        # Add options to international template pages
        ##
        ready do

            # Get all the french tags
            sitemap.resources.select{ | d | d.data.template }.each do | resource |

                if resource.path[ 0...5 ] === locale.to_s

                    # Debug
                    # puts resource.path[ 0...5 ]
                    # puts locale.to_s

                    resource.add_metadata options: {
                        locale: locale,
                        lang:   locale
                    }

                end

            end

        end

    end
