### ISSUE TITLE
Suggestion: Broken Link Checker

### ISSUE THREAD

**Issue by nicolasgarnil** [middleman/middleman#902]
Is there any Broken Link Checker functionality http://wordpress.org/plugins/broken-link-checker/ available for middleman?

I don't imagine it as an extension but as something you an enable/disable inside the build block.

For example:

``` ruby
configure :build do
  activate :broken_link_checker
end
```

The build process fails if one or more broken links are found.

One could also enable it but decide to ignore the broken links:

``` ruby
configure :build do
  activate :broken_link_checker, ignore: true
end
```

The build process succeeds with warnings if one or more broken links are found. 

What do you think about it?

**Comment by ramaboo** [comment]
@nicolasgarnil Did you ever build one of these because I did? Checks internal, external, links with IDs and links that 301.

**Comment by nicolasgarnil** [comment]
No, I did not. I used an existing broken link checker tool. Go ahead and PR
your solution, I can assist you testing it in my blog and other MM projects
I manage.

**Comment by dwcramer** [comment]
@ramaboo Would love to see this. Build-time link checking for internal links is indeed a very useful feature.

**Comment by lbain** [comment]
@ramaboo Any news on this? I'd love to use it as well :)

**Comment by JTronLabs** [comment]
Could you potentially use [HTML-Proofer](https://github.com/gjtorikian/html-proofer) and activate it in the build/development blocks?
