### ISSUE TITLE
Middleman not respecting "set :fonts_dir, 'assets/fonts'" in config.rb

### ISSUE THREAD

**Issue by mrbinky3000** [middleman/middleman#913]
If you use the set :fonts option in config.rb, it's getting ignored.
This is a fresh install of Ruby and Middleman.  We're spooling up a new developer on our project.
See the screenshot for gem list.

![middleman-snapshot](https://f.cloud.github.com/assets/161068/575162/4ad95030-c7d7-11e2-95f8-da59ce01e438.gif)

**Comment by fullofcaffeine** [comment]
What's the point of this configuration, by the way? It's not documented anywhere. 

To use webfonts served from within the same site, I had to manually add the folder to sprockets, instead:

```
sprockets.append_path File.join root, 'source/fonts'
```

**Comment by tdreyno** [comment]
It is a config option that only Compass cares about.
