### ISSUE TITLE
Using middleman programmatically.

### ISSUE THREAD

**Issue by thawatchai** [middleman/middleman#931]
We're running a relatively high traffic website. What we want is as follows:
- a user uses his dashboard to create a content.
- the content object is saved and a template file is generated.
- middleman is called to build the template file to a html file.

In other words, we want to use middleman programmatically from rails to generate static files.

We're using rails' `caches_page` now but it has several limitations. A page needs to be visited in order to generate a cache file. We use some ad-hoc techniques to generate the files in advance, but it isn't perfect. It seems like rails doesn't really pay attentions much on caching for content-based high-traffic sites.

If we can use middleman programmatically, we can generate all pages in advance. When a user changes a page, only the page is regenerated. This will reduce much of the resources we need for serving public-facing part of the site, and we'll use rails only for user part of the site (which is an angular.js app).

Please advice how we can accomplish this with middleman?

PS. This might be related to #235.

**Comment by egardner** [comment]
I know it's been a while, but I'm trying to figure out how to do something along these lines in Middleman v4.

In a MM v3 app, I was able to run the following code from an RSpec `spec_helper` file to run a few tests:

```ruby
Capybara.app = Middleman::Application.server.inst do
  set :root, File.expand_path(File.join(File.dirname(__FILE__), ".."))
  set :environment, :development
  set :show_exceptions, false
end
```

In v4, it looks like the `server` method has been removed in favor of the new Builder API. Is there a simple way to get a Rack application from this somehow, in order to pass on to a test runner like Capybara?

For reference, I'm essentially trying to adapt [this code](https://github.com/simonrice/middleman-rspec) to work in a v4 project.

**Comment by tdreyno** [comment]
```
app = ::Middleman::Application.new do
  set :root, File.expand_path(File.join(File.dirname(__FILE__), ".."))
  set :environment, :development
  set :show_exceptions, false
end
```

Should work. Just a normal ruby class now.

**Comment by tdreyno** [comment]
I'm using this for my projects: https://gist.github.com/tdreyno/c977de5d398c8c2d4b6a

**Comment by egardner** [comment]
Thanks! The gist was helpful, I was able to adapt what you wrote there for my (very basic) test setup: https://gist.github.com/egardner/967b33e2893b6f550b7a.

I know the notion of automated testing for static sites might sound strange to some folks but it is definitely helpful at times.

**Comment by tdreyno** [comment]
I never really thought about it, but a lot of the Ruby devs on my team are really into it and it's working out great. I expect their contributions to improve the situation for everyone :)

**Comment by tirdadc** [comment]
Going back to the original request, I'm trying to programmatically trigger a Middleman 4.x build from a Rails controller with this:
```
stdin, stdout, stderr = Open3.capture3('cd /var/srv/rails-project/middleman-project && middleman build')
```

and I'm seeing this error:
```
/Users/test/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.7/bin/middleman:3:in `require': cannot load such file -- middleman-core/profiling (LoadError)
	from /Users/text/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.7/bin/middleman:3:in `<top (required)>'
	from /Users/test/.rbenv/versions/2.2.3/bin/middleman:23:in `load'
	from /Users/test/.rbenv/versions/2.2.3/bin/middleman:23:in `<main>'
```

my Rails app lives at /var/srv/rails-project and I just have a separate folder under it for the middleman-project. I am also including the middleman gem in the Rails app itself.

How do I trigger this correctly in v4?

**Comment by tirdadc** [comment]
neither backticks or Open3 would properly change the [Bundler](http://bundler.io/v1.3/man/bundle-exec.1.html) environment, so I had to use `with_clean_env`:

> Using with_clean_env is also necessary if you are shelling out to a different bundle. Any Bundler commands run in a subshell will inherit the current Gemfile, so commands that need to run in the context of a different bundle also need to use with_clean_env.

```
Bundler.with_clean_env do
  Dir.chdir "/var/srv/rails-project/middleman-project" do
    `bundle exec middleman build`
  end
end
```

Works like a charm!

**Comment by tdreyno** [comment]
Maybe try `bundle exec middleman build` ?

Does `Open3.capture3` pass along shell variables? You may need to set the `MM_ROOT` environmental path variable to the project path.
