### ISSUE TITLE
Middleman minify javascript error

### ISSUE THREAD

**Issue by dmendonca** [middleman/middleman#968]
Hi, everyone,

I'm having a problem with the next code inside the config.rb document:

configure :build do
    activate :minify_javascript
end

While the building, it builds all the files of the project correctly, excepts all de .js files.

The message while building is for example:

error    build/js/somefile.js

And it doesn't even create a non-minified file.

The version of the Middleman is 3.0.13

Thanks!

**Comment by KamilLelonek** [comment]
For me it doesn't work as well with CentOS.

**Comment by tdreyno** [comment]
@KamilLelonek Do you have a JS environment installed? Try installing node.js

**Comment by KamilLelonek** [comment]
Of course, I tried with the latest 3 versions (5, 4, and 0.2.17). The problem occurs while minifying JS.

**Comment by bhollis** [comment]
@KamilLelonek would you mind filing a separate issue for your problem, and provide as much detail as possible about what you're doing, what your `config.rb` and `Gemfile` are, how your OS is configured (what's installed), the actual error message, etc.
