### ISSUE TITLE
Frontmatter in Layout files

### ISSUE THREAD

**Issue by ungoldman** [middleman/middleman#983]
It would be great to be able to add **frontmatter** to **layout** files.

Example use case:

`/source/layouts/docs.erb`

``` erb
---
css:
  - docs
---

<% wrap_layout :layout do %>
  <div class="content">
    <%= yield %>
  </div>
<% end %>
```

`/source/localizable/docs/*.html.erb`

``` erb
---
layout: docs
---

...
```

This way any file using the docs layout would also have the corresponding CSS file included without having to explicitly call it out in every template that uses the layout.
---

Another great thing to have on top of this would be the ability to add arbitrary data to layouts, for example:

`/source/layouts/android.erb`

``` erb
---
platform: android
---

<% wrap_layout :docs do %>
  <div class="content">
    <%= yield %>
  </div>
<% end %>
```

`/source/localizable/docs/android/*.html.erb`

``` erb
---
layout: android
---

<h3><%= current_page.layout.platform %></h3>
```

.. or something along those lines, allowing a template to inherit and access data from its layout.
---

After digging through docs and code I don't think either of these features exist for now but they're definitely features I would love to see and have an immediate use for. Do these feature requests make sense within the scope of the project or just in general?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿 🌷 🌾 and came across this issue.

Sorry that this has lingered for quite a while! While I think it's a good idea, I'd suggest either closing this issue or submitting a PR with an implementation.

**Comment by ungoldman** [comment]
Wow this is a classic! I think I will close as I'm no longer using middleman. Thanks for checking in!
