### ISSUE TITLE
Middleman server and CORS

### ISSUE THREAD

**Issue by LandonSchropp** [middleman/middleman#998]
Thanks for creating such an awesome tool! Is there some way to configure Middleman server to set the `Access-Control-Allow-Origin` header?

**Comment by osabate** [comment]
I've done some tests but not luck.. I'm using Middleman 3.1.6.
Added this line to the `Gemfile` :  `gem 'rack-cors', :require => 'rack/cors'`
And the previous posted chunk to the `config.rb` file.
Anyone?

**Comment by tdreyno** [comment]
You really shouldn't be using Middleman server in production.

**Comment by osabate** [comment]
Not used in production but locally.

**Comment by tdreyno** [comment]
gotcha, well, Rack shouldn't have any problems adding headers. I've never used that middleware, you might try writing your own which just added keys to the Rack headers object. Should be about a 10-15 line file.
